"""Original Topic 2.1 content. Reuses the standard Revise360 task schema."""
import json
from pathlib import Path
C=['#40c4ff','#aa6eeb','#ff785a','#ffa028','#50dc96','#f05aaa']
LESSONS=[]
def mc(q,a,*wrong,fb=None):return dict(t='mcq',q=q,a=[a,*wrong],fb=fb or a)
def order(q,steps,fb):return dict(t='order',q=q,steps=steps,fb=fb)
def match(q,pairs,fb):return dict(t='match',q=q,pairs=pairs,fb=fb)
def sort(q,cats,items,fb):return dict(t='sort',q=q,cats=cats,items=items,fb=fb)
def S(name,facts,diagram,challenge,answer,task,extra=None):
 return dict(name=name,facts=facts,diagram=diagram,challenge=challenge,answer=answer,tasks=[task]+([extra] if extra else []),info=answer)
def L(n,title,slug,subject,mission,donow,outcomes,starter,starter_answer,terms,stations,final,plenary,practical=''):
 LESSONS.append(dict(n=n,title=title,slug=slug,subject=subject,mission=mission,donow=donow,outcomes=outcomes,starter=starter,starter_answer=starter_answer,terms=terms,stations=stations,final=final,plenary=plenary,practical=practical))
L(1,'Abstraction studio','AbstractionStudio','Abstraction',
'Choose the details a school equipment-loan system needs. Explain what can be left out and why.',
'Would a photograph always be more useful than a simple map?',
['Explain abstraction.','Select details for a stated purpose.','Justify why some details can be ignored.'],
'A pupil needs to find the library. Which is more useful: a map of corridors or a list of wall colours? Explain.',
'A corridor map shows routes and destinations. Wall colours are usually unnecessary for finding a route.',
[['Abstraction','Keeping relevant details and removing unnecessary detail for a particular purpose.'],['Model','A simplified representation of a real system.']],
[
S('Keep the purpose',['Start with the problem to solve.','Relevant details depend on the purpose.','A simpler model can still be useful.'],['PURPOSE','Find the library','Keep: rooms and routes','Ignore: paint textures'], 'Why can a map omit carpet patterns?', 'Carpet patterns do not help identify a route to the library.',mc('Which detail belongs on a route map?','Connections between rooms','The price of each carpet','Every wall texture','Every pupil name')),
S('Essential information',['A loan system must identify the borrower.','It must identify the borrowed item.','It needs enough data to track the loan.'],['LOAN RECORD','Borrower ID: 241','Item ID: CAM07','Due date: 12 October'], 'Name two details needed to track a camera loan.', 'Borrower ID and item ID identify who has which camera. The due date helps track returns.',sort('Classify details for tracking loans.',['Needed','Not needed'],[['Borrower ID','Needed'],['Item ID','Needed'],['Favourite film','Not needed'],['Shoe brand','Not needed']],'Keep details that support identifying and returning the item.')),
S('Remove distractions',['Not every real-world detail belongs in a model.','Removing detail makes a model easier to use.','Do not remove information needed for accuracy.'],['CAMERA ICON','Keep: lens and body','Ignore: serial number','Purpose: recognise item'], 'Why might an icon omit the serial number?', 'Its purpose is to recognise a camera category. A serial number identifies one particular camera.',mc('What would damage a route map?','Removing the corridor connections','Removing wallpaper patterns','Using simple room outlines','Omitting ceiling colours')),
S('Purpose changes relevance',['A detail can matter in one task and not another.','A repair system needs different data from a route map.','Explain choices using the stated task.'],['TWO PURPOSES','Find room: location','Repair light: fault type','Same school, new detail'], 'When would a room light fault become relevant?', 'When planning repairs, the fault and room location help staff repair the correct light.',match('Match purpose to a useful detail.',[['Find a room','Corridor connections'],['Repair a camera','Fault description'],['Return a loan','Borrower ID']],'Each detail supports a particular decision.')),
S('Abstraction in software',['Users can work without knowing every internal detail.','A button can hide several processing steps.','The hidden steps still happen.'],['CLICK: RETURN ITEM','Find the loan','Mark item available','Show confirmation'], 'What does a return button hide from its user?', 'It hides the detailed steps for finding the loan and updating its stored status.',mc('A return button is an abstraction because it...','Hides internal steps behind one clear action','Deletes the loan system','Removes every calculation','Guarantees there are no errors')),
S('Evaluate a model',['Check whether the model solves the problem.','Add missing relevant details.','Remove detail that only distracts.'],['ROUTE MAP REVIEW','Rooms: yes','Connections: missing','Textures: unnecessary'], 'How should this route map be improved?', 'Add the connections between rooms so users can plan a route. Textures can be removed.',mc('Which justification is strongest?','Keep due dates so overdue loans can be identified','Keep everything just in case','Remove all numbers','Keep only colourful details'))
],
[sort('Choose data for identifying overdue equipment loans.',['Keep','Omit'],[['Borrower ID','Keep'],['Due date','Keep'],['Item ID','Keep'],['Favourite snack','Omit']],'The system needs to identify the loan and whether its due date has passed.'),mc('Why is abstraction useful here?','It reduces unnecessary detail while preserving what the task needs','It removes the need to test','It makes every detail irrelevant','It changes the purpose automatically')],
[['Define abstraction. [2]','Keep relevant detail (1) and remove unnecessary detail for a purpose (1).'],['A delivery map omits the colour of each house. Explain why this is appropriate. [2]','The map is used to find routes (1). House colours are not needed to represent the route connections (1).'],['Give one detail that a loan system should retain and justify it. [2]','Borrower ID identifies who has the item, or due date supports identifying overdue items. One suitable detail (1) with a linked reason (1).']])
L(2,'Model design lab','ModelDesignLab','Applying abstraction',
'Build and test simple models. Select the data needed to compare locations and calculate fares.',
'Can a simplified model give a correct answer?',
['Apply abstraction to a new problem.','Identify inputs, processing and outputs.','Refine a model when requirements change.'],
'A program compares two places north or south. Does it need latitude, shop names or building colours?',
'Latitude is relevant to north/south position. Shop names and building colours are not.',
[['Input','Data supplied to an algorithm.'],['Output','Information produced by an algorithm.']],
[
S('Define the question',['A model answers a specific question.','Write the required output first.','Then decide which inputs are necessary.'],['QUESTION','Which point is further north?','INPUT: two latitudes','OUTPUT: north / same'], 'Why define the output before selecting data?', 'The required answer determines which data the model needs.',mc('Which input supports a north/south comparison?','Latitude','Population','Building colour','Ticket price')),
S('Signed coordinates',['Northern latitudes are positive.','Southern latitudes are negative.','A larger latitude is further north.'],['LATITUDES','A = -12','B = -35','A is further north'], 'Which is further north: -8 or -21? Explain.', '-8 is larger than -21, so it is further north.',mc('Which latitude is further north?','-3','-17','-40','-61',fb='-3 is the greatest value, so it is furthest north.')),
S('Equality matters',['Two values can be equal.','A two-way comparison may miss this case.','Specify an output for every valid case.'],['COMPARE A AND B','A > B: A north','A < B: B north','A == B: same latitude'], 'Why is an equality case needed?', 'Without it, equal latitudes could be incorrectly labelled north or south.',mc('A = 12 and B = 12. What should be output?','Same latitude','A is north','B is north','No valid coordinates')),
S('Inputs and processing',['Inputs supply the data.','Processes transform or compare it.','Outputs communicate the result.'],['FARE MODEL','Input: distance','Process: distance * 2','Output: fare'], 'Classify multiplying distance by 2.', 'It is a process because it transforms the input into the fare.',sort('Classify each part of the fare model.',['Input','Process','Output'],[['Distance entered','Input'],['Multiply by 2','Process'],['Fare displayed','Output']],'Input enters, a process calculates, and output leaves the system.')),
S('Change the requirement',['A new requirement may need new data.','Review the model before adding detail.','Keep the change relevant to the new purpose.'],['OLD: north / south','Input: latitude','NEW: east / west','Add: longitude'], 'What extra coordinate supports east/west comparison?', 'Longitude supports comparing east/west positions within a stated coordinate convention.',mc('A fare now depends on passenger age. What changes?','Add age as an input and a discount rule','Add every passenger hobby','Remove distance','Stop producing a fare')),
S('Test the simplified model',['Use examples with known answers.','Include less obvious cases.','Refine the rules if an example fails.'],['TEST PAIRS','10 and 20','-10 and -20','15 and 15'], 'Why test equal and negative latitudes?', 'They check equality and signed-number comparisons that positive unequal examples may miss.',order('Order the model-development steps.',['State the required answer','Choose relevant inputs','Write the processing rules','Check known examples'],'Test against the original question.'))
],
[mc('A fare is distance * 2. Distance is 7. What is output?','14','9','5','2'),match('Match each improvement to its purpose.',[['Add an equality branch','Handle equal values'],['Remove wall colours','Reduce irrelevant detail'],['Add age','Apply an age discount']],'Only add detail that supports the requirement.')],
[['Identify input, process and output for a fare calculated as distance multiplied by 2. [3]','Distance (1), multiply by 2 (1), fare (1).'],['Explain why comparing only positive latitudes is insufficient testing. [2]','It misses negative values (1), where incorrect use of absolute values could reverse the result (1).'],['A model compares only north/south locations. Explain a refinement needed for equal latitudes. [2]','Add a test for equality (1) and output a same-latitude result (1).']])
L(3,'Decomposition workshop','DecompositionWorkshop','Decomposition and structure diagrams',
'Break an equipment-loan system into manageable parts and build a structure diagram.',
'How could a team share the work of building one program?',
['Decompose a problem into sub-problems.','Interpret and create structure diagrams.','Explain benefits of decomposition.'],
'A school club needs to register members, lend equipment and record returns. Name three smaller problems.',
'Manage members, issue loans and process returns are three suitable sub-problems.',
[['Decomposition','Breaking a problem into smaller, manageable sub-problems.'],['Structure diagram','A hierarchy showing a system and its component sub-problems.']],
[
S('Split the problem',['Start with the whole task.','Identify separate responsibilities.','Break large parts down further.'],['EQUIPMENT SYSTEM','Members','Loans','Returns'], 'Suggest three parts of a library system.', 'Manage members, issue books and process returned books are suitable parts.',mc('Which example is decomposition?','Split a shop into stock, orders and payments','Remove irrelevant stock colours','Put every instruction in one block','Change the screen font')),
S('Read the hierarchy',['The top box is the whole system.','Child boxes are parts of their parent.','Lower levels show more detail.'],['Loan system','  Issue loan','    Check availability','    Record borrower'], 'What are the two parts of Issue loan?', 'Check availability and record borrower.',mc('What does a line to a child box mean?','The child is a component of the parent','The child always runs next','The child is an output value','The parent is false')),
S('Refine a sub-problem',['Refinement adds useful detail.','Stop when each task is clear enough to solve.','Keep the hierarchy logically grouped.'],['PROCESS RETURN','Find active loan','Mark loan returned','Make item available'], 'Break Process return into three smaller tasks.', 'Find the active loan, mark it returned and make the item available again.',order('Order a sensible refinement process.',['Identify the whole system','Name its main sub-problems','Split a complex sub-problem','Check the parts cover the requirements'],'Refinement adds detail to a decomposition.')),
S('Structure versus flow',['Structure diagrams show parts.','Flowcharts show execution and decisions.','A hierarchy does not specify run order.'],['STRUCTURE: parts','FLOWCHART: execution','Hierarchy is not a loop','Branches are not yes/no'], 'Why is a structure diagram not a flowchart?', 'It shows what the system contains, rather than the order of execution and decision paths.',sort('Classify the diagram features.',['Structure diagram','Flowchart'],[['Parent and child modules','Structure diagram'],['Yes/no decision branch','Flowchart'],['System broken into parts','Structure diagram'],['Arrow showing next action','Flowchart']],'Do not read a hierarchy as execution order.')),
S('Work as a team',['Smaller tasks can be allocated to people.','Parts can be tested separately.','Interfaces between parts must still agree.'],['TEAM PLAN','A: member records','B: loan checks','Shared: member ID'], 'Why must both programmers agree on member ID?', 'Their parts exchange member details. A consistent ID allows the parts to work together.',mc('Which is a benefit of decomposition?','Individual parts are easier to understand and test','Testing becomes unnecessary','Parts never need to communicate','Every program runs faster')),
S('Check coverage',['Compare the parts with the requirements.','Look for missing responsibilities.','Avoid duplicate or unclear tasks.'],['REQUIREMENTS','Register / lend / return','CURRENT PARTS','Register / lend'], 'Which responsibility is missing?', 'Processing returns is missing and must be included.',mc('The system must report overdue loans. What should be added?','An overdue-report sub-problem','A wallpaper sub-problem','A second unrelated system','Nothing because all systems report automatically'))
],
[match('Match each sub-problem to a suitable smaller task.',[['Members','Add a member record'],['Loans','Check item availability'],['Returns','Mark an item available']],'Each child must belong to its parent.'),mc('Why test each part before combining them?','It helps locate faults within smaller sections','It proves the whole system cannot fail','It removes the need for shared data','It guarantees the fastest code')],
[['Define decomposition. [2]','Break a complex problem (1) into smaller manageable sub-problems (1).'],['Draw a structure diagram for a club system with members, loans and returns. Decompose loans into two tasks. [4]','Whole system above three appropriate parts (1), correct parent-child connections (1), check availability beneath loans (1), record loan beneath loans (1).'],['Explain one advantage of decomposition for a team. [2]','Separate tasks can be assigned to different people (1), allowing work on manageable parts in parallel (1).']])
L(4,'Algorithm planning room','AlgorithmPlanningRoom','Algorithmic thinking: sequence',
'Design precise steps for issuing an equipment loan, then check their order and outputs.',
'Why can instructions that seem obvious to a person confuse a computer?',
['Explain algorithmic thinking.','Identify inputs, processes and outputs.','Write precise ordered instructions.'],
'Put these actions in order: display total, input price, calculate total.',
'Input price, calculate total, display total.',
[['Algorithm','A finite set of precise steps for solving a problem.'],['Sequence','Executing instructions in their stated order.']],
[
S('A clear goal',['Algorithmic thinking plans a solution as steps.','State what must be achieved.','Check that the steps reach that goal.'],['GOAL: issue a loan','Read borrower and item','Check whether available','Record or reject loan'], 'Why state the goal before writing steps?', 'The goal defines what counts as a correct result.',mc('Algorithmic thinking involves...','Planning precise steps to solve a problem','Only choosing a screen colour','Removing all processing','Guessing an output')),
S('Input, process, output',['Identify data entering the algorithm.','Identify operations on the data.','Identify the result to communicate.'],['INPUT: hours, rate','PROCESS: hours * rate','OUTPUT: charge'], 'Name the inputs for calculating hire cost.', 'The number of hours and the hourly rate.',sort('Classify the hire steps.',['Input','Process','Output'],[['Read hours','Input'],['Multiply hours by rate','Process'],['Display charge','Output']],'The calculation is the process.')),
S('Order matters',['A value must be available before use.','Calculate before displaying the result.','Changing order can change behaviour.'],['Read quantity','Read unit price','total = quantity * price','Print total'], 'What is wrong with printing total first?', 'The total has not yet been calculated from the inputs.',order('Order a total-cost algorithm.',['Input quantity','Input unit price','Calculate quantity times unit price','Output total'],'Read both values before calculating.')),
S('Remove ambiguity',['Instructions need clear actions and quantities.','Avoid words such as some or enough.','Specify what happens in each case.'],['VAGUE: add some points','PRECISE: add 3 points','VAGUE: repeat a bit','PRECISE: repeat 4 times'], 'Rewrite Add some bonus points precisely.', 'Add 5 bonus points to score is one precise example.',mc('Which instruction is precise?','Increase score by 2','Increase score a little','Process the result somehow','Repeat until it seems right')),
S('Follow the steps',['Trace an algorithm in its exact order.','Use the current value of a variable.','Assignment replaces its previous value.'],['x = 3','x = x + 4','x = x * 2','print(x)'], 'What is printed? Show the intermediate value.', 'x becomes 7 and then 14, so 14 is printed.',mc('For x = 5, then x = x + 2, then x = x * 3, what is x?','21','17','15','10',fb='5 + 2 = 7, then 7 * 3 = 21.')),
S('Check the result',['Use a simple example with a known answer.','Compare expected and actual results.','Correct the steps when they differ.'],['quantity = 3','price = 4','Expected total: 12','Wrong rule: quantity + price'], 'How should the wrong rule be corrected?', 'Multiply quantity by price. Adding gives 7, not the expected 12.',mc('A total is wrong. What is the useful next step?','Trace each calculation using known inputs','Change all variable names at random','Ignore the expected result','Delete every input'))
],
[order('Put a simple loan algorithm in order.',['Read borrower ID and item ID','Check the item is available','Record the loan if available','Display the result'],'The check must happen before recording the loan.'),mc('What is the charge for 4 hours at 3 per hour?','12','7','1','43')],
[['Explain algorithmic thinking. [2]','Plan a logical sequence of steps (1) that solves a stated problem (1).'],['Write an algorithm to input length and width and output area. [3]','Input length and width (1), area = length * width (1), output area (1).'],['Explain why the order of instructions matters. [2]','Later instructions can depend on earlier results (1), so using a result before calculation can be incorrect (1).']])
L(5,'Decision control centre','DecisionControlCentre','Algorithmic thinking: selection',
'Build decisions that handle thresholds, equal values and combined conditions correctly.',
'Is age greater than 16 the same as age at least 16?',
['Apply selection to decisions.','Handle boundary and equality cases.','Combine conditions accurately.'],
'A club accepts pupils aged 12 or older. Should age 12 be accepted?',
'Yes. Age 12 is included, so the condition must be age >= 12.',
[['Selection','Choosing which instructions to execute using a condition.'],['Condition','An expression evaluated as true or false.']],
[
S('Two possible paths',['A condition selects a path.','IF handles the true case.','ELSE handles the false case.'],['if available == true then','  print("Loan allowed")','else','  print("Unavailable")','endif'], 'What happens when available is false?', 'The ELSE branch prints Unavailable.',mc('If available is false, which message is printed?','Unavailable','Loan allowed','Both messages','No message')),
S('Include the boundary',['Greater than excludes equality.','Greater than or equal includes equality.','Match the condition to the rule.'],['RULE: age at least 12','Use: age >= 12','11: reject','12: accept'], 'Why does age > 12 not match the rule?', 'It rejects a pupil aged exactly 12, although the rule includes them.',mc('Which condition means score is at least 50?','score >= 50','score > 50','score < 50','score == 49')),
S('Three-way decisions',['Some problems need more than two outcomes.','Check greater, less and equal cases.','Each valid input should have an outcome.'],['A > B: A wins','A < B: B wins','Otherwise: draw'], 'What happens if the draw case is omitted?', 'Equal values may get the wrong result or no intended output.',mc('A = 7 and B = 7. What is the correct result?','Draw','A wins','B wins','A is greater')),
S('Both conditions',['AND is true when both conditions are true.','Use it when both requirements must hold.','Check each requirement separately.'],['member = true','available = false','member AND available','Result: false'], 'Can this member borrow the unavailable item?', 'No. Both membership and availability are required, and availability is false.',mc('Which permits a loan only if both checks pass?','member AND available','member OR available','NOT member','available == false')),
S('Either condition',['OR is true when at least one condition is true.','It is also true when both are true.','Do not confuse OR with exactly one.'],['discount = student OR senior','Student only: yes','Senior only: yes','Both: yes'], 'Does a person who meets both conditions qualify?', 'Yes. OR includes the case where both conditions are true.',mc('student = false, senior = true. What is student OR senior?','True','False','Equal to student only','An error')),
S('Nested decisions',['A decision can sit inside another decision.','The outer path controls whether it is reached.','Indentation helps show the structure.'],['if member then','  if available then','    print("Issue")','  endif','endif'], 'If member is false, is the inner decision reached?', 'No. The outer IF body is skipped.',mc('Which describes nesting?','Placing one selection inside another','Deleting all conditions','Always running both branches','Changing an input to an output'))
],
[match('Match the phrase to its condition.',[['At least 10','x >= 10'],['Below 10','x < 10'],['Exactly 10','x == 10']],'Equality must be handled as the wording requires.'),mc('A loan needs a member AND an available item. Member is true and available is false. Result?','Reject the loan','Issue the loan','Issue two loans','Ignore availability')],
[['Write a condition for a temperature from 18 to 24 inclusive. [2]','temperature >= 18 (1) AND temperature <= 24 (1).'],['Explain the difference between AND and OR. [2]','AND needs both conditions true (1). OR needs at least one true (1).'],['An algorithm uses age > 16 for a rule of at least 16. Identify and correct the error. [2]','The boundary age 16 is rejected (1). Use age >= 16 (1).']])
L(6,'Loop planning lab','LoopPlanningLab','Algorithmic thinking: iteration',
'Plan repetition that counts accurately and terminates. Combine loops with decisions.',
'How could a program process 100 loans without writing the same instructions 100 times?',
['Choose count- or condition-controlled iteration.','Trace loops and running totals.','Explain why loops terminate.'],
'A task repeats exactly five times. Would a counter or an unknown stopping condition be clearer?',
'A count-controlled loop is suitable because the number of repetitions is known.',
[['Iteration','Repeating a group of instructions.'],['Accumulator','A variable used to build a running total.']],
[
S('Repeat a known count',['Use a count-controlled loop for a known count.','Be clear whether the last value is included.','OCR for loops include their stated end value.'],['for i = 1 to 3','  print(i)','next i','Output: 1, 2, 3'], 'How many times does this loop print?', 'Three times, because 1, 2 and 3 are included.',mc('OCR pseudocode: for i = 1 to 4. How many iterations?','4','3','5','1')),
S('Repeat until a condition',['A while loop checks before its body.','It can execute zero times.','The condition must eventually become false.'],['count = 0','while count < 3','  count = count + 1','endwhile','Final count: 3'], 'When does the loop stop?', 'When count becomes 3, count < 3 is false.',mc('A while condition is false before the first check. How often does its body run?','Zero times','Once','Twice','Forever')),
S('Accumulate a total',['Set a starting total before the loop.','Add each new value to the running total.','Do not reset the total during each iteration.'],['total = 0','Values: 4, 6, 3','Totals: 4, 10, 13','Output: 13'], 'What goes wrong if total = 0 is inside the loop?', 'Earlier values are discarded at each iteration, so the running total is lost.',mc('Starting at 0, add 5, 2 and 8. What is the total?','15','8','10','7')),
S('Guarantee progress',['A loop needs a way to reach its stopping case.','Update the control variable correctly.','Trace the update and condition together.'],['x = 0','while x < 3','  print(x)','  x = x + 1','endwhile'], 'What happens if the update is removed?', 'x stays 0, so x < 3 remains true and the loop does not terminate.',mc('What fixes a loop whose counter never changes?','Update the counter towards the stopping condition','Print the counter twice','Rename the counter only','Remove all conditions')),
S('Selection inside a loop',['A loop can repeat a decision.','The decision runs for each item.','Only matching items affect the count.'],['count = 0','Values: 4, 9, 7','For each value:','  if value >= 7: count + 1','Result: 2'], 'How many of 2, 7, 8 and 3 are at least 7?', 'Two values: 7 and 8.',mc('Which values pass value >= 5 in [1, 5, 8]?','5 and 8','Only 8','1 and 5','All three')),
S('Nested loops',['An inner loop runs for each outer iteration.','Count repetitions at both levels.','Multiply fixed counts when both fully execute.'],['Outer: 3 repetitions','Inner: 2 repetitions','Print once in inner body','Total prints: 6'], 'How many prints for outer 4 and inner 3?', 'Twelve prints: the three inner iterations run for each of four outer iterations.',mc('Outer loop runs twice. Inner loop runs five times each time. Total inner executions?','10','7','5','2'))
],
[order('Order a running-total algorithm.',['Set total to 0','Repeat for each input value','Add the value to total inside the loop','Output total after the loop'],'Initialise once, update repeatedly and output at the end.'),mc('A loop starts n = 1, adds 1 while n < 4. What is n after the loop?','4','3','5','1')],
[['Explain one difference between count-controlled and condition-controlled loops. [2]','Count-controlled repetition uses a specified count/range (1). Condition-controlled repetition depends on a condition (1).'],['Write pseudocode to input three numbers and output their total. [4]','Initialise total (1), loop exactly three times (1), input and add each value (1), output total after the loop (1).'],['Why might a while loop never terminate? [2]','Its condition remains true (1), for example because the control variable is never updated (1).']],
'In Python, write and run a program that inputs three numbers and prints their total. Test 2, 3, 4 (expected 9) and -2, 2, 0 (expected 0).')
L(7,'Linear search depot','LinearSearchDepot','Linear search',
'Search equipment records one at a time. Trace successful and unsuccessful linear searches.',
'How would you find an item in a box with no useful ordering?',
['Describe and trace linear search.','Interpret a search code segment.','Compare successful and unsuccessful searches.'],
'Search [18, 4, 27, 9] from left to right for 27. Which values are checked?',
'18, then 4, then 27. Stop when 27 is found.',
[['Linear search','Checking items one at a time until a target is found or the list ends.'],['Index','A position used to access an item in a list.']],
[
S('Check one at a time',['Start at the first item.','Compare the item with the target.','Continue if it does not match.'],['List: 18, 4, 27, 9','Target: 27','Checks: 18, 4, 27','Found at index 2'], 'How many target comparisons find 27?', 'Three comparisons. With zero-based indexing, its index is 2.',order('Order a successful search for 27 in [18, 4, 27, 9].',['Compare 18 with 27','Compare 4 with 27','Compare 27 with 27','Report found and stop'],'Do not continue checking after the first match in this version.')),
S('Unsorted lists',['Linear search does not need sorted data.','Every item is still checked in sequence.','It also works on sorted lists.'],['UNSORTED','42, 7, 19, 3','Linear search: works','Sorting first: not needed'], 'Why can linear search use an unsorted list?', 'It checks items directly and does not discard a half based on value order.',mc('Which list can linear search use?','Both sorted and unsorted lists','Only sorted lists','Only lists of even length','Only lists without duplicates')),
S('Unsuccessful searches',['A target may not be present.','Continue until the list is exhausted.','Then report not found.'],['List: 8, 2, 6, 4','Target: 7','Check all four items','Result: not found'], 'How many target comparisons are needed here?', 'Four, one for each item.',mc('Search [3, 8, 1] for 9. Target comparisons?','3','0','1','9')),
S('Read the code',['i tracks the current index.','found records whether a match exists.','Increase i after checking an item.'],['i = 0; found = false','while i < n AND NOT found','  if data[i] == target then','    found = true','  endif; i = i + 1'], 'What does data[i] == target test?', 'It compares the current list item with the search target.',mc('Why include i < n?','To stop before accessing beyond the list','To force the target to exist','To sort the list','To skip index 0')),
S('Index versus value',['An index is a position, not the stored value.','Zero-based indexing starts at 0.','Report the form of result requested.'],['Index: 0  1  2  3','Value: 6  2  9  4','Target 9: index 2','Checks needed: 3'], 'State the value, index and comparison count for 9.', 'Value 9, index 2, and three target comparisons.',match('Match the quantities for finding 9 in [6, 2, 9, 4].',[['Value found','9'],['Zero-based index','2'],['Target comparisons','3']],'Index and comparison count differ by one in this successful left-to-right search.')),
S('Best and worst cases',['First-item success needs one comparison.','Last-item success checks every item.','An absent target also checks every item.'],['List length: 100','First item: 1 comparison','Last item: 100','Absent: 100'], 'Why does a longer list worsen the worst case?', 'More items must be checked before a last-item match or not-found result.',mc('For 20 items, which case needs 20 comparisons?','Target absent','Target first','Target second','Every successful search'))
],
[mc('Search [13, 5, 21, 8, 3] for 8. What is its zero-based index?','3','4','8','2'),mc('In the same search, how many target comparisons occur?','4','3','5','8')],
[['Describe a linear search for an absent target. [3]','Start at the first item (1), compare each item with the target (1), report not found after the final item (1).'],['Trace a search for 6 in [9, 2, 4, 6, 1]. Give checked values and its zero-based index. [2]','Checks 9, 2, 4, 6 (1). Index 3 (1).'],['Explain one reason to use linear search for a short unsorted list. [2]','No sorting is required (1), so a short one-off search can directly check the items (1).']])
L(8,'Binary search archive','BinarySearchArchive','Binary search',
'Use ordered records to halve a search range. Track low, high and midpoint values.',
'Why does a dictionary put words in order?',
['Describe and trace binary search.','Explain why sorted data is required.','Compare binary and linear search choices.'],
'In [2, 5, 8, 11, 14], the middle value is 8. Where can target 14 still be?',
'Only to the right of 8 because the list is in ascending order.',
[['Binary search','Searching sorted data by comparing with the middle item and discarding the impossible half.'],['Midpoint','The middle index of the current search range.']],
[
S('Sorted data first',['The list must be ordered.','Use the order to rule out one half.','Unsorted data makes this reasoning unsafe.'],['Sorted: 2, 5, 8, 11, 14','Middle value: 8','Target: 14','Keep the right half'], 'Why is sorted order required?', 'It guarantees smaller values lie before the middle and larger values after it.',mc('What must hold before binary search is used?','The data is sorted by the search key','The target is first','The list length is even','Every value is positive')),
S('Find the midpoint',['Use low and high indices.','Take the integer midpoint.','Our examples round down.'],['low = 0; high = 5','mid = (low + high) DIV 2','mid = 2','Compare data[2]'], 'What is mid when low = 3 and high = 8?', '(3 + 8) DIV 2 = 5.',mc('low = 2, high = 6. Midpoint index?','4','3','6','8')),
S('Discard the wrong half',['If target is greater, move low above mid.','If target is smaller, move high below mid.','The middle item has already been checked.'],['Target > data[mid]','low = mid + 1','','Target < data[mid]','high = mid - 1'], 'Why use mid + 1 rather than mid?', 'The midpoint has already failed to match and should not remain in the search range.',match('Match each comparison to the update.',[['Target greater','low = mid + 1'],['Target smaller','high = mid - 1'],['Target equal','Report found']],'Remove the checked midpoint as well as the impossible half.')),
S('Trace a successful search',['Recalculate the midpoint after each update.','Count comparisons with the target.','Stop immediately at a match.'],['List: 3, 6, 9, 12, 15, 18, 21','Target: 18','mid 3: value 12','mid 5: value 18','Found in 2 comparisons'], 'What values are checked when searching for 6?', '12, then 6. The target is found after two comparisons.',mc('Search this list for 21. Checked values?','12, 18, 21','3, 6, 9, 12, 15, 18, 21','12, 15, 21','21 only')),
S('Trace not found',['A search can exhaust the remaining range.','Stop when low is greater than high.','Do not access another midpoint after stopping.'],['List: 2, 4, 6, 8, 10','Target: 7','Checks: 6, 8','Then low = 3; high = 2','Result: not found'], 'Why does low > high mean not found?', 'No indices remain in the possible search range.',mc('For target 1 in [2, 4, 6, 8, 10], what is checked?','6 then 2','6 then 4 then 2','Only 1','All five values')),
S('Choose the search',['Binary search can use fewer comparisons.','Sorting first also takes work.','Consider list size and repeated searches.'],['Short unsorted list','One search: linear suits','Large sorted list','Many searches: binary suits'], 'Why not always sort before a one-off search?', 'Sorting takes work. For a short unsorted list, one linear scan may be simpler and cheaper overall.',mc('Which is the strongest case for binary search?','Many lookups in a large sorted list','One lookup in three unsorted items','A list that cannot be ordered','A target known to be the first item'))
],
[order('Order the checks for target 14 in [2, 4, 6, 8, 10, 12, 14].',['Check 8 at index 3','Keep indices 4 to 6','Check 12 at index 5','Check 14 at index 6'],'Round down at each midpoint.'),mc('What is the worst-case advantage as a sorted list grows?','Binary search repeatedly halves the remaining range','Binary search checks every item twice','Linear search always checks fewer items','Sorting is free')],
[['Explain why binary search requires sorted data. [2]','Ordering locates smaller and larger values on known sides (1), allowing one half to be safely discarded (1).'],['Trace binary search for 4 in [2, 4, 6, 8, 10, 12, 14]. Round midpoint down. [3]','Check 8 at index 3 (1), keep indices 0 to 2 (1), check 4 at index 1 and stop (1).'],['Explain when linear search could be a better choice. [2]','A short unsorted list with one lookup (1), because sorting first adds work not needed for a linear scan (1).']])
L(9,'Bubble sort conveyor','BubbleSortConveyor','Bubble sort',
'Sort equipment codes by comparing neighbours. Record complete passes and recognise when to stop.',
'Can moving one item at a time eventually put a whole list in order?',
['Describe adjacent comparisons and swaps.','Trace complete bubble-sort passes.','Explain an early stopping condition.'],
'For ascending order, should neighbouring values 7 and 3 be swapped? Why?',
'Yes. 7 is greater than 3, so swapping puts the smaller value first.',
[['Pass','One traversal of the part of the list currently being processed.'],['Swap','Exchanging the positions of two values.']],
[
S('Compare neighbours',['Compare adjacent values.','Swap if the left value is greater.','Leave correctly ordered neighbours unchanged.'],['Ascending order','Compare: 7, 3','Swap: 3, 7','Compare: 3, 5 -> no swap'], 'Should equal neighbouring values be swapped?', 'No. They are already in a valid ascending order.',mc('Which pair needs swapping for ascending order?','9, 4','2, 8','5, 5','1, 3')),
S('Complete the first pass',['Work from left to right in these examples.','Compare each adjacent pair in turn.','The largest value reaches the right-hand end.'],['Start: 5, 1, 4, 2','After pair 1: 1, 5, 4, 2','After pair 2: 1, 4, 5, 2','After pair 3: 1, 4, 2, 5'], 'Is the list fully sorted after this pass?', 'No. 4 and 2 are still out of order, though 5 is in its final position.',order('Order the states in the first left-to-right pass.',['5, 1, 4, 2','1, 5, 4, 2','1, 4, 5, 2','1, 4, 2, 5'],'The largest item moves right one comparison at a time.')),
S('Continue the passes',['A pass does not always finish the sort.','The next pass fixes the next-largest value.','An optimised version excludes the sorted end.'],['After pass 1: 1, 4, 2, 5','Pass 2: compare 1 and 4','Then swap 4 and 2','After pass 2: 1, 2, 4, 5'], 'What is the list after the second pass?', '1, 2, 4, 5.',mc('After pass 1 gives [2, 3, 1, 4], what does pass 2 give?','2, 1, 3, 4','1, 2, 3, 4','2, 3, 4, 1','4, 3, 2, 1')),
S('Swaps and comparisons',['A comparison may not cause a swap.','Keep comparison and swap counts separate.','A full first pass on four items compares three pairs.'],['Start: 1, 2, 4, 3','Compare 1/2: no swap','Compare 2/4: no swap','Compare 4/3: swap'], 'How many comparisons and swaps occur?', 'Three adjacent comparisons and one swap.',mc('First full pass on [1, 2, 3, 4]: how many swaps?','0','1','3','4')),
S('Read the swap',['Keep one value temporarily.','Overwrite its original position safely.','Restore the saved value in the other position.'],['temp = a[i]','a[i] = a[i+1]','a[i+1] = temp'], 'Why is temp needed in this three-line swap?', 'It preserves the original a[i] so it is not lost when a[i] is overwritten.',order('Order the three-line swap.',['Save a[i] in temp','Copy a[i+1] into a[i]','Copy temp into a[i+1]'],'Both original values must survive the swap.')),
S('Stop when unchanged',['Track whether any swap occurred.','A complete pass with no swaps shows sorted order.','Reset the swap flag before each new pass.'],['Start pass: swapped = false','On a swap: swapped = true','No swaps in whole pass?','Stop: list is sorted'], 'Why is one correct pair not enough to stop?', 'Other adjacent pairs may still be out of order. The whole active pass must be checked.',mc('Which is a safe early stopping condition?','A complete pass makes no swaps','The first pair is ordered','Exactly one swap occurs','The list contains an even number'))
],
[mc('First full left-to-right bubble pass on [4, 3, 2, 1] gives...','3, 2, 1, 4','1, 2, 3, 4','1, 4, 3, 2','4, 2, 3, 1'),mc('Why can the rightmost value then be excluded?','It is the largest and is in its final position','It is always the smallest','It was never compared','All other values are now sorted')],
[['Show the first left-to-right pass on [6, 2, 5, 1], recording each swap. [3]','2,6,5,1 (1); 2,5,6,1 (1); 2,5,1,6 (1).'],['Explain how a swap flag can reduce unnecessary passes. [2]','Reset the flag before a pass and set it on a swap (1). Stop after a whole pass leaves it false (1).'],['Explain why one pass does not necessarily sort a list. [2]','It places the largest remaining value at the end (1), but other values can still be out of order (1).']])
L(10,'Merge and insertion works','MergeInsertionWorks','Merge sort and insertion sort',
'Trace two ways to build sorted lists. Compare merging sorted groups with inserting into a sorted prefix.',
'How do you put a new playing card into a sorted hand?',
['Trace merge sort splits and merges.','Trace insertion sort.','Compare the main sorting methods.'],
'Merge sorted lists [2, 7] and [3, 5]. What is the sorted result?',
'2, 3, 5, 7. Repeatedly take the smaller front value, then append the remainder.',
[['Merge','Combine sorted lists into one sorted list.'],['Sorted prefix','The ordered section at the beginning of a list.']],
[
S('Divide the list',['Merge sort splits a list into smaller parts.','Continue until single-item lists remain.','A single-item list is already sorted.'],['[7, 2, 6, 3]','[7, 2]   [6, 3]','[7] [2]  [6] [3]'], 'Why can splitting stop at one item?', 'A single item cannot be out of order relative to another item in its list.',order('Order these merge-sort stages.',['Split the original list','Split again into single items','Merge into sorted pairs','Merge the pairs into the sorted list'],'Splitting alone does not order the data.')),
S('Merge sorted groups',['Compare the front unmerged values.','Take the smaller value into the output.','Append the remainder when one group empties.'],['Left: 2, 7','Right: 3, 6','Take: 2, 3, 6','Append: 7','Result: 2, 3, 6, 7'], 'Which value is chosen after 2? Why?', '3, because it is smaller than the other front value, 7.',mc('Merge [1, 8] and [4, 6]. Result?','1, 4, 6, 8','1, 8, 4, 6','4, 6, 1, 8','8, 6, 4, 1')),
S('Read a merge segment',['Read from each sorted input group.','Advance only the pointer you used.','Do not discard unmerged values.'],['if left[i] <= right[j]','  output left[i]','  i = i + 1','else: output right[j]','      j = j + 1'], 'Why increment only the pointer used?', 'The other front value has not been output yet and must remain available for comparison.',mc('Left is exhausted but right has [9, 12]. What next?','Append 9 and 12','Discard both values','Start splitting again','Reverse the output')),
S('Insert into a prefix',['Treat the first item as a sorted prefix.','Take the next item as the key.','Insert the key at its correct position.'],['Start: 6, 2, 5, 1','Insert 2: 2, 6, 5, 1','Insert 5: 2, 5, 6, 1','Insert 1: 1, 2, 5, 6'], 'What is the sorted prefix after inserting 5?', '2, 5, 6. The final value 1 has not yet been inserted.',mc('After inserting 3 into prefix [2, 7, 9], the prefix is...','2, 3, 7, 9','3, 2, 7, 9','2, 7, 9, 3','2, 7, 3, 9')),
S('Shift and insert',['Save the key before shifting.','Move larger prefix values one position right.','Place the key in the gap.'],['Prefix: 2, 7, 9; key = 5','Shift 9 right','Shift 7 right','Place 5 after 2','Result: 2, 5, 7, 9'], 'Why save the key before shifting values?', 'Shifting could overwrite its original position. Saving it preserves the value for insertion.',order('Insert key 4 into sorted prefix [1, 6, 8].',['Save key 4','Shift 8 one place right','Shift 6 one place right','Place 4 after 1'],'Only values larger than the key need shifting.')),
S('Compare the methods',['Bubble sort compares neighbours over passes.','Insertion sort grows a sorted prefix.','Merge sort splits and merges sorted groups.'],['Bubble: neighbour swaps','Insertion: prefix + key','Merge: split then merge','Typical merge uses extra space'], 'Which method can use few shifts on nearly sorted data?', 'Insertion sort, because many keys are already close to their correct positions.',match('Match the method to its main approach.',[['Bubble','Compare and swap neighbours'],['Insertion','Insert a key into a sorted prefix'],['Merge','Split then merge sorted groups']],'Do not describe merge sort as repeated adjacent swapping.'))
],
[mc('Insertion sort on [4, 1, 3, 2]: after inserting the first two keys, the list is...','1, 3, 4, 2','1, 2, 3, 4','4, 3, 1, 2','1, 4, 2, 3'),mc('Which statement describes the usual school-level merge-sort implementation?','It uses additional temporary storage during merging','It never splits data','It only swaps adjacent pairs','It needs the input already sorted')],
[['Show the split and merge stages for [8, 3, 6, 1]. [4]','Split into [8,3] and [6,1] (1), split into singles (1), merge to [3,8] and [1,6] (1), merge to [1,3,6,8] (1).'],['Show the list after each insertion for [5, 2, 4, 1]. [3]','[2,5,4,1] (1), [2,4,5,1] (1), [1,2,4,5] (1).'],['Give one difference between merge and insertion sort. [2]','Merge splits and combines sorted groups (1). Insertion places successive keys into a growing sorted prefix (1).']])
L(11,'Flowchart design studio','FlowchartDesignStudio','Producing algorithms: flowcharts',
'Design a flowchart for an equipment loan. Use the correct symbols and labelled decision paths.',
'How could a diagram make a decision easier to check?',
['Recognise flowchart symbols.','Follow decision paths.','Create a complete flowchart.'],
'A program reads age, checks age >= 12 and prints a result. Which step is a decision?',
'The check age >= 12 is a decision because it has true and false paths.',
[['Flowchart','A diagram using symbols and arrows to show an algorithm.'],['Decision','A condition that selects between paths.']],
[
S('Start and finish',['A terminal marks start or end.','A flow line shows the next step.','Every intended path needs a clear destination.'],['TERMINAL: start / end','ARROW: next step','Follow one path at a time'], 'Why should an arrow have a clear direction?', 'It shows which instruction executes next.',match('Match the symbol name to its role.',[['Terminal','Start or end'],['Flow line','Direction of execution'],['Process','Calculation or assignment']],'A terminal is commonly drawn as an oval or rounded rectangle.')),
S('Read and write',['A parallelogram represents input or output.','Label the action and the data.','Inputs and outputs are different operations.'],['INPUT: borrower ID','INPUT: item ID','OUTPUT: loan result'], 'Which symbol should contain Input age?', 'An input/output parallelogram.',mc('Which action belongs in an input/output symbol?','Display the total','Set total to 0','Test total > 10','Start')),
S('Process the data',['A rectangle represents a process.','Use it for calculations or assignments.','Show the operation clearly.'],['PROCESS','charge = hours * rate','total = total + charge'], 'Which symbol should contain total = total + 3?', 'A process rectangle, because the value is being updated.',mc('Which label is a process?','total = price * quantity','Input quantity','Output total','Is quantity > 0?')),
S('Branch on a decision',['A diamond contains a condition.','Label outgoing paths Yes/No or True/False.','Both outcomes must be handled.'],['DECISION: available?','Yes: record loan','No: show unavailable','Both paths reach End'], 'What is missing if only the Yes path is drawn?', 'The behaviour when the item is unavailable is not defined.',mc('What belongs inside a decision diamond?','age >= 12','Input age','Print age','Start')),
S('Use a subprogram',['A predefined-process symbol calls a named subprogram.','Its detailed steps may be shown elsewhere.','It supports a clear top-level algorithm.'],['MAIN FLOW','Read item ID','Call checkAvailability','Use returned result'], 'How does a subprogram symbol help a large flowchart?', 'It keeps the main diagram manageable while detailed steps are defined separately.',mc('A rectangle with extra vertical lines at its sides usually means...','Subprogram or predefined process','Input/output','Start only','A decision')),
S('Check every route',['Trace each branch using sample data.','Check that arrows connect correctly.','Compare outputs with the requirement.'],['Test available = true','Expected: loan recorded','Test available = false','Expected: unavailable'], 'Why test both branches?', 'A correct true path does not prove the false path behaves correctly.',order('Order a simple flowchart design process.',['State inputs and required outputs','Choose symbols for the steps','Connect and label the paths','Trace each possible branch'],'Check the design before coding it.'))
],
[sort('Choose a flowchart symbol for each action.',['Input/output','Process','Decision'],[['Read hours','Input/output'],['charge = hours * 3','Process'],['charge > 12?','Decision'],['Print charge','Input/output']],'The symbol should match the action.'),mc('What must a decision have in this two-way flowchart?','A labelled path for each outcome','Only a Yes path','No outgoing arrows','Two start symbols')],
[['Name the symbols for input, a calculation and a decision. [3]','Parallelogram (1), rectangle (1), diamond (1).'],['Draw a flowchart that inputs age, outputs Allowed if age >= 12 and otherwise outputs Too young. [5]','Input age (1), correct decision (1), labelled branches (1), correct outputs (1), connected start/end paths (1).'],['Explain why testing only one path is insufficient. [2]','The other branch may contain an error (1), so a test must execute that branch too (1).']],
'Create the flowchart in a diagram tool or on paper. Implement it in Python and check ages 11, 12 and 13.')
L(12,'Pseudocode workshop','PseudocodeWorkshop','Producing algorithms: pseudocode',
'Translate a clear design into readable pseudocode and equivalent Python. Keep each decision and loop intact.',
'How can you explain an algorithm without choosing a particular programming language?',
['Write clear pseudocode.','Translate between algorithm representations.','Distinguish assignment and comparison.'],
'What happens after score = 5 followed by score = score + 2?',
'The value of score becomes 7. The second assignment replaces its previous value.',
[['Pseudocode','A readable description of algorithm steps using programming-like notation.'],['Assignment','Storing a value in a variable.']],
[
S('Readable instructions',['Pseudocode focuses on the algorithm.','Use consistent, unambiguous notation.','OCR exam reference language is one defined notation.'],['INPUT quantity','INPUT price','total = quantity * price','OUTPUT total'], 'Why must pseudocode still be precise?', 'Another person must be able to follow it and obtain the intended result.',mc('Which is an effective pseudocode instruction?','total = quantity * price','Work out something useful','Do the normal thing','Use some numbers')),
S('Assignment or equality',['Assignment changes a stored value.','A comparison checks a relationship.','In OCR notation, = assigns and == compares.'],['score = 7','Stores 7 in score','','score == 7','Tests whether score is 7'], 'Explain the different jobs of = and == here.', '= assigns a value. == compares two values and produces true or false.',match('Match the expression to its role.',[['count = 0','Assignment'],['count == 0','Equality comparison'],['count > 0','Greater-than comparison']],'The same variable can be assigned and later compared.')),
S('Write selection',['Put the true actions inside the IF branch.','Use ELSE for the alternative.','End the selection clearly.'],['if age >= 12 then','  print("Allowed")','else','  print("Too young")','endif'], 'What output is produced for age 12?', 'Allowed, because 12 >= 12 is true.',mc('Which line belongs at the end in OCR notation?','endif','next age','endwhile','input age')),
S('Write repetition',['Use a count-controlled loop for a fixed count.','Initialise a running total once.','Put repeated input and addition in the loop.'],['total = 0','for i = 1 to 3','  value = int(input())','  total = total + value','next i; print(total)'], 'Why is print(total) after the loop?', 'The required result is the final total after all three inputs have been added.',order('Order the running-total design.',['Initialise total to 0','Repeat input and addition three times','Finish the loop','Output total'],'Output at the end if only the final total is required.')),
S('Translate to Python',['Keep the same inputs, branches and outputs.','Python uses a colon and indentation.','Python range excludes its stop value.'],['# Python','for i in range(1, 4):','    print(i)','','Outputs: 1, 2, 3'], 'Why is the stop value 4 rather than 3?', 'Python range(1, 4) includes 1, 2 and 3 but excludes 4.',mc('Python range(3) produces which values?','0, 1, 2','1, 2, 3','0, 1, 2, 3','Only 3')),
S('Check equivalence',['Different representations can do the same job.','Use identical inputs to compare outputs.','Check loop counts and boundary conditions.'],['OCR: for i = 1 to 3','Python: range(1, 4)','Both repeat 3 times','Check the actual values too'], 'Why can a direct copy of loop bounds be wrong?', 'OCR for loops include the end value while Python range excludes the stop value.',mc('What best checks equivalent behaviour?','Trace both versions with the same inputs','Count the letters in each program','Use different inputs in each version','Compare only variable names'))
],
[mc('OCR for i = 2 to 4 prints i. Which Python range matches?','range(2, 5)','range(2, 4)','range(4)','range(1, 4)'),mc('Which describes pseudocode?','A precise readable description that need not execute as a program','Always valid Python','Always machine code','A diagram with no text')],
[['Write pseudocode to input quantity and unit price and output the total. [3]','Read both inputs (1), multiply them (1), output the product (1).'],['Write selection that outputs Free if cost == 0 and Pay otherwise. [3]','Correct equality test (1), Free on true path (1), Pay on false path (1).'],['Explain the loop-bound difference between OCR for and Python range. [2]','OCR for includes its end value (1). Python range excludes its stop value (1).']],
'Write the three-number total in Python, run it with 3, 4 and 5, and compare the output with your pseudocode. Expected total: 12.')
L(13,'Algorithm repair clinic','AlgorithmRepairClinic','Interpreting, correcting and completing algorithms',
'Predict what an algorithm actually does, identify a fault, and complete missing steps to meet its requirements.',
'Can code run successfully and still give the wrong answer?',
['Interpret algorithms using sample inputs.','Correct faulty conditions and updates.','Complete missing algorithm steps.'],
'A total-cost algorithm adds price and quantity. Is this the correct calculation?',
'No. Total cost requires price multiplied by quantity.',
[['Logic error','An error in the algorithm that produces unintended behaviour.'],['Refinement','Improving an algorithm so it meets its requirements more fully.']],
[
S('Read what is written',['Follow the code, not the intended outcome.','Record changing values in order.','Predict outputs before changing anything.'],['x = 4','y = x + 3','x = y * 2','print(x)'], 'What is printed and why?', '14. y becomes 7, then x is assigned 7 * 2.',mc('x = 2; y = x * 5; print(y + 1). Output?','11','10','15','3')),
S('Correct an operation',['Compare the calculation with the requirement.','Check using a small known example.','Change the faulty operation only.'],['Need: total cost','quantity = 3; price = 5','Wrong: total = quantity + price','Correct: quantity * price'], 'What are the wrong and correct results?', 'The wrong result is 8. The correct total is 15.',mc('A rectangle area uses length + width. Correction?','length * width','length - width','length / width','length == width')),
S('Correct a boundary',['Translate inclusive wording carefully.','Check the value exactly at the threshold.','A running program can still reject valid input.'],['RULE: score at least 40','Wrong: score > 40','Correct: score >= 40','Test: 39, 40, 41'], 'Which test exposes the error?', '40, because it should pass but the faulty condition rejects it.',mc('The rule is fewer than 10. Which condition fits?','n < 10','n <= 10','n > 10','n == 10')),
S('Complete an update',['A loop must move towards its end condition.','Choose an update consistent with the start.','Trace at least two iterations.'],['n = 3','while n > 0','  print(n)','  [missing update]','endwhile'], 'Complete the update so it prints 3, 2, 1.', 'n = n - 1.',mc('Which update makes this countdown terminate?','n = n - 1','n = n + 1','n = 3','n = n')),
S('Refine an omitted case',['Check whether every valid situation is handled.','Equal values often need their own case.','Refine the output rather than hiding the case.'],['if a > b: A wins','else: B wins','','Fault: a == b','Needs: draw result'], 'What happens incorrectly when a == b?', 'The ELSE branch declares B the winner even though the values are equal.',mc('How should the two-player comparison be refined?','Add a separate draw outcome for equal values','Always choose A','Remove all comparisons','Ignore equal inputs')),
S('Recheck the correction',['Retest the original failing input.','Check an input that previously worked.','One successful test is not proof of correctness.'],['Fix: score >= 40','Retest: 40 -> pass','Check: 39 -> fail','Check: 41 -> pass'], 'Why rerun a previously successful case?', 'The correction might accidentally break behaviour that was already correct.',order('Order the repair process.',['State the expected behaviour','Trace the faulty algorithm','Correct the identified fault','Retest failing and working cases'],'Use evidence to decide whether the correction works.'))
],
[mc('total = 0 inside a loop causes only the latest input to be kept. What is the fix?','Move total = 0 before the loop','Print total earlier','Reset total twice','Remove every input'),mc('A loop should visit indices 0 to 4. Which OCR loop fits?','for i = 0 to 4','for i = 1 to 4','for i = 0 to 5','for i = 4 to 4')],
[['Trace x = 3, y = x + 2, x = y * 4, print(x). Give y and the output. [2]','y = 5 (1), output 20 (1).'],['A loop starts n = 1 and repeats while n < 4 but never updates n. Explain and correct the fault. [3]','n remains 1 (1), so the condition stays true (1). Add n = n + 1 inside the loop (1).'],['An algorithm reports B wins whenever A is not greater than B. Explain a required refinement. [2]','Equal values are wrongly treated as a B win (1). Add an equality branch that outputs Draw (1).']],
'Implement the repaired countdown in Python. Confirm it prints 3, 2, 1 and stops. Change the initial value to 1 and check again.')
L(14,'Algorithm construction lab','AlgorithmConstructionLab','Producing algorithms: combined solutions',
'Design a complete equipment-hire calculation using inputs, selection, iteration and a running total.',
'How can you turn a long written requirement into a program you can check?',
['Extract requirements from a problem.','Combine sequence, selection and iteration.','Refine and test a complete solution.'],
'A club charges 3 per hour for each item. What is the charge for two items hired for 2 and 4 hours?',
'6 + 12 = 18. Calculate each item charge and add it to the total.',
[['Requirement','A statement of what a solution must do.'],['Nested structure','A control structure placed inside another control structure.']],
[
S('Read the requirements',['List every input and required output.','Separate rules from background detail.','Agree what valid inputs mean.'],['Hire three items','Input hours for each item','Each costs 3 per hour','Output combined charge'], 'Which inputs and output are required?', 'Three hour values are inputs. The combined charge is the output.',sort('Classify the stated requirement.',['Input','Process','Output'],[['Hours for each item','Input'],['Multiply hours by 3','Process'],['Add item charges','Process'],['Display combined charge','Output']],'Turn prose into clear data and operations.')),
S('Break down the solution',['Separate input, calculation and reporting.','Give each sub-problem a clear purpose.','Combine the results consistently.'],['HIRE PROGRAM','Read hire details','Calculate charges','Display total'], 'How could Calculate charges be refined?', 'Calculate each item charge, add it to the running total and apply any required discount.',mc('Which is a useful sub-problem?','Calculate one item charge','Choose an unrelated game','Hide all inputs','Remove the total')),
S('Build the running total',['Initialise total once before repetition.','Read hours for each item.','Add hours * 3 to the total.'],['total = 0','for item = 1 to 3','  hours = int(input())','  total = total + hours * 3','next item'], 'What total results from hours 1, 2 and 3?', '3 + 6 + 9 = 18.',order('Order the calculation.',['Set total to 0','Repeat input of hours for each item','Add hours times 3 to total each time','Finish the loop'],'The total must survive between iterations.')),
S('Apply a rule once',['Apply a whole-order discount after summing.','Match the threshold exactly.','Do not repeatedly discount intermediate totals.'],['If total >= 30','  total = total - 5','Then output total','30 becomes 25'], 'What should happen to totals 29 and 30?', '29 stays 29. 30 qualifies and becomes 25.',mc('A total of 33 gets 5 off. Final charge?','28','38','5','33')),
S('Selection inside repetition',['Decisions can apply to individual items.','Keep per-item rules inside the loop.','Keep whole-order rules after the loop.'],['For each item:','  if hours > 5 then','    flag long hire','After all items:','  apply order discount'], 'Where should a per-item long-hire check go?', 'Inside the loop, so every item is checked using its own hours.',mc('Which rule belongs after the loop?','Discount based on the combined order total','Read each item hours','Check each item availability','Calculate each item charge')),
S('Test the complete design',['Calculate expected results independently.','Test both sides of a decision boundary.','Record actual output and compare.'],['Hours: 1, 2, 3 -> 18','Hours: 3, 3, 4 -> 25','Second raw total: 30','Discount applied once'], 'Why is the second test useful?', 'It reaches the exact discount boundary of 30 and checks that the result is 25.',mc('Which expected output fits hours 4, 4, 4 with the stated discount?','31','36','41','12'))
],
[mc('Where should total = 0 be placed?','Before the item loop','Inside every iteration','After printing the answer','Only in the discount branch'),mc('Hours 2, 2, 5 at 3 per hour. Discount is 5 if total >= 30. Output?','27','22','30','9')],
[['Identify the inputs, processing and output of the hire program. [3]','Hours for each item (1), calculate and sum charges then apply the rule (1), combined charge (1).'],['Write pseudocode for three item-hour inputs at 3 per hour. Subtract 5 if total >= 30, then output the charge. [6]','Initialise total (1), three-iteration loop (1), input hours (1), accumulate hours * 3 (1), correct discount after loop (1), output final total (1).'],['Give inputs that test the exact discount threshold and state the expected output. [2]','For example 3, 3, 4 hours makes a raw total of 30 (1) and output 25 (1).']],
'Implement the full hire program in Python. Test 1, 2, 3 (18), 3, 3, 4 (25) and 4, 4, 4 (31). Compare each output with your design.')
L(15,'Bug investigation lab','BugInvestigationLab','Identifying common errors and fixes',
'Distinguish syntax and logic errors, identify faulty lines and explain precise corrections.',
'Why does a program running without an error message not prove it is correct?',
['Distinguish syntax and logic errors.','Locate and correct faulty code.','Use test evidence to verify a fix.'],
'Python print("Ready" is missing a closing bracket. Is the problem a syntax rule or a wrong calculation?',
'It breaks Python syntax because the opening parenthesis is not closed.',
[['Syntax error','Code that breaks the grammatical rules of the language.'],['Logic error','Validly structured code whose behaviour does not meet the intended requirement.']],
[
S('Syntax rules',['A language has rules for valid code.','Missing punctuation can break those rules.','Read the diagnostic and inspect nearby code.'],['# Python: faulty','print("Ready"','','# Correct','print("Ready")'], 'What single character fixes this example?', 'Add the closing parenthesis after the closing quote.',mc('Which is a Python syntax error?','A missing colon after an if condition','Multiplying when addition was intended','Using > instead of >= in a valid condition','Printing the wrong variable')),
S('Logic can be wrong',['A program can execute and give a wrong result.','Compare behaviour with the requirement.','Use known inputs to expose the fault.'],['Need average of a and b','Wrong: a + b / 2','Correct: (a + b) / 2','For 6 and 10: 8'], 'What does the wrong expression give for 6 and 10?', '11, because division happens before addition. The correct average is 8.',mc('Which expression correctly averages x and y?','(x + y) / 2','x + y / 2','x * y / 2','x - y / 2')),
S('Off-by-one errors',['A loop may run once too often or too little.','Check the start and end conventions.','Array indices must stay within their valid range.'],['Python list length: 4','Valid indices: 0, 1, 2, 3','Wrong: range(5)','Correct: range(4)'], 'Why is index 4 invalid for this list?', 'A four-item zero-indexed list ends at index 3.',mc('Python range(1, 4) repeats how many times?','3','4','5','1')),
S('Faulty initialisation',['A running total needs an initial value.','Initialise it once before the loop.','Repeated initialisation loses earlier work.'],['Wrong inside loop:','  total = 0','  total = total + value','Only last value survives'], 'Where should total = 0 be moved?', 'Before the loop, so earlier additions remain in the total.',mc('A counter starts at 1 but should count from zero. What type of fault can this cause?','A logic error in the count','Always a syntax error','A missing quotation mark','A translation requirement')),
S('Trace the faulty line',['Change one cause at a time.','Explain how the faulty line affects the result.','A renamed variable alone may not fix the rule.'],['Rule: age at least 12','Fault: if age > 12 then','Input: 12','Actual: rejected'], 'Give the corrected line and a reason.', 'Use if age >= 12 then. Equality must be included.',match('Match the fault to its correction.',[['Missing Python colon','Add : after the condition'],['Exclusive threshold','Use >= for at least'],['Counter never changes','Update the counter in the loop']],'Corrections should address the actual cause.')),
S('Verify with evidence',['Retest the input that exposed the error.','Check nearby and previously working cases.','Record expected and actual results.'],['Fix age >= 12','11 -> reject','12 -> accept','13 -> accept'], 'Why check 11 as well as 12?', 'It verifies that the correction has not started accepting values below the threshold.',order('Order the debugging steps.',['Reproduce the incorrect behaviour','Locate and explain the fault','Apply a targeted correction','Retest and compare outputs'],'An error message or wrong result is evidence to investigate.'))
],
[sort('Classify the errors.',['Syntax','Logic'],[['Python if x > 0 with no colon','Syntax'],['Average calculated as a + b / 2','Logic'],['Missing closing quote','Syntax'],['Discount applied below the wrong threshold','Logic']],'Syntax breaks language rules. Logic breaks the intended solution.'),mc('The corrected average works for 6 and 10. What should you conclude?','That test passes, but other suitable tests are still useful','Every possible input is proven correct','No logic errors can remain','Testing should never use equal inputs')],
[['State the difference between syntax and logic errors. [2]','Syntax breaks language grammar (1). Logic gives unintended behaviour even when the code is syntactically valid (1).'],['Correct average = a + b / 2 and explain why the change is needed. [3]','Use (a + b) / 2 (1). Division otherwise happens first (1). Parentheses add the values before halving (1).'],['A four-item Python list is accessed with range(5). Explain and correct the issue. [2]','It includes invalid index 4 (1). Use range(4) to visit indices 0 to 3 (1).']],
'In Python, test the faulty and corrected average with 6 and 10, then 4 and 4. Expected corrected outputs are 8 and 4.')
L(16,'Trace table observatory','TraceTableObservatory','Trace tables',
'Follow assignments, decisions and loops precisely. Record variable changes and outputs in trace tables.',
'How can you check what a program does without running it?',
['Complete trace tables.','Trace selection and nested iteration.','Use traces to locate logic errors.'],
'x = 2, x = x + 3, print(x). List each value stored in x and the output.',
'x is first 2 and then 5. The output is 5.',
[['Trace table','A table recording variable values and outputs while stepping through an algorithm.'],['Dry run','Following an algorithm manually with chosen inputs.']],
[
S('Record each change',['Follow statements in execution order.','Record a new value when a variable changes.','Keep outputs in their own column.'],['x = 2','y = x + 3','x = y * 2','print(x)','x: 2 then 10; y: 5'], 'What belongs in the output column?', '10, because only print(x) produces output.',mc('Does an assignment automatically produce output?','No, it changes stored data','Yes, every assignment prints','Only if the number is positive','Always twice')),
S('Use current values',['Use the most recently assigned value.','The right-hand side is evaluated first.','Then the new value replaces the old one.'],['a = 3','b = a + 2','a = b + 4','b = a - 1','Final: a = 9, b = 8'], 'What is b after its final assignment?', '8. The current value of a is 9, so b becomes 9 - 1.',mc('x = 4; x = x * 2; y = x + 1. What is y?','9','5','8','4')),
S('Trace only the chosen branch',['Evaluate the condition using current values.','Follow only the branch selected.','Skipped assignments do not change variables.'],['x = 7','if x >= 5 then','  y = x + 1','else: y = 0','print(y)'], 'Which assignment is skipped?', 'y = 0 is skipped because x >= 5 is true.',mc('For x = 3 in the displayed algorithm, what is printed?','0','4','7','8')),
S('Trace a running total',['Record each loop iteration.','Update the total using the current counter.','Output only where the algorithm says.'],['total = 0','for i = 1 to 3','  total = total + i','next i','print(total)'], 'What are the totals after iterations 1, 2 and 3?', '1, 3 and 6. The output after the loop is 6.',mc('Same algorithm but i = 1 to 4. Final total?','10','4','6','9')),
S('Trace nested loops',['The inner loop restarts for each outer value.','Record counter values in separate columns.','Do not merge distinct output events.'],['for a = 1 to 2','  for b = 1 to 2','    print(a + b)','  next b','next a'], 'List the outputs in execution order.', '2, 3, 3, 4.',mc('How many output events occur here?','4','2','3','1')),
S('Locate a fault with a trace',['Find the first unexpected value.','Link it to the statement that caused it.','Retest after making the correction.'],['total = 0','Inputs: 3, 4, 5','Wrong update: total = value','Totals: 3, 4, 5','Need: total = total + value'], 'Which update produces totals 3, 7 and 12?', 'total = total + value, which accumulates instead of replacing the total.',mc('Why is tracing useful for debugging?','It shows when values first differ from expectations','It automatically repairs code','It replaces every form of testing','It guarantees no syntax errors'))
],
[mc('total = 0. For i = 1 to 3, add i * 2. What is printed after the loop?','12','6','10','3'),mc('n = 4. While n > 1, print n then subtract 1. Outputs?','4, 3, 2','4, 3, 2, 1','3, 2, 1','Only 4')],
[['Trace x = 5, y = x - 2, x = y * 4, print(x). State each assignment and the output. [4]','x = 5 (1), y = 3 (1), x = 12 (1), output 12 (1).'],['A loop starts total = 0 and adds i for i = 1 to 4 inclusive. Give the total after each iteration. [4]','1 (1), 3 (1), 6 (1), 10 (1).'],['Explain how a trace table can help find a logic error. [2]','It records intermediate values in execution order (1), so the first wrong value can be linked to the statement that produced it (1).']])

EXTRA={
1:[('For recognising a camera icon, which detail is least necessary?','The exact serial number','The lens outline','The body outline'),('Which detail helps identify an overdue loan?','Due date','Favourite colour','Wallpaper pattern'),('Removing required corridor links is...','Too much simplification','Always useful abstraction','A sorting method'),('A fault description becomes relevant when...','Planning repairs','Finding a room by route','Comparing latitude'),('Hiding processing behind a button means...','Users need not manage every internal step','No processing occurs','The code has disappeared'),('A model should be judged against...','Its stated purpose','Its number of colours','How much detail it retains')],
2:[('The required output helps determine...','Which inputs are relevant','The computer brand','The number of wall colours'),('Which is further north: -15 or -4?','-4','-15','They are equal'),('Which comparison checks equal values?','A == B','A > B','A < B'),('A displayed fare is...','Output','Input','An arithmetic operation'),('Which input supports an age discount?','Passenger age','Passenger shoe brand','Vehicle colour'),('Which case checks equality?','8 and 8','8 and 9','-8 and 8')],
3:[('Which is a sub-problem of a loan system?','Process a return','Change the weather','Draw every classroom'),('The top box of a structure diagram is...','The complete system','Always the first output','A yes/no decision'),('Refinement means...','Breaking a large part into clearer smaller tasks','Removing all requirements','Only changing colours'),('Does left-to-right position in a structure diagram define execution order?','No','Yes, always','Only if the boxes are blue'),('A shared interface helps parts...','Exchange data consistently','Avoid all testing','Run without inputs'),('An omitted return function is found by checking...','The decomposition against the requirements','Only the font size','Only the logo')],
4:[('A useful algorithm must...','Reach the stated goal through precise steps','Depend on guessing','Always use exactly ten steps'),('Multiplying hours by rate is...','Processing','Input','A route map'),('Which must happen before outputting a calculated total?','Calculate the total','End the program','Discard the inputs'),('Which word often makes an instruction ambiguous?','Some','Exactly','Multiply'),('x = 3; x = x + 4; x = x * 2. Output?','14','11','10'),('3 items cost 4 each. Why is output 7 wrong?','It adds instead of multiplying','It multiplies correctly','It uses no inputs')],
5:[('An IF condition evaluates to...','True or false','Only a string','Always 1'),('Which age is excluded by age > 12 but included by age >= 12?','12','13','14'),('Which result fits a = 9 and b = 4?','A wins','B wins','Draw'),('true AND false is...','False','True','Undefined'),('true OR true is...','True','False','Only one true is allowed'),('An inner branch inside a false outer IF is...','Skipped','Always executed','Repeated twice')],
6:[('OCR for i = 2 to 5 executes...','4 times','3 times','5 times'),('Which loop can execute zero times?','A while loop','Every do-until loop','A loop fixed at three repetitions'),('Where should a running total normally be initialised?','Before the loop','After every addition','After the final output'),('x = 0, while x < 3, x = x + 1. Final x?','3','2','4'),('Count values > 5 in [5, 6, 2, 8]. Count?','2','3','4'),('Outer 3, inner 4, both fixed counts. Inner runs?','12','7','4')],
7:[('Search [8, 6, 4] for 8. Comparisons?','1','3','0'),('Must linear search sort its input first?','No','Yes','Only for numbers'),('An absent target in six items needs how many target comparisons?','6','1','3'),('What does i = i + 1 do in a linear search?','Moves to the next index','Sorts the list','Changes the target'),('In [6, 2, 9, 4], index 1 stores...','2','6','9'),('The best-case linear search finds the target...','At the first item','At the last item','After checking every item')],
8:[('Binary search on unsorted data can...','Discard the half containing the target','Always find the target','Sort the data automatically'),('low = 0, high = 6. Rounded-down midpoint?','3','6','2'),('If target < data[mid], which update is correct?','high = mid - 1','low = mid + 1','high = mid + 1'),('For [3,6,9,12,15,18,21], target 18 is at index...','5','6','18'),('When low > high, the remaining range is...','Empty','The whole list','One definite match'),('Why can binary search scale well?','It discards about half the remaining items each time','It checks all items every time','It makes sorting free')],
9:[('Comparing adjacent values means comparing...','Neighbouring items','Only first and last items','Random items'),('After the first pass on [5,1,4,2], the final item is...','5','2','1'),('After two passes on [5,1,4,2], the list is...','1,2,4,5','1,4,2,5','5,4,2,1'),('A comparison always produces a swap. Is this true?','No','Yes','Only for equal values'),('Without saving a value before overwriting it, a swap may...','Lose an original value','Sort the whole list','Create a new index'),('When should swapped be reset to false?','Before each pass','Only after a swap','After every comparison')],
10:[('Merge sort splits until...','Single-item lists remain','All values are equal','The list is already reversed'),('Which value is chosen first when merging [4,9] and [2,7]?','2','4','9'),('After taking left[i], which pointer advances?','i','j','Both every time'),('Insertion sort grows...','A sorted prefix','An unsorted prefix only','A binary search range'),('When inserting 5 into [2,7,9], which values shift?','7 and 9','Only 2','2, 7 and 9'),('Which method splits and merges groups?','Merge sort','Bubble sort','Linear search')],
11:[('Which symbol marks the end?','Terminal','Decision diamond','Input parallelogram'),('Output total is drawn in...','An input/output symbol','A decision diamond','A terminal only'),('Assign total = 0 is drawn in...','A process rectangle','An input/output symbol','A decision diamond'),('The two paths from a condition can be labelled...','True and False','Start and End only','Input and Output only'),('A subprogram symbol refers to...','A defined set of steps elsewhere','An undefined random operation','Only a variable value'),('A disconnected branch means...','The next step is unclear','The flowchart is automatically correct','The branch runs faster')],
12:[('Pseudocode should be...','Clear enough to trace','Deliberately vague','Identical to machine code'),('After x = 4 then x = 7, x contains...','7','4','11'),('For age 11, the displayed selection outputs...','Too young','Allowed','Both messages'),('Why initialise total once?','So repeated additions accumulate','So every input is discarded','So no loop is needed'),('Python range(1, 3) yields...','1 and 2','1, 2 and 3','0, 1 and 2'),('Equivalent representations should produce...','The same specified outputs for the same inputs','Different results by design','The same number of characters')],
13:[('x = 4; y = x + 3. What is y?','7','3','12'),('For length 6 and width 2, area is...','12','8','4'),('Which value exposes > 40 used for at least 40?','40','41','50'),('A countdown from 3 using n = n - 1 should stop at...','0 when the condition is n > 0','3','4'),('A draw should be reported when...','a == b','a > b','a < b'),('Retesting a previously working input checks...','The fix has not broken existing behaviour','That testing is unnecessary','Only the variable spelling')],
14:[('For one item at 3 per hour for 5 hours, charge is...','15','8','2'),('A structure diagram is useful for...','Organising the main sub-problems','Showing every loop iteration','Printing the bill'),('Hours 1, 2, 3 at 3 per hour total...','18','6','9'),('Total 29 with a discount at >= 30 becomes...','29','24','34'),('A decision inside a loop is...','Nested selection','A separate input only','Abstraction with no processing'),('Hours 3, 3, 4 before the discount total...','30','25','10')],
15:[('Python print("Ready") has...','Balanced parentheses','A missing closing parenthesis','No valid string'),('For a = 6, b = 10, a + b / 2 gives...','11','8','16'),('Last valid zero-based index in a five-item list?','4','5','1'),('Resetting total in each iteration causes...','Previous additions to be lost','A syntax error in every language','The correct overall sum'),('A missing Python colon is corrected by...','Adding the colon after the condition','Changing + to *','Resetting a counter'),('A passing test proves...','That tested case produced the expected result','All possible cases are correct','The program has no remaining errors')],
16:[('A trace table records output...','Only when an output statement executes','After every assignment automatically','Before inputs are known'),('a = 3; b = a + 2; a = b + 4. Final a?','9','7','3'),('A skipped ELSE assignment should...','Not change its variable','Still be executed','Always set it to zero'),('Totals after adding 1, then 2, then 3 from zero?','1, 3, 6','1, 2, 3','0, 1, 2'),('Outer a = 1..2, inner b = 1..2, print a+b. First output?','2','1','4'),('total = value differs from total = total + value because it...','Replaces the total instead of accumulating','Always gives the same result','Is always a syntax error')]
}
for l in LESSONS:
 for s,row in zip(l['stations'],EXTRA[l['n']]):s['tasks'].append(mc(*row,fb=row[1]+'. '+s['facts'][0]))

if __name__ == "__main__":
 Path(__file__).with_name("content.json").write_text(json.dumps(LESSONS, indent=2, ensure_ascii=False))
 print(len(LESSONS), "lessons")
