# Wall bullets, read back off the rendered 1.6 scenes so the decks match the rooms exactly.
B = {
"el-l01": [
 ["A new system is judged on far more than whether it works.",
  "Six kinds of impact come up again and again: ethical, legal, cultural, environmental, privacy and the wider effect on society.",
  "Most real decisions involve several at once, pulling in different directions."],
 ["An ethical issue asks whether something should be done, not whether it can be.",
  "Examples: tracking people's location, using AI to mark exams, selling data about children, automating jobs away.",
  "There is rarely one right answer, which is why the exam asks you to discuss both sides."],
 ["A good answer gives arguments for, arguments against, and a conclusion you can defend.",
  "Each argument needs a reason and, ideally, who it affects.",
  "'It's bad' is not an argument. 'It's bad because…, which harms…' is."],
 ["A stakeholder is anyone affected by a system: users, staff, customers, the wider public.",
  "The same change helps some stakeholders and harms others.",
  "Naming the stakeholders is usually the first mark in an impact question."],
 ["Copying films, music, games or software without paying is illegal, and it is also an ethical question.",
  "For: content is expensive, some is unavailable legally, one copy costs the maker nothing extra.",
  "Against: creators lose income, studios make fewer risky projects, the money funds crime."],
 ["Name the impact: ethical, legal, cultural, environmental, privacy.",
  "Name the stakeholders and say how each is affected.",
  "Give both sides, then conclude."]],
"el-l02": [
 ["Personal data is anything that identifies you, on its own or combined with something else.",
  "Typical collection: what you search, where you go, who you message, how long you look at something.",
  "Data is valuable because it predicts what you will do next."],
 ["Cookies and identifiers follow a device from site to site, building a profile.",
  "Apps can request location, contacts, microphone and camera, often for features that don't need them.",
  "A profile built from many small facts can be more revealing than any single one."],
 ["Consent should be informed, freely given and easy to withdraw.",
  "In practice it is often a long notice nobody reads, or a design that makes refusing hard.",
  "Children's data has stronger protection in law, because consent is harder to give meaningfully."],
 ["Collecting data does bring real benefits: better services, safety features, fraud detection, research.",
  "It also brings risks: profiling, discrimination, breaches, and being watched.",
  "Almost every privacy question is a trade-off, not a villain."],
 ["A data breach exposes data that was collected for a legitimate reason.",
  "The harm is real: fraud, blackmail, and details that cannot be made private again.",
  "The best protection is not collecting what isn't needed, and deleting what is no longer used."],
 ["Name what is collected, who gets it, and what could go wrong.",
  "Weigh the benefit against the risk for each stakeholder.",
  "Conclude with a limit you can defend: what should be allowed, and what shouldn't."]],
"el-l03": [
 ["Governs how organisations collect, store and use personal data.",
  "Data must be used fairly and lawfully, for a stated purpose, kept accurate, kept no longer than needed, and kept secure.",
  "People have rights: to see their data, to correct it, and in many cases to have it deleted."],
 ["Created to deal with hacking, which no earlier law covered.",
  "Three main offences: unauthorised access; unauthorised access with intent to commit a further offence; unauthorised modification of data.",
  "Access without permission is an offence even if nothing is changed or taken."],
 ["Protects the creator of original work: software, music, film, writing, images.",
  "Copying, sharing or selling without permission infringes copyright.",
  "It applies automatically the moment work is created: no registration needed."],
 ["Personal data misused or leaked: Data Protection Act.",
  "Access, hacking or changing data without permission: Computer Misuse Act.",
  "Copying or sharing someone's creative work: Copyright, Designs and Patents Act."],
 ["Freedom of Information allows anyone to request information held by public bodies, such as what a council spent.",
  "It covers public information, not personal data about individuals.",
  "Health and safety, equality and consumer law also apply to technology."],
 ["Name the Act in full, including the year, then state the relevant principle.",
  "Say which part of the situation breaches it.",
  "If more than one Act applies, say so: many real cases involve two."]],
"el-l04": [
 ["Shopping, banking, learning, healthcare and government moved online within a generation.",
  "That is faster and cheaper for people who can get online.",
  "Services that used to have a counter or a phone line increasingly have neither."],
 ["The digital divide is the gap between people who have good access to technology and those who don't.",
  "Causes: cost of devices and data, poor broadband, age, disability, and skills.",
  "Effects: worse access to education, jobs, cheaper prices and public services."],
 ["Public wifi, libraries and school device loans widen access.",
  "Subsidised connections and low-cost devices lower the cost barrier.",
  "Training matters as much as hardware: a device nobody can use helps nobody."],
 ["Networks let a company work across many countries at once, around the clock.",
  "Work can be done wherever it is cheapest, which creates jobs in some places and removes them in others.",
  "Culture travels too: the same films, games and platforms reach almost everywhere."],
 ["Remote working spread when networks made it practical, changing commuting, offices and town centres.",
  "Automation removes repetitive jobs and creates different ones, usually needing different skills.",
  "The people who lose a job are rarely the ones who get the new one."],
 ["Name the group affected before saying how.",
  "Use the words the specification uses: digital divide, globalisation, automation, access.",
  "Discuss means both sides, then a conclusion you can defend."]],
"el-l05": [
 ["Every device has an environmental cost at three stages: manufacture, use and disposal.",
  "For a phone, manufacture is usually the largest share by far.",
  "Judging a device on its running cost alone misses most of its impact."],
 ["Devices need metals that are mined, including rare earth elements, gold, copper and lithium.",
  "Mining and refining use energy and water, and can pollute land and rivers.",
  "Some materials come from areas with poor working conditions or conflict."],
 ["Devices use electricity, and so do the networks and data centres behind them.",
  "Streaming, cloud storage and AI all move the energy cost from your device to a building somewhere else.",
  "Where the electricity comes from decides how much carbon that energy represents."],
 ["Electronic waste is the fastest growing waste stream in the world.",
  "Devices contain toxic materials: lead, mercury, cadmium. In landfill these leak into soil and water.",
  "Much e-waste is shipped abroad and stripped by hand, often in unsafe conditions."],
 ["Repair, reuse and upgrade extend a device's life, which is the biggest single saving.",
  "Proper recycling recovers metals so they need not be mined again.",
  "Designing for repair, and laws requiring spare parts, change what is possible."],
 ["Say which stage you mean: manufacture, use or disposal.",
  "Give the mechanism, not just the label: what is used, emitted or leaked, and why that matters.",
  "Where there is a trade-off, name it: recycling costs money, longer life means older technology."]],
"el-l06": [
 ["Ask who uses it, who runs it, who pays for it, and who is affected without choosing to be.",
  "The last group is the one students forget, and often where the marks are.",
  "List them before writing anything else."],
 ["Local: this street, this school, this town.",
  "National: jobs, laws, infrastructure and services across the country.",
  "Global: supply chains, emissions, and where the work and waste actually go."],
 ["Read the scenario twice: once for what changes, once for who it touches.",
  "For each stakeholder, ask what they gain, what they lose, and what they now have to do differently.",
  "Then decide which impacts are big enough to write about."],
 ["Almost every scenario has a genuine benefit and a genuine cost.",
  "Answers that only attack, or only praise, lose marks.",
  "State the trade-off plainly: what is gained, at whose expense."],
 ["A conclusion is a position, not a summary.",
  "Say what should happen, and which argument decided it for you.",
  "A condition is often the strongest conclusion: yes, provided that…"],
 ["A hospital replaces paper notes with tablets carried by every nurse.",
  "Stakeholders: patients, nurses, doctors, IT staff, administrators, the trust's finances.",
  "Impacts run from bedside to national policy."]],
"el-l07": [
 ["A software licence sets out what you may do with the program: use it, copy it, change it, share it.",
  "Buying software usually buys a licence to use it, not ownership of it.",
  "Breaking the licence terms is a copyright matter, from lesson 3."],
 ["The source code is kept secret and cannot be modified by users.",
  "Usually paid for, with a licence limiting how many machines or users.",
  "Comes with professional support, tested releases and, often, training and warranties."],
 ["The source code is published, and may be used, changed and shared under the licence terms.",
  "Usually free of charge, though not always.",
  "Support comes from the community, or from a company paid to provide it."],
 ["Proprietary: licence fees, but support is part of the deal.",
  "Open source: no licence fee, but you may need staff who can maintain it, or a paid support contract.",
  "Free to download is not the same as free to run."],
 ["Think about budget, the skills available, how critical the system is, and whether it must be adapted.",
  "Critical systems with no in-house expertise point to proprietary; tight budgets with technical staff point to open source.",
  "Many organisations run both, choosing per job."],
 ["Open source does not mean unlicensed: the licence still sets conditions.",
  "Open source is not automatically less secure, nor automatically more secure.",
  "Proprietary does not always mean paid, and free does not always mean open source."]],
}
