#!/usr/bin/env python3
"""What the revision bank covers, written out from the bank itself.

docs/REVISION-QUIZ-COVERAGE.md is generated by this, not maintained by hand,
because a coverage table kept by hand is a coverage table that is wrong. It
reports what is there and, more usefully, what is not: the lessons no question
points at and the outcomes nothing asks about. Section 30 asks that every
question maps to a lesson and a station; this is the other direction, and it is
the one that shows the holes.

    python3 tools/revcoverage.py            # print it
    python3 tools/revcoverage.py --write    # write docs/REVISION-QUIZ-COVERAGE.md
"""
import collections
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import revschema as S

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "REVISION-QUIZ-COVERAGE.md"


def main():
    bank = S.load_bank()
    stations = S.load_stations()
    lessons = stations["lessons"]

    by_topic = collections.defaultdict(list)
    for q in bank:
        by_topic[q["topic"]].append(q)

    L = []
    w = L.append
    w("# What the revision bank covers")
    w("")
    w("Generated by `tools/revcoverage.py` from `revision/`, so it cannot drift from")
    w("the bank it describes. Every number here is a count of what is on disk.")
    w("")
    w("A question is tied to one station of one lesson, and that is where \"revisit")
    w("this\" sends a learner. This file reads that mapping backwards: for each")
    w("lesson, how many questions point at it, and which of its stations and")
    w("outcomes nothing asks about at all.")
    w("")
    w("## The bank")
    w("")
    w("| topic | | questions | marks | subtopics | lessons reached |")
    w("|---|---|---:|---:|---:|---|")
    for topic in sorted(by_topic, key=lambda t: (S.PAPER[t], t)):
        qs = by_topic[topic]
        subs = {q["subtopic"] for q in qs}
        reached = {q["revisitLessonId"] for q in qs if q.get("revisitLessonId")}
        mine = sorted(l for l in lessons if lessons[l]["unit"] == topic
                      and lessons[l].get("stations"))
        w("| %s | %s | %d | %d | %d | %d of %d |"
          % (topic, S.TOPIC_TITLE[topic], len(qs), sum(q["marks"] for q in qs),
             len(subs), len(reached), len(mine)))
    w("| | **total** | **%d** | **%d** | **%d** | |"
      % (len(bank), sum(q["marks"] for q in bank),
         len({(q["topic"], q["subtopic"]) for q in bank})))
    w("")

    # ---- families and types
    w("## Question families")
    w("")
    w("Section 8 asks for a mix rather than a pile of one kind. The ranges are its,")
    w("not ours.")
    w("")
    w("| family | questions | share | section 8 asks for |")
    w("|---|---:|---:|---|")
    for name, (lo, hi) in sorted(S.BALANCE.items()):
        n = sum(1 for q in bank if kind(q["type"]) == name)
        w("| %s | %d | %d%% | %d-%d%% |"
          % (name, n, round(100 * n / len(bank)), round(100 * lo), round(100 * hi)))
    ex = sum(1 for q in bank if q.get("examStyle"))
    lo, hi = S.EXAM_STYLE_BAND
    w("| exam-style | %d | %d%% | %d-%d%% |"
      % (ex, round(100 * ex / len(bank)), round(100 * lo), round(100 * hi)))
    w("")
    w("| type | questions | | type | questions |")
    w("|---|---:|---|---|---:|")
    types = collections.Counter(q["type"] for q in bank).most_common()
    half = (len(types) + 1) // 2
    for i in range(half):
        a = "`%s` | %d" % types[i]
        b = ("`%s` | %d" % types[i + half]) if i + half < len(types) else " | "
        w("| %s | | %s |" % (a, b))
    w("")

    # ---- per lesson
    w("## Every lesson, and what points at it")
    w("")
    w("A lesson with no questions is not a bug on its own - a revision HQ lesson or")
    w("an end-of-topic test has nothing of its own to revise, and its content is")
    w("asked about through the lessons it revises. A teaching lesson with none is a")
    w("gap, and they are listed separately below.")
    w("")
    per_lesson = collections.Counter(q.get("revisitLessonId") for q in bank)
    per_station = collections.defaultdict(set)
    per_outcome = collections.Counter()
    for q in bank:
        if q.get("revisitStationId"):
            per_station[q["revisitLessonId"]].add(q["revisitStationId"])
        for o in q.get("outcomes") or []:
            per_outcome[o] += 1

    empty_teaching, empty_revision, empty_other = [], [], []
    w("| topic | lesson | title | questions | stations with questions | outcomes asked |")
    w("|---|---|---|---:|---|---|")
    for lid in sorted(lessons, key=lambda l: (S.PAPER.get(lessons[l]["unit"], 9),
                                              lessons[l]["unit"], lessons[l]["lesson"])):
        Lsn = lessons[lid]
        if Lsn["unit"] not in S.TOPIC_TITLE:
            continue
        sts = Lsn.get("stations") or []
        outs = list(Lsn.get("outcomeText") or {})
        n = per_lesson.get(lid, 0)
        if not n:
            if not sts:
                empty_other.append((Lsn["unit"], lid, Lsn["title"]))
            elif Lsn.get("kind") == "challenge" or "Revision HQ" in Lsn["title"]:
                empty_revision.append((Lsn["unit"], lid, Lsn["title"]))
            else:
                empty_teaching.append((Lsn["unit"], lid, Lsn["title"]))
            continue
        asked = sum(1 for o in outs if per_outcome.get(o))
        w("| %s | `%s` | %s | %d | %d of %d | %d of %d |"
          % (Lsn["unit"], lid, Lsn["title"], n,
             len(per_station.get(lid, ())), len(sts), asked, len(outs)))
    w("")

    w("## Lessons nothing points at")
    w("")
    if empty_teaching:
        w("These teach something of their own and nothing asks about it. They are")
        w("gaps:")
        w("")
        for unit, lid, title in empty_teaching:
            w("- %s `%s` %s" % (unit, lid, title))
    else:
        w("Every teaching lesson has at least one question against it.")
    w("")
    if empty_revision:
        w("These are revision and challenge lessons. They have stations, but the")
        w("stations revise other lessons rather than teaching anything of their own,")
        w("so a question sends a learner to the lesson that taught it instead:")
        w("")
        w(", ".join("`%s`" % lid for _, lid, _ in empty_revision))
        w("")
    if empty_other:
        w("These have no stations - revision and assessment lessons - so there is")
        w("nothing for a question to revisit:")
        w("")
        w(", ".join("`%s`" % lid for _, lid, _ in empty_other))
        w("")

    # ---- outcomes
    all_outs = []
    for lid, Lsn in lessons.items():
        if Lsn["unit"] in S.TOPIC_TITLE:
            all_outs += [(lid, o, t) for o, t in (Lsn.get("outcomeText") or {}).items()]
    asked = [x for x in all_outs if per_outcome.get(x[1])]
    w("## Outcomes")
    w("")
    w("%d of the %d lesson outcomes in the eleven topics have at least one question"
      % (len(asked), len(all_outs)))
    w("against them. An outcome with none is not necessarily untested - a question")
    w("names the outcomes of its own subtopic, and one question often covers ground")
    w("belonging to two - but it is where to look next.")
    w("")
    missing = collections.defaultdict(list)
    for lid, o, t in all_outs:
        if not per_outcome.get(o):
            missing[lessons[lid]["unit"]].append((o, t))
    if missing:
        w("| topic | outcome | what it asks for |")
        w("|---|---|---|")
        for unit in sorted(missing, key=lambda u: (S.PAPER[u], u)):
            for o, t in missing[unit]:
                w("| %s | `%s` | %s |" % (unit, o, t.strip().rstrip(".")))
        w("")

    text = "\n".join(L) + "\n"
    if "--write" in sys.argv:
        OUT.write_text(text, encoding="utf-8")
        print("wrote %s (%d lines)" % (OUT.relative_to(ROOT), len(L)))
    else:
        print(text)
    return 0


def kind(t):
    for name, types in (("recognition", S.SELECTED), ("written", S.WRITTEN),
                        ("written", S.SELF_REVIEW), ("computed", S.COMPUTED)):
        if t in types:
            return name
    return "other"


if __name__ == "__main__":
    sys.exit(main())
