from kit import mcq, multi, sort, match, order

K13 = "1.3 Computer networks, connections and protocols"
SUB13 = "OCR J277 Paper 1  |  Computer systems"

L3 = dict(id="nw-l03", topic="1.3", lesson=3, title="Network showdown", img="NW_L03_NetworkShowdown_360",
  description="Client-server takes on peer-to-peer. Find out who does what in each model, then settle the torrent debate.",
  kicker=f"{K13}  |  Lesson 3", scene_title="Network showdown", subtitle=SUB13,
  intro="Two ways to organise a network go head to head: client-server and peer-to-peer. Find out which computers do what in each model, then decide which one wins for different situations.",
  keywords=["Client", "Server", "Peer", "Client-server", "Peer-to-peer", "Torrent"],
  stations=[
   dict(name="Client-server model", bullets=["A central server provides services such as files, logins, email or web pages.",
        "Clients request services from the server, and the server responds.", "Used by most schools and businesses."],
        challenge="Name three services your school's servers provide when you use a computer.", ill=("clientserver",),
        fact="In a client-server network, the server... and the clients...",
        tasks=[mcq("In a client-server network, what does a client do?", "Requests services, such as files or web pages, from a server",
                   ["Provides services to every other computer", "Connects the network to the internet", "Stores everyone's backups"],
                   "Clients ask; servers provide. Connecting to the internet is the router's job."),
               mcq("Which of these is acting as a server?", "A computer that stores students' files and checks their logins",
                   ["A laptop being used to write an essay", "A phone browsing a website", "A printer cable"],
                   "A server provides a service to other computers on the network.")]),
   dict(name="Peer-to-peer model", bullets=["There is no central server: every computer is an equal peer.",
        "Peers share files and resources directly with each other.", "Each user looks after their own files, security and backups."],
        challenge="Where might you find a peer-to-peer network at home?", ill=("icons", [("laptop", "Peer"), ("pc", "Peer"), ("laptop", "Peer")]),
        fact="In a peer-to-peer network, each computer...",
        tasks=[mcq("What is a peer in a peer-to-peer network?", "A computer that both requests and provides resources, as an equal",
                   ["A computer that only requests services", "The central server", "The network's router"],
                   "Peers act as both client and server, sharing directly with each other."),
               mcq("Who is responsible for backups in a peer-to-peer network?", "Each user, for their own computer",
                   ["A network manager", "The central server", "The internet service provider"],
                   "With no server, there's no central backup: every user has to manage their own.")]),
   dict(name="Client-server: pros and cons", bullets=["Easier to manage security, backups and software updates from one place.",
        "Expensive to set up, and needs IT specialists to maintain it.", "The server is a single point of failure."],
        challenge="Why does a school choose client-server rather than peer-to-peer?",
        ill=("tiles", [("Central backups", "g"), ("File security", "g"), ("Easy updates", "g"), ("Expensive", "r"), ("Needs IT staff", "r"), ("Single point of failure", "r")], 3),
        fact="The main advantages of client-server are... The main disadvantages are...",
        tasks=[mcq("Which is an advantage of a client-server network?", "It is easier to take backups of all the shared data",
                   ["It is cheaper to set up", "There is no dependency on a single machine", "No specialist staff are needed"],
                   "All the shared data is stored on the server, so one backup covers it. The other options describe peer-to-peer."),
               mcq("Why is the server a single point of failure?", "If it stops working, the clients can't reach the files and services it provides",
                   ["Only one person can log in at a time", "It can only store one file", "It has only one network cable"],
                   "Everything depends on the server, so a server failure affects every client.")]),
   dict(name="Peer-to-peer: pros and cons", bullets=["Cheaper and easier to set up: no expensive server is needed.",
        "No dependency on a single machine.", "Less secure, harder to keep files organised, and users must do their own backups."],
        challenge="A family business has three computers. Would you recommend peer-to-peer? Why?",
        ill=("tiles", [("Cheap to set up", "g"), ("No server needed", "g"), ("Easy to maintain", "g"), ("Less secure", "r"), ("Own backups", "r"), ("Messy file store", "r")], 3),
        fact="The main advantages of peer-to-peer are... The main disadvantages are...",
        tasks=[mcq("Which is a disadvantage of peer-to-peer?", "Users need to manage their own backups",
                   ["Needs expensive server hardware", "Requires IT specialists to maintain", "The server is a single point of failure"],
                   "The other three are disadvantages of client-server."),
               mcq("Why is peer-to-peer usually cheaper to set up?", "No expensive server hardware is needed",
                   ["It doesn't need any cables", "It only works with one computer", "It doesn't need electricity"],
                   "The peers are ordinary computers, so there's no server to buy or specialist to pay.")]),
   dict(name="Who's who?", bullets=["Servers provide services and resources.", "Clients request them.", "Peers do both, as equals."],
        challenge="Label each device on the wall diagram as a server, client or peer.", ill=("clientserver",),
        fact="A server... A client... A peer...",
        tasks=[match("Match each role to what it does.", [["Server", "Provides services and resources to other computers"],
                     ["Client", "Requests services from a server"], ["Peer", "Both requests and provides resources, as an equal"]],
                     "These are the definitions to learn for the exam."),
               mcq("A games console downloads an update from the manufacturer's server. What is the console?", "A client",
                   ["A server", "A peer", "A router"], "The console requests the update, so it is the client.")]),
   dict(name="How torrents work", bullets=["A big file is split into many small pieces.",
        "Your computer downloads different pieces from lots of other users at once, and uploads pieces to others.",
        "The more people sharing, the faster it can be."],
        challenge="Is torrenting client-server or peer-to-peer? Is it a quicker or slower way to download big files, and why?",
        ill=("flow", ["File split into pieces", "Pieces from many peers", "You share pieces too", "File rebuilt"]),
        fact="Torrenting works by...",
        tasks=[mcq("Torrenting is an example of which model?", "Peer-to-peer", ["Client-server", "Standalone", "Star topology"],
                   "Every user's computer shares pieces directly with the others, so they act as peers."),
               mcq("Why can torrent downloads be fast?", "Pieces come from many peers at the same time, so no single server limits the speed",
                   ["Torrent files are always tiny", "They skip the internet", "Only one person can download at once"],
                   "Lots of peers each sending a piece adds up to a fast download, especially for popular files.")]),
  ],
  final=dict(name="Final challenge: client-server or P2P?", floor_title="Final challenge: client-server or peer-to-peer?",
    intro="Twelve statements from the network review. Tap the star and sort each one into client-server or peer-to-peer.",
    ill=("compare", "Client-server", ["Central server", "Clients request", "Managed by IT staff"], "Peer-to-peer", ["No server", "Equal peers", "Users manage it"], "b", "p"),
    tasks=[sort("Does each statement describe client-server or peer-to-peer?", ["Client-server", "Peer-to-peer"], [
      ["Each user has to back up their own machine", "Peer-to-peer"], ["Files end up scattered and hard to find", "Peer-to-peer"],
      ["No expensive central machine to buy", "Peer-to-peer"], ["One nightly backup covers everyone's shared work", "Client-server"],
      ["Carries on working if one computer is switched off", "Peer-to-peer"], ["Security settings are hard to apply consistently", "Peer-to-peer"],
      ["Permissions are set once, centrally", "Client-server"], ["Needs trained staff to look after it", "Client-server"],
      ["New software can be pushed to every machine at once", "Client-server"], ["Costs more to buy and to run", "Client-server"],
      ["Anyone can set it up without training", "Peer-to-peer"], ["Everything stops if the central machine fails", "Client-server"]],
      "Now mark each statement on your worksheet: is it an advantage or a disadvantage?")]),
  info=[(0, "Virtual servers", "One powerful physical computer can run many virtual servers at once, each acting as a separate server. Most school and cloud servers work this way."),
        (1, "Napster", "In 1999, Napster made peer-to-peer music sharing famous. It was shut down in 2001 after legal action, because most of the music was shared without permission."),
        (2, "Server rooms", "Servers are kept in locked, air-conditioned rooms, often with backup power supplies, because a server failure affects everyone."),
        (3, "P2P is legal", "Peer-to-peer technology is completely legal. What's illegal is sharing copyrighted films, music or games without permission."),
        (4, "Online games", "Most online games use dedicated servers. Some older games used peer-to-peer, where one player's console hosted the match for everyone."),
        (5, "Updates from peers", "Some operating systems can download pieces of an update from other computers on your network, peer-to-peer, instead of all from the maker's servers.")],
  ws=dict(title="Client-server and peer-to-peer", objectives=["know what a client-server model is", "know what a peer-to-peer model is", "understand the different roles computers have in each model"],
    starter="A class of 30 needs to share one big video file. Describe two ways it could be done, and say which would be quicker.",
    keyterms=["Client-server", "Peer-to-peer"], keyq="What are the differences between peer-to-peer and client-server networks?",
    exam=[("Describe what a server does in a client-server network.", 2, 2), ("Give two reasons a small office might choose peer-to-peer.", 2, 2),
          ("A school is choosing between client-server and peer-to-peer. Recommend one and justify your choice using two characteristics.", 6, 6)],
    confidence=["What a client-server model is", "What a peer-to-peer model is", "The roles of servers, clients and peers"]))

L5 = dict(id="nw-l05", topic="1.3", lesson=5, title="Inside the internet", img="NW_L05_InsideTheInternet_360",
  description="Find out what the internet really is, how DNS finds websites, and what hosting and the cloud mean.",
  kicker=f"{K13}  |  Lesson 5", scene_title="Inside the internet", subtitle=SUB13,
  intro="You use the internet every day, but what actually is it? Find out how websites are found, where they live, and what people really mean by 'the cloud'.",
  keywords=["Internet", "DNS", "Domain name", "IP address", "Hosting", "Cloud", "Web server"],
  stations=[
   dict(name="What is the internet?", bullets=["A worldwide collection of computer networks: the biggest WAN.",
        "Networks are joined by routers and linked by cables, including undersea fibre.", "The World Wide Web is a service that uses the internet; it isn't the internet itself."],
        challenge="Define the internet in one sentence.", ill=("worldmap",), fact="The internet is...",
        tasks=[mcq("What is the internet?", "A worldwide collection of connected computer networks", ["All the websites in the world", "One huge computer owned by a tech company", "The Wi-Fi in your home"],
                   "The internet is the network of networks. Websites are part of the World Wide Web, which runs on the internet."),
               mcq("What is the World Wide Web?", "A collection of web pages that are accessed over the internet", ["Another name for the internet", "The cables that link countries", "A type of router"],
                   "The web is one service that uses the internet. Email and online games are others.")]),
   dict(name="Domain Name Service (DNS)", bullets=["People use domain names like www.google.com; computers use IP addresses.",
        "DNS turns a domain name into the matching IP address.", "DNS is made up of many domain name servers, not just one."],
        challenge="Why don't we just type IP addresses into our browsers?", ill=("dns",), fact="DNS is used to...",
        tasks=[mcq("What does DNS do?", "Turns a domain name into an IP address", ["Stores every web page", "Gives devices their MAC addresses", "Encrypts Wi-Fi signals"],
                   "DNS looks up the IP address for a domain name so your browser knows where to send its request."),
               order("Put the steps in order to show how a browser finds www.google.com.", ["You type www.google.com into the browser",
                     "The browser asks a domain name server for the IP address", "Domain name servers look up the name, asking other DNS servers if they need to",
                     "The IP address is sent back to the browser", "The browser requests the page from the web server at that IP address"],
                     "You don't need the names of the servers for the exam, just the idea that DNS is many servers working together.")]),
   dict(name="Hosting", bullets=["Hosting means storing websites, files or services on a server so others can reach them over the internet.",
        "Hosting companies run data centres full of servers and rent out space."],
        challenge="Why would a small business pay a hosting company instead of running its own web server?", ill=("icons", [("server", "Web server"), ("server", "File server"), ("server", "Mail server")]),
        fact="Hosting is...",
        tasks=[mcq("What is meant by hosting?", "Storing websites or files on a server so they can be accessed over the internet", ["Inviting people to use your Wi-Fi", "Buying a domain name", "Printing web pages"],
                   "A host provides the server space and connection that keep a website available."),
               mcq("Why might a business use a hosting company?", "It doesn't need to buy, run and look after its own servers", ["Its website becomes invisible to competitors", "It no longer needs a domain name", "It stops needing the internet"],
                   "The hosting company handles the hardware, power, cooling and connection.")]),
   dict(name="The cloud", bullets=["Storage, software and services on remote servers, accessed over the internet.",
        "Examples: Google Drive and Microsoft OneDrive.", "You can reach your files from any device, anywhere with a connection."],
        challenge="What is the advantage of working in the cloud, rather than installing programs and saving files locally?", ill=("icons", [("laptop", "Laptop"), ("cloud", "The cloud"), ("phone", "Phone")]),
        fact="The cloud means...",
        tasks=[mcq("Which is the best description of the cloud?", "Storage and services on remote servers, reached over the internet", ["Wireless networks in the sky", "Files saved on a USB stick", "A type of weather satellite"],
                   "'The cloud' is just other people's servers, in data centres, that you use over the internet."),
               mcq("Which is a disadvantage of using the cloud?", "It relies on a stable internet connection", ["You can access files anywhere", "It's easy to scale up", "It has good backup options"],
                   "No connection means no access. The other three are advantages.")]),
   dict(name="Web servers and clients", bullets=["A web server stores web pages and sends them to clients when they are requested.",
        "A client, such as the browser on your phone, requests a page and displays it."],
        challenge="Describe the client-server relationship between a web server and a mobile phone.",
        ill=("pair", "phone", "server", "Client: phone", "Web server", "Request for a page", "Web page sent back"), fact="A web server... The client...",
        tasks=[mcq("In the relationship between a phone and a web server, what is the phone?", "The client", ["The server", "The router", "The host"],
                   "The phone requests the page, so it is the client. The web server responds."),
               mcq("What does a web server do?", "Stores web pages and sends them to clients that request them", ["Turns domain names into IP addresses", "Connects Wi-Fi devices", "Blocks viruses"],
                   "Turning names into addresses is DNS's job; the web server delivers the pages.")]),
   dict(name="File servers", bullets=["A file server stores files centrally for everyone on a network.",
        "A desktop PC is a client: it requests a file, and the file server sends it."],
        challenge="Describe the relationship between a file server and a desktop PC.",
        ill=("pair", "pc", "server", "Client: desktop PC", "File server", "Request for a file", "File sent back"), fact="A file server...",
        tasks=[match("Match each device to its role.", [["Web server", "Sends web pages to browsers"], ["File server", "Stores files for users on a network"],
                     ["Desktop PC opening a file", "Client"], ["Phone loading a website", "Client"]], "Servers provide; clients request."),
               mcq("Which is an advantage of storing work on a file server?", "You can open your work from any computer on the network", ["It works without a network", "Files can never be deleted", "It makes the computer faster"],
                   "Files stored centrally follow you to whichever networked computer you use.")]),
  ],
  final=dict(name="Final challenge: the cloud", floor_title="Final challenge: is the cloud worth it?",
    intro="Eight statements about the cloud. Tap the star and sort each one into advantage or disadvantage.",
    ill=("icons", [("pc", "Your device"), ("cloud", "The cloud"), ("server", "Data centre")]),
    tasks=[sort("Is each statement an advantage or a disadvantage of the cloud?", ["Advantage", "Disadvantage"], [
      ["Copies are kept automatically, so files survive a failed laptop", "Advantage"], ["Your files sit on someone else's servers", "Disadvantage"],
      ["A slow connection makes large files painful", "Disadvantage"], ["More space can be added the day you need it", "Advantage"],
      ["There's a bill every month for as long as you use it", "Disadvantage"], ["No servers to buy, power or replace", "Advantage"],
      ["Nothing works if the internet goes down", "Disadvantage"], ["The same files open on any device, anywhere", "Advantage"]],
      "Group these on your worksheet, and add one more of your own to each column.")]),
  models=[
   (3, "rack", "What the cloud actually is", "The cloud is this: racks of other people's computers in a building somewhere, with a switch at the top and a great deal of cooling. Nothing is stored in the sky."),
  ],
  info=[(0, "How many people?", "Around two-thirds of the world's population now use the internet, and most of them connect through phones."),
        (1, "8.8.8.8", "The address 8.8.8.8 actually belongs to Google's public DNS service. Some people set their devices to use it instead of their internet provider's DNS."),
        (2, "Cool servers", "Data centres use a lot of electricity for cooling. Some are built in cold countries to cut cooling costs."),
        (3, "Someone else's computer", "Your cloud files are stored on real servers in data centres, often copied to several locations so they survive a failure."),
        (4, "The web's birthday", "Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN in Switzerland."),
        (5, "Root servers", "At the top of DNS are root name servers. There are 13 root server addresses, but each one is copied to hundreds of servers around the world.")],
  ws=dict(title="The internet", objectives=["understand what the internet actually is", "understand the terms Domain Name Service and domain name server",
          "understand what is meant by hosting and the cloud", "understand what is meant by the terms web server and client"],
    starter="You save a file on a school computer and open it later at home. Describe what has to happen for that to work.",
    keyterms=["DNS (Domain Name Service)", "Hosting", "The cloud"], keyq="How does the internet work?",
    exam=[("Describe what the internet is.", 2, 2), ("Explain the steps DNS goes through when a browser looks up a web address.", 4, 4),
          ("A school is considering moving its files to the cloud. Discuss the benefits and the risks.", 8, 8)],
    confidence=["What the internet is", "How DNS works", "Hosting, the cloud, web servers and clients"]))

L9 = dict(id="nw-l09", topic="1.3", lesson=9, title="Connection café", img="NW_L09_ConnectionCafe_360",
  description="Ethernet, Wi-Fi or Bluetooth? Compare wired and wireless connections and recommend the right one for each job.",
  kicker=f"{K13}  |  Lesson 9", scene_title="Connection café", subtitle=SUB13,
  intro="Every device in this café needs to connect, but which way is best? Compare Ethernet, Wi-Fi and Bluetooth, then recommend the right connection for each job.",
  keywords=["Ethernet", "Wi-Fi", "Bluetooth", "Wired", "Wireless", "Bandwidth", "Range"],
  stations=[
   dict(name="Ethernet", bullets=["A wired standard for connecting devices on a LAN.", "Data is sent in frames containing source and destination addresses.",
        "Uses twisted pair or fibre optic cable, usually into a switch."],
        challenge="Why do many gamers plug their console into the router with a cable?", ill=("icons", [("pc", "Device"), ("switch", "Switch"), ("router", "Router")]),
        fact="Ethernet is...",
        tasks=[mcq("What type of connection is Ethernet?", "Wired", ["Wireless", "Satellite", "Bluetooth"], "Ethernet uses cables, usually twisted pair copper or fibre."),
               mcq("What does an Ethernet frame contain so it reaches the right device?", "Source and destination addresses", ["A Wi-Fi password", "A domain name", "A Bluetooth pairing code"],
                   "Each frame carries the MAC address it came from and the one it's going to.")]),
   dict(name="Wi-Fi", bullets=["A wireless connection using radio waves, through a wireless access point.", "Range of around 100 metres, less indoors.", "High bandwidth, but uses more power than Bluetooth."],
        challenge="What does a laptop need to connect to Wi-Fi?", ill=("icons", [("laptop", "Laptop"), ("wap", "Access point"), ("phone", "Phone")]),
        fact="Wi-Fi uses... Its range is about...",
        tasks=[mcq("What is the typical range of Wi-Fi?", "About 100 metres", ["About 10 metres", "About 1 kilometre", "Unlimited"], "Walls and interference usually reduce this indoors."),
               mcq("What does a device need in order to join a Wi-Fi network?", "A wireless NIC, and to be in range of a wireless access point", ["An Ethernet cable", "A Bluetooth headset", "A satellite dish"],
                   "The wireless NIC sends and receives the radio signals to and from the WAP.")]),
   dict(name="Bluetooth", bullets=["A short-range wireless connection directly between two devices.", "Range of around 10 metres.", "Low bandwidth and low power consumption."],
        challenge="Why is Bluetooth better than Wi-Fi for wireless earbuds?", ill=("icons", [("phone", "Phone"), ("headphones", "Earbuds")]),
        fact="Bluetooth is used for...",
        tasks=[mcq("What is the typical range of Bluetooth?", "About 10 metres", ["About 100 metres", "About 1 kilometre", "About 1 metre"], "Bluetooth is designed for devices close together."),
               mcq("Why is Bluetooth good for wireless earbuds?", "It uses very little power, so batteries last longer", ["It has the highest bandwidth", "It has the longest range", "It needs a cable"],
                   "Earbuds have tiny batteries, and they only need a short range and low bandwidth.")]),
   dict(name="Wi-Fi vs Bluetooth", bullets=["Complete the table on your worksheet for range, bandwidth and power consumption."],
        challenge="Which would you use to transfer a 2 GB video from a laptop to a school server, and why?",
        ill=("table", ["", "Wi-Fi", "Bluetooth"], [["Range", "100 metres", "10 metres"], ["Bandwidth", "High", "Low"], ["Power use", "High", "Low"]]),
        fact="The main differences between Wi-Fi and Bluetooth are...",
        tasks=[sort("Does each feature describe Wi-Fi or Bluetooth?", ["Wi-Fi", "Bluetooth"], [["Range of about 100 metres", "Wi-Fi"], ["Range of about 10 metres", "Bluetooth"],
                    ["High bandwidth", "Wi-Fi"], ["Low bandwidth", "Bluetooth"], ["Higher power consumption", "Wi-Fi"], ["Low power consumption", "Bluetooth"]],
                    "Wi-Fi is for networks; Bluetooth is for linking two nearby devices.")]),
   dict(name="Wired vs wireless", bullets=["Wired: faster, more reliable and easier to secure, but needs lots of cabling.",
        "Wireless: access from anywhere in range and less disruptive to set up, but slower, less secure, and blocked by walls."],
        challenge="Which is better: a wired or a wireless network? Give both sides.", ill=("compare", "Wired", ["Faster", "More reliable", "Easier to secure"], "Wireless", ["Use anywhere in range", "Easy to set up", "Blocked by walls"], "b", "g"),
        fact="Wired connections are... Wireless connections are...",
        tasks=[mcq("Which is an advantage of a wired connection over wireless?", "It is usually faster and more reliable", ["You can use it anywhere in the building", "It needs no cabling", "It is easier to set up in an old building"],
                   "The other options are advantages of wireless."),
               mcq("Why is a wireless network usually harder to secure?", "Its signals travel through the air, so anyone in range could try to connect or intercept them", ["Wireless data can't be encrypted", "It has no passwords", "It uses copper cables"],
                   "That's why Wi-Fi needs strong encryption, which is next lesson's topic.")]),
   dict(name="Recommend a connection", bullets=["Think about speed, reliability, security, range, power use and how easy it is to set up.", "Always justify your choice with the scenario."],
        challenge="Recommend a connection for a café offering free internet to customers. Justify your choice.", ill=("tiles", [("Fast?", "b"), ("Reliable?", "b"), ("Secure?", "p"), ("Range?", "g"), ("Battery?", "o"), ("Easy to set up?", "g")], 3),
        fact="To recommend a connection, I should think about...",
        tasks=[mcq("A school hall needs 30 laptops online for one day. Which connection is best?", "Wi-Fi", ["Ethernet", "Bluetooth", "USB cables"], "Wi-Fi avoids running 30 temporary cables."),
               mcq("A server room needs the fastest, most reliable links. Which connection is best?", "Ethernet", ["Wi-Fi", "Bluetooth", "Satellite"], "Servers don't move, so cabled links give the best speed and reliability."),
               mcq("A wireless mouse for a laptop: which connection is best?", "Bluetooth", ["Ethernet", "Wi-Fi", "Fibre optic"], "Short range, low data and low power: a perfect fit for Bluetooth.")]),
  ],
  final=dict(name="Final challenge: wired or wireless?", floor_title="Final challenge: wired or wireless?",
    intro="Eleven statements from the survey. Tap the star and sort each one into wired or wireless.",
    ill=("icons", [("pc", "Wired"), ("switch", "Switch"), ("wap", "Access point"), ("laptop", "Wireless")]),
    tasks=[sort("Does each statement describe wired or wireless connections?", ["Wired", "Wireless"], [
      ["Thick walls and other signals can interrupt it", "Wireless"], ["Needs cable runs, sockets and switches everywhere", "Wired"],
      ["Speeds drop the further you are from the access point", "Wireless"], ["A cable gives the same speed every time", "Wired"],
      ["An attacker has to get inside the building to tap it", "Wired"], ["Signals spread outside the building where anyone can capture them", "Wireless"],
      ["Best choice for machines that never move", "Wired"], ["Lets a class of laptops move room to room", "Wireless"],
      ["Can be set up in an old building without drilling holes", "Wireless"], ["Handles very large file transfers most quickly", "Wired"],
      ["Performance drops as more devices join the same access point", "Wireless"]],
      "Mark each one on your worksheet: is it an advantage or a disadvantage?")]),
  info=[(0, "Where Ethernet began", "Ethernet was invented at Xerox's research lab in California in 1973. The same idea, much faster, still connects most wired networks today."),
        (1, "Wi-Fi's real name", "Wi-Fi is the everyday name for a family of IEEE standards called 802.11. Each new version, such as Wi-Fi 6, is faster than the last."),
        (2, "A Viking king", "Bluetooth is named after Harald Bluetooth, a 10th-century Danish king. Its logo combines the runes for his initials, H and B."),
        (3, "Checking frames", "Every Ethernet frame ends with a cyclic redundancy check: a calculated value that lets the receiver spot if the frame was damaged on the way."),
        (4, "Li-Fi", "Li-Fi is an experimental technology that sends data using flickering LED light instead of radio waves. It can't pass through walls, which makes it hard to eavesdrop on."),
        (5, "Mesh at home", "Many homes now use mesh Wi-Fi: several access points that pass data to each other so the signal reaches every room.")],
  ws=dict(title="Modes of connection", objectives=["understand that Ethernet is a wired method of connection", "understand that Wi-Fi and Bluetooth are wireless methods of connection",
          "understand the benefits and drawbacks of wired versus wireless connections", "be able to recommend a connection type for a specified scenario"],
    starter="Count the devices around you that connect without a cable. For each one, say why a cable would be worse.", keyterms=["Ethernet", "Wi-Fi", "Bluetooth"], keyq="Which is better: a wired or wireless network?",
    exam=[("Describe two differences between Wi-Fi and Bluetooth.", 4, 4), ("Explain one benefit and one drawback of using cables rather than Wi-Fi.", 4, 4),
          ("A café wants to offer internet access to customers. Recommend a connection type and justify your choice.", 4, 5)],
    confidence=["Ethernet as a wired connection", "Wi-Fi and Bluetooth", "Recommending a connection for a scenario"]))

L10 = dict(id="nw-l10", topic="1.3", lesson=10, title="Cipher room", img="NW_L10_CipherRoom_360",
  description="Crack a cipher, learn how keys work, and find out how Wi-Fi keeps your data secret with WPA2.",
  kicker=f"{K13}  |  Lesson 10", scene_title="Cipher room", subtitle=SUB13,
  intro="Wireless signals travel through the air, so anyone nearby could pick them up. In the cipher room you'll crack a code, learn how keys work, and see how Wi-Fi keeps data secret.",
  keywords=["Encryption", "Cipher", "Key", "Public key", "Private key", "WPA2", "ROT13"],
  stations=[
   dict(name="Why encrypt?", bullets=["Encryption scrambles data so only someone with the key can read it.", "Wi-Fi signals travel through the air, so anyone in range could intercept them.",
        "Encrypted data is useless to anyone without the key."], challenge="What is the purpose of encryption?", ill=("icons", [("laptop", "Sender"), ("lock", "Encrypted"), ("wap", "Access point")]),
        fact="Encryption is used to...",
        tasks=[mcq("What is the purpose of encryption?", "To scramble data so only someone with the key can understand it", ["To make data travel faster", "To compress files", "To stop signals leaving the building"],
                   "Encryption doesn't stop interception; it makes intercepted data useless."),
               mcq("Why is encryption especially important for wireless networks?", "Radio signals can be picked up by anyone within range", ["Wireless is always slower", "Cables can't carry encrypted data", "Wi-Fi has no passwords"],
                   "With a cable, an attacker needs physical access. Wireless signals spread out into the air.")]),
   dict(name="ROT13 and the Romans", bullets=["A substitution cipher replaces each letter with another one, using a rule or key.", "ROT13 moves each letter 13 places: A becomes N. Doing it twice gives the original back.",
        "Julius Caesar used a shift cipher to send secret messages."], challenge="Decode this ROT13 message: URYYB JBEYQ", ill=("caesar", 13),
        fact="A substitution cipher works by...",
        tasks=[mcq("What is HELLO in ROT13?", "URYYB", ["IFMMP", "OLSSV", "HELLO"], "H→U, E→R, L→Y, L→Y, O→B."),
               mcq("Why isn't ROT13 secure?", "Anyone who knows the rule can reverse it, because there's no secret key", ["It only works on numbers", "It makes messages longer", "It can't be decoded at all"],
                   "ROT13 is used to hide spoilers or puzzle answers, not to keep secrets.")]),
   dict(name="Keys", bullets=["The key is the secret used to encrypt and decrypt a message.", "Without the key, the message is very hard to work out.",
        "If a key is sent with the message it could be intercepted, so master keys are known but never sent."], challenge="Why is it risky to send the key along with the message?", ill=("icons", [("key", "Key"), ("lock", "Lock")]),
        fact="The key is...",
        tasks=[mcq("What is an encryption key?", "The secret value used to encrypt and decrypt data", ["The password to your email", "The first letter of the message", "The Wi-Fi network's name"],
                   "Anyone with the key can unlock the message, so the key must be protected."),
               mcq("Why are master keys never sent over the network?", "They could be intercepted, and then all the data could be decrypted", ["They are too large to send", "The network doesn't allow it", "They change every second"],
                   "If an attacker captures the key, the encryption is worthless.")]),
   dict(name="Public and private keys", bullets=["A public key can be shared with anyone; it's used to encrypt messages sent to you.", "Only your matching private key can decrypt them.",
        "So the private key is never shared with anyone."], challenge="Why must a private key never be shared?", ill=("compare", "Public key", ["Shared with anyone", "Used to encrypt"], "Private key", ["Kept secret", "Used to decrypt"], "g", "r"),
        fact="A public key... A private key...",
        tasks=[mcq("Which key can be shared with anyone?", "The public key", ["The private key", "Both keys", "Neither key"], "The public key only locks messages; it can't unlock them."),
               mcq("What happens if someone gets hold of your private key?", "They can decrypt messages meant only for you", ["Nothing, as it's useless without the public key", "Your messages get shorter", "Your Wi-Fi speeds up"],
                   "That's why a private key is never shared.")]),
   dict(name="The WPA2 handshake", bullets=["Before any data is sent, the device and the access point check each other.", "Both work out the same master key from the Wi-Fi password.",
        "They swap random numbers to calculate a temporary key, without ever sending the key itself."], challenge="Why is the master key never sent over the air?",
        ill=("flow", ["Master key from password", "Random numbers swapped", "Transient key calculated", "Group key sent", "Acknowledgement"]),
        fact="WPA2 authenticates devices by...",
        tasks=[order("Put the steps of the Wi-Fi handshake in order.", ["Both devices work out the same master key from the Wi-Fi password",
                     "The access point sends a random number to the device", "The device uses the random numbers and addresses to calculate a session key",
                     "The device replies with its own random number and a check value", "The access point calculates the same session key",
                     "The access point sends the shared group key, protected by a check value", "The device acknowledges, and encrypted data can begin"],
                     "Both sides calculate the same keys, so the keys themselves never travel over the air."),
               mcq("What does WPA2 do before any data is sent?", "Checks that both devices know the same key, so they can trust each other", ["Deletes old data", "Speeds up the connection", "Turns off encryption"],
                   "This check is called authentication.")]),
   dict(name="Staying safe on Wi-Fi", bullets=["Use networks protected with WPA2 or WPA3.", "Open networks with no password send data without Wi-Fi encryption.",
        "A strong Wi-Fi password matters, because the master key is made from it."], challenge="Why is it risky to use online banking on an open café network?",
        ill=("tiles", [("WPA3", "g"), ("WPA2", "g"), ("Open network", "r"), ("WEP (old)", "r")], 2), fact="To stay safe on Wi-Fi, you should...",
        tasks=[mcq("Which network is the safest to use?", "One protected with WPA2 or WPA3 and a strong password", ["An open network with no password", "One with the password 'password'", "One that uses old WEP security"],
                   "WEP was cracked years ago, and open networks don't encrypt Wi-Fi traffic."),
               mcq("Why does the strength of the Wi-Fi password matter?", "The master key is made from it, so a weak password makes the key easier to guess", ["It changes the range", "It sets the bandwidth", "It doesn't matter"],
                   "Attackers try common passwords to recreate the key.")]),
  ],
  final=dict(name="Final challenge: code breakers", floor_title="Final challenge: code breakers",
    intro="Match each encryption term to its meaning. Use the ROT13 wheel below to decode the hidden hint on your worksheet.",
    ill=("caesar", 13),
    tasks=[match("Match each term to its meaning.", [["Plaintext", "The original, readable message"], ["Ciphertext", "The scrambled message"],
      ["Key", "The secret used to encrypt and decrypt"], ["Public key", "Shared with anyone and used to encrypt"],
      ["Private key", "Kept secret and used to decrypt"], ["Encryption", "Scrambling data so it can't be read without the key"]],
      "Learn these terms: they come up in exam questions on wireless security.")]),
  info=[(0, "Bletchley Park", "In the Second World War, codebreakers at Bletchley Park, including Alan Turing, cracked the German Enigma cipher, which helped shorten the war."),
        (1, "Caesar's shift", "Julius Caesar is said to have used a shift of 3: A became D, B became E, and so on. That's why shift ciphers are called Caesar ciphers."),
        (2, "Spoiler alert", "ROT13 is still used online to hide spoilers and puzzle answers: it's easy to reverse, but you won't read it by accident."),
        (3, "The padlock", "The padlock in your browser means HTTPS, which uses public and private keys to set up a secure connection with the website."),
        (4, "WEP was cracked", "The first Wi-Fi security, WEP, had serious flaws and could be cracked in minutes. WPA and then WPA2 replaced it."),
        (5, "WPA3", "WPA3 arrived in 2018. It protects even weak passwords better, by making it much harder to guess them offline.")],
  ws=dict(title="Wi-Fi encryption", objectives=["know the basics of how cryptography can work with a simple key", "know how wireless devices authenticate each other before communicating data",
          "understand the difference between private and public keys", "understand why private keys are never shared"],
    starter="Shift every letter of MEET AT NOON forward by 5 places. Swap with a partner and decode theirs. What would make this code harder to crack?", keyterms=["Encryption", "Public key", "Private key"],
    keyq="What is the purpose of encryption?",
    exam=[("Explain why wireless traffic needs encrypting more urgently than traffic on a cable.", 3, 3), ("Describe how a public key and a private key are used together.", 4, 4),
          ("Explain why the Wi-Fi key itself is never sent between the device and the access point.", 3, 3)],
    confidence=["How a simple substitution cipher works", "How devices authenticate with WPA2", "Public and private keys"]))

L11 = dict(id="nw-l11", topic="1.3", lesson=11, title="Address sorting office", img="NW_L11_AddressSortingOffice_360",
  description="Sort MAC, IPv4 and IPv6 addresses, and find out why the world needed IPv6.",
  kicker=f"{K13}  |  Lesson 11", scene_title="Address sorting office", subtitle=SUB13,
  intro="Every piece of data needs an address, just like a parcel. Learn to tell MAC, IPv4 and IPv6 addresses apart, and find out why the world ran out of IPv4 addresses.",
  keywords=["MAC address", "IP address", "IPv4", "IPv6", "Hexadecimal", "Network", "Host"],
  stations=[
   dict(name="MAC addresses", bullets=["Media Access Control address: a unique address given to every network interface card when it is made.",
        "48 bits, written as 12 hexadecimal digits in pairs.", "Used by switches to send frames to the right device on a LAN."],
        challenge="Why does every NIC need a unique MAC address?", ill=("big", "00-15-E9-2B-99-3C", "Six pairs of hexadecimal digits, set when the NIC is made"),
        fact="A MAC address is...",
        tasks=[mcq("When is a MAC address given to a device?", "When its network interface card is made", ["Every time it joins a network", "When you name the device", "When DNS looks it up"],
                   "The manufacturer sets it, and it is meant to stay the same."),
               mcq("Which is a MAC address?", "00-15-E9-2B-99-3C", ["180.17.255.1", "2001:0DB8:AC10:FE01::", "www.bbc.co.uk"], "MAC addresses are six pairs of hexadecimal digits.")]),
   dict(name="IP addresses", bullets=["Internet Protocol address: identifies a device on a network so data can be routed to it.", "Given by the network, so it can change when a device moves to another network.",
        "Used by routers to send packets across networks."], challenge="Why can your phone's IP address change, but its MAC address stays the same?", ill=("big", "180.17.255.1", "An IPv4 address: four numbers separated by dots"),
        fact="An IP address is...",
        tasks=[mcq("What is an IP address used for?", "Identifying a device so packets can be routed to it across networks", ["Encrypting Wi-Fi data", "Naming a website", "Storing a device's files"],
                   "Routers read the destination IP address to decide where to send each packet next."),
               mcq("Which device mainly uses IP addresses to forward data?", "A router", ["A switch", "A printer", "A monitor"], "Switches use MAC addresses inside a LAN; routers use IP addresses between networks.")]),
   dict(name="IPv4", bullets=["32 bits, written as four numbers from 0 to 255 separated by dots.", "Part of the address identifies the network; the rest identifies the device (node).",
        "There are about 4.3 billion possible addresses: not enough for every device today."], challenge="Why can't an IPv4 number be bigger than 255?", ill=("big", "192.168.1.20", "Network part: 192.168.1    Device (node) part: 20"),
        fact="An IPv4 address is written as...",
        tasks=[mcq("Which is a valid IPv4 address?", "192.168.1.20", ["256.10.3.4", "10.0.0", "1.2.3.4.5"], "Four numbers, each from 0 to 255."),
               mcq("How many bits are in an IPv4 address?", "32", ["48", "64", "128"], "Four numbers of 8 bits each makes 32 bits.")]),
   dict(name="IPv6", bullets=["128 bits, written as eight groups of four hexadecimal digits separated by colons.", "Created because IPv4 addresses were running out.",
        "Allows about 340 undecillion (3.4 × 10³⁸) addresses."], challenge="State the reason we need IPv6.", ill=("big", "2001:0DB8:AC10:FE01:0000:0000:0000:0000", "Eight groups of hexadecimal, separated by colons"),
        fact="IPv6 was introduced because...",
        tasks=[mcq("Why was IPv6 introduced?", "The world was running out of IPv4 addresses", ["IPv4 was too slow", "IPv4 couldn't use Wi-Fi", "To replace MAC addresses"],
                   "Billions of phones, computers and smart devices need addresses."),
               mcq("How many bits are in an IPv6 address?", "128", ["32", "48", "64"], "128 bits gives an enormous number of possible addresses.")]),
   dict(name="LAN or WAN addressing?", bullets=["Within a LAN, switches use MAC addresses to deliver frames.", "Between networks, routers use IP addresses to route packets.",
        "Every device has both."], challenge="Which address would a switch use, and which would a router use?", ill=("pair", "switch", "router", "Switch: MAC", "Router: IP", "Inside the LAN", "Across the WAN"),
        fact="MAC addresses are used... IP addresses are used...",
        tasks=[mcq("Which address does a switch use to deliver a frame?", "The MAC address", ["The IPv4 address", "The domain name", "The IPv6 address"], "Switches work within a LAN, using MAC addresses."),
               mcq("Which address stays with a device when it moves to a different network?", "Its MAC address", ["Its IP address", "Both change", "Neither is used"], "The MAC is built into the NIC; the IP address comes from the network it joins.")]),
   dict(name="Network and device parts", bullets=["In 192.168.1.20, the first part (192.168.1) identifies the network.", "The last part (20) identifies the device, or node, on that network.",
        "Devices on the same network share the network part."], challenge="Two laptops are 192.168.1.20 and 192.168.1.35. Are they on the same network? How can you tell?",
        ill=("tiles", [("192", "b"), ("168", "b"), ("1", "b"), ("20", "g")], 4), fact="The network part of an IPv4 address... The node part...",
        tasks=[mcq("In the address 192.168.1.20, which part identifies the device?", "20", ["192", "168.1", "192.168"], "In this common home setup, the last number identifies the device."),
               mcq("Which address is on the same network as 192.168.1.20?", "192.168.1.35", ["192.168.2.20", "10.0.1.20", "172.16.1.20"], "It shares the same network part: 192.168.1.")]),
  ],
  final=dict(name="Final challenge: sort the mail", floor_title="Final challenge: sort the mail",
    intro="Nine parcels have arrived at the sorting office. Tap the star and sort each one: MAC, IPv4 or IPv6?",
    ill=("tiles", [("180.17.255.1", "b"), ("00-15-E9-2B-99-3C", "k"), ("2001:0DB8:AC10::", "g"), ("32 bits", "b"), ("48 bits", "k"), ("128 bits", "g")], 3),
    tasks=[sort("Does each item describe a MAC, IPv4 or IPv6 address?", ["MAC", "IPv4", "IPv6"], [
      ["180.17.255.1", "IPv4"], ["2001:0DB8:AC10:FE01:0000:0000:0000:0000", "IPv6"], ["00-15-E9-2B-99-3C", "MAC"],
      ["32 bits long", "IPv4"], ["128 bits long", "IPv6"], ["48 bits, set when the NIC is made", "MAC"],
      ["Four numbers from 0 to 255", "IPv4"], ["Eight groups of hexadecimal separated by colons", "IPv6"], ["Used by switches within a LAN", "MAC"]],
      "These are the three addresses from your starter. Can you identify them straight away now?")]),
  info=[(0, "Hexadecimal", "Hexadecimal uses 16 digits: 0 to 9, then A to F. Each pair of hex digits is exactly one byte, which is why MAC addresses are written in pairs."),
        (1, "Hiding your MAC", "Many phones now use a random MAC address on each Wi-Fi network, so shops and venues can't track you from place to place."),
        (2, "Why 255?", "Each part of an IPv4 address is 8 bits. The biggest number 8 bits can hold is 11111111 in binary, which is 255."),
        (3, "IPv4 ran out", "The last big blocks of IPv4 addresses were handed out in 2011. Many networks now share one public address between many devices."),
        (4, "Home networks", "Addresses starting 192.168 are private: they only work inside your home network. Your router shares one public IP address between all your devices."),
        (5, "Shortening IPv6", "Groups of zeros in IPv6 can be shortened with ::, so 2001:0DB8:0000:0000:0000:0000:0000:0001 can be written as 2001:DB8::1.")],
  ws=dict(title="IP and MAC addressing", objectives=["understand the uses of MAC and IP addressing", "understand the difference between IPv4 and IPv6", "understand the need for IPv6"],
    starter="A parcel needs a house number and a postcode to arrive. Suggest why a computer might need more than one kind of address too.", starter_lines=3,
    keyterms=["MAC address", "IP address"], keyq="What are the differences between the three types of network address?",
    exam=[("State what a MAC address identifies.", 1, 1), ("Explain why IPv6 addresses were needed.", 2, 2), ("Describe two differences between an IPv4 address and an IPv6 address.", 4, 4),
          ("Explain why a device keeps its MAC address but can be given a different IP address.", 3, 3)],
    confidence=["Uses of MAC and IP addresses", "The difference between IPv4 and IPv6", "Why IPv6 is needed"]))

L12 = dict(id="nw-l12", topic="1.3", lesson=12, title="Protocol city", img="NW_L12_ProtocolCity_360",
  description="Explore the standards and protocols that make networks work, from HTTP to TCP/IP.",
  kicker=f"{K13}  |  Lesson 12", scene_title="Protocol city", subtitle=SUB13,
  intro="Networks only work because everyone follows the same rules. Tour Protocol city to learn why standards matter and what the seven common protocols do.",
  keywords=["Standard", "Protocol", "HTTP", "HTTPS", "FTP", "POP", "IMAP", "SMTP", "TCP/IP"],
  stations=[
   dict(name="Standards", bullets=["Agreed rules and specifications so hardware and software from different makers work together.", "Examples: USB, Wi-Fi (IEEE 802.11), Ethernet and HTML.",
        "Without standards, devices couldn't talk to each other."], challenge="What would happen if every phone maker used a different charging connector?", ill=("tiles", [("USB", "b"), ("Wi-Fi", "g"), ("Ethernet", "p"), ("HTML", "o")], 4),
        fact="Standards are needed because...",
        tasks=[mcq("Why are standards needed in computing?", "So hardware and software from different manufacturers can work together", ["To make devices more expensive", "To stop people making new products", "To keep networks slow"],
                   "Standards mean a laptop from one company can use Wi-Fi from another."),
               mcq("Which of these is a standard?", "USB", ["A web browser's logo", "A student's password", "A file name"], "USB sets rules that every maker follows for connectors and data transfer.")]),
   dict(name="Protocols", bullets=["A protocol is a set of rules that governs how devices communicate on a network.", "It covers the format of data, addressing and how errors are handled.",
        "Different protocols do different jobs."], challenge="What is the difference between a standard and a protocol?", ill=("pair", "pc", "server", "Device", "Server", "Following the same rules", "Understood!"),
        fact="A protocol is...",
        tasks=[mcq("What is a network protocol?", "A set of rules for how devices communicate on a network", ["A type of cable", "A network's password", "A kind of virus"], "Both ends must follow the same protocol to understand each other."),
               mcq("Why must both devices use the same protocol?", "So each can understand the data the other sends", ["So they have the same MAC address", "To use less electricity", "So they can share a screen"],
                   "It's like two people agreeing to speak the same language.")]),
   dict(name="Web protocols", bullets=["HTTP (Hypertext Transfer Protocol): a client-server way of requesting and delivering HTML files.", "HTTPS (Hypertext Transfer Protocol Secure): adds encryption and authentication.",
        "Look for the padlock in your browser."], challenge="Why should a shopping website use HTTPS rather than HTTP?", ill=("tiles", [("HTTP", "o"), ("HTTPS", "g")], 2),
        fact="HTTP is used for... HTTPS adds...",
        tasks=[mcq("What is HTTP used for?", "Requesting and delivering web pages between browsers and web servers", ["Sending email", "Uploading files", "Routing packets"], "HTTP delivers HTML files from web servers to browsers."),
               mcq("What does HTTPS add to HTTP?", "Encryption and authentication of the data between client and server", ["Faster downloads", "Email attachments", "Bigger images"], "The S stands for Secure.")]),
   dict(name="Email protocols", bullets=["SMTP (Simple Mail Transfer Protocol) sends email to a mail server.", "POP (Post Office Protocol) retrieves email from a mail server.",
        "IMAP (Internet Message Access Protocol) retrieves email and manages it on the server, so it syncs across devices."], challenge="Why is IMAP better than POP if you read email on a phone and a laptop?",
        ill=("flow", ["Your email app", "SMTP: send", "Mail server", "POP / IMAP: collect"]), fact="SMTP... POP... IMAP...",
        tasks=[match("Match each email protocol to its job.", [["SMTP", "Sends email to a mail server"], ["POP", "Retrieves email from a mail server"],
                     ["IMAP", "Retrieves email and manages mailboxes on the server"]], "IMAP keeps mail on the server, so every device sees the same inbox."),
               mcq("Which protocol keeps your emails in sync across your phone and laptop?", "IMAP", ["POP", "SMTP", "FTP"], "IMAP manages mail on the server rather than just downloading it.")]),
   dict(name="FTP", bullets=["File Transfer Protocol: sends files between computers.", "Often used to upload web pages and their files to a web server for hosting."],
        challenge="A web designer has finished a site. Which protocol might they use to put it on the web server?", ill=("pair", "laptop", "server", "Designer", "Web server", "Files uploaded with FTP", ""),
        fact="FTP is used for...",
        tasks=[mcq("What is FTP used for?", "Sending files between computers", ["Sending email", "Encrypting web pages", "Finding IP addresses"], "File Transfer Protocol does exactly what its name says."),
               mcq("Which protocol would upload a website's files to a web server?", "FTP", ["SMTP", "POP", "IMAP"], "FTP is the classic way to upload web pages for hosting.")]),
   dict(name="TCP/IP", bullets=["TCP (Transmission Control Protocol): splits data into packets and makes sure they all arrive, error-free and in order.",
        "IP (Internet Protocol): routes packets across a wide area network using IP addresses.", "They work together as TCP/IP."], challenge="What would happen to a web page if some packets went missing and nothing checked?",
        ill=("stack", [("TCP", "Packets arrive complete and in order", "b"), ("IP", "Packets routed to the right address", "g")]), fact="TCP makes sure... IP...",
        tasks=[mcq("What does TCP do?", "Makes sure all the packets arrive without errors and in the right order", ["Routes packets between networks", "Sends email", "Encrypts Wi-Fi"], "If a packet goes missing, TCP gets it sent again."),
               mcq("What does IP do?", "Routes packets across networks to the right address", ["Checks packets arrive in order", "Uploads files", "Stores web pages"], "IP handles addressing and routing; TCP handles reliability.")]),
  ],
  final=dict(name="Final challenge: protocol match", floor_title="Final challenge: protocol match",
    intro="Match each protocol to what it does. The letters below are your starter puzzle: can you find all the acronyms?",
    ill=("tiles", [("HTTP", "o"), ("HTTPS", "g"), ("FTP", "b"), ("SMTP", "p"), ("POP", "k"), ("IMAP", "y"), ("TCP", "r"), ("IP", "n")], 4),
    tasks=[match("Match each protocol to its description.", [["HTTP", "Requests and delivers web pages (HTML files)"], ["HTTPS", "Web pages with encryption and authentication"],
      ["FTP", "Sends files between computers"], ["SMTP", "Sends email to a mail server"], ["POP", "Retrieves email from a mail server"],
      ["IMAP", "Retrieves email and manages mailboxes on the server"], ["TCP", "Error-free transmission of packets"], ["IP", "Routes packets across a WAN"]],
      "Learn these eight: exam questions often ask you to name the protocol for a job."),
      # Matching a protocol to its definition is not the same as picking one for
      # a job, which is what the exam asks. These six jobs are described in the
      # language a question would use rather than in the words of the
      # definitions above, so knowing the list is not enough to answer them.
      sort("Which protocol does each job need?", ["HTTPS", "FTP", "SMTP", "IMAP"],
           [["Entering card details on a shop's checkout page", "HTTPS"],
            ["Your mail app handing a finished message to the mail server", "SMTP"],
            ["Reading the same inbox on a phone and a laptop, both in step", "IMAP"],
            ["Uploading a finished website to its web server", "FTP"],
            ["A bank's online login page", "HTTPS"],
            ["Moving a folder of large files onto a server", "FTP"]],
           "Two of these turn on one word. Card details and a login page need the S on the "
           "end, because that is the encryption. Sending a message is SMTP and reading one "
           "is IMAP, however much it feels like email should be a single protocol.")]),
  info=[(0, "USB-C", "A standard can become law: from the end of 2024, new phones sold in the EU had to use USB-C charging ports."),
        (1, "Who writes the rules?", "Organisations such as the IEEE and the IETF agree networking standards, so that companies around the world build compatible products."),
        (2, "Port numbers", "Protocols use numbered 'ports'. Web servers usually listen on port 80 for HTTP and port 443 for HTTPS."),
        (3, "The @ symbol", "Ray Tomlinson sent the first network email in 1971 and chose the @ symbol to separate the user's name from their computer's name."),
        (4, "FTP is fading", "Plain FTP sends passwords unencrypted, so many hosts now use secure versions, such as SFTP, instead."),
        (5, "Packets take different routes", "The packets for one web page can travel by completely different routes. TCP puts them back in order when they arrive.")],
  ws=dict(title="Standards and common protocols", objectives=["understand the need for standards in computing", "understand the seven common protocols and what they are used for"],
    starter="List every acronym you already associate with the internet. Which ones do you think are rules for sending data, and which are something else?",
    keyterms=["Standard", "Protocol"], keyq="What are standards and protocols?",
    exam=[("Explain why agreed standards matter when devices from different makers connect.", 3, 3), ("Name the protocol used to send email to a mail server.", 1, 1),
          ("Describe what HTTPS adds to HTTP and why it matters.", 3, 3), ("Explain how TCP and IP work together when a web page is requested.", 4, 4)],
    confidence=["Why standards are needed", "The common protocols and what they do", "The difference between standards and protocols"]))

L13 = dict(id="nw-l13", topic="1.3", lesson=13, title="Parcel depot", img="NW_L13_ParcelDepot_360",
  description="Follow a parcel from box to sack to van, and find out why layering protocols makes networks easier to build.",
  kicker=f"{K13}  |  Lesson 13", scene_title="Parcel depot", subtitle=SUB13,
  intro="A parcel travels inside a box, inside a sack, inside a van, and each stage only deals with the one next to it. Networking works the same way. Find out why protocols are layered and what each layer does.",
  keywords=["Layer", "Protocol", "Application", "Transport", "Internet", "Link"],
  stations=[
   dict(name="Why layers?", bullets=["Networking is a complex job, so it's divided into smaller, simpler tasks called layers.", "Each layer has a defined responsibility.",
        "Each layer provides a service to the layer above it."], challenge="Why is it easier to solve a big problem in layers?", ill=("stack", [("Layer 4", "Your app", "p"), ("Layer 3", "", "b"), ("Layer 2", "", "g"), ("Layer 1", "The connection", "o")]),
        fact="Protocols are layered because...",
        tasks=[mcq("Why is networking divided into layers?", "To split a complex task into smaller, simpler tasks that work together", ["To make networks slower but safer", "Because cables have layers", "So only one protocol is ever used"],
                   "Each layer can focus on one job."),
               mcq("What does each layer do for the layer above it?", "Provides a service to it", ["Deletes its data", "Replaces it", "Encrypts it with a private key"], "Each layer relies on the one below to do its job.")]),
   dict(name="The parcel model", bullets=["A parcel goes in a box, the box goes in a sack, the sack goes in a van.",
        "Swap the van for a train and the parcel inside doesn't change at all.", "Each stage only has to deal with the stage next to it."],
        challenge="Describe the four stages of sending a parcel, and say which one could be swapped without affecting the others.", ill=("stack", [("Parcel", "The message", "p"), ("Box", "Addressed and sealed", "b"), ("Sack", "Sorted for a route", "g"), ("Van", "The journey itself", "o")]),
        fact="The parcel shows layering because...",
        tasks=[mcq("You change from Wi-Fi to an Ethernet cable. What else has to change?", "Nothing else: only the bottom layer changes", ["Your web browser", "Every website", "The HTTP protocol"],
                   "That's the point of layers: one can be swapped without affecting the others."),
               mcq("In the parcel analogy, what does swapping the van for a train show?", "One layer can change without changing the others", ["All layers must be the same", "Parcels need protocols", "Layers can't be changed"],
                   "The parcel, box and sack are unaffected by how the journey is made.")]),
   dict(name="Advantages of layering", bullets=["Easier to develop and troubleshoot: you can work on one layer at a time.", "Layers can be changed or upgraded independently.",
        "Different companies can make products for different layers that still work together."], challenge="State three advantages of layering a complex task like networking.",
        ill=("tiles", [("Easier to fix", "g"), ("Swap layers", "g"), ("Work in parallel", "g"), ("Mix makers", "g")], 2), fact="The advantages of layering are...",
        tasks=[multi("Which are advantages of layering protocols? Select all that apply.", ["A layer can be changed without affecting the others", "Problems can be traced to one layer",
                     "Different companies can make parts that work together", "Networks no longer need any protocols", "Data never gets lost"],
                     ["A layer can be changed without affecting the others", "Problems can be traced to one layer", "Different companies can make parts that work together"],
                     "Layers still need protocols, and data can still go missing: TCP deals with that."),
               mcq("A network technician is troubleshooting. Why do layers help?", "They can test one layer at a time to find where the problem is", ["They can ignore the network", "Every layer is identical", "They can remove all the layers"],
                   "Technicians often start at the bottom: is the cable plugged in?")]),
   dict(name="The four layers", bullets=["Application: the programs you use, e.g. HTTP, SMTP, FTP.", "Transport: TCP makes sure data arrives reliably.",
        "Internet: IP routes packets.  Link: the physical connection, e.g. Ethernet or Wi-Fi."], challenge="Which layer does your web browser work in?",
        ill=("stack", [("Application", "HTTP, SMTP, FTP", "p"), ("Transport", "TCP", "b"), ("Internet", "IP", "g"), ("Link", "Ethernet, Wi-Fi", "o")]), fact="The four layers are...",
        tasks=[order("Put the four layers in order, from top (closest to the user) to bottom.", ["Application", "Transport", "Internet", "Link"],
                     "You don't need to name the layers for the J277 exam, but it helps to understand layering."),
               mcq("Which layer sends data over the actual cable or radio signal?", "Link", ["Application", "Transport", "Internet"], "The link layer covers Ethernet, Wi-Fi and the hardware.")]),
   dict(name="Sending an email", bullets=["Your email app uses SMTP (application layer).", "TCP makes sure it all arrives (transport layer).",
        "IP routes it to the mail server (internet layer), over Wi-Fi (link layer)."], challenge="Show the jigsaw for sending an HTML email with no encryption over Wi-Fi to a mail server.",
        ill=("stack", [("SMTP", "Application", "p"), ("TCP", "Transport", "b"), ("IP", "Internet", "g"), ("Wi-Fi", "Link", "o")]), fact="When I send an email, the layers used are...",
        tasks=[match("Match each layer to the protocol used when sending an email over Wi-Fi.", [["Application", "SMTP"], ["Transport", "TCP"], ["Internet", "IP"], ["Link", "Wi-Fi"]],
                     "This is the second jigsaw on your worksheet.")]),
   dict(name="Layers in action", bullets=["Loading a web page: HTTP (or HTTPS), then TCP, then IP, then Ethernet or Wi-Fi.", "Each layer adds its own information, like putting a letter in an envelope.",
        "The receiver unwraps the layers in reverse."], challenge="Describe the layers used when you load a web page over an Ethernet cable.",
        ill=("flow", ["HTTP", "TCP", "IP", "Ethernet"]), fact="When a web page loads, the layers...",
        tasks=[mcq("Which protocol would be in the application layer when loading a web page?", "HTTP", ["TCP", "IP", "Ethernet"], "HTTP is used by the browser, which is an application."),
               mcq("Which layer would change if you moved from a school PC on a cable to a laptop on Wi-Fi?", "The link layer", ["The application layer", "The transport layer", "All of them"],
                   "Only the physical connection changed.")]),
  ],
  final=dict(name="Final challenge: build the stack", floor_title="Final challenge: build the stack",
    intro="Eight protocols and technologies have been dropped on the floor. Tap the star and sort each one into its layer.",
    ill=("stack", [("Application", "?", "p"), ("Transport", "?", "b"), ("Internet", "?", "g"), ("Link", "?", "o")]),
    tasks=[sort("Which layer does each protocol or technology belong to?", ["Application", "Transport", "Internet", "Link"], [
      ["HTTP", "Application"], ["FTP", "Application"], ["SMTP", "Application"], ["IMAP", "Application"],
      ["TCP", "Transport"], ["IP", "Internet"], ["Ethernet", "Link"], ["Wi-Fi", "Link"]],
      "Now RAG the revision checklist on your worksheet, ready for the end-of-unit assessment.")]),
  info=[(0, "Seven or four?", "There are two famous layer models: the 7-layer OSI model, used for teaching and troubleshooting, and the 4-layer TCP/IP model, which the internet actually uses."),
        (1, "Swap without breaking", "When Wi-Fi 6 arrived, you didn't need new websites or browsers. Only the link layer changed, thanks to layering."),
        (2, "Start at the bottom", "IT technicians often troubleshoot from the bottom layer up: is the cable plugged in? Is Wi-Fi connected? Only then do they check the apps."),
        (3, "Envelopes in envelopes", "Each layer wraps the data with its own header, a bit like putting a letter in an envelope, then in a parcel. This is called encapsulation."),
        (4, "New protocols, same layers", "The newest version of HTTP, HTTP/3, runs over a different transport protocol called QUIC, but the layers above and below didn't need to change."),
        (5, "Standards for each layer", "Different organisations look after different layers, such as the IEEE for Ethernet and Wi-Fi, and the IETF for TCP/IP.")],
  ws=dict(title="The concept of layers", objectives=["know why protocols are layered", "understand the advantages of layering"],
    starter="A parcel goes in a box, the box goes in a sack, the sack goes in a van. What happens if the van is replaced by a train? Why does that not affect the parcel?", starter_lines=4,
    keyterms=["Layer", "Protocol"], keyq="What are the benefits of layering protocols?",
    exam=[("Give three benefits of dividing networking into layers.", 3, 3), ("Explain how layering makes it possible to change from Wi-Fi to a cable without changing any software.", 3, 3)],
    rag=["Types of network: LAN, WAN, standalone", "Factors affecting network performance", "Client-server and peer-to-peer", "Hardware to connect a LAN",
         "The internet, DNS, hosting and the cloud", "Star and mesh topologies", "Modes of connection", "Wi-Fi encryption", "IP and MAC addressing", "Standards and protocols", "Layers"],
    confidence=["Why protocols are layered", "The advantages of layering", "Which protocols belong in which layer"]))

L14 = dict(id="nw-l14", topic="1.3", lesson=14, title="Revision HQ 2", img="NW_L14_RevisionHQ2_360",
  description="Recap lessons 9 to 13 and find out what to revise before your end-of-unit assessment.",
  kicker=f"{K13}  |  Lesson 14", scene_title="Revision HQ 2", subtitle="Get ready for your end-of-unit assessment on lessons 9 to 13",
  intro="Each station sums up one lesson from the second half of the unit. Answer its quiz, and your score screen will show which topics are secure and which to revise before the test.",
  keywords=["Ethernet", "Wi-Fi", "Encryption", "IPv4", "IPv6", "MAC", "Protocols", "Layers"], revision=True,
  stations=[
   dict(name="Lesson 9: Modes of connection", bullets=["Ethernet is wired: fast, reliable and secure, but needs cabling.", "Wi-Fi is wireless, about 100 m range, high bandwidth.", "Bluetooth: about 10 m, low bandwidth, low power."],
        challenge="Which is better: a wired or wireless network?", ill=("icons", [("pc", "Ethernet"), ("wap", "Wi-Fi"), ("headphones", "Bluetooth")]),
        tasks=[mcq("Which connection has a range of about 10 metres and low power use?", "Bluetooth", ["Wi-Fi", "Ethernet", "Fibre optic"], "Bluetooth is designed for nearby devices with small batteries."),
               mcq("Which is an advantage of a wired connection?", "More reliable and easier to secure", ["Can be used anywhere in range", "No cables needed", "Easy to set up in any room"], "The others are wireless advantages."),
               mcq("What does Ethernet send data in?", "Frames with source and destination addresses", ["Radio waves", "Emails", "Web pages only"], "Frames carry MAC addresses so the switch knows where to send them.")]),
   dict(name="Lesson 10: Wi-Fi encryption", bullets=["Encryption scrambles data so only someone with the key can read it.", "A public key is shared; a private key is never shared.", "WPA2 authenticates devices without sending the key."],
        challenge="What is the purpose of encryption?", ill=("icons", [("key", "Key"), ("lock", "Encrypted")]),
        tasks=[mcq("Why is encryption needed on Wi-Fi?", "Signals can be intercepted by anyone in range", ["Wi-Fi is slow", "Cables can't carry data", "It increases the range"], "Encryption makes intercepted data useless."),
               mcq("Which key must never be shared?", "The private key", ["The public key", "Both", "Neither"], "The private key decrypts your messages."),
               mcq("What does WPA2 do before data is sent?", "Authenticates the devices using keys made from the password", ["Deletes old data", "Turns off encryption", "Speeds up the network"], "The keys are calculated on both sides, never sent.")]),
   dict(name="Lesson 11: IP and MAC addressing", bullets=["MAC: 48 bits, hexadecimal pairs, set when the NIC is made; used in a LAN.", "IPv4: 32 bits, four numbers 0 to 255.", "IPv6: 128 bits, hexadecimal groups; needed because IPv4 ran out."],
        challenge="What are the differences between the three types of address?", ill=("tiles", [("MAC", "k"), ("IPv4", "b"), ("IPv6", "g")], 3),
        tasks=[mcq("Which is an IPv6 address?", "2001:0DB8:AC10:FE01:0000:0000:0000:0000", ["180.17.255.1", "00-15-E9-2B-99-3C", "www.example.com"], "Eight groups of hexadecimal separated by colons."),
               mcq("Why was IPv6 introduced?", "IPv4 addresses were running out", ["IPv4 was too secure", "To replace MAC addresses", "To make Wi-Fi faster"], "IPv4 only allows about 4.3 billion addresses."),
               mcq("Which address does a switch use?", "MAC address", ["IPv4 address", "IPv6 address", "Domain name"], "Switches deliver frames within a LAN using MAC addresses.")]),
   dict(name="Lesson 12: Standards and protocols", bullets=["Standards let hardware and software from different makers work together.", "A protocol is a set of rules for communication.", "HTTP/HTTPS, FTP, SMTP, POP, IMAP, TCP/IP."],
        challenge="What are standards and protocols?", ill=("tiles", [("HTTP", "o"), ("HTTPS", "g"), ("FTP", "b"), ("SMTP", "p"), ("POP", "k"), ("IMAP", "k")], 3),
        tasks=[mcq("Which protocol sends email to a mail server?", "SMTP", ["POP", "IMAP", "HTTP"], "SMTP sends; POP and IMAP retrieve."),
               mcq("What does HTTPS add to HTTP?", "Encryption and authentication", ["Faster speeds", "Email support", "File uploads"], "The S stands for Secure."),
               mcq("What does TCP do?", "Makes sure packets arrive without errors and in order", ["Routes packets", "Sends email", "Stores web pages"], "IP routes; TCP makes it reliable.")]),
   dict(name="Lesson 13: Layers", bullets=["Networking is divided into layers, each with a defined job.", "Each layer provides a service to the layer above.", "A layer can be changed without affecting the others."],
        challenge="What are the benefits of layering protocols?", ill=("stack", [("Application", "HTTP", "p"), ("Transport", "TCP", "b"), ("Internet", "IP", "g"), ("Link", "Wi-Fi", "o")]),
        tasks=[mcq("Why are protocols layered?", "To divide a complex task into smaller, simpler tasks", ["To make networks slower", "So only one protocol is used", "To stop encryption"], "Each layer has one clear responsibility."),
               mcq("Which is an advantage of layering?", "One layer can be changed without affecting the others", ["No protocols are needed", "Data can never be lost", "Only one company can make network products"], "E.g. swapping Wi-Fi for Ethernet."),
               mcq("Which layer does Wi-Fi belong to?", "Link", ["Application", "Transport", "Internet"], "The link layer covers the physical connection.")]),
   dict(name="Exam technique", bullets=["State: give a short fact. Describe: give the key features. Explain: say how or why, using 'because'.", "Match your answer to the marks: one point per mark.",
        "Use the key terms from this unit."], challenge="Which command word needs you to give a reason?", ill=("tiles", [("State", "b"), ("Describe", "g"), ("Explain", "o"), ("Compare", "p")], 2),
        tasks=[mcq("A question says 'Explain'. What do you need to include?", "Reasons: how or why something happens", ["Just a single word", "A drawing", "A list of acronyms only"], "Link each point with 'because' or 'so'."),
               mcq("How many points should you aim for in a 4-mark question?", "Four clear points", ["One", "Two", "Ten"], "Usually one mark per valid point."),
               mcq("A question says 'State'. What is expected?", "A short, direct fact", ["A full paragraph", "An essay", "A diagram with labels"], "State questions don't need explanations."),
               # Knowing that Explain needs a reason is not the same as telling
               # an answer that gives one from an answer that does not. These
               # six sentences are about lessons 9 to 13, so the judgement
               # revises the content as well as the technique.
               sort("Each of these is an answer to a two-mark Explain question. "
                    "Would it earn a mark?",
                    ["Earns a mark", "Earns nothing"],
                    [["Fibre is better than copper.", "Earns nothing"],
                     ["Fibre carries data as light, so it is not affected by electrical interference.", "Earns a mark"],
                     ["WPA2 encrypts the data, so anyone intercepting it cannot read it.", "Earns a mark"],
                     ["Encryption makes the network safe.", "Earns nothing"],
                     ["A MAC address is fixed to the device itself, so it identifies the hardware wherever it connects.", "Earns a mark"],
                     ["IP addresses and MAC addresses are different from each other.", "Earns nothing"]],
                    "Look at what the three failures have in common: each one states that "
                    "something is the case and stops. The three that earn the mark all turn "
                    "on a 'so' or a 'because'. That is the whole difference between a "
                    "Describe answer and an Explain one.")]),
  ],
  final=dict(name="Final challenge: key terms", floor_title="Final challenge: key terms",
    intro="Match each key term from lessons 9 to 13 with its meaning. These definitions often come up in the test.",
    ill=("tiles", [("Ethernet", "b"), ("Bluetooth", "p"), ("Encryption", "y"), ("IPv6", "g"), ("Protocol", "o"), ("Layer", "k")], 3),
    tasks=[match("Match each key term to its meaning.", [["Ethernet", "A wired standard for connecting devices on a LAN"], ["Bluetooth", "Short-range, low-power wireless connection between two devices"],
      ["Encryption", "Scrambling data so it can't be read without the key"], ["IPv6", "A 128-bit address, written in hexadecimal"], ["Protocol", "A set of rules for how devices communicate"],
      ["Layer", "A part of networking with one defined responsibility"]], "Check your results table to see which lessons to revise first.")]),
  info=[(0, "Revision tip", "Cover your notes and write the key facts from memory, then check. Testing yourself works much better than rereading."),
        (1, "Exam favourite", "Questions often ask you to recommend wired or wireless for a scenario. Always link your choice to the scenario's needs."),
        (2, "Spot the address", "If it has dots and numbers up to 255, it's IPv4. Colons and hex, it's IPv6. Dashes and hex pairs, it's a MAC address."),
        (3, "Protocol memory trick", "SMTP 'Sends Mail To People'. POP 'Pulls Off Post'. IMAP 'I Manage All Places'."),
        (4, "Layers in one line", "Each layer does one job and serves the layer above: that's the core idea to explain in the exam."),
        (5, "Marks matter", "Look at the number of marks: a 2-mark 'explain' question usually needs a point and a reason.")],
  ws=dict(title="Revision HQ 2: lessons 9 to 13", objectives=["know which lessons I am secure on and which to revise", "be ready for the end-of-unit assessment"],
    starter="Without notes, list as many key terms from lessons 9 to 13 as you can in two minutes.", starter_lines=3,
    keyterms=["Ethernet", "Encryption", "IP address", "Protocol", "Layer"],
    keyq="Which parts of this topic could I explain to somebody else, and which can I only recognise?",
    exam=[("Explain one advantage of using IPv6 instead of IPv4.", 2, 2), ("Describe how public and private keys are used.", 3, 3)],
    rag=["Modes of connection", "Wi-Fi encryption", "IP and MAC addressing", "Standards and protocols", "Layers"],
    confidence=["Lessons 9 and 10", "Lessons 11 and 12", "Lesson 13"]))
