from kit import mcq, multi, sort, match, order

K11 = "1.1 Systems architecture"
SUB11 = "OCR J277 Paper 1  |  Computer systems"

L1 = dict(id="sa-l01", topic="1.1", lesson=1, title="Fetch-execute factory", img="SA_L01_FetchExecuteFactory_360",
  description="Step inside the CPU and follow an instruction through the fetch-decode-execute cycle. Includes a 3D CPU you can take apart.",
  kicker=f"{K11}  |  Lesson 1", scene_title="Fetch-execute factory", subtitle=SUB11,
  intro="Every program you run is broken into instructions, and the CPU processes them billions of times a second. Follow an instruction through the factory and meet the registers that make it happen.",
  keywords=["CPU", "Fetch", "Decode", "Execute", "Register", "ALU", "Control unit", "Cache"],
  stations=[
   dict(name="Purpose of the CPU", bullets=["The CPU (central processing unit) processes data and instructions.", "It does this by carrying out the fetch-decode-execute cycle, over and over.",
        "It is sometimes called the brain of the computer."], challenge="Write, in your own words, the purpose of a CPU.", ill=("icons", [("cpu", "CPU"), ("ram", "RAM")]),
        fact="The purpose of the CPU is...",
        tasks=[mcq("What is the purpose of the CPU?", "To process data and instructions by fetching, decoding and executing them", ["To store files permanently", "To display images on the screen", "To connect the computer to the internet"],
                   "Storage, display and networking are done by other components."),
               mcq("What does CPU stand for?", "Central processing unit", ["Computer power unit", "Central program utility", "Control processing unit"], "It's the central part that processes everything.")]),
   dict(name="Stage 1: Fetch", bullets=["The program counter (PC) holds the address of the next instruction.", "The address is copied to the MAR, and the instruction is fetched from RAM into the MDR.",
        "The PC is incremented, so it points to the next instruction."], challenge="Describe what happens to the program counter during the fetch stage.", ill=("flow", ["PC holds address", "Copied to MAR", "Instruction to MDR", "PC + 1"]),
        fact="During the fetch stage...",
        tasks=[mcq("During the fetch stage, what happens to the program counter?", "It is incremented to point to the next instruction", ["It is cleared to zero", "It stores the result of a calculation", "It decodes the instruction"],
                   "The PC always holds the address of the next instruction, so it moves on by one."),
               mcq("Where is the instruction fetched from?", "Main memory (RAM)", ["The hard drive", "The ALU", "The monitor"], "Programs being run are held in RAM.")]),
   dict(name="Stage 2: Decode", bullets=["The instruction is now inside the CPU.", "The control unit (CU) decodes it: it works out what the instruction means and what needs to be done."],
        challenge="Which component decodes instructions?", ill=("icons", [("cpu", "Control unit")]), fact="During the decode stage...",
        tasks=[mcq("Which component decodes instructions?", "The control unit (CU)", ["The ALU", "The cache", "The MDR"], "The CU works out what each instruction means."),
               mcq("What does 'decode' mean in the fetch-decode-execute cycle?", "Working out what the instruction means and what needs to be done", ["Encrypting the instruction", "Deleting the instruction", "Sending the instruction to the printer"],
                   "Only once it's decoded can the instruction be carried out.")]),
   dict(name="Stage 3: Execute", bullets=["The instruction is carried out. Depending on the instruction, the CPU may:", "fetch data from memory to use in a calculation, done by the ALU;",
        "jump to another instruction, or write data from the accumulator back to RAM."], challenge="Give two different things that might happen during the execute stage.",
        ill=("tiles", [("Load data", "b"), ("Calculate (ALU)", "o"), ("Jump", "p"), ("Store to RAM", "g")], 2), fact="During the execute stage...",
        tasks=[mcq("Where are the results of calculations stored?", "The accumulator", ["The program counter", "The MAR", "The hard drive"], "The ALU does the maths and the accumulator holds the answer."),
               mcq("After the execute stage, what happens next?", "The cycle starts again with the next fetch", ["The computer switches off", "The program is deleted", "The CPU waits for the user to press a key"],
                   "The cycle repeats billions of times a second.")]),
   dict(name="The registers", bullets=["Registers are tiny, very fast memory locations inside the CPU.", "PC: address of the next instruction. MAR: address to fetch from or write to.",
        "MDR: data fetched or to be written. ACC: results of calculations."], challenge="Complete the registers table on your worksheet.",
        ill=("table", ["Register", "Holds"], [["PC", "Next instruction's address"], ["MAR", "Address to fetch or store"], ["MDR", "Data fetched or to store"], ["ACC", "Results of calculations"]]),
        fact="Registers are...",
        tasks=[match("Match each register to its purpose.", [["Program counter (PC)", "Holds the address of the next instruction"], ["Memory address register (MAR)", "Holds the address where data is to be stored or fetched"],
                     ["Memory data register (MDR)", "Holds data fetched from, or to be written to, main memory"], ["Accumulator (ACC)", "Holds the results of calculations"]],
                     "This is Task 2 on your worksheet and a very common exam question.")]),
   dict(name="Other CPU components", bullets=["ALU (arithmetic logic unit): performs calculations and logical decisions.", "CU (control unit): decodes instructions and sends signals to control how data moves.",
        "Cache: fast memory for frequently used instructions and data."], challenge="How does the cache stop the CPU having to wait for RAM?", ill=("tiles", [("ALU", "o"), ("Control unit", "p"), ("Cache", "y")], 3),
        fact="The ALU... The CU... The cache...",
        tasks=[match("Match each component to what it does.", [["ALU", "Performs calculations and logical decisions"], ["Control unit", "Decodes instructions and controls how data moves around the CPU"],
                     ["Cache", "Fast memory for frequently used instructions and data"]], "Use the 3D CPU model to see where the cache sits."),
               mcq("Why is cache faster to use than RAM?", "It is inside the CPU, very close to where the processing happens", ["It is bigger than RAM", "It stores data permanently", "It uses the internet"],
                   "Cache is the worktop next to the chef: fewer things fit, but they're within reach.")]),
  ],
  final=dict(name="Final challenge: the cycle", floor_title="Final challenge: run the cycle",
    intro="Put the six steps of the fetch-decode-execute cycle in the right order. Then tap the orange 3D markers to explore the hardware.",
    ill=("flow", ["Fetch", "Decode", "Execute"]),
    tasks=[order("Put the steps of the fetch-decode-execute cycle in order.", ["The PC holds the address of the next instruction", "The address is copied into the MAR",
      "The instruction is fetched from RAM into the MDR", "The PC is incremented to point to the next instruction", "The control unit decodes the instruction", "The instruction is executed"],
      "Then the whole cycle repeats for the next instruction.")]),
  models=[(("right", 210, 540), "cpu", "Inside a CPU", "Turn the CPU and click its parts. The metal lid is see-through, so you can see the cores and cache inside."),
          (("front", 270, 1684), "motherboard", "The motherboard", "See where the CPU sits, how it's kept cool, and where RAM goes.")],
  info=[(0, "The first microprocessor", "The Intel 4004, released in 1971, was the first CPU on a single chip. It had about 2,300 transistors; modern CPUs have billions."),
        (1, "Billions per second", "A 3 GHz CPU can run about 3 billion cycles every second, so the fetch-decode-execute cycle happens faster than you can imagine."),
        (2, "Instruction sets", "Each type of CPU understands its own set of instructions. PCs mostly use x86 CPUs, while phones and many new laptops use ARM."),
        (3, "Hot stuff", "CPUs get hot while they work. Many slow themselves down automatically if they reach around 100°C, to avoid damage."),
        (4, "Registers are tiny", "A register holds just one value, but it's the fastest memory in the whole computer."),
        (5, "The kitchen analogy", "Cache is like the worktop next to you: only a few things fit, but they're within reach. RAM is the cupboard across the kitchen, and storage is the shop down the road.")],
  ws=dict(title="Purpose of the CPU", objectives=["understand what the CPU of a computer does", "know what CPU registers are", "know the stages of the fetch-execute cycle", "know about other components of the CPU"],
    starter="A chef can keep three ingredients on the worktop, twenty in the cupboard and anything else at the shop. Which is like cache, which is like RAM and which is like secondary storage? Why does the worktop make cooking faster?", starter_lines=3,
    keyterms=["CPU", "Fetch-decode-execute cycle"], keyq="What is the architecture of a CPU?",
    exam=[("Describe what the CPU does while a program is running.", 2, 2), ("Name two registers found in a CPU and state what each one holds.", 4, 4), ("A computer's cache is full. Explain the effect this has on the CPU.", 3, 3)],
    confidence=["What the CPU does", "The CPU registers", "The stages of the fetch-execute cycle", "The ALU, CU and cache"]))

L2 = dict(id="sa-l02", topic="1.1", lesson=2, title="Von Neumann HQ", img="SA_L02_VonNeumannHQ_360",
  description="Meet John von Neumann and explore the stored-program architecture inside nearly every computer. Includes a 3D model of the architecture.",
  kicker=f"{K11}  |  Lesson 2", scene_title="Von Neumann HQ", subtitle=SUB11,
  intro="Almost every computer you've used follows a design described in 1945. Explore the von Neumann architecture, its components and registers, and find out what other designs exist.",
  keywords=["Von Neumann", "Stored program", "MAR", "MDR", "Program counter", "Accumulator", "Keyword"],
  stations=[
   dict(name="John von Neumann", bullets=["A Hungarian-American mathematician and computer scientist.", "In 1945 he described a design for a computer that stores programs in memory.",
        "Nearly all modern computers still follow his ideas."], challenge="Who was John von Neumann, and why is he important to computing?", ill=("icons", [("user", "John von Neumann"), ("pc", "Stored-program computer")]),
        fact="John von Neumann was...",
        tasks=[mcq("What is John von Neumann best known for in computing?", "Describing a computer design where programs are stored in memory", ["Inventing the World Wide Web", "Founding a games company", "Creating Python"],
                   "His 1945 report described the stored-program computer."),
               mcq("When did von Neumann describe his architecture?", "1945", ["1985", "2001", "1850"], "Around the end of the Second World War.")]),
   dict(name="The stored-program concept", bullets=["Instructions and data are both stored in the same main memory.", "The CPU fetches instructions and data from memory, one at a time.",
        "Loading a different program means the same computer can do a different job."], challenge="Explain how data and instructions are stored in von Neumann architecture.", ill=("icons", [("cpu", "CPU"), ("ram", "Instructions + data")]),
        fact="In von Neumann architecture, instructions and data are...",
        tasks=[mcq("In von Neumann architecture, where are instructions stored?", "In main memory, together with the data", ["Only inside the ALU", "In a separate memory from data", "On paper tape outside the computer"],
                   "Storing both in the same memory is the key feature."),
               mcq("Why is the stored-program idea so useful?", "The same computer can run different programs just by loading them into memory", ["It makes computers use no power", "It removes the need for a CPU", "It stops programs having bugs"],
                   "Early computers had to be rewired for each new job.")]),
   dict(name="Program counter and accumulator", bullets=["Program counter (PC): holds the address of the next instruction to be fetched.", "It increments during each fetch-decode-execute cycle.",
        "Accumulator (ACC): holds the results of calculations done by the ALU."], challenge="Explain the purpose of the program counter and how its value changes.",
        ill=("tiles", [("PC: next address", "b"), ("ACC: results", "o")], 2), fact="The PC... The accumulator...",
        tasks=[mcq("What does the program counter hold?", "The address of the next instruction", ["The result of the last calculation", "The current instruction's data", "The number of programs running"], "It increments with each cycle."),
               mcq("Which register holds the results of calculations?", "Accumulator", ["MAR", "Program counter", "MDR"], "The ALU's results go into the accumulator.")]),
   dict(name="MAR and MDR", bullets=["MAR (memory address register): holds the address of the data or instruction to be fetched or stored.", "MDR (memory data register): holds the data or instruction fetched from memory, or to be written to it.",
        "They work as a pair to move data between the CPU and RAM."], challenge="Describe the purpose of the memory data register.", ill=("pair", "cpu", "ram", "MAR + MDR", "RAM", "Address from MAR", "Data into MDR"),
        fact="The MAR holds... The MDR holds...",
        tasks=[mcq("Which register holds the address of data to be fetched from memory?", "Memory address register (MAR)", ["Memory data register (MDR)", "Accumulator", "Program counter"], "Address: MAR. Data: MDR."),
               mcq("What does the MDR hold?", "Data or an instruction fetched from memory, or waiting to be written to memory", ["The address of the next instruction", "The results of calculations", "The clock speed"],
                   "It's the CPU's 'in tray and out tray' for memory.")]),
   dict(name="Other architectures", bullets=["Harvard architecture stores instructions and data in separate memories, with separate buses.", "It lets an instruction and data be fetched at the same time.",
        "It's used in many embedded systems and microcontrollers."], challenge="What other architectures exist, and where are they used?", ill=("compare", "Von Neumann", ["One shared memory", "Most PCs and phones"], "Harvard", ["Separate memories", "Many microcontrollers"], "b", "p"),
        fact="Another architecture is...",
        tasks=[mcq("What is the main difference in Harvard architecture?", "Instructions and data are held in separate memories", ["It has no CPU", "It stores everything on a hard drive", "It only works with the internet"],
                   "Separate memories mean both can be fetched at once."),
               mcq("Where is Harvard architecture commonly used?", "In microcontrollers inside embedded systems", ["In web browsers", "In printers' paper trays", "In monitors' screens"], "Many small dedicated devices use it.")]),
   dict(name="Keywords", bullets=["Every programming language has keywords: reserved words with a special meaning.", "Python keywords include if, else, while, for, def, return, True and False.",
        "You can't use a keyword as a variable name."], challenge="Find three Python keywords and write what each one does.", ill=("code", ["for count in range(3):", "    if count == 2:", "        print(\"Done\")", "    else:", "        print(count)"], 28),
        fact="A keyword is...",
        tasks=[mcq("Which of these is a Python keyword?", "while", ["total", "score", "myList"], "while starts a loop. The others are just names a programmer might choose."),
               mcq("Why can't you call a variable 'if'?", "It's a keyword with a special meaning in the language", ["It's too short", "Variables must start with a capital letter", "It would use too much memory"],
                   "Keywords are reserved by the language.")]),
  ],
  final=dict(name="Final challenge: name that part", floor_title="Final challenge: name that part",
    intro="Match each component or register to its definition. This is a real exam question. Then explore the orange 3D model of the architecture.",
    ill=("tiles", [("PC", "b"), ("MAR", "b"), ("MDR", "b"), ("ACC", "b"), ("ALU", "o"), ("CU", "p"), ("Cache", "y")], 4),
    tasks=[match("Match each component or register to its definition.", [["Program counter", "Stores the address of the next instruction; increments each cycle"], ["Control unit", "Decodes instructions and sends control signals"],
      ["MAR", "Stores the address of the data to be fetched or stored"], ["ALU", "Performs mathematical calculations and logical operations"], ["MDR", "Stores data fetched from, or to be written to, memory"],
      ["Accumulator", "Stores the results of calculations"], ["Cache", "Fast memory for frequently used instructions and data"]], "Exam tip: learn these seven definitions word for word in your own style.")]),
  models=[(("right", 1178, 540), "vonneumann", "Von Neumann architecture", "Turn the model and click each block. Notice that the one RAM block holds both instructions and data."),
          (("back", 1178, 540), "cpu", "Inside a CPU", "See the registers' neighbours: the cores and cache on the silicon die.")],
  info=[(0, "A brilliant mind", "Von Neumann also made major contributions to maths, physics and game theory, and worked on some of the first electronic computers."),
        (1, "Rewiring computers", "Before stored programs, machines like ENIAC had to be physically rewired with cables to change the job they did."),
        (2, "The von Neumann bottleneck", "Because instructions and data share one memory, the CPU can only fetch one at a time. This limit is called the von Neumann bottleneck."),
        (3, "Best of both", "Modern CPUs mix both ideas: they use von Neumann-style shared RAM, but separate caches for instructions and data, like Harvard architecture."),
        (4, "Harvard Mark I", "Harvard architecture is named after the Harvard Mark I computer of 1944, which read instructions from punched tape and kept data separately."),
        (5, "How many keywords?", "Python has about 35 keywords. Try typing help(\"keywords\") into Python to see the full list.")],
  ws=dict(title="Architecture of the CPU", objectives=["describe the von Neumann architecture", "know the components of the von Neumann architecture", "understand what a keyword is"],
    starter="The same laptop can run a game, then a word processor, then a browser, with no hardware changed. What makes that possible?", starter_lines=3,
    keyterms=["ALU", "CU (control unit)"], keyq="What other architectures exist and where are they used?",
    exam=[("Name the register that holds the address of the next instruction to be fetched.", 1, 1), ("Describe what the memory data register holds and when it is used.", 2, 2),
          ("Explain what happens during each of the three stages of the fetch-decode-execute cycle.", 6, 7)],
    confidence=["The von Neumann architecture", "The PC, MAR, MDR and accumulator", "What a keyword is"]))

L3 = dict(id="sa-l03", topic="1.1", lesson=3, title="Speed lab", img="SA_L03_SpeedLab_360",
  description="Find out how clock speed, cache size and number of cores affect CPU performance. Includes a 3D multi-core CPU and a motherboard with cooling.",
  kicker=f"{K11}  |  Lesson 3", scene_title="Speed lab", subtitle=SUB11,
  intro="Why is one computer faster than another? In the speed lab you'll test the three characteristics that affect CPU performance: clock speed, cache size and the number of cores.",
  keywords=["Clock speed", "Hertz", "GHz", "Cache", "Cores", "Overclocking", "Performance"],
  stations=[
   dict(name="Clock speed", bullets=["The number of fetch-decode-execute cycles a CPU can carry out each second.", "Measured in hertz (Hz): 1 Hz is one cycle per second.",
        "A 3.5 GHz CPU runs 3.5 billion cycles per second. Higher clock speed means more instructions each second."], challenge="State what is meant by a 2.5 GHz processor.", ill=("big", "3.5 GHz", "3.5 billion cycles every second"),
        fact="Clock speed is...",
        tasks=[mcq("What does clock speed measure?", "How many fetch-decode-execute cycles the CPU can carry out per second", ["How much the CPU weighs", "How much RAM there is", "The size of the hard drive"], "More cycles per second means more instructions processed."),
               mcq("How many cycles per second does a 2 GHz processor run?", "2 billion", ["2 million", "2 thousand", "200"], "Giga means billion.")]),
   dict(name="Overclocking and heat", bullets=["Overclocking runs a CPU faster than its intended clock speed.", "Faster CPUs produce more heat, so they need better cooling, like heatsinks and fans.",
        "Too much heat can make a computer unstable or damage the CPU."], challenge="Why do faster CPUs need better cooling?", ill=("icons", [("cpu", "CPU"), ("fan", "Cooling fan")]),
        fact="Overclocking means... The risk is...",
        tasks=[mcq("What is overclocking?", "Running a CPU faster than its intended clock speed", ["Adding more RAM", "Slowing a CPU down to save power", "Changing the time on the computer's clock"], "It can boost performance but creates extra heat."),
               mcq("Why can overclocking be risky?", "The CPU gets hotter, which can cause crashes or damage", ["It deletes files", "It uses less electricity", "It stops the fans working"], "That's why overclockers use powerful cooling.")]),
   dict(name="Cache size", bullets=["Cache is fast memory inside the CPU for frequently used instructions and data.", "A bigger cache holds more, so the CPU makes fewer slow trips to RAM.",
        "Cache comes in levels: L1 is fastest and smallest; L2 and L3 are bigger and a little slower."], challenge="Explain how a bigger cache improves performance.", ill=("stack", [("L1 cache", "Fastest, smallest", "y"), ("L2 cache", "Bigger, slower", "o"), ("L3 cache", "Biggest, slower", "r"), ("RAM", "Much slower", "n")]),
        fact="A larger cache improves performance because...",
        tasks=[mcq("Why does a larger cache usually improve performance?", "More instructions and data can be kept close to the CPU, so it waits for RAM less often", ["It increases the clock speed", "It adds extra cores", "It makes the hard drive faster"],
                   "Fetching from cache is much quicker than fetching from RAM."),
               mcq("Which level of cache is the fastest?", "L1", ["L2", "L3", "They are all the same"], "L1 is closest to the core, so it's the quickest but also the smallest.")]),
   dict(name="Number of cores", bullets=["Each core is a processing unit that can fetch, decode and execute instructions on its own.", "A quad-core CPU can process four instructions at the same time.",
        "Doubling the cores doesn't always double the speed: software must be written to use them, and some tasks can't be split up."], challenge="Why doesn't a dual-core CPU always run a program twice as fast as a single-core one?",
        ill=("tiles", [("Core 1", "b"), ("Core 2", "b"), ("Core 3", "b"), ("Core 4", "b")], 4), fact="More cores improve performance because... but...",
        tasks=[mcq("What is a core?", "A processing unit that can fetch, decode and execute instructions independently", ["A type of RAM", "The centre of the hard drive", "A cooling fan"], "Multi-core CPUs have several of these on one chip."),
               mcq("Why might a quad-core CPU not be four times faster?", "Not all software is designed to split its work between cores", ["Cores can only run one at a time", "Extra cores slow down the clock", "Cores don't do any processing"],
                   "Some jobs have to be done step by step, so extra cores sit waiting.")]),
   dict(name="Single core, 2.5 GHz", bullets=["'Single core' means the CPU has one processing unit.", "'2.5 GHz' means it runs 2.5 billion fetch-decode-execute cycles each second.",
        "Exam answers should link each characteristic to its effect on performance."], challenge="A computer has a 2.5 GHz processor and 5 GB of RAM. State the purpose of its CPU.", ill=("tiles", [("1 core", "b"), ("2.5 GHz", "o")], 2),
        fact="A single core 2.5 GHz processor...",
        tasks=[mcq("What is meant by a single core 2.5 GHz processor?", "It has one processing unit that carries out 2.5 billion cycles per second", ["It has 2.5 cores", "It has 2.5 GB of cache", "It can run for 2.5 hours"],
                   "This is a real exam question worth 2 marks: one for each part."),
               mcq("Which change would most help a CPU run several programs at the same time?", "Adding more cores", ["Lowering the clock speed", "Removing the cache", "Using a bigger monitor"], "Each core can work on a different task.")]),
   dict(name="Units of speed", bullets=["1 kilohertz (kHz) = 1,000 cycles per second.", "1 megahertz (MHz) = 1 million cycles per second.", "1 gigahertz (GHz) = 1 billion cycles per second."],
        challenge="Put these in order, slowest first: 900 MHz, 1.2 GHz, 400 kHz.", ill=("table", ["Unit", "Cycles per second"], [["kHz", "1,000"], ["MHz", "1,000,000"], ["GHz", "1,000,000,000"]]),
        fact="The units of clock speed are...",
        tasks=[mcq("Which is the fastest clock speed?", "2 GHz", ["20 MHz", "200 kHz", "900 MHz"], "2 GHz is 2,000 MHz."),
               mcq("Which three characteristics of a CPU affect its performance?", "Clock speed, cache size and the number of cores", ["Clock speed, screen size and storage", "Cache size, RAM and network speed", "Cores, monitor and keyboard"],
                   "These three are the ones named in the specification.")]),
  ],
  final=dict(name="Final challenge: fastest to slowest", floor_title="Final challenge: race the processors",
    intro="Five processors are on the starting line. Put them in order, slowest first. Then explore the orange 3D models.",
    ill=("tiles", [("200 kHz", "n"), ("20 MHz", "b"), ("800 MHz", "p"), ("2 GHz", "o"), ("3.5 GHz", "r")], 5),
    tasks=[order("Put these processors in order of clock speed, slowest first.", ["200 kilohertz", "20 megahertz", "800 megahertz", "2 gigahertz", "3.5 gigahertz"],
      "Remember: kilo is thousand, mega is million, giga is billion.")]),
  models=[(("back", 1258, 401), "cpu", "A quad-core CPU", "Click the cores and the cache to see how each affects performance."),
          (("right", 1178, 540), "motherboard", "Keeping cool", "Click the heatsink and fan to see how a fast CPU is kept cool.")],
  info=[(0, "Turbo boost", "Many CPUs speed themselves up automatically for short bursts when there's lots of work, then slow down again to stay cool."),
        (1, "World records", "Enthusiasts have overclocked CPUs past 9 GHz using liquid nitrogen to keep them cold, but only for a few minutes."),
        (2, "Cache sizes", "Cache is measured in megabytes, while RAM is measured in gigabytes. Cache is tiny, but much faster."),
        (3, "Phones have many cores", "Many smartphones have eight cores: some powerful ones for games and some low-power ones to save battery."),
        (4, "It's not just the CPU", "The amount of RAM, the speed of storage and the graphics card also affect how fast a computer feels."),
        (5, "Hertz", "The unit hertz is named after Heinrich Hertz, a German physicist who proved radio waves exist.")],
  ws=dict(title="How CPU characteristics affect performance", objectives=["understand three ways in which the speed of a CPU, and therefore a computer, can be increased", "begin learning how to program"],
    starter="Two laptops both have 8 GB of RAM, but one feels much faster. Suggest three things about their processors that could explain the difference.", starter_lines=3,
    keyterms=["Cache", "Register"], keyq="What factors affect CPU performance?",
    exam=[("State three characteristics of a CPU that affect its performance.", 3, 3), ("A laptop is advertised with a quad-core 3.2 GHz processor. Explain what this tells you about the CPU.", 3, 4),
          ("A user edits video and finds their computer slow. Explain how each of the three characteristics could improve its performance.", 6, 7)],
    confidence=["How clock speed affects performance", "How cache size affects performance", "How the number of cores affects performance"]))

L4 = dict(id="sa-l04", topic="1.1", lesson=4, title="Smart home", img="SA_L04_SmartHome_360",
  description="Find the embedded systems hidden around a smart home, and take apart a 3D washing machine to see the computer inside.",
  kicker=f"{K11}  |  Lesson 4", scene_title="Smart home", subtitle=SUB11,
  intro="This house is full of computers, but hardly any of them look like one. Find out what embedded systems are, where they are, and how they take input, process it and give output.",
  keywords=["Embedded system", "Dedicated function", "Microcontroller", "Input", "Process", "Output", "Firmware"],
  stations=[
   dict(name="What is an embedded system?", bullets=["A computer system built into a larger device.", "It has a dedicated function: it does one job, or a small set of jobs.",
        "Examples: washing machines, microwaves, traffic lights and car engine management."], challenge="Explain what an embedded system is.", ill=("icons", [("washer", "Washing machine"), ("cpu", "Embedded computer")]),
        fact="An embedded system is...",
        tasks=[mcq("What is an embedded system?", "A computer system built into a larger device to do a dedicated job", ["A laptop used for many different tasks", "A program saved in the cloud", "A type of monitor"],
                   "It's part of something bigger, and it has a specific purpose."),
               mcq("Which is an example of an embedded system?", "The controller in a microwave oven", ["A desktop PC", "A laptop", "A tablet running many apps"], "The others are general-purpose computers.")]),
   dict(name="Characteristics", bullets=["Limited functions: runs one dedicated program.", "Usually small, low power and cheap to mass produce.",
        "Very reliable, and often has to respond in real time."], challenge="Why are embedded systems usually cheap and low power?", ill=("tiles", [("One job", "b"), ("Small", "g"), ("Low power", "g"), ("Reliable", "p"), ("Cheap", "o"), ("Real time", "k")], 3),
        fact="Embedded systems are usually...",
        tasks=[multi("Which are typical characteristics of embedded systems? Select all that apply.", ["Dedicated to a specific task", "Low power consumption", "Small in size", "Reliable",
                     "Designed to run lots of different apps", "Needs a large monitor and keyboard"], ["Dedicated to a specific task", "Low power consumption", "Small in size", "Reliable"],
                     "Running lots of apps is what general-purpose computers do."),
               mcq("Why are embedded systems usually cheap to make?", "They only need enough processing power for one job, and are made in huge numbers", ["They have no processor", "They are made by hand", "They don't need electricity"],
                   "Simple, mass-produced hardware keeps the cost down.")]),
   dict(name="Embedded systems everywhere", bullets=["At home: washing machines, microwaves, smart thermostats, TVs and fridges.", "Out and about: traffic lights, cash machines and car systems, like automatic lights and anti-lock brakes.",
        "On you: fitness trackers and smartwatches."], challenge="List five embedded systems you have used today.", ill=("icons", [("washer", "Washer"), ("phone", "Tracker"), ("router", "Traffic lights")]),
        fact="Examples of embedded systems include...",
        tasks=[mcq("Which of these contains an embedded system?", "A car's automatic headlights", ["A pencil", "A paper book", "A wooden chair"], "A sensor and microcontroller switch the lights on when it gets dark."),
               mcq("Complete the exam sentence: embedded systems have limited...", "functions", ["colours", "keyboards", "screens"], "Embedded systems have limited functions and are built into a larger machine.")]),
   dict(name="Input, process, output", bullets=["Input: buttons, dials and sensors, such as a water temperature sensor.", "Process: a microcontroller runs the program and makes decisions.",
        "Output: motors, heaters, lights and displays."], challenge="Choose a device in your home and describe its inputs, its processing and its outputs.", ill=("flow", ["Input: dial and sensors", "Process: microcontroller", "Output: motor and heater"]),
        fact="A washing machine is a computer because...",
        tasks=[sort("Is each part of a washing machine an input, process or output?", ["Input", "Process", "Output"], [["Program dial", "Input"], ["Temperature sensor", "Input"],
                     ["Microcontroller running the wash program", "Process"], ["Motor turning the drum", "Output"], ["Water heater", "Output"], ["Display showing time left", "Output"]],
                     "Take apart the 3D washing machine to see each part.")]),
   dict(name="Programming embedded systems", bullets=["The program is stored permanently in the device, often called firmware.", "Embedded systems are often programmed in C or C++, which run fast and give close control of the hardware.",
        "Some firmware can be updated, like a smart TV's software update."], challenge="What programming language is mainly used for embedded systems, and why?", ill=("code", ["// C code for a thermostat", "if (temperature < target) {", "    heater_on();", "} else {", "    heater_off();", "}"], 26),
        fact="Embedded systems are programmed using...",
        tasks=[mcq("Which programming language is mainly used for embedded systems?", "C (and C++)", ["HTML", "Scratch", "SQL"], "C is fast and gives close control of the hardware."),
               mcq("What is firmware?", "The program stored permanently in a device to control it", ["The outer case of a device", "A type of cable", "A website"], "It's usually held in ROM or flash memory.")]),
   dict(name="Embedded or general purpose?", bullets=["A general-purpose computer, like a laptop, can run many different programs.", "An embedded system is built in to one device and does one dedicated job.",
        "Some devices blur the line, like smart TVs that run apps."], challenge="Explain why a laptop is not an embedded system.", ill=("compare", "Embedded", ["One dedicated job", "Built into a device"], "General purpose", ["Runs many programs", "Laptop, desktop"], "g", "b"),
        fact="The difference between embedded and general-purpose computers is...",
        tasks=[mcq("Why is a laptop not an embedded system?", "It's a general-purpose computer that can run many different programs", ["It doesn't have a CPU", "It is too heavy", "It has no memory"], "Embedded systems have a dedicated function."),
               mcq("A car has a computer that only controls the anti-lock brakes. What is it?", "An embedded system", ["A general-purpose computer", "A server", "A web browser"], "It's built in, with one job.")]),
  ],
  final=dict(name="Final challenge: spot the embedded system", floor_title="Final challenge: spot the embedded system",
    intro="Eight devices from around the house and street. Tap the star and sort each one into embedded system or general-purpose computer. Then take apart the 3D washing machine.",
    ill=("icons", [("washer", "Washing machine"), ("laptop", "Laptop"), ("phone", "Fitness tracker")]),
    tasks=[sort("Is each device an embedded system or a general-purpose computer?", ["Embedded", "General purpose"], [["Washing machine", "Embedded"], ["Microwave oven", "Embedded"],
      ["Traffic lights", "Embedded"], ["Car anti-lock brakes", "Embedded"], ["Smart thermostat", "Embedded"], ["Laptop", "General purpose"], ["Desktop PC", "General purpose"], ["Tablet running apps", "General purpose"]],
      "The exam paragraph: embedded systems have limited functions and are often built into a larger machine.")]),
  models=[(("back", 1178, 540), "washingmachine", "Inside a washing machine", "The casing is see-through. Click each part to see whether it's an input, the process, or an output."),
          (("left", 210, 540), "cpu", "A processor", "Embedded systems use small, low-power processors called microcontrollers.")],
  info=[(0, "Computers on wheels", "A modern car has dozens of embedded computers, often more than 50, controlling everything from the engine to the windows."),
        (1, "Life-saving computers", "Pacemakers are embedded systems that must be extremely reliable and run for years on one battery."),
        (2, "The Internet of Things", "When embedded systems connect to the internet, like smart speakers and doorbells, they're called the Internet of Things."),
        (3, "Microcontrollers", "A microcontroller combines a CPU, memory and input/output on one tiny chip: a whole computer the size of a fingernail."),
        (4, "Space-proof code", "The Mars rovers are controlled by embedded systems whose software can be updated from Earth, millions of kilometres away."),
        (5, "Real time", "Anti-lock brakes must respond in milliseconds. Systems that must react instantly are called real-time systems.")],
  ws=dict(title="Embedded systems", objectives=["understand what is meant by the term embedded system", "know several examples of embedded systems", "understand how to program"],
    starter="List five devices in your home that contain a computer but don't look like one. What does each one do with the data it collects?", starter_lines=3,
    keyterms=["Von Neumann architecture", "MAR"], keyq="What are embedded systems, and what are their characteristics?",
    exam=[("Name an embedded system and explain why it is described as a computer.", 3, 3), ("Describe two characteristics of embedded systems.", 4, 4), ("Explain why a laptop is not an embedded system.", 2, 2)],
    rag=["The purpose of the CPU and the fetch-execute cycle", "Common CPU components: ALU, CU, cache, registers", "Von Neumann architecture: MAR, MDR, PC, accumulator",
         "How clock speed, cache size and number of cores affect performance", "The purpose, characteristics and examples of embedded systems"],
    confidence=["What an embedded system is", "Examples of embedded systems", "How embedded systems take input, process and output"]))
