from kit import mcq, multi, sort, match, order

K14 = "1.4 Network security"
SUB14 = "OCR J277 Paper 1  |  Computer systems"

L6 = dict(id="ns-l06", topic="1.4", lesson=6, title="Cracking lab", img="NS_L06_CrackingLab_360",
  description="See how fast a computer can guess passwords, and learn what makes a password, and a login page, hard to crack.",
  kicker=f"{K14}  |  Lesson 6", scene_title="Cracking lab", subtitle=SUB14,
  intro="A brute-force attack simply tries passwords until one works. In the cracking lab you'll see how fast that is, what makes a password strong, and how a login page fights back.",
  keywords=["Brute force", "Dictionary attack", "Password", "Lockout", "Two-factor", "Hashing"],
  stations=[
   dict(name="What is a brute-force attack?", bullets=["Software tries every possible combination of characters until it finds the password.",
        "No clever trick is needed: just speed, and modern computers are very fast.", "It's often automated and aimed at thousands of accounts at once."],
        challenge="Why is a brute-force attack described as 'trial and error'?", ill=("icons", [("robot", "Attack software"), ("key", "Guesses"), ("form", "Login page")]),
        fact="A brute-force attack is...",
        tasks=[mcq("What is a brute-force attack?", "Trying huge numbers of possible passwords until the right one is found", ["Tricking a user into revealing a password", "Flooding a server with traffic", "Entering code into a text box"],
                   "No trickery: it's simply trial and error at high speed."),
               mcq("Which account is most at risk from brute force?", "One with a short password made only of lower-case letters", ["One with a long passphrase", "One that uses two-factor authentication", "One that locks after three failed attempts"],
                   "Fewer possible combinations means less time to crack.")]),
   dict(name="Dictionary attacks", bullets=["A dictionary attack tries lists of common passwords and real words first.",
        "Lists from previous data breaches are used, because people reuse passwords.", "'password', '123456' and 'qwerty' are tried within the first second."],
        challenge="Why is 'Liverpool2015' a weaker password than it looks?", ill=("code", ["123456", "password", "qwerty", "liverpool", "letmein"], 30),
        fact="A dictionary attack works by...",
        tasks=[mcq("How is a dictionary attack different from pure brute force?", "It tries likely words and known passwords first, instead of every combination", ["It only works on dictionaries", "It attacks the router", "It needs physical access"],
                   "Most people choose predictable passwords, so this is much faster."),
               mcq("Why is reusing a password across sites dangerous?", "If one site is breached, attackers try the same password everywhere else", ["It uses more storage", "It slows down logins", "It stops two-factor working"],
                   "This is called credential stuffing.")]),
   dict(name="How long would it take?", bullets=["Each extra character multiplies the number of possible passwords.",
        "Using upper case, numbers and symbols increases the choices per character.", "A short password can fall in seconds; a long passphrase could take centuries."],
        challenge="Use the starter site to test a password you don't use. How could you improve it?",
        ill=("table", ["Password", "Time to crack"], [["dog", "Instant"], ["Dog2015", "Minutes"], ["purpletoasterdance", "Centuries"]]), fact="Password strength depends on...",
        tasks=[mcq("Which password is hardest to brute-force?", "correct-horse-battery-staple", ["P@ss1", "Summer2024", "abc123"], "Length matters more than anything: a long passphrase has far more combinations."),
               mcq("Why does adding one character make such a difference?", "Every extra character multiplies the number of possible combinations", ["It confuses the attacker", "It makes the password encrypted", "It blocks the login page"],
                   "With 95 possible characters, each extra one multiplies the possibilities by 95.")]),
   dict(name="Password policies", bullets=["Organisations set rules: a minimum length, a mix of character types, and no reuse.",
        "Passphrases of three random words are long, strong and memorable.", "Password managers create and store a different strong password for every site."],
        challenge="Write three rules for a school password policy, and explain each.", ill=("tiles", [("Long", "g"), ("Mixed characters", "g"), ("Never reused", "g"), ("Never shared", "g")], 2),
        fact="A good password policy says...",
        tasks=[multi("Which of these belong in a strong password policy? Select all that apply.", ["A minimum length of at least 12 characters", "A mix of letters, numbers and symbols",
                     "A different password for each account", "Never sharing passwords", "Writing passwords on a note by the screen", "Using your name and year of birth"],
                     ["A minimum length of at least 12 characters", "A mix of letters, numbers and symbols", "A different password for each account", "Never sharing passwords"],
                     "The last two make life easier for attackers, not for you."),
               mcq("Why do experts recommend a password manager?", "It creates and remembers a different strong password for every site", ["It makes passwords shorter", "It shares passwords with friends safely", "It removes the need for any password"],
                   "You only have to remember one strong master password.")]),
   dict(name="Fighting back", bullets=["Account lockouts: after a few failed attempts the account is locked or delayed.", "CAPTCHA tests block automated software.",
        "Two-factor authentication means a stolen password isn't enough.", "Rate limiting slows down repeated attempts from the same source."],
        challenge="Why does a delay of a few seconds after a failed login make brute force much harder?",
        ill=("tiles", [("Lockouts", "g"), ("CAPTCHA", "g"), ("Two-factor", "g"), ("Rate limiting", "g")], 2), fact="Login pages defend against brute force by...",
        tasks=[mcq("How does an account lockout stop brute force?", "The attacker can only make a few guesses before the account is locked", ["It deletes the attacker's computer", "It encrypts the password", "It hides the login page"],
                   "Millions of guesses per second becomes three guesses."),
               mcq("Why does two-factor authentication help even if a password is guessed?", "The attacker also needs the second factor, such as a code on the user's phone", ["It changes the password automatically", "It blocks the internet", "It makes the password longer"],
                   "Two-factor is one of the most effective defences there is.")]),
   dict(name="Behind the scenes", bullets=["Websites should store a hash of your password, not the password itself.",
        "Hashing is one-way: you can check a password, but not work it out from the hash.", "A 'salt' adds random data so identical passwords have different hashes."],
        challenge="Why is it serious if a website stores passwords as plain text?", ill=("flow", ["Password", "Hashing", "Stored hash", "Checked at login"]), fact="Websites should store passwords by...",
        tasks=[mcq("What should a website store instead of your password?", "A hash of the password", ["The password in plain text", "Your email address only", "A photograph of you"],
                   "Hashing means even a stolen database doesn't reveal the passwords directly."),
               mcq("Why is hashing described as one-way?", "You can turn a password into a hash, but you can't turn a hash back into the password", ["It only works on one computer", "It can only be used once", "It works only for short passwords"],
                   "Attackers have to guess, hash the guess and compare, which is slow if the password is strong.")]),
  ],
  final=dict(name="Final challenge: password strength", floor_title="Final challenge: rank the passwords",
    intro="Six passwords have been submitted to the security team. Tap the star and put them in order, weakest first.",
    ill=("tiles", [("Short = seconds", "r"), ("Long = centuries", "g")], 2),
    tasks=[order("Put these passwords in order, weakest first.", ["123456", "chelsea", "Summer24", "Tr0ub4dor", "Xq7!vR2t", "three-random-words-together"],
      "Length beats complexity: a long passphrase is both stronger and easier to remember.")]),
  info=[(0, "Billions per second", "A powerful computer with graphics cards can test billions of password guesses per second against a stolen list of hashes."),
        (1, "The top password", "Lists of leaked passwords are still topped by '123456'. It's usually the first guess an attacker makes."),
        (2, "Have I been pwned", "Free services let you check whether your email address has appeared in a known data breach, so you know which passwords to change."),
        (3, "Three random words", "The UK's National Cyber Security Centre recommends three random words as a password: long, strong and easy to remember."),
        (4, "Rainbow tables", "Attackers precompute huge tables of hashes to look up stolen ones instantly. Adding a random 'salt' to each password defeats this."),
        (5, "Not just logins", "Wi-Fi passwords, phone PINs and even bike locks can be brute-forced. A four-digit PIN has only 10,000 combinations.")],
  ws=dict(title="Brute-force attacks", objectives=["understand what a brute-force attack is", "understand how to identify and protect against brute-force attacks"],
    starter="Estimate how many guesses a computer would need to find a 4-digit PIN, then a 6-letter lower-case password. What does that tell you about password length?", starter_lines=3,
    keyterms=["Brute-force attack", "Password"], keyq="How does a brute-force attack work?",
    exam=[("Describe how a brute-force attack works.", 2, 2), ("Explain two measures a website can use to make brute-force attacks impractical.", 4, 4),
          ("Explain why a long passphrase is harder to crack than a short complex password.", 3, 3)],
    confidence=["What a brute-force attack is", "What makes a password strong", "How login pages defend against brute force"]))

L7 = dict(id="ns-l07", topic="1.4", lesson=7, title="Traffic flood", img="NS_L07_TrafficFlood_360",
  description="Watch a website drown under fake traffic: DoS, DDoS, botnets and zombies, and the day half the internet went down.",
  kicker=f"{K14}  |  Lesson 7", scene_title="Traffic flood", subtitle=SUB14,
  intro="A denial-of-service attack doesn't steal anything: it stops a service working at all. Find out how one computer, or a million, can take a website offline, and what defenders can do.",
  keywords=["Denial of service", "DDoS", "Botnet", "Zombie", "Bandwidth", "Downtime"],
  stations=[
   dict(name="Denial of service", bullets=["A denial-of-service (DoS) attack floods a server with requests so it can't respond to real users.",
        "Nothing is stolen: the aim is disruption.", "The service slows down or goes offline completely."],
        challenge="What does a DoS attack set out to achieve?", ill=("icons", [("robot", "Attacker"), ("server", "Server"), ("user", "Real users")]), fact="A denial-of-service attack...",
        tasks=[mcq("What does a denial-of-service attack set out to do?", "Stop real users from being able to use a service", ["Steal passwords from a database", "Encrypt files for a ransom", "Read data as it crosses the network"],
                   "It denies service: that's exactly what the name says."),
               mcq("What is the main cost of a DoS attack to a business?", "Downtime: lost sales and customers while the service is unavailable", ["The electricity used by the attack", "The cost of new keyboards", "Nothing, if no data is stolen"],
                   "An online shop that's offline earns nothing.")]),
   dict(name="DDoS and botnets", bullets=["A distributed denial-of-service (DDoS) attack uses many computers at once.",
        "Infected computers under an attacker's control are called zombies, and the network of them is a botnet.", "The owners usually have no idea their device is taking part."],
        challenge="Why is a DDoS attack harder to block than a DoS attack?", ill=("flow", ["Attacker", "Botnet of zombies", "Flood of requests", "Server overwhelmed"]),
        fact="A DDoS attack uses...",
        tasks=[mcq("What is a botnet?", "A network of infected computers controlled by an attacker", ["A program that blocks adverts", "A type of firewall", "A backup server"],
                   "Each infected machine is called a zombie."),
               mcq("Why is a distributed attack harder to stop?", "The traffic comes from thousands of different addresses, so it's hard to tell it from real users", ["It uses less bandwidth", "It only happens at night", "It comes from one address that is easy to block"],
                   "Blocking one address does nothing when there are 100,000 of them.")]),
   dict(name="21 October 2016", bullets=["A huge DDoS attack hit Dyn, a company that runs DNS servers for much of the internet.",
        "Netflix, Twitter, Spotify, Reddit, PayPal and many news sites became unreachable.", "The Mirai botnet was made of hacked smart devices, such as cameras and routers, using default passwords."],
        challenge="Why did taking down one company affect so many websites?", ill=("icons", [("wap", "Smart devices"), ("router", "Botnet"), ("server", "DNS provider")]),
        fact="In the 2016 attack...",
        tasks=[mcq("What were most of the devices in the Mirai botnet?", "Internet-connected devices such as cameras and routers, still using default passwords", ["Supercomputers in universities", "Games consoles owned by the attacker", "Company mail servers"],
                   "Smart devices are rarely updated and often ship with the same password."),
               mcq("Why did attacking a DNS provider knock out so many sites?", "Without DNS, browsers couldn't turn domain names into IP addresses", ["It deleted the websites", "It encrypted every web page", "It switched off the undersea cables"],
                   "The sites were still running; nobody could find them.")]),
   dict(name="Effects", bullets=["Customers can't reach the service, so sales and trust are lost.", "Staff can't work if internal systems are affected.",
        "Sometimes a DDoS is a smokescreen while another attack happens elsewhere."], challenge="List three effects of a week-long DDoS attack on an online shop.",
        ill=("tiles", [("Lost sales", "r"), ("Lost trust", "o"), ("Staff idle", "y"), ("Recovery costs", "p")], 2), fact="The effects of a DoS attack are...",
        tasks=[multi("Which are effects of a successful DDoS attack on a company? Select all that apply.", ["Customers can't buy anything while the site is down", "Damage to the company's reputation",
                     "Staff unable to use internal systems", "The company's data is automatically encrypted", "Every customer's password is revealed"],
                     ["Customers can't buy anything while the site is down", "Damage to the company's reputation", "Staff unable to use internal systems"],
                     "A DoS attack doesn't steal or encrypt data: it blocks access."),
               mcq("Why might attackers launch a DDoS as a distraction?", "The security team is busy, so another attack may go unnoticed", ["It backs up the data first", "It switches off the firewall by law", "It makes the servers faster"],
                   "Attacks often come in combinations.")]),
   dict(name="Defending the server", bullets=["Firewalls and filters can block suspicious traffic patterns.", "Rate limiting caps how many requests one source can make.",
        "Extra capacity and traffic-spreading services absorb large floods.", "Intrusion detection systems and monitoring spot attacks early."],
        challenge="Which defence would you buy first for a small online shop, and why?", ill=("tiles", [("Firewall", "g"), ("Rate limiting", "g"), ("Extra capacity", "g"), ("Monitoring", "g")], 2),
        fact="To defend against DoS attacks, organisations...",
        tasks=[mcq("How does rate limiting help against a DoS attack?", "It caps how many requests each source can make, so floods are throttled", ["It encrypts the web pages", "It hides the server's IP address forever", "It deletes the attacker's account"],
                   "Genuine users rarely make hundreds of requests a second."),
               mcq("Which helps stop your devices being used in a botnet?", "Changing default passwords and keeping devices updated", ["Turning the router upside down", "Using a longer network cable", "Paying the ransom"],
                   "Mirai spread entirely through default passwords.")]),
   dict(name="Watching the attacks", bullets=["Attack maps show DDoS traffic around the world in near real time.", "Monitoring normal traffic makes unusual spikes obvious.",
        "Many attacks are bought as a service for a few pounds, which is illegal."], challenge="Discuss what the digital attack map shows and what patterns you notice.",
        ill=("worldmap",), fact="Attacks can be detected by...",
        tasks=[mcq("Why does knowing normal traffic patterns help?", "Because an unusual spike stands out as a possible attack", ["Because attacks only happen on Mondays", "Because it makes servers faster", "Because it encrypts the traffic"],
                   "Detection is the first step in responding."),
               mcq("Paying a website to 'stress test' someone else's server is:", "Illegal under the Computer Misuse Act", ["Fine if you don't do it yourself", "Legal if the attack fails", "Legal if you are under 18"],
                   "People have been prosecuted in the UK for using these services.")]),
  ],
  final=dict(name="Final challenge: the anatomy of a DDoS", floor_title="Final challenge: the anatomy of a DDoS",
    intro="Put the stages of a DDoS attack in the right order, from the attacker's first move to the website going offline.",
    ill=("flow", ["Infect", "Build botnet", "Command", "Flood", "Offline"]),
    tasks=[order("Put the stages of a DDoS attack in order.", ["Malware infects thousands of poorly secured devices", "The infected devices become zombies in a botnet",
      "The attacker sends a command to the botnet", "Every zombie sends requests to the target server at once", "The server runs out of capacity and stops responding to real users"],
      "This is the illustration you need for your Hacker's Handbook page on denial of service.")]),
  info=[(0, "It's not always an attack", "A sudden rush of genuine visitors, such as tickets going on sale, can knock a site over too. That's sometimes called the 'hug of death'."),
        (1, "Mirai's source code", "The code behind the Mirai botnet was published online, so copies of it are still scanning the internet for weak devices today."),
        (2, "Attack sizes", "The largest recorded DDoS attacks have exceeded the capacity of entire countries' internet connections, measured in terabits per second."),
        (3, "Smart devices", "Your fridge, doorbell or camera can join a botnet. Change default passwords and install updates on anything you connect to the internet."),
        (4, "Absorbing floods", "Large providers protect customers by spreading traffic across many data centres, so no single server has to take the whole flood."),
        (5, "Ransom DDoS", "Some criminals threaten a DDoS attack unless a company pays. Police advise reporting it and not paying.")],
  ws=dict(title="Denial-of-service attacks", objectives=["understand what a denial-of-service attack is", "understand how to identify and protect against denial-of-service attacks"],
    starter="An online shop is unreachable for a whole Saturday. List everything that costs the company while the site is down.", starter_lines=3,
    keyterms=["Denial of service", "Botnet"], keyq="How does a denial-of-service attack work, and how can it be defended against?",
    exam=[("Describe what a denial-of-service attack does to a service.", 2, 2), ("Explain why an attack from a botnet is harder to block than one from a single computer.", 3, 3),
          ("Describe two measures that reduce the impact of a DDoS attack on a website.", 4, 4)],
    confidence=["What a denial-of-service attack is", "Botnets and zombies", "Defending against DDoS attacks"]))

L8 = dict(id="ns-l08", topic="1.4", lesson=8, title="Packet sniffers", img="NS_L08_PacketSniffers_360",
  description="Data can be read as it travels. Learn how interception works, what it gives attackers, and how encryption stops it.",
  kicker=f"{K14}  |  Lesson 8", scene_title="Packet sniffers", subtitle=SUB14,
  intro="Every message you send crosses networks you don't control. Find out how attackers capture data in transit, what they can do with it, and why encryption is the answer.",
  keywords=["Interception", "Packet sniffing", "Encryption", "Man in the middle", "VPN", "HTTPS"],
  stations=[
   dict(name="Data interception and theft", bullets=["Data is captured as it travels across a network, without the sender or receiver knowing.",
        "Attackers can also steal data at rest: from a stolen laptop, USB stick or printout.", "The aim is usually personal details, passwords or company secrets."],
        challenge="Write a definition of data interception and theft.", ill=("pair", "laptop", "server", "Sender", "Server", "Data in transit", "Attacker listening"),
        fact="Data interception and theft is...",
        tasks=[mcq("What is data interception?", "Capturing data as it travels across a network", ["Encrypting data before it is sent", "Deleting data from a server", "Flooding a network with traffic"],
                   "The data still arrives, so the victim may never know."),
               mcq("Which is an example of data theft rather than interception?", "A laptop full of customer records is stolen from a car", ["Packets are captured on public Wi-Fi", "A router is monitored by software", "Traffic is copied as it crosses a switch"],
                   "Theft takes the data at rest; interception takes it in transit.")]),
   dict(name="Packet sniffing", bullets=["Packet sniffer software captures the packets travelling on a network.",
        "Network managers use it legitimately to find faults; attackers use the same tools to steal data.", "Unsecured or public Wi-Fi makes sniffing much easier."],
        challenge="Name a piece of software or hardware used for packet sniffing.", ill=("icons", [("wap", "Open Wi-Fi"), ("pc", "Sniffer"), ("disk", "Captured packets")]),
        fact="Packet sniffing means...",
        tasks=[mcq("What does packet sniffer software do?", "Captures and examines the packets travelling across a network", ["Blocks websites for children", "Encrypts a hard drive", "Backs up files automatically"],
                   "It's a normal network management tool that attackers misuse."),
               mcq("Why is free public Wi-Fi risky?", "Traffic may be unencrypted, and anyone nearby could capture it", ["It is always slower", "It uses more battery", "It cannot reach secure websites"],
                   "Attackers also set up fake hotspots with convincing names.")]),
   dict(name="Man in the middle", bullets=["The attacker sits between you and the service, passing messages on.", "Both sides think they're talking directly to each other.",
        "A fake Wi-Fi hotspot, such as 'Free Airport WiFi', is a common trick."], challenge="Why is a fake hotspot so effective?",
        ill=("flow", ["You", "Attacker", "Website"]), fact="A man-in-the-middle attack is...",
        tasks=[mcq("In a man-in-the-middle attack, what does the attacker do?", "Sits between the two parties, reading and passing on the messages", ["Blocks all traffic to the website", "Encrypts the victim's files", "Guesses passwords repeatedly"],
                   "Neither side realises anyone is in between."),
               mcq("Which warning sign might suggest a fake hotspot?", "An open network with a convincing name and no password", ["A network that asks for WPA2 security", "A network with a padlock icon", "A network named after your own router"],
                   "Open networks give attackers the easiest route in.")]),
   dict(name="What attackers gain", bullets=["Usernames and passwords typed into unencrypted sites.", "Bank details, private messages and company documents.",
        "Enough personal information to commit identity fraud."], challenge="What could someone do with an intercepted school login?",
        ill=("tiles", [("Logins", "r"), ("Bank details", "o"), ("Private messages", "y"), ("Company secrets", "p")], 2), fact="Intercepted data can be used to...",
        tasks=[mcq("Why is intercepted data valuable to criminals?", "It can be used for fraud, or sold to others", ["It makes their internet faster", "It proves their software works", "It deletes their own records"],
                   "Stolen data is traded openly on criminal marketplaces."),
               mcq("Which everyday habit most increases the risk of data theft?", "Writing passwords down and leaving them by the computer", ["Locking your screen", "Using a password manager", "Updating your phone"],
                   "People remain the easiest way in.")]),
   dict(name="Encryption is the answer", bullets=["Encryption scrambles data so intercepted packets are useless without the key.",
        "HTTPS encrypts traffic between a browser and a website; WPA2 encrypts Wi-Fi.", "A VPN encrypts everything between your device and a trusted server."],
        challenge="Why does encryption not stop interception, but still protect you?", ill=("tiles", [("HTTPS", "g"), ("WPA2", "g"), ("VPN", "g"), ("Encrypted files", "g")], 2),
        fact="Encryption protects data by...",
        tasks=[mcq("How does encryption protect data in transit?", "Intercepted data can't be understood without the key", ["It stops packets being captured at all", "It makes the network faster", "It deletes the attacker's copy"],
                   "You can't stop someone capturing packets, but you can make them worthless."),
               mcq("What does a VPN do?", "Encrypts all your traffic between your device and a trusted server", ["Blocks adverts only", "Speeds up your broadband", "Stops your device needing a password"],
                   "That's why VPNs are recommended on public Wi-Fi.")]),
   dict(name="Other protections", bullets=["Don't send sensitive data over open Wi-Fi; use mobile data or a VPN.", "Log off, lock screens and shred printouts.",
        "Physical security: locked server rooms and cabinets.", "Access levels mean a stolen login only reaches part of the data."],
        challenge="List five things a company could do to reduce data interception and theft.",
        ill=("tiles", [("Encrypt", "g"), ("Lock screens", "g"), ("Shred printouts", "g"), ("Locked rooms", "g"), ("Access levels", "g"), ("Staff training", "g")], 3),
        fact="To protect against interception and theft, organisations...",
        tasks=[multi("Which of these reduce the risk of data interception and theft? Select all that apply.", ["Using HTTPS and WPA2 encryption", "Using a VPN on public Wi-Fi",
                     "Locking screens and logging off", "Shredding printouts with personal data", "Sharing one login for the whole office", "Keeping the server room door propped open"],
                     ["Using HTTPS and WPA2 encryption", "Using a VPN on public Wi-Fi", "Locking screens and logging off", "Shredding printouts with personal data"],
                     "The last two create exactly the weaknesses attackers look for.")]),
  ],
  final=dict(name="Final challenge: safe or risky?", floor_title="Final challenge: safe or risky?",
    intro="Eight habits from around the office. Tap the star and sort each one into safe or risky for data interception and theft.",
    ill=("icons", [("wap", "Public Wi-Fi"), ("lock", "Encryption"), ("disk", "Stolen data")]),
    tasks=[sort("Is each habit safe or risky?", ["Safe", "Risky"], [
      ["Banking on open café Wi-Fi with no VPN", "Risky"], ["Checking the padlock and HTTPS before logging in", "Safe"],
      ["Leaving a laptop unlocked at a desk", "Risky"], ["Shredding printouts containing customer details", "Safe"],
      ["Writing the Wi-Fi password on the office whiteboard", "Risky"], ["Using a VPN when working away from the office", "Safe"],
      ["Emailing a spreadsheet of personal data unencrypted", "Risky"], ["Keeping the server room locked", "Safe"]],
      "Most of the risky ones are about people, not technology.")]),
  models=[
   (1, "switch", "Where a sniffer sits", "Traffic for the whole network passes through here. Anything plugged into a port, or the switch itself if an attacker reaches it, can be made to copy what goes by."),
  ],
  info=[(0, "Wireshark", "Wireshark is a free packet sniffer used by network managers worldwide. The same tool in the wrong hands is an attacker's dream."),
        (1, "HTTPS everywhere", "Most websites now use HTTPS by default, which is why intercepting browsing is far less useful than it once was."),
        (2, "Evil twin", "A fake hotspot with the same name as a real one is called an evil twin. Phones may join it automatically."),
        (3, "Data protection law", "UK law requires organisations to protect personal data. Serious breaches can lead to very large fines."),
        (4, "Shoulder to shoulder", "Interception isn't always technical: reading a screen on a train, or a document on a printer, works too."),
        (5, "Encrypted devices", "Modern phones and laptops encrypt their storage, so a stolen device doesn't hand over its data.")],
  ws=dict(title="Data interception and theft", objectives=["understand the threat that data interception and theft poses", "understand how to identify and protect against data interception"],
    starter="You are working on a train and open your email over the free Wi-Fi. List everything that could go wrong, and what would prevent each one.", starter_lines=3,
    keyterms=["Data interception", "Encryption"], keyq="How is data captured in transit, and how can it be protected?",
    exam=[("Describe how data can be intercepted as it travels across a network.", 2, 2), ("Explain why encryption makes intercepted data useless to an attacker.", 3, 3),
          ("Describe two further measures that reduce the risk of data theft in an office.", 4, 4)],
    confidence=["What data interception and theft is", "How packet sniffing works", "Protecting data in transit"]))

L9 = dict(id="ns-l09", topic="1.4", lesson=9, title="Defence depot", img="NS_L09_DefenceDepot_360",
  description="The first four prevention methods: penetration testing, anti-malware, firewalls and user access levels.",
  kicker=f"{K14}  |  Lesson 9", scene_title="Defence depot", subtitle=SUB14,
  intro="Now for the defences. In the first half of the depot you'll meet penetration testing, anti-malware software, firewalls and user access levels, and learn which attacks each one stops.",
  keywords=["Penetration testing", "Anti-malware", "Firewall", "Access levels", "Policy", "Forensics"],
  stations=[
   dict(name="Penetration testing", bullets=["Evaluating the security of a system by safely trying to exploit its weaknesses.",
        "It's done with the owner's permission, and the findings are reported so they can be fixed.", "Testers act like attackers, including trying social engineering."],
        challenge="Write the definition of penetration testing in your own words.", ill=("icons", [("user", "Tester"), ("lock", "System"), ("form", "Report")]), fact="Penetration testing is...",
        tasks=[mcq("What is penetration testing?", "Attacking a system with the owner's permission to find its weaknesses", ["Attacking a rival company's website", "Installing anti-malware on every computer", "Encrypting the hard drives"],
                   "Permission is what separates it from a crime."),
               mcq("What makes penetration testing legal?", "The organisation has given permission for the tests", ["The tester works at night", "No data is ever accessed", "The tester uses their own laptop"],
                   "Without permission it's a crime, however good the intentions.")]),
   dict(name="Anti-malware software", bullets=["Scans files and programs and compares them against known malware.", "Watches for suspicious behaviour to catch new threats.",
        "Must be kept up to date, because new malware appears daily.", "Quarantines or removes anything it finds."],
        challenge="Why does anti-malware need updating so often?", ill=("icons", [("bug", "Malware"), ("lock", "Scanner"), ("disk", "Quarantine")]), fact="Anti-malware software...",
        tasks=[mcq("What does anti-malware software do?", "Detects, blocks and removes malicious software", ["Blocks traffic entering a network", "Sets who can see which files", "Tests the system's security with permission"],
                   "Don't confuse it with a firewall: that controls traffic."),
               mcq("Why must anti-malware be updated regularly?", "New malware appears constantly, so it needs new definitions", ["It runs out of storage", "The licence changes colour", "It forgets old malware"],
                   "Out-of-date protection is one of the ways people are a weak point.")]),
   dict(name="Firewalls", bullets=["A firewall controls the traffic entering and leaving a network.", "It checks packets against a set of rules and blocks anything not allowed.",
        "It can block suspicious ports, addresses and programs.", "Firewalls can be hardware, software, or both."],
        challenge="Explain the difference between a firewall and anti-malware software.", ill=("pair", "cloud", "router", "Internet", "Firewall", "Checked by rules", "Blocked or allowed"),
        fact="A firewall...",
        tasks=[mcq("What does a firewall do?", "Controls traffic entering and leaving a network using a set of rules", ["Scans files for viruses", "Encrypts the hard drive", "Backs up data automatically"],
                   "It is the gatekeeper between a network and the outside world."),
               mcq("Which attack does a firewall help most against?", "Unauthorised access attempts and suspicious traffic from outside", ["A member of staff losing a printout", "Someone watching you type a PIN", "A trojan already installed by a user"],
                   "Firewalls can't help with attacks that come from people inside.")]),
   dict(name="User access levels", bullets=["Each user only gets access to what they need for their role.", "Students, teachers and network managers have different rights.",
        "If an account is compromised, the damage is limited to that user's access."], challenge="Why shouldn't every teacher have network manager rights?",
        ill=("tiles", [("Student", "b"), ("Teacher", "p"), ("Office staff", "o"), ("Network manager", "r")], 2), fact="User access levels...",
        tasks=[mcq("What are user access levels for?", "Limiting each user to the data and settings they need", ["Blocking viruses", "Encrypting network traffic", "Testing the network's security"],
                   "This is sometimes called the principle of least privilege."),
               mcq("A student's account is stolen by an attacker. Why do access levels help?", "The attacker can only reach what a student can reach", ["The account deletes itself", "The attacker is logged out after a minute", "The network shuts down"],
                   "Damage is limited to that account's rights.")]),
   dict(name="Monitoring and policies", bullets=["Network forensics means watching network traffic to detect intrusions and collect evidence.",
        "An acceptable use policy is the set of rules a user signs up to before being allowed on the network.", "Logs record who did what and when."],
        challenge="Write three rules from your school's acceptable use policy.", ill=("icons", [("pc", "Monitoring"), ("form", "Policy"), ("user", "Users")]),
        fact="Network forensics is... An acceptable use policy is...",
        tasks=[match("Match each term to its definition.", [["Network forensics", "Watching network traffic to spot intrusions and gather evidence about what happened"],
                     ["Penetration testing", "Attacking a system with permission, to find its weaknesses before criminals do"], ["Acceptable use policy", "The rules a user signs up to before they are allowed on the network"]],
                     "Learn these three: they come up as definition questions.")]),
   dict(name="Which defence?", bullets=["Match the defence to the threat: anti-malware for malware, firewalls for unwanted traffic.",
        "Access levels limit the damage when an account is compromised.", "Penetration testing finds the gaps before attackers do."],
        challenge="Which defence would you buy first for a small business, and why?", ill=("tiles", [("Pen testing", "g"), ("Anti-malware", "b"), ("Firewall", "p"), ("Access levels", "o")], 2),
        fact="To choose a defence, you should...",
        tasks=[mcq("A company keeps getting infected by malware from downloads. Which helps most?", "Anti-malware software, kept up to date", ["A longer Wi-Fi password", "A bigger monitor", "A penetration test once every five years"],
                   "Match the defence to the threat."),
               mcq("A company wants to find weaknesses before criminals do. What should it arrange?", "A penetration test", ["A denial-of-service attack on a rival", "More printers", "A longer lunch break"],
                   "Testing with permission is the professional way to find holes.")]),
  ],
  final=dict(name="Final challenge: defence definitions", floor_title="Final challenge: defence definitions",
    intro="Match each prevention method to what it does. These definitions come up in every exam series.",
    ill=("tiles", [("Pen testing", "g"), ("Anti-malware", "b"), ("Firewall", "p"), ("Access levels", "o"), ("Forensics", "y"), ("Policy", "r")], 3),
    tasks=[match("Match each prevention method to its description.", [["Penetration testing", "Attacking a system with permission, to find weaknesses before criminals do"],
      ["Anti-malware software", "Detects, blocks and removes malicious software"], ["Firewall", "Controls traffic entering and leaving a network using rules"],
      ["User access levels", "Limits each user to the data and settings their role needs"], ["Network forensics", "Monitors and analyses traffic to detect intrusions and gather evidence"],
      ["Acceptable use policy", "The rules a user signs up to before using the network"]], "Learn these six, then lesson 10 adds passwords, encryption and physical security.")]),
  info=[(0, "Bug bounties", "Big companies pay 'bug bounties' to anyone who reports a security flaw responsibly. Some researchers earn a full-time living this way."),
        (1, "Red team, blue team", "In large organisations, a red team attacks and a blue team defends, so both sides practise against a real opponent."),
        (2, "Zero-day", "A 'zero-day' is a weakness nobody has patched yet. Anti-malware may miss it, which is why behaviour monitoring matters."),
        (3, "Two firewalls", "Many networks have a hardware firewall at the boundary and software firewalls on each computer, so one mistake isn't fatal."),
        (4, "Least privilege", "Giving everyone the minimum access they need is called the principle of least privilege. It's one of the oldest rules in security."),
        (5, "Logs matter", "After an incident, logs are what let investigators work out what happened, which accounts were used and what was taken.")],
  ws=dict(title="Identifying and preventing vulnerabilities (part 1)", objectives=["understand the ways people are a weak point in system security",
          "know how penetration testing, anti-malware, firewalls and user access levels help against cyberattack"],
    starter="Your school has £5,000 to spend on security. List what you would buy, in order, and say what each purchase protects against.", starter_lines=3,
    keyterms=["Penetration testing", "Firewall"], keyq="Which protections stop which attacks, and why does no single one stop everything?",
    exam=[("Describe what happens during a penetration test, and why organisations pay for one.", 3, 3), ("Explain how a firewall reduces the risk of unauthorised access.", 3, 3),
          ("Explain how user access levels limit the damage caused by a stolen password.", 3, 3)],
    confidence=["Penetration testing", "Anti-malware and firewalls", "User access levels and policies"]))

L10 = dict(id="ns-l10", topic="1.4", lesson=10, title="Defence depot 2", img="NS_L10_DefenceDepot2_360",
  description="Passwords, encryption and physical security, and choosing the right defence for each threat.",
  kicker=f"{K14}  |  Lesson 10", scene_title="Defence depot 2", subtitle=SUB14,
  intro="The second half of the depot: passwords, encryption and physical security. Then the real skill: choosing the right defence for each threat, and layering them so one failure isn't a disaster.",
  keywords=["Password", "Encryption", "Physical security", "Backups", "Two-factor", "Layers"],
  stations=[
   dict(name="Passwords", bullets=["Long passwords, ideally passphrases, with a mix of characters.", "Different password for every account, never shared or written down.",
        "Backed up by lockouts and two-factor authentication."], challenge="Describe a situation where a password alone isn't enough.",
        ill=("tiles", [("Long", "g"), ("Unique", "g"), ("Never shared", "g"), ("Two-factor", "g")], 2), fact="Passwords protect systems by...",
        tasks=[mcq("Which attack do strong passwords protect against most directly?", "Brute-force attacks", ["Denial of service", "Data interception on public Wi-Fi", "A flood of traffic from a botnet"],
                   "A long password takes impossibly long to guess."),
               mcq("Give an example of when a password alone isn't enough.", "When it has been phished or appears in a data breach", ["When the computer is switched off", "When the screen is too small", "When the password is 20 characters long"],
                   "That's why two-factor authentication matters.")]),
   dict(name="Encryption", bullets=["Scrambles data so it can't be understood without the key.", "Protects data in transit (HTTPS, WPA2, VPN) and at rest (encrypted drives).",
        "It doesn't stop data being stolen: it makes stolen data useless."], challenge="Give an example of when each type of encryption would be used.",
        ill=("compare", "In transit", ["HTTPS", "WPA2", "VPN"], "At rest", ["Encrypted laptop", "Encrypted USB stick"], "b", "g"), fact="Encryption protects...",
        tasks=[mcq("What does encryption protect against?", "Intercepted or stolen data being understood", ["Denial-of-service floods", "Malware being installed", "Weak passwords being guessed"],
                   "Encryption is about confidentiality, not access."),
               mcq("A laptop with encrypted storage is stolen. What is the result?", "The thief has the hardware, but can't read the data without the key", ["The data deletes itself instantly", "The laptop stops working forever", "The data is emailed back to the owner"],
                   "This is why organisations encrypt every mobile device.")]),
   dict(name="Physical security", bullets=["Locked doors, server cabinets and equipment cages.", "Keycards, visitor passes, CCTV and staffed reception desks.",
        "Locking screens, shredding printouts and secure disposal of old drives."], challenge="Survey your classroom: what physical security can you see?",
        ill=("icons", [("lock", "Locked doors"), ("server", "Server cabinet"), ("user", "Keycard")]), fact="Physical security means...",
        tasks=[mcq("Why does physical security matter for network security?", "Someone with physical access to a server can bypass many other protections", ["It makes the network faster", "It stops viruses spreading by email", "It encrypts the hard drives"],
                   "A locked door is one of the cheapest and most effective controls."),
               mcq("Which is an example of physical security?", "A locked server room with keycard access", ["A 16-character password", "Anti-malware software", "A firewall rule"],
                   "Physical security protects the hardware itself.")]),
   dict(name="Backups and updates", bullets=["Regular backups mean ransomware doesn't have to be paid.", "Keep at least one backup disconnected or off-site.",
        "Patching software closes the weaknesses worms and attackers use."], challenge="Explain why a backup stored on the same computer isn't much use.",
        ill=("flow", ["Backup daily", "Store off-site", "Test the restore"]), fact="Backups and updates help because...",
        tasks=[mcq("Why do backups defend against ransomware?", "The files can be restored instead of paying the ransom", ["They stop the malware installing", "They encrypt the attacker's computer", "They block the email"],
                   "Backups are recovery, not prevention, and they're vital."),
               mcq("Why should a backup be kept disconnected or off-site?", "Ransomware can encrypt any backup that is connected", ["It saves electricity", "Backups work faster when cold", "It makes the files smaller"],
                   "Connected backups get encrypted along with everything else.")]),
   dict(name="Match the defence", bullets=["Each threat has defences that work best against it.", "Most real protection comes from combining several.",
        "Your task: place each protection with the threat it stops."], challenge="Complete the matching task on your worksheet.",
        ill=("tiles", [("Ransomware → backups", "y"), ("Phishing → training", "o"), ("Brute force → lockouts", "b"), ("Interception → encryption", "g")], 2),
        fact="The best defence for each threat is...",
        tasks=[match("Match each threat to the defence that works best against it.", [["Ransomware", "Regular off-site backups"], ["Phishing", "Staff training and two-factor authentication"],
                     ["Brute-force attack", "Account lockouts and strong passwords"], ["Data interception", "Encryption, such as HTTPS and a VPN"],
                     ["SQL injection", "Input validation and parameterised queries"], ["Malware downloads", "Anti-malware software and updates"]],
                     "In the bonus Cyber defence game you'll have to make exactly these choices, on a budget.")]),
   dict(name="Layers of defence", bullets=["No single protection stops everything, and any one can fail.", "Layering means an attacker has to beat several defences in a row.",
        "Technology, people and physical measures all matter."], challenge="Describe three layers protecting a school's data, from the door to the database.",
        ill=("stack", [("People", "Training and policies", "o"), ("Network", "Firewall and monitoring", "b"), ("Accounts", "Passwords and access levels", "p"), ("Physical", "Locks and CCTV", "g")]),
        fact="Layered security means...",
        tasks=[mcq("Why do organisations layer their defences?", "If one protection fails, others still stand between the attacker and the data", ["It makes the network faster", "It is required to use Wi-Fi", "One strong protection is impossible"],
                   "This is often called defence in depth."),
               mcq("Which combination best protects against a stolen password?", "Two-factor authentication, access levels and monitoring", ["A bigger hard drive and a fast router", "Anti-malware alone", "A longer network cable"],
                   "Layers cover each other's weaknesses.")]),
  ],
  final=dict(name="Final challenge: build the defences", floor_title="Final challenge: build the defences",
    intro="Eight security measures are waiting to be installed. Tap the star and sort each one into the type of protection it is.",
    ill=("tiles", [("Technical", "b"), ("Physical", "g"), ("People", "o")], 3),
    tasks=[sort("Is each measure a technical, physical or people-based protection?", ["Technical", "Physical", "People"], [
      ["A firewall filtering incoming traffic", "Technical"], ["A locked server cabinet", "Physical"], ["Staff training on spotting phishing", "People"],
      ["Encrypting laptops' storage", "Technical"], ["Keycard access to the IT office", "Physical"], ["An acceptable use policy everyone signs", "People"],
      ["Automatic software updates", "Technical"], ["CCTV covering the server room door", "Physical"]],
      "A good security plan uses all three types, which is what the Cyber defence game asks you to balance.")]),
  info=[(0, "Change it only when needed", "Modern advice is to stop forcing regular password changes: it pushes people towards weak, predictable patterns. Change passwords when there's a reason."),
        (1, "Encryption by default", "Messaging apps like WhatsApp and Signal use end-to-end encryption, so even the company running the service can't read the messages."),
        (2, "The cleaner test", "Security teams ask: could someone dressed as a cleaner walk in and plug something into a server? Often the answer used to be yes."),
        (3, "Test your backups", "A backup that has never been restored isn't a backup. Organisations practise restoring, so they know it works before they need it."),
        (4, "Patch Tuesday", "Microsoft releases security patches on the second Tuesday of each month. Attackers study them to work out what to exploit on unpatched systems."),
        (5, "Cheapest first", "Many of the strongest protections, like updates, backups, training and locking doors, cost very little compared with the damage they prevent.")],
  ws=dict(title="Identifying and preventing vulnerabilities (part 2)", objectives=["know how passwords, encryption and physical security help against cyberattack",
          "be able to choose suitable protections for a given threat"],
    starter="A company has been hit by ransomware and lost a week of work. List the three changes you would insist on before it reopens.", starter_lines=3,
    keyterms=["Encryption", "Physical security"], keyq="How can we protect ourselves against hackers?",
    exam=[("Explain how encryption protects data stored on a stolen laptop.", 3, 3), ("Give two examples of physical security and state what each one prevents.", 4, 4),
          ("A company has lost data to ransomware. Recommend three measures it should introduce, and justify each one.", 6, 6)],
    rag=["The six forms of attack", "Malware types and their effects", "SQL injection", "Phishing and social engineering", "Brute-force attacks",
         "Denial-of-service attacks", "Data interception and theft", "Penetration testing, anti-malware, firewalls, access levels", "Passwords, encryption, physical security"],
    confidence=["Passwords and encryption", "Physical security", "Choosing the right defence for a threat"]))
