from kit import mcq, multi, sort, match, order

K23 = "2.3 Producing robust programs"
SUB23 = "OCR J277 Paper 2  |  Computational thinking, algorithms and programming"

L1 = dict(id="rp-lesson1", topic="2.3", lesson=1, title="Security desk", img="RP_L01_SecurityDesk",
  description="Check every sign-up at the security desk: learn the validation checks that stop bad data getting in.",
  kicker=f"{K23}  |  Lesson 1", scene_title="Security desk", subtitle=SUB23,
  intro="Nothing gets into the program without passing the security desk. Learn the validation checks programmers use to make sure input data is sensible before it's processed.",
  keywords=["Defensive design", "Validation", "Type check", "Range check", "Presence check", "Format check", "Length check"],
  stations=[
   dict(name="Defensive design", bullets=["Designing a program so it can't be broken by mistakes or deliberate misuse.", "Includes input validation, authentication, anticipating misuse and maintainable code.",
        "Assume users will do something unexpected."], challenge="List three things that could go wrong if a program trusted every input.", ill=("icons", [("user", "User"), ("form", "Input"), ("lock", "Checked")]),
        fact="Defensive design means...",
        tasks=[mcq("What is defensive design?", "Designing a program so it copes with mistakes and misuse without breaking", ["Adding a firewall", "Writing the program as fast as possible", "Designing the program's colours"],
                   "Defensive design plans for everything that could go wrong."),
               mcq("What is input validation?", "Checking data entered meets certain rules before it is processed", ["Checking the user's identity", "Encrypting the data", "Testing the finished program"],
                   "Validation checks that data is sensible, not that it is correct.")]),
   dict(name="Type check", bullets=["Checks the data is the correct data type, such as a whole number rather than text.", "Stops a program crashing when it tries to do maths with text."],
        challenge="Which inputs on a sign-up form need a type check?", ill=("code", ['year = input("Year of birth: ")', "if not year.isnumeric():", "    valid = False"], 28, [1]),
        fact="A type check makes sure...",
        tasks=[mcq("Which check would stop 'twelve' being entered as an age?", "Type check", ["Length check", "Presence check", "Range check"], "It isn't a number, so it's the wrong type."),
               mcq("What does isnumeric() check in the code?", "Whether the input contains only digits", ["Whether the input is empty", "Whether it's in the right range", "Whether it's 10 characters long"],
                   "It returns True only if every character is a digit.")]),
   dict(name="Range check", bullets=["Checks data falls within acceptable limits, such as 1 to 3.", "Anything outside the range is rejected."],
        challenge="Suggest a sensible range check for a month and for a percentage score.", ill=("code", ["choice = int(input(\"Choose 1-3: \"))", "if choice < 1 or choice > 3:", "    valid = False"], 28, [1]),
        fact="A range check makes sure...",
        tasks=[mcq("Which check would reject a month of 13?", "Range check", ["Type check", "Presence check", "Format check"], "Months must be from 1 to 12."),
               mcq("A menu accepts 1, 2 or 3. Which input should a range check reject?", "4", ["1", "2", "3"], "4 is outside the range 1 to 3.")]),
   dict(name="Presence check", bullets=["Checks that some data has been entered.", "Stops required fields, like a username, being left blank."],
        challenge="Which fields on a sign-up form must have a presence check?", ill=("code", ['name = input("Username: ")', 'if name == "":', "    valid = False"], 28, [1]),
        fact="A presence check makes sure...",
        tasks=[mcq("What does a presence check do?", "Checks that something has been entered", ["Checks the data type", "Checks the length", "Checks the user is present in the room"], "It rejects empty input."),
               mcq("Which input would fail a presence check?", "An empty input", ["0", "abc", "12/05/2010"], "0 and abc are still data; only empty input fails.")]),
   dict(name="Format and length checks", bullets=["A format check makes sure data matches a pattern, such as DD/MM/YYYY or a postcode.", "A length check makes sure data has the right number of characters, such as 11 digits for a mobile number."],
        challenge="Describe a format check and a length check for a UK postcode.", ill=("code", ['if date[2] != "/" or date[5] != "/":', "    valid = False", "if len(phone) != 11:", "    valid = False"], 26, [0, 2]),
        fact="A format check... A length check...",
        tasks=[mcq("Which check makes sure a date is written as DD/MM/YYYY?", "Format check", ["Range check", "Type check", "Presence check"], "It checks the pattern, such as slashes in the right places."),
               mcq("Which check makes sure a password is at least 8 characters?", "Length check", ["Format check", "Type check", "Range check"], "It counts the characters.")]),
   dict(name="Whitelists and blacklists", bullets=["A whitelist stores the only inputs a program should accept, e.g. A, B and C.", "A blacklist stores inputs a program should reject, e.g. illegal characters in file names.",
        "A string can be cast to a number after it has been checked."], challenge="Would you use a whitelist or a blacklist for a menu with options A, B and C? Why?",
        ill=("compare", "Whitelist", ["Only accept A, B, C"], "Blacklist", ["Reject / \\ : * ?"], "g", "r"), fact="A whitelist... A blacklist...",
        tasks=[mcq("What is a whitelist?", "A list of the only inputs that are allowed", ["A list of inputs to reject", "A list of users", "A list of errors"], "Anything not on the whitelist is rejected."),
               mcq("Which is the best use of a blacklist?", "Rejecting illegal characters in a file name", ["Accepting only A, B or C", "Checking a number is 1 to 3", "Checking a field isn't empty"],
                   "There are only a few illegal characters, so listing them is simpler.")]),
  ],
  final=dict(name="Final challenge: date checks", floor_title="Final challenge: validate the date",
    intro="A club membership form checks a date of birth in the format DD/MM/YYYY. Tap the star and sort each rule into the type of check it is.",
    ill=("icons", [("form", "Join today"), ("user", "New user"), ("lock", "Validated")]),
    tasks=[sort("Which type of check is each date rule?", ["Presence", "Length", "Format", "Type", "Range"], [
      ["The field has not been left blank", "Presence"], ["The date is exactly 10 characters long", "Length"], ["The date follows the pattern DD/MM/YYYY", "Format"],
      ["The day, month and year are all whole numbers", "Type"], ["The month is between 1 and 12", "Range"], ["The year is no earlier than 1920", "Range"],
      ["The day is at least 01", "Range"]], "Use these rules when you write your own date validation program.")]),
  info=[(0, "Valid isn't correct", "Validation checks data is sensible, not true. A birthday of 01/01/2000 passes every check even if it's wrong. Asking twice, called verification, helps catch that."),
        (1, "Leap years", "A year is a leap year if it divides by 4, except century years, which must divide by 400. So 2000 was a leap year, but 1900 wasn't."),
        (2, "Double checking", "Websites usually validate in your browser for speed, then again on the server, because a clever user can skip the browser's checks."),
        (3, "Postcodes", "UK postcodes follow patterns like LLN NLL or LLNN NLL, where L is a letter and N a number. A format check can test for this."),
        (4, "Why it matters", "Unvalidated input is one of the main ways attackers break into systems, for example with SQL injection, which you'll meet in topic 1.4."),
        (5, "Casting", "input() always gives a string. int() casts it to a whole number, but it will crash on 'abc', so check it's numeric first.")],
  ws=dict(title="Input validation", objectives=["know what is meant by defensive design when writing programs", "understand why input validation is necessary", "know a range of validation techniques used to write robust programs"],
    starter="A club membership form asks for a name, a date of birth and a mobile number. For each field, write down one check the program should make before it accepts the data.", starter_lines=3,
    keyterms=["Defensive design", "Anticipating misuse"], keyq="How can a programmer make sure a program copes with anything a user types?",
    exam=[("Describe what input validation is and why programmers use it.", 2, 2), ("A form asks for a UK mobile number. Describe two validation checks it should make, and say what each one catches.", 4, 4),
          ("Explain the difference between a range check and a type check, using an example of each.", 4, 4)],
    confidence=["What defensive design means", "Why input validation is necessary", "The five types of validation check"]))

L2 = dict(id="rp-lesson2", topic="2.3", lesson=2, title="Cyber defence HQ", img="RP_L02_CyberDefenceHQ",
  description="Defend a program against misuse, bots and weak passwords with authentication and defensive design.",
  kicker=f"{K23}  |  Lesson 2", scene_title="Cyber defence HQ", subtitle=SUB23,
  intro="Programs are under attack from careless users, clever attackers and automated bots. Find out how programmers anticipate misuse and use authentication to keep programs safe.",
  keywords=["Authentication", "Anticipating misuse", "CAPTCHA", "Bot", "Password", "Two-factor"],
  stations=[
   dict(name="Anticipating misuse", bullets=["Thinking ahead about how users might accidentally or deliberately misuse a program.", "E.g. typing text where a number is expected, or clicking a button many times.",
        "Plan for every eventuality."], challenge="List three ways a user might misuse a program that asks for their age.", ill=("icons", [("user", "User"), ("bug", "Misuse"), ("robot", "Bot")]),
        fact="Anticipating misuse means...",
        tasks=[mcq("What does anticipating misuse mean?", "Planning for the ways users might accidentally or deliberately misuse a program", ["Blocking all users", "Only testing with normal data", "Making the program run faster"],
                   "Programmers imagine what could go wrong and plan for it."),
               mcq("A user types their name into a box asking for a number. What should a robust program do?", "Reject it with a helpful message and ask again", ["Crash", "Accept it anyway", "Delete the user's account"],
                   "Robust programs handle bad input gracefully.")]),
   dict(name="When things go wrong", bullets=["Even with valid input, a program can crash: dividing by zero, a lost connection, a printer out of paper, or a full disk.",
        "Programmers use exception handling so the program copes instead of crashing."], challenge="Fill in the four problems shown on the wall.",
        ill=("tiles", [("Divide by zero", "r"), ("Connection lost", "r"), ("Printer out of paper", "r"), ("Disk full", "r")], 2), fact="Problems that could crash a running program include...",
        tasks=[multi("Which of these could crash a program even when the input is valid? Select all that apply.", ["Dividing by zero", "The network connection dropping", "The printer running out of paper",
                     "The storage being full", "Using descriptive variable names", "Adding comments"], ["Dividing by zero", "The network connection dropping", "The printer running out of paper", "The storage being full"],
                     "Descriptive names and comments help maintainability; they don't crash programs."),
               mcq("How can a program cope with a problem like a missing file?", "Exception handling: catching the error and responding sensibly", ["Ignoring it", "Using a longer variable name", "Removing all input"],
                   "The program can show a message instead of crashing.")]),
   dict(name="Authentication", bullets=["Checking a user is who they say they are before they can use a system.", "Usually a username and password.",
        "Strong passwords are long and mix upper and lower case, numbers and symbols."], challenge="Explain the difference between validation and authentication.", ill=("icons", [("user", "User"), ("form", "Login"), ("lock", "Access")]),
        fact="Authentication means...",
        tasks=[mcq("What is authentication?", "Checking a user's identity before they can use a system", ["Checking data is sensible", "Testing a program", "Encrypting a file"], "Validation checks data; authentication checks people."),
               mcq("Which is the strongest password?", "Tr0ub4dor&3!Pz", ["password", "123456", "olly2010"], "Long, with mixed case, numbers and symbols.")]),
   dict(name="Forgotten passwords and new users", bullets=["A reset link or code can be sent to a registered email address or phone.", "New users often confirm their email address before the account is activated.",
        "Two-factor authentication adds a code sent to your phone."], challenge="Why is a reset link sent to your email, not shown on screen?", ill=("flow", ["Forgot password", "Link sent to email", "Set new password"]),
        fact="If a user forgets their password...",
        tasks=[mcq("Why does a website email a link to reset your password?", "Only the real owner should be able to access that email account", ["Emails are faster than web pages", "It saves storage", "To show you adverts"],
                   "It proves you own the account before letting you change the password."),
               mcq("What is two-factor authentication?", "Using a second check, such as a code sent to your phone, as well as a password", ["Typing your password twice", "Having two usernames", "Logging in on two devices"],
                   "Even if someone steals your password, they'd also need your phone.")]),
   dict(name="Bots and CAPTCHA", bullets=["Bots are programs that fill in forms automatically, e.g. to make fake accounts or guess passwords.", "CAPTCHA tests like 'I'm not a robot' are easy for humans but hard for bots.",
        "Audio CAPTCHAs help users who can't see the images."], challenge="Why would an attacker want a program that fills in forms automatically? Suggest two ways a website can stop one.", ill=("pair", "robot", "user", "Bot", "Human", "Fails the test", "Passes the test"),
        fact="CAPTCHA is used to...",
        tasks=[mcq("What is a CAPTCHA used for?", "Stopping automated bots from using a form", ["Checking a date's format", "Speeding up a website", "Encrypting passwords"], "It tells humans and bots apart."),
               mcq("How are CAPTCHAs made accessible to people who can't see images?", "An audio version is offered", ["They are skipped completely", "The text is made smaller", "A second password is needed"],
                   "Accessibility options help everyone use the site.")]),
   dict(name="Validate a password", bullets=["It must be at least 10 characters long.", "It must contain a digit and a letter.", "It must not be one of the 100 most common passwords."],
        challenge="Write the first three lines of a password validation program.", ill=("code", ['pw = input("New password: ").strip()', "if len(pw) < 10: valid = False", "if not any(c.isdigit() for c in pw):", "    valid = False", "if pw.lower() in common: valid = False"], 22),
        fact="A password is accepted if...",
        tasks=[multi("Which passwords pass all three rules? Select all that apply.", ["three-red-kites-9", "Pa55word", "correct7horse", "sunshine", "12345678901", "b3"],
                     ["three-red-kites-9", "correct7horse"], "Pa55word and sunshine appear on common password lists, 12345678901 has no letter, and b3 is far too short."),
               mcq("Why does the program use strip() on the input first?", "It removes spaces typed by accident at the start or end", ["It encrypts the password", "It shortens the password", "It checks the length"],
                   "Cleaning up input before checking it is called sanitisation.")]),
  ],
  final=dict(name="Final challenge: defend the program", floor_title="Final challenge: defend the program",
    intro="Eight defences have been set up around the program. Tap the star and sort each one into validation, authentication or anticipating misuse.",
    ill=("tiles", [("Validation", "b"), ("Authentication", "p"), ("Anticipating misuse", "o")], 3),
    tasks=[sort("Is each defence validation, authentication or anticipating misuse?", ["Validation", "Authentication", "Misuse"], [
      ["A username and password login", "Authentication"], ["A code sent to your phone", "Authentication"], ["Checking an age is between 11 and 19", "Validation"],
      ["Checking an email contains an @", "Validation"], ["Not crashing when the printer runs out of paper", "Misuse"], ["Handling a user dividing by zero", "Misuse"],
      ["Checking a field isn't left empty", "Validation"], ["Confirming a new account from an email link", "Authentication"]],
      "Validation checks data, authentication checks people, and anticipating misuse plans for what could go wrong.")]),
  info=[(0, "Most common password", "Lists of leaked passwords are still topped by '123456'. Attackers try these first, which is why systems should reject common passwords."),
        (1, "Try and except", "In Python, try and except let a program catch an error, like a missing file, and show a message instead of crashing."),
        (2, "Brute force maths", "An 8-letter password using only lowercase letters has about 200 billion combinations. A computer can try that many surprisingly quickly."),
        (3, "Password managers", "A password manager stores a different strong password for every site, so you only need to remember one master password."),
        (4, "Invisible checks", "Newer bot detection works mostly in the background, judging whether a visitor is human from how they move and click, so most people never see a puzzle."),
        (5, "Sanitising input", "Sanitisation cleans input before it's checked, such as trimming spaces or converting to lower case, so the same data is always treated the same way.")],
  ws=dict(title="Defensive design considerations", objectives=["know what is meant by defensive design considerations", "know a range of problems that can occur when a program is running",
          "understand some authentication techniques programmers use"],
    starter="Think of three ways someone could get into a school computer account without ever breaking the software. How could the school stop each one?", starter_lines=3,
    keyterms=["Authentication", "Input validation"], keyq="How can a program defend itself against careless users and deliberate attackers?",
    exam=[("Describe what is meant by authentication, using an example.", 2, 2), ("Describe two techniques a website can use to stop automated programs creating accounts.", 4, 4),
          ("A program divides one number by another entered by the user. Explain how the programmer should handle a division by zero.", 3, 3)],
    confidence=["What defensive design considerations are", "Problems that can occur when a program runs", "Authentication techniques"]))

L5 = dict(id="rp-lesson5", topic="2.3", lesson=5, title="Test lab", img="RP_L05_TestLab",
  description="Choose normal, boundary, invalid and erroneous test data, and build a test table that really tests a program.",
  kicker=f"{K23}  |  Lesson 5", scene_title="Test lab", subtitle=SUB23,
  intro="Just because a program works for one input doesn't mean it works for all of them. In the test lab you'll learn the four types of test data and build a proper test plan.",
  keywords=["Test data", "Normal", "Boundary", "Invalid", "Erroneous", "Test plan"],
  stations=[
   dict(name="Why test with different data?", bullets=["A program that works for one input may still fail for others.", "A test plan lists each test, the data used, the type of test and the expected result.",
        "Good testing covers valid, invalid and erroneous inputs."], challenge="What makes a good testing strategy?", ill=("table", ["Test", "Data", "Type", "Expected"], [["1", "14", "Normal", "Accepted"], ["2", "11", "Boundary", "Accepted"], ["3", "24", "Invalid", "Rejected"]]),
        fact="A test plan should include...",
        tasks=[mcq("Why should a program be tested with lots of different data?", "It may work for some inputs but fail for others", ["To make it run faster", "Because one test is illegal", "To use up memory"], "Testing only one value proves very little."),
               mcq("What does a test plan include for each test?", "The test data, the type of test and the expected result", ["The programmer's password", "The colour of the screen", "The number of lines of code"], "You then compare the actual result with the expected one.")]),
   dict(name="Normal data", bullets=["Typical, valid data that the program should accept.", "For a school-age field from 11 to 19: 14."], challenge="Give two more examples of normal data for an age from 11 to 19.",
        ill=("big", "14", "Normal: comfortably inside the range"), fact="Normal data is...",
        tasks=[mcq("Which is normal data for an age from 11 to 19?", "14", ["11", "24", "fourteen"], "14 is a typical, valid value."),
               mcq("What should happen when normal data is entered?", "It is accepted and processed", ["It is rejected", "The program crashes", "It asks again"], "Normal data should always work.")]),
   dict(name="Boundary data", bullets=["Valid data on the very edge of the accepted range.", "For an age from 11 to 19: 11 and 19.", "Boundaries are where programmers most often make mistakes, like < instead of <=."],
        challenge="What are the boundary values for a canteen menu that accepts 1 to 4?", ill=("tiles", [("11", "y"), ("19", "y")], 2), fact="Boundary data is...",
        tasks=[mcq("Which is boundary data for an age from 11 to 19?", "19", ["14", "24", "nineteen"], "19 is valid, but right on the edge."),
               mcq("Why is boundary data so important to test?", "Mistakes like using < instead of <= only show up at the edges", ["It's the most common data", "It makes the program faster", "It can't be entered by users"],
                   "Off-by-one errors are some of the most common bugs.")]),
   dict(name="Invalid data", bullets=["Data of the correct type, but outside the accepted range.", "For an age from 11 to 19: 24 or -3.", "The program should reject it."],
        challenge="Give an example of invalid data for a month number.", ill=("big", "24", "Invalid: right type, outside the range"), fact="Invalid data is...",
        tasks=[mcq("Which is invalid data for an age from 11 to 19?", "24", ["14", "19", "fourteen"], "It's a number, but outside the range."),
               mcq("What should a robust program do with invalid data?", "Reject it and ask again", ["Accept it", "Crash", "Change it to 100 without telling the user"], "Rejecting it with a message is the robust response.")]),
   dict(name="Erroneous data", bullets=["Data of the wrong type that should be rejected.", "For an age from 11 to 19: 'fourteen'.", "Without a type check, erroneous data can crash a program."],
        challenge="What would happen to a program that doubles a number if the user typed 'five'?", ill=("big", "\"fourteen\"", "Erroneous: the wrong data type"), fact="Erroneous data is...",
        tasks=[mcq("Which is erroneous data for an age from 11 to 19?", "fourteen", ["14", "11", "24"], "Text is the wrong type for an age."),
               mcq("What's the difference between invalid and erroneous data?", "Invalid is the right type but out of range; erroneous is the wrong type", ["They mean the same thing", "Erroneous is always a number", "Invalid data is always accepted"],
                   "24 is invalid; fourteen is erroneous.")]),
   dict(name="Test a comment box", bullets=["A comment box allows up to 200 characters.", "Test just under, exactly at, and just over the limit.", "The program should show how many characters are left, or how many are over."],
        challenge="Fill in five tests for the comment box on your worksheet.", ill=("table", ["Characters", "Type", "Expected"], [["120", "Normal", "Accepted"], ["200", "Boundary", "Accepted"], ["201", "Invalid", "Rejected, -1"]]),
        fact="To test the comment box, I would...",
        tasks=[mcq("Which is boundary data for a 200-character limit?", "200 characters", ["120 characters", "250 characters", "The word 'hello'"], "200 is the very edge of what's allowed."),
               mcq("A canteen menu accepts 1 to 4. What should happen if 5 is entered?", "It is rejected and the user is asked again", ["Option 4 runs", "The program ends", "It is accepted"], "5 is invalid data.")]),
  ],
  final=dict(name="Final challenge: sort the test data", floor_title="Final challenge: sort the test data",
    intro="A form accepts a school-age value from 11 to 19. Tap the star and sort each piece of test data into normal, boundary, invalid or erroneous.",
    ill=("tiles", [("Normal", "g"), ("Boundary", "y"), ("Invalid", "o"), ("Erroneous", "r")], 4),
    tasks=[sort("Which type of test data is each input for a score from 0 to 100?", ["Normal", "Boundary", "Invalid", "Erroneous"], [
      ["14", "Normal"], ["16", "Normal"], ["11", "Boundary"], ["19", "Boundary"], ["24", "Invalid"], ["-3", "Invalid"], ["fourteen", "Erroneous"], ["N/A", "Erroneous"]],
      "Use these categories for the task on your worksheet.")]),
  info=[(0, "Off by one", "Using < instead of <= is so common it has a name: an off-by-one error. Boundary tests are designed to catch it."),
        (1, "Fuzz testing", "Fuzz testing sends thousands of random inputs to a program automatically, to find ones that crash it."),
        (2, "Where limits come from", "Character limits are often inherited from older systems. Text messages were capped at 160 characters because of the space left in the mobile signalling channel."),
        (3, "Test first", "Some programmers write their tests before the code. This is called test-driven development."),
        (4, "Expected vs actual", "A test only passes if the actual result matches the expected result. Writing the expected result first stops you fooling yourself."),
        (5, "Paid to break things", "Penetration testers are paid to try to break into systems, finding weaknesses before criminals do.")],
  ws=dict(title="Suitable test data", objectives=["understand that just because a program works doesn't mean it works for all inputs", "understand that test data should include normal, boundary, invalid and erroneous data"],
    starter="A program asks for a school year group from 7 to 11. Suggest five pieces of test data for it, and explain what each one is testing.", starter_lines=3,
    keyterms=["Testing", "Iterative testing"], keyq="What makes a good testing strategy?",
    extra=dict(title="Task: test the comment box", instr="Fill in five tests for a comment box with a 200-character limit.", head=["Test", "Characters input", "Type of test", "Reason for the test"],
               rows=[["1", "", "", ""], ["2", "", "", ""], ["3", "", "", ""], ["4", "", "", ""], ["5", "", "", ""]]),
    exam=[("A booking form accepts a number of tickets from 1 to 6. Give four pieces of test data, name the type of each, and state why the test is needed.", 8, 8)],
    confidence=["Why a range of test data is needed", "Normal, boundary, invalid and erroneous data", "Writing a test plan"]))

L6 = dict(id="rp-lesson6", topic="2.3", lesson=6, title="Revision HQ 2.3", img="RP_L06_RevisionHQ23",
  description="Recap lessons 1 to 5 of Producing robust programs and find out what to revise before your test.",
  kicker=f"{K23}  |  Lesson 6", scene_title="Revision HQ 2.3", subtitle="Get ready for your end-of-topic test on lessons 1 to 5",
  intro="Each station sums up one lesson. Answer its quiz, and your score screen will show which lessons are secure and which need work. Then plan a 12-mark answer on robust programs.",
  keywords=["Validation", "Authentication", "Maintainability", "Testing", "Test data", "Robust"], revision=True,
  stations=[
   dict(name="Lesson 1: Input validation", bullets=["Validation checks input is sensible before it's processed.", "Type, range, presence, format and length checks.", "Whitelists accept; blacklists reject."],
        challenge="Explain what is meant by a length check and give an example.", ill=("tiles", [("Type", "b"), ("Range", "g"), ("Presence", "p"), ("Format", "o"), ("Length", "k")], 3),
        tasks=[mcq("Which check would reject an empty username?", "Presence check", ["Range check", "Type check", "Format check"], "Nothing has been entered."),
               mcq("Which check ensures a score is between 0 and 100?", "Range check", ["Length check", "Presence check", "Format check"], "It checks the limits."),
               mcq("What does input validation mean?", "Checking input meets rules before it's processed", ["Checking who the user is", "Testing the program", "Encrypting input"], "Validation is about data, not people.")]),
   dict(name="Lesson 2: Defensive design", bullets=["Anticipating misuse: planning for mistakes and deliberate misuse.", "Authentication: checking identity with passwords, 2FA and CAPTCHA.", "Exception handling stops crashes."],
        challenge="Describe two authentication techniques.", ill=("icons", [("lock", "Login"), ("phone", "2FA code"), ("robot", "CAPTCHA")]),
        tasks=[mcq("What is authentication?", "Checking a user is who they say they are", ["Checking data is valid", "Adding comments", "Testing with boundary data"], "It verifies identity."),
               mcq("What is a CAPTCHA for?", "Stopping bots using a form", ["Checking passwords are strong", "Speeding up forms", "Validating dates"], "It tells humans and bots apart."),
               mcq("Which could crash a program even with valid input?", "Dividing by zero", ["A descriptive variable name", "A comment", "Indentation"], "Exception handling can deal with it.")]),
   dict(name="Lesson 3: Maintainability", bullets=["Descriptive names, comments, indentation and white space.", "Sub-programs split code into reusable parts.", "Makes code easier to debug, update and maintain."],
        challenge="Describe three ways a programmer can make their code easier to maintain.", ill=("code", ["# Returns the total score", "def total_score(scores):", "    total = 0", "    for s in scores:", "        total = total + s", "    return total"], 24),
        tasks=[mcq("Which makes code easier to maintain?", "Descriptive variable names", ["Single-letter names", "No indentation", "No comments"], "Names should say what data is stored."),
               mcq("Why use sub-programs?", "Code is reused and each part can be tested separately", ["They make code run faster", "They remove the need for testing", "They validate input automatically"], "Write once, use many times."),
               mcq("What happens to comments when code runs?", "They are ignored", ["They are printed", "They slow the code down", "They cause errors"], "They're for people, not the computer.")]),
   dict(name="Lesson 4: Testing and errors", bullets=["Iterative testing: during development. Final testing: at the end, before release.", "Syntax errors break the language's rules, so the code won't run.", "Logic errors run but give the wrong result."],
        challenge="Explain what is meant by the term iterative testing.", ill=("compare", "Syntax error", ["Won't run", 'prnt("Hi")'], "Logic error", ["Runs, wrong result", "average = total / 0"], "r", "o"),
        tasks=[mcq("When does iterative testing happen?", "While the program is being developed", ["Only after release", "Before any code is written", "Only once"], "Each part is tested as it's written."),
               mcq("A program runs but gives the wrong answer. What type of error is this?", "Logic error", ["Syntax error", "Validation error", "Hardware error"], "The code follows the rules but the logic is wrong."),
               mcq("Which is a syntax error?", "A missing colon at the end of an if statement", ["Using + instead of -", "Dividing by the wrong variable", "A loop that runs one time too many"], "The translator can't understand the line.")]),
   dict(name="Lesson 5: Test data", bullets=["Normal: typical valid data.", "Boundary: valid data on the edge of the range.", "Invalid: right type, out of range. Erroneous: wrong type."],
        challenge="Suggest test data for an order form accepting quantities 1 to 10.", ill=("tiles", [("5: normal", "g"), ("1, 10: boundary", "y"), ("11: invalid", "o"), ("'ten': erroneous", "r")], 2),
        tasks=[mcq("A form accepts 1 to 10. Which is boundary data?", "10", ["5", "11", "ten"], "10 is valid but on the edge."),
               mcq("A form accepts 1 to 10. Which is erroneous data?", "ten", ["5", "10", "11"], "It's text, the wrong type."),
               mcq("A form accepts 1 to 10. Which is invalid data?", "11", ["1", "5", "ten"], "Right type, outside the range.")]),
   dict(name="Plan a 12-mark answer", bullets=["What does it mean to produce a robust program?", "Cover validation, authentication, anticipating misuse, maintainability and testing.",
        "For each point, explain why it makes the program more robust."], challenge="Plan the points you would include in a long answer about producing robust programs.",
        ill=("flow", ["Validation", "Authentication", "Misuse", "Maintainability", "Testing"]),
        tasks=[multi("Which points belong in a 12-mark answer on producing robust programs? Select all that apply.", ["Input validation, with examples of checks", "Authentication of users",
                     "Planning for misuse and runtime errors", "Maintainable code with comments and sub-programs", "Testing with normal, boundary, invalid and erroneous data", "The colour scheme of the program"],
                     ["Input validation, with examples of checks", "Authentication of users", "Planning for misuse and runtime errors", "Maintainable code with comments and sub-programs", "Testing with normal, boundary, invalid and erroneous data"],
                     "Everything except the colour scheme contributes to robustness."),
               mcq("What makes a 12-mark answer stand out?", "Explaining why each technique makes the program robust, with examples", ["Listing as many keywords as possible", "Writing in bullet points only", "Repeating the question"],
                   "Depth and examples earn the top marks.")]),
  ],
  final=dict(name="Final challenge: key terms", floor_title="Final challenge: key terms",
    intro="Match each key term from topic 2.3 to its meaning. These are the terms from your key terminology sheet.",
    ill=("tiles", [("Validation", "b"), ("Authentication", "p"), ("Maintainability", "g"), ("Iterative", "o"), ("Syntax", "r"), ("Boundary", "y")], 3),
    tasks=[match("Match each key term to its meaning.", [["Input validation", "Checking data meets rules before it's processed"], ["Authentication", "Verifying a user's identity before they can use a system"],
      ["Maintainability", "Techniques that make code easier to debug, update and maintain"], ["Iterative testing", "Testing during development, module by module"],
      ["Syntax error", "Breaking the rules of the language, so the code won't run"], ["Boundary data", "Valid data on the edge of the accepted range"]],
      "Check your results table to see which lessons to revise first.")]),
  info=[(0, "Revision tip", "Explain each topic out loud to someone else. If you can teach it, you know it."),
        (1, "Common mix-up", "Validation checks data; authentication checks people. Examiners love this difference."),
        (2, "Program practice", "Finish your outstanding programs: date of birth validation, the password strength checker, the comment box counter and the menu whitelist."),
        (3, "Error spotting", "In exam code, read each line slowly. Look for misspelt keywords (syntax) and wrong operators or variables (logic)."),
        (4, "Super challenge", "Try converting a decimal to a fraction: 0.75 is 75/100, then divide both by their greatest common factor (25) to get 3/4."),
        (5, "Robust means...", "A robust program keeps working correctly whatever users throw at it: that's the thread that links every lesson in this topic.")],
  ws=dict(title="Revision HQ 2.3: complete outstanding programs", objectives=["understand how robust programs are made", "know which lessons I'm secure on and which to revise"],
    starter="A school is about to publish an app written by students. List everything you would check before it goes live.", starter_lines=5, keyterms=["Logical error", "Test data"],
    keyq="What makes a robust program?",
    checklist=["Security desk worksheet (L1): date of birth validation", "Cyber defence HQ worksheet (L2): the password strength checker",
               "Code clinic worksheet (L3): rewriting Exhibit A using good practice", "Bug hunt lab worksheet (L4): every error in the total cost program",
               "Test lab worksheet (L5): the comment box test plan"],
    exam=[("A program will be used by hundreds of students. Explain the techniques a programmer should use to make it robust.", 8, 9)],
    confidence=["Validation and defensive design", "Maintainability", "Testing and test data"]))
