from kit import mcq, multi, sort, match, order

K12 = "1.2 Memory and storage"
SUB12 = "OCR J277 Paper 1  |  Computer systems"
def convert(q, frm, to, value, fb=""): return dict(t="convert", q=q, **{"from": frm}, to=to, value=value, fb=fb)

L1 = dict(id="ms-l01", topic="1.2", lesson=1, title="Memory bay", img="MS_L01_MemoryBay_360",
  description="Primary storage up close: what RAM and ROM do, and why one forgets everything when you switch off.",
  kicker=f"{K12}  |  Lesson 1", scene_title="Memory bay", subtitle=SUB12,
  intro="The CPU can only work with data that's in primary storage. Find out what RAM and ROM are for, which one forgets everything at power off, and why your computer needs both.",
  keywords=["Primary storage", "RAM", "ROM", "Volatile", "Non-volatile", "BIOS"],
  stations=[
   dict(name="Why primary storage?", bullets=["Primary storage is memory the CPU can access directly.", "Secondary storage is far too slow for the CPU to work from.",
        "Programs and data currently in use are copied into primary storage first."], challenge="Why can't the CPU just work straight from the hard drive?",
        ill=("icons", [("cpu", "CPU"), ("ram", "Primary storage"), ("disk", "Secondary storage")]), fact="Primary storage is needed because...",
        tasks=[mcq("What is primary storage?", "Memory the CPU can access directly, holding data and instructions in use", ["Long-term storage for files you aren't using", "The cloud", "A backup drive"],
                   "RAM, ROM, cache and registers are all primary storage."),
               mcq("Why are programs copied into RAM before they run?", "RAM is much faster than secondary storage, so the CPU doesn't have to wait", ["RAM is bigger than a hard drive", "RAM keeps data when the power is off", "Secondary storage can't hold programs"],
                   "Speed is the whole reason primary storage exists.")]),
   dict(name="RAM", bullets=["Random Access Memory: read and write, and volatile.", "Holds the operating system, open applications and the data in use.",
        "Volatile means its contents are lost when the power is switched off."], challenge="List three things stored in RAM right now on the computer in front of you.",
        ill=("icons", [("ram", "RAM")]), fact="RAM is...",
        tasks=[mcq("What does volatile mean?", "The contents are lost when the power is switched off", ["The contents can't be changed", "It stores data permanently", "It can explode if it gets hot"],
                   "That's why unsaved work disappears in a power cut."),
               mcq("Which is stored in RAM while a computer is running?", "The operating system and the programs currently open", ["Only the BIOS", "Files you haven't opened for years", "Nothing at all"],
                   "Anything being used is copied into RAM.")]),
   dict(name="ROM", bullets=["Read Only Memory: read-only, and non-volatile.", "Holds the boot program, often called the BIOS.",
        "It tells the computer how to start up and load the operating system from secondary storage."], challenge="Why must the start-up instructions be in ROM rather than RAM?",
        ill=("icons", [("cpu", "ROM chip")]), fact="ROM is...",
        tasks=[mcq("What is stored in ROM?", "The start-up instructions, often called the BIOS", ["Your documents", "The programs you have open", "Temporary internet files"],
                   "ROM holds the small program that gets everything else started."),
               mcq("Why is ROM used for the boot program?", "It is non-volatile, so the instructions are still there when the power comes on", ["It is faster than cache", "It can be written to easily", "It is bigger than RAM"],
                   "If it were in RAM it would be empty at switch-on.")]),
   dict(name="RAM vs ROM", bullets=["RAM: read and write, volatile, large, holds what's in use.", "ROM: read-only, non-volatile, small, holds start-up instructions.",
        "Both are primary storage, and both are on the motherboard."], challenge="Complete the RAM and ROM comparison table on your worksheet.",
        ill=("table", ["", "RAM", "ROM"], [["Volatile?", "Yes", "No"], ["Read/write?", "Read and write", "Read only"], ["Holds", "Programs in use", "Boot program"]]),
        fact="The differences between RAM and ROM are...",
        tasks=[sort("Does each statement describe RAM or ROM?", ["RAM", "ROM"], [["Volatile: loses its contents at power off", "RAM"], ["Non-volatile", "ROM"],
                    ["Can be read from and written to", "RAM"], ["Can normally only be read from", "ROM"], ["Holds the operating system while the computer runs", "RAM"],
                    ["Holds the BIOS or boot program", "ROM"]], "Both are primary storage, but they do very different jobs.")]),
   dict(name="The boot sequence", bullets=["Power on: the CPU runs the instructions in ROM.", "The BIOS checks the hardware, then looks for the operating system.",
        "The operating system is loaded from secondary storage into RAM, and takes over."], challenge="Put the boot steps in order on your worksheet.",
        ill=("flow", ["Power on", "ROM: BIOS runs", "Hardware checked", "OS loaded into RAM"]), fact="When a computer starts up...",
        tasks=[order("Put the start-up steps in order.", ["The computer is switched on", "The CPU runs the boot program stored in ROM", "The BIOS checks the hardware is working",
                     "The operating system is copied from secondary storage into RAM", "The operating system takes control"], "This is why both types of primary storage are needed.")]),
   dict(name="More RAM, faster computer?", bullets=["If RAM fills up, the computer has to use slower secondary storage instead.", "More RAM means more programs and data can be held at once.",
        "Beyond a point, adding RAM makes little difference: the CPU or storage becomes the limit."], challenge="Why does adding RAM usually make a slow computer feel faster?",
        ill=("compare", "Not enough RAM", ["Constant swapping", "Everything feels slow"], "Plenty of RAM", ["Programs stay in memory", "Fast switching"], "r", "g"),
        fact="Adding more RAM helps because...",
        tasks=[mcq("Why does a computer slow down when RAM is full?", "It has to use much slower secondary storage as extra memory", ["The CPU switches itself off", "ROM takes over", "The monitor refreshes less often"],
                   "That's virtual memory, which is the next lesson."),
               mcq("A computer has plenty of free RAM but still feels slow. What does adding more RAM do?", "Very little: the bottleneck is somewhere else", ["Doubles the clock speed", "Makes the hard drive bigger", "Removes all malware"],
                   "More RAM only helps when RAM is the limit.")]),
  ],
  final=dict(name="Final challenge: primary storage", floor_title="Final challenge: primary storage",
    intro="Eight statements about memory. Tap the star and sort each one into RAM, ROM or both.",
    ill=("icons", [("ram", "RAM"), ("cpu", "ROM")]),
    tasks=[sort("Does each statement describe RAM, ROM, or both?", ["RAM", "ROM", "Both"], [
      ["Loses its contents when the power goes off", "RAM"], ["Holds the BIOS", "ROM"], ["Is a type of primary storage", "Both"],
      ["Can be written to by the operating system", "RAM"], ["Keeps its contents with no power", "ROM"], ["Is found on the motherboard", "Both"],
      ["Holds the programs you currently have open", "RAM"], ["Is read-only in normal use", "ROM"]],
      "Copy any you got wrong onto your worksheet comparison table.")]),
  info=[(0, "Core memory", "Early computers used 'core memory': tiny magnetic rings threaded on wires by hand. A few kilobytes filled a cabinet."),
        (1, "How fast?", "RAM can be read in tens of nanoseconds. A hard disk takes milliseconds, which is around a hundred thousand times longer."),
        (2, "Flashable ROM", "Modern boot ROM is usually flash memory, so it can be updated. That's what a 'BIOS update' or 'firmware update' does."),
        (3, "Why 'random access'?", "Any location in RAM can be reached just as quickly as any other. Tape, by contrast, has to be wound to the right place."),
        (4, "RAM in phones", "Phones have RAM too, usually 4 GB to 12 GB. It's why a phone with more RAM can keep more apps open in the background."),
        (5, "Power cuts", "Some servers keep a battery-backed cache, so data in memory isn't lost if the power fails before it's written to disk.")],
  ws=dict(title="RAM and ROM", objectives=["understand the need for primary storage", "know the difference between RAM and ROM", "know the purpose of RAM and ROM"],
    starter="A computer loses power mid-lesson. Which of your work survives, and which does not? Explain why.", starter_lines=3, keyterms=["RAM", "ROM"], keyq="What are the differences between RAM and ROM?",
    extra=dict(title="Task: compare RAM and ROM", instr="Complete the table using full sentences.", head=["", "RAM", "ROM"],
               rows=[["Full name", "", ""], ["Purpose", "", ""], ["Volatile or non-volatile", "", ""], ["Read or read/write", "", ""]]),
    exam=[("State what is meant by the term volatile.", 1, 1), ("Describe the purpose of ROM in a computer system.", 2, 2), ("Explain why a computer needs primary storage.", 3, 3)],
    confidence=["The need for primary storage", "The purpose of RAM", "The purpose of ROM"]))

L2 = dict(id="ms-l02", topic="1.2", lesson=2, title="Swap space", img="MS_L02_SwapSpace_360",
  description="What happens when RAM runs out: paging, virtual memory and why the computer grinds to a halt.",
  kicker=f"{K12}  |  Lesson 2", scene_title="Swap space", subtitle=SUB12,
  intro="Open too many programs and RAM fills up. Rather than refusing to work, the computer borrows space from secondary storage. Find out how virtual memory works, and why it's slow.",
  keywords=["Virtual memory", "Paging", "Swap", "RAM full", "Secondary storage", "Thrashing"],
  stations=[
   dict(name="When RAM runs out", bullets=["Every open program needs space in RAM.", "When RAM is full, something has to move out to make room.",
        "Without virtual memory, the computer would refuse to open anything else."], challenge="What happens if you open a graphics app when RAM is already full?",
        ill=("compare", "RAM", ["Word processor", "Browser", "FULL"], "Hard disk", ["Free space", "Can be borrowed"], "r", "b"), fact="When RAM is full...",
        tasks=[mcq("What happens when RAM becomes full?", "Data that isn't being used right now is moved to secondary storage to free up space", ["The computer switches off", "The CPU slows its clock", "Files are deleted permanently"],
                   "That borrowed space is called virtual memory."),
               mcq("Which is most likely to fill RAM?", "Having many large programs open at once", ["Having a large hard drive", "Having a fast CPU", "Having a big monitor"],
                   "Each program needs its own space in memory.")]),
   dict(name="What is virtual memory?", bullets=["A section of secondary storage used as if it were extra RAM.", "Data not currently needed is moved there, freeing RAM for what is needed.",
        "The CPU can only work with data in RAM, so anything needed must be moved back first."], challenge="Write a definition of virtual memory.",
        ill=("flow", ["RAM full", "Move idle data to disk", "Free space in RAM", "New program loads"]), fact="Virtual memory is...",
        tasks=[mcq("What is virtual memory?", "Space on secondary storage used as extra RAM when RAM is full", ["Memory that only exists in the cloud", "A faster type of RAM", "The memory used by virtual reality"],
                   "It's real storage space, used as if it were memory."),
               mcq("Can the CPU work directly on data held in virtual memory?", "No: it must be copied back into RAM first", ["Yes, just as quickly as RAM", "Yes, but only for small files", "Only when the computer is idle"],
                   "That copying back and forth is what costs time.")]),
   dict(name="Swapping", bullets=["Data moves out of RAM to disk, and back again when needed: this is swapping, or paging.",
        "If the CPU needs something that isn't in RAM, something else must move out to make room.", "Every swap takes time, because secondary storage is slow."],
        challenge="Explain what happens when a program in virtual memory is needed again.", ill=("flow", ["CPU needs page", "Not in RAM", "Swap something out", "Load page in"]),
        fact="Swapping means...",
        tasks=[order("Put the steps in order for when the CPU needs data that is in virtual memory.", ["The CPU asks for data that isn't in RAM", "Something not currently needed is moved from RAM to the disk",
                     "The data is copied from the disk into the free space in RAM", "The CPU can now use the data"], "Each of these steps involves slow disk access.")]),
   dict(name="Why it's slow", bullets=["Secondary storage is thousands of times slower than RAM.", "Heavy swapping is sometimes called disk thrashing: the computer spends more time swapping than working.",
        "You notice it as constant disk activity and everything feeling sluggish."], challenge="Why does a computer relying on virtual memory feel so slow?",
        ill=("compare", "RAM", ["Nanoseconds", "Fast"], "Disk", ["Milliseconds", "Thousands of times slower"], "g", "r"), fact="Virtual memory is slow because...",
        tasks=[mcq("Why is virtual memory slower than RAM?", "Secondary storage takes far longer to read and write than RAM", ["It uses a different power supply", "It is stored in the cloud", "The CPU ignores it"],
                   "Even a fast SSD is much slower than RAM."),
               mcq("What is disk thrashing?", "The computer spending most of its time swapping data instead of doing useful work", ["A hard disk being physically damaged", "Deleting temporary files", "Defragmenting the disk"],
                   "It's the point where virtual memory stops helping.")]),
   dict(name="Avoiding virtual memory", bullets=["Install more RAM so more can stay in memory.", "Close programs you aren't using.",
        "An SSD makes swapping less painful, but it's still far slower than RAM."], challenge="Why does doubling the RAM make a computer significantly faster?",
        ill=("tiles", [("More RAM", "g"), ("Close programs", "g"), ("Use an SSD", "b")], 3), fact="To avoid using virtual memory, you can...",
        tasks=[mcq("What is the best way to avoid heavy use of virtual memory?", "Install more RAM", ["Buy a bigger monitor", "Use a faster internet connection", "Delete the operating system"],
                   "More RAM means less swapping."),
               mcq("Why does doubling RAM make a heavily loaded computer much faster?", "Far less swapping is needed, so the CPU waits for the disk much less often", ["The CPU's clock speed doubles", "The hard disk spins twice as fast", "Programs become smaller"],
                   "The time saved is disk time, not CPU time.")]),
   dict(name="Virtual memory in action", bullets=["A user has a word processor and a browser open, filling RAM.", "They open a graphics app, so the least-used data is swapped out to disk.",
        "Switching back to the word processor swaps it in again, which is why the switch feels slow."], challenge="Illustrate this scenario on your worksheet.",
        ill=("stack", [("Graphics app", "Just opened: in RAM", "g"), ("Browser", "In RAM", "b"), ("Word processor", "Swapped out to disk", "r")]), fact="In this scenario...",
        tasks=[mcq("The user switches back to the swapped-out word processor. What happens?", "It is copied back into RAM, and something else is swapped out", ["It reopens from scratch, losing the work", "It runs from the disk at full speed", "Nothing: it was never moved"],
                   "That's why switching back takes a moment."),
               mcq("Which would remove the delay completely?", "Having enough RAM to hold all three programs at once", ["Turning off the monitor", "Using a smaller mouse pointer", "Closing the ROM"],
                   "With enough RAM, no swapping is needed.")]),
  ],
  final=dict(name="Final challenge: the swap", floor_title="Final challenge: the swap",
    intro="Six statements about virtual memory. Tap the star and sort each one into true or false.",
    ill=("flow", ["RAM", "Swap", "Disk"]),
    tasks=[sort("Is each statement about virtual memory true or false?", ["True", "False"], [
      ["It uses secondary storage as extra memory", "True"], ["The CPU can work on it directly, without using RAM", "False"],
      ["It is slower than using RAM", "True"], ["It is needed because RAM is limited", "True"],
      ["Adding more RAM reduces how much it is used", "True"], ["It makes a computer faster than having enough RAM", "False"]],
      "Virtual memory is a rescue, not an upgrade.")]),
  info=[(0, "Page file", "On Windows this space is called the page file; on Linux it's the swap partition. You can see it using up disk space."),
        (1, "How big?", "Virtual memory is often set to around the same size as the installed RAM, but the operating system usually manages it automatically."),
        (2, "Thrashing sounds", "On old computers with spinning hard disks, you could hear thrashing: the drive clicking constantly while nothing happened on screen."),
        (3, "Phones too", "Some phones now use storage as extra RAM in the same way, advertised as 'RAM expansion' or 'virtual RAM'."),
        (4, "Pages", "Memory is swapped in fixed-size blocks called pages, usually 4 kB, rather than whole programs at a time."),
        (5, "SSD wear", "Heavy swapping writes a lot of data, which slowly wears out an SSD. Another reason to fit enough RAM.")],
  ws=dict(title="Virtual memory", objectives=["understand the need for virtual memory", "understand how virtual memory works"],
    starter="You open ten browser tabs, a game and a video editor on an old laptop. Describe what happens and why.", starter_lines=3, keyterms=["Virtual memory", "Volatile"],
    keyq="Why do we need virtual memory, and what can we do to avoid using it?",
    exam=[("Describe what is meant by virtual memory.", 2, 2), ("Explain why using virtual memory slows a computer down.", 3, 3),
          ("State one way a user could reduce the need for virtual memory.", 1, 1)],
    confidence=["What virtual memory is", "How data is swapped between RAM and disk", "Why virtual memory is slow"]))

L3 = dict(id="ms-l03", topic="1.2", lesson=3, title="Storage warehouse", img="MS_L03_StorageWarehouse_360",
  description="Why computers need secondary storage, and how magnetic, optical and solid state devices actually work.",
  kicker=f"{K12}  |  Lesson 3", scene_title="Storage warehouse", subtitle=SUB12,
  intro="Everything you keep lives in secondary storage. Find out why it's needed, then look inside the three types: magnetic, optical and solid state.",
  keywords=["Secondary storage", "Magnetic", "Optical", "Solid state", "Non-volatile", "Flash"],
  stations=[
   dict(name="Why secondary storage?", bullets=["It is non-volatile, so data is kept when the power is off.", "It holds programs and files that aren't currently in use.",
        "It is much larger, and much cheaper per gigabyte, than RAM."], challenge="Why do computers have secondary storage as well as RAM?",
        ill=("icons", [("disk", "Hard disk"), ("ram", "RAM")]), fact="Secondary storage is needed because...",
        tasks=[mcq("Why do computers need secondary storage?", "To keep programs and data permanently, even when the power is off", ["Because the CPU works from it directly", "Because it is faster than RAM", "To make the case heavier"],
                   "Non-volatile storage is what makes saving possible."),
               mcq("Which statement is true?", "Secondary storage is slower than RAM but much larger and cheaper per gigabyte", ["Secondary storage is faster than RAM", "Secondary storage is volatile", "Secondary storage can't hold programs"],
                   "That trade-off is why computers have both.")]),
   dict(name="Magnetic storage", bullets=["Hard disk drives use spinning platters coated in magnetic material.", "A read/write head moves across the surface, magnetising tiny areas as 1s and 0s.",
        "Magnetic tape works the same way, but reads in sequence from a long strip."], challenge="Why are moving parts a problem for a laptop's storage?",
        ill=("icons", [("disk", "Hard disk drive")]), fact="Magnetic storage works by...",
        tasks=[mcq("How does a hard disk drive store data?", "By magnetising tiny areas on spinning platters", ["By burning pits with a laser", "In flash memory cells with no moving parts", "On punched cards"],
                   "The read/write head floats just above the surface."),
               mcq("What is magnetic tape mostly used for now?", "Large, cheap, long-term backups and archives", ["Running the operating system", "Storing photos on a phone", "Distributing films to cinemas"],
                   "Tape is slow to search but very cheap per terabyte.")]),
   dict(name="Optical storage", bullets=["CDs, DVDs and Blu-ray discs are read by a laser.", "Data is stored as pits and lands burned into the surface, which reflect the laser differently.",
        "Discs are cheap, light and portable, but hold relatively little and scratch easily."], challenge="Rank CD, DVD and Blu-ray by capacity.",
        ill=("icons", [("disk", "Optical disc")]), fact="Optical storage works by...",
        tasks=[mcq("How is data read from an optical disc?", "A laser detects pits and lands on the surface", ["A magnet reads the platters", "Electricity is trapped in flash cells", "A needle follows a groove"],
                   "Blu-ray uses a blue laser with a shorter wavelength, so it fits more data."),
               order("Put these optical discs in order of capacity, smallest first.", ["CD (about 700 MB)", "DVD (about 4.7 GB)", "Blu-ray (about 25 GB)"], "Each generation uses a shorter-wavelength laser.")]),
   dict(name="Solid state storage", bullets=["SSDs, USB sticks and memory cards use flash memory.", "Data is stored as electrical charge in cells, with no moving parts.",
        "Very fast, silent, durable and light, but more expensive per gigabyte."], challenge="Why is solid state best for a laptop that gets carried around?",
        ill=("icons", [("ram", "SSD"), ("disk", "USB stick")]), fact="Solid state storage works by...",
        tasks=[mcq("How does solid state storage hold data?", "As electrical charge in flash memory cells, with no moving parts", ["On magnetic platters", "As pits burned by a laser", "On a spool of tape"],
                   "No moving parts means it's quiet, fast and hard to damage by knocks."),
               mcq("Which is a disadvantage of solid state storage?", "It costs more per gigabyte than magnetic storage", ["It is very slow", "It is easily damaged by being dropped", "It is very heavy"],
                   "Prices keep falling, but magnetic is still cheaper per terabyte.")]),
   dict(name="Inside the devices", bullets=["Magnetic: platters, spindle, read/write head, actuator arm.", "Optical: laser, lens, spinning disc, pits and lands.",
        "Solid state: controller chip and flash memory chips."], challenge="Label the parts of a hard disk on your worksheet.",
        ill=("tiles", [("Platters", "b"), ("Read/write head", "b"), ("Laser", "p"), ("Pits and lands", "p"), ("Flash chips", "g"), ("Controller", "g")], 3),
        fact="The main parts are...",
        tasks=[match("Match each part to the type of storage it belongs to.", [["Spinning platters and a read/write head", "Magnetic"], ["A laser reading pits and lands", "Optical"],
                     ["Flash memory chips and a controller", "Solid state"], ["A long spool read in sequence", "Magnetic tape"]], "Knowing how each works explains its strengths and weaknesses.")]),
   dict(name="Choosing a type", bullets=["Magnetic: huge capacity, cheap, but slower and fragile when moved.", "Optical: cheap and portable, small capacity, easily scratched.",
        "Solid state: fast and durable, but dearer per gigabyte."], challenge="Which type would you fit in a school's file server, and why?",
        ill=("compare", "Magnetic", ["Cheap per TB", "Moving parts"], "Solid state", ["Fast, durable", "Costs more"], "b", "g"), fact="Each type suits...",
        tasks=[mcq("A laptop needs fast, durable storage for its operating system. Which type?", "Solid state", ["Magnetic tape", "Optical disc", "Punched card"], "SSDs boot quickly and survive being carried around."),
               mcq("A company needs to archive 500 TB cheaply, and rarely needs it back. Which type?", "Magnetic tape", ["Solid state", "Optical disc", "RAM"], "Tape is the cheapest way to store enormous archives.")]),
  ],
  final=dict(name="Final challenge: sort the storage", floor_title="Final challenge: sort the storage",
    intro="Nine devices and descriptions have arrived at the warehouse. Tap the star and sort each into magnetic, optical or solid state.",
    ill=("icons", [("disk", "Magnetic"), ("disk", "Optical"), ("ram", "Solid state")]),
    tasks=[sort("Is each item magnetic, optical or solid state?", ["Magnetic", "Optical", "Solid state"], [
      ["Hard disk drive", "Magnetic"], ["Blu-ray disc", "Optical"], ["USB memory stick", "Solid state"],
      ["Backup tape", "Magnetic"], ["DVD", "Optical"], ["SD card in a camera", "Solid state"],
      ["Spinning platters and a read/write head", "Magnetic"], ["A laser reading pits and lands", "Optical"], ["Flash memory with no moving parts", "Solid state"]],
      "Use these for your Top Trumps cards next lesson.")]),
  info=[(0, "The first hard disk", "IBM's first hard disk, in 1956, stored about 3.75 MB, weighed over a tonne and was delivered by forklift."),
        (1, "Heads that fly", "A hard disk's head floats just nanometres above the platter, closer than a speck of dust. That's why a knock can wreck it."),
        (2, "Why Blu-ray?", "A blue laser has a shorter wavelength than a red one, so it can read smaller pits, which means more data on the same-sized disc."),
        (3, "Tape lives on", "Tape is far from dead: it stores much of the world's long-term archives, including film studios' back catalogues."),
        (4, "Wear levelling", "Flash cells wear out after many writes, so SSD controllers spread writes evenly across the chips to make them last."),
        (5, "M-DISC", "Some archival optical discs claim a lifespan of hundreds of years, far longer than a typical hard drive.")],
  ws=dict(title="Common types of storage", objectives=["understand the need for secondary storage", "know the common types of storage", "know how each type works"],
    starter="List everything stored on the computer you are using that must still be there tomorrow morning.", starter_lines=3, keyterms=["Secondary storage", "Non-volatile"],
    keyq="Why do computers have secondary storage?",
    exam=[("State what is meant by non-volatile storage.", 1, 1), ("Describe how a hard disk drive stores data.", 2, 2), ("Describe how data is read from an optical disc.", 2, 2)],
    confidence=["The need for secondary storage", "Magnetic, optical and solid state", "How each type works"]))

L4 = dict(id="ms-l04", topic="1.2", lesson=4, title="Top Trumps", img="MS_L04_TopTrumps_360",
  description="Compare storage devices on capacity, speed, portability, durability, reliability and cost.",
  kicker=f"{K12}  |  Lesson 4", scene_title="Top Trumps", subtitle=SUB12,
  intro="Every storage device is a compromise. Learn the six characteristics examiners ask about, then compare the devices like a set of Top Trumps cards.",
  keywords=["Capacity", "Speed", "Portability", "Durability", "Reliability", "Cost"],
  stations=[
   dict(name="The six characteristics", bullets=["Capacity: how much it holds. Speed: how quickly data is read and written.",
        "Portability: how easy it is to carry. Durability: how well it survives knocks.", "Reliability: how likely it is to keep working. Cost: usually per gigabyte."],
        challenge="Which two characteristics matter most for a school server, and why?",
        ill=("tiles", [("Capacity", "b"), ("Speed", "p"), ("Portability", "o"), ("Durability", "y"), ("Reliability", "g"), ("Cost", "k")], 3),
        fact="The six characteristics are...",
        tasks=[multi("Which of these are characteristics used to compare storage devices? Select all that apply.", ["Capacity", "Speed", "Portability", "Durability", "Screen size", "Number of USB ports"],
                     ["Capacity", "Speed", "Portability", "Durability"], "Reliability and cost complete the list of six."),
               mcq("What does durability mean for a storage device?", "How well it survives being knocked, dropped or moved", ["How much data it holds", "How quickly it transfers data", "How much it costs"],
                   "Solid state scores well here; hard disks don't.")]),
   dict(name="Magnetic: the card", bullets=["Capacity: very high, several terabytes. Cost: lowest per gigabyte.",
        "Speed: moderate. Portability: poor for internal drives, moderate for external.", "Durability: poor, because of moving parts. Reliability: good while it stays still."],
        challenge="Fill in the Top Trumps card for a hard disk drive.", ill=("table", ["Hard disk", "Rating"], [["Capacity", "High"], ["Speed", "Medium"], ["Durability", "Low"], ["Cost per GB", "Low"]]),
        fact="A hard disk drive scores...",
        tasks=[mcq("What is a hard disk drive's biggest advantage?", "A very large capacity at a low cost per gigabyte", ["It survives being dropped", "It is the fastest storage available", "It fits in a pocket easily"],
                   "Cheap terabytes are why servers still use them."),
               mcq("What is its biggest weakness?", "Moving parts make it fragile and slower than solid state", ["It can't store video", "It is volatile", "It needs a laser"],
                   "Never move a running hard disk if you can help it.")]),
   dict(name="Optical: the card", bullets=["Capacity: low, from 700 MB to 50 GB. Cost: very low per disc.",
        "Speed: slow. Portability: excellent, thin and light.", "Durability: poor, easily scratched. Reliability: good if stored carefully."],
        challenge="Fill in the Top Trumps card for a Blu-ray disc.", ill=("table", ["Optical disc", "Rating"], [["Capacity", "Low"], ["Speed", "Slow"], ["Portability", "High"], ["Durability", "Low"]]),
        fact="An optical disc scores...",
        tasks=[mcq("Why are optical discs still used to distribute films and games?", "They are very cheap to produce in huge numbers and easy to post", ["They are the fastest storage", "They hold more than a hard disk", "They can't be copied"],
                   "Mass production makes each disc cost pennies."),
               mcq("Which characteristic is an optical disc weakest on?", "Capacity", ["Portability", "Cost per disc", "Weight"], "Even Blu-ray holds far less than a modern hard disk.")]),
   dict(name="Solid state: the card", bullets=["Capacity: high and rising. Cost: highest per gigabyte of the three.",
        "Speed: fastest. Portability: excellent. Durability: excellent, no moving parts.", "Reliability: very good, though cells do wear out after many writes."],
        challenge="Fill in the Top Trumps card for an SSD.", ill=("table", ["Solid state", "Rating"], [["Capacity", "High"], ["Speed", "Fastest"], ["Durability", "High"], ["Cost per GB", "High"]]),
        fact="Solid state storage scores...",
        tasks=[mcq("Why is solid state storage chosen for laptops and phones?", "It is fast, light, silent and survives being carried around", ["It is the cheapest per gigabyte", "It holds more than any other type", "It never wears out"],
                   "The price premium buys speed and durability."),
               mcq("What eventually limits the life of flash memory?", "Each cell can only be written a limited number of times", ["The laser wears out", "The platters slow down", "The tape snaps"],
                   "Controllers spread writes out to delay this.")]),
   dict(name="Head to head", bullets=["Fastest: solid state. Cheapest per gigabyte: magnetic.", "Most portable: optical and small solid state devices.",
        "Toughest: solid state. Biggest archive on a budget: tape."], challenge="Which device wins on each characteristic?",
        ill=("compare", "Magnetic", ["Cheap, huge", "Fragile, slower"], "Solid state", ["Fast, tough", "Costs more"], "b", "g"), fact="Comparing the three types...",
        tasks=[sort("Which type of storage does each statement describe best?", ["Magnetic", "Optical", "Solid state"], [
                    ["Cheapest per gigabyte for very large amounts", "Magnetic"], ["Fastest read and write speeds", "Solid state"],
                    ["Cheapest way to send a film to millions of homes", "Optical"], ["Most durable when carried around", "Solid state"],
                    ["Easily scratched", "Optical"], ["Contains moving parts that can fail", "Magnetic"]], "These comparisons are what exam questions ask you to justify.")]),
   dict(name="Justify your choice", bullets=["Exam answers need the characteristic and the reason.", "'An SSD, because it is fast and has no moving parts, so it survives being carried' scores; 'an SSD because it's better' doesn't.",
        "Mention capacity, speed, portability, durability, reliability or cost by name."], challenge="Write a full justification for the storage in a digital camera.",
        ill=("flow", ["Name the device", "Name the characteristic", "Link it to the situation"]), fact="A good justification includes...",
        tasks=[mcq("Which is the best exam answer?", "An SSD, because it has no moving parts, so it is durable enough to be carried around all day", ["An SSD, because it is better", "An SSD, because I have one", "An SSD, because it is modern"],
                   "Characteristic plus reason plus situation."),
               mcq("A student writes 'a hard disk, because it is cheap'. How could it be improved?", "Say cheap per gigabyte, and link it to needing a lot of storage on a budget", ["Add the brand name", "Say it is heavy", "Nothing: it's already full marks"],
                   "Link the characteristic to the scenario every time.")]),
  ],
  final=dict(name="Final challenge: Top Trumps", floor_title="Final challenge: Top Trumps",
    intro="Eight cards, one characteristic each. Tap the star and sort each statement into the device it describes.",
    ill=("tiles", [("Hard disk", "b"), ("Optical disc", "p"), ("SSD", "g"), ("Tape", "o")], 4),
    tasks=[sort("Which device does each statement describe?", ["Hard disk", "Optical disc", "SSD", "Tape"], [
      ["Several terabytes, cheap, with spinning platters", "Hard disk"], ["About 25 GB, thin, light and easily scratched", "Optical disc"],
      ["The fastest of the four, with no moving parts", "SSD"], ["Read in sequence, ideal for huge cheap archives", "Tape"],
      ["Best for a laptop that gets carried everywhere", "SSD"], ["Best for distributing a film to millions of homes", "Optical disc"],
      ["Best value for a school server's bulk storage", "Hard disk"], ["Best for backing up 500 TB for ten years", "Tape"]],
      "Copy the ones you found hardest onto your Top Trumps cards.")]),
  info=[(0, "Cost per gigabyte", "Hard disk storage costs a few pence per gigabyte; SSD storage costs several times more, although the gap keeps narrowing."),
        (1, "Speed in numbers", "A hard disk transfers roughly 100-200 MB per second; a modern NVMe SSD can exceed 5,000 MB per second."),
        (2, "Helium drives", "Some large hard disks are filled with helium instead of air, so the platters meet less resistance and more can be packed in."),
        (3, "Rewritable discs", "CD-R and DVD-R can be written once; RW versions use a material that can be melted back and rewritten hundreds of times."),
        (4, "Tape robots", "Data centres use robot arms to fetch tapes from racks, like a huge automated library."),
        (5, "Right tool, right job", "Big systems use all three: SSDs for speed, hard disks for bulk, and tape for archives.")],
  ws=dict(title="Characteristics of storage devices", objectives=["know the characteristics of storage devices", "be able to compare devices using those characteristics"],
    starter="You are buying storage for a school trip camera. Write the five questions you would ask before choosing.", starter_lines=3, keyterms=["Capacity", "Durability"],
    keyq="What are the differences between secondary storage devices?",
    extra=dict(title="Top Trumps cards", instr="Rate each device out of 5 for each characteristic, then add a typical capacity.",
               head=["Device", "Capacity", "Speed", "Portability", "Durability", "Cost per GB"],
               rows=[["Hard disk", "", "", "", "", ""], ["Optical disc", "", "", "", "", ""], ["Solid state", "", "", "", "", ""], ["Magnetic tape", "", "", "", "", ""]]),
    exam=[("State two characteristics used to compare storage devices.", 2, 2), ("Explain why an SSD is more suitable than a hard disk for a laptop.", 4, 4)],
    confidence=["The six characteristics", "Comparing the three types", "Justifying a choice of device"]))

L5 = dict(id="ms-l05", topic="1.2", lesson=5, title="Pick the storage", img="MS_L05_PickTheStorage_360",
  description="Nine real situations, from distributing a film to backing up photos: choose the right device and justify it.",
  kicker=f"{K12}  |  Lesson 5", scene_title="Pick the storage", subtitle=SUB12,
  intro="Now put it to work. Nine customers each need storage, and each needs a different answer. Choose the device, name the characteristic, and justify the choice.",
  keywords=["Suitability", "Capacity", "Portability", "Speed", "Cost", "Justify"],
  stations=[
   dict(name="How to choose", bullets=["Ask: how much data? How fast? Does it need carrying? How long must it last? What's the budget?",
        "Then match those answers to a device's characteristics.", "Always justify: device, characteristic, reason."], challenge="What questions would you ask a customer before recommending storage?",
        ill=("flow", ["How much?", "How fast?", "Carried?", "How long?", "Budget?"]), fact="To choose a device, ask...",
        tasks=[mcq("Which question matters most for choosing storage for a video camera?", "How portable and durable does it need to be?", ["What colour is the camera?", "How fast is the internet?", "How large is the screen?"],
                   "A camera is carried, knocked and used away from mains power."),
               mcq("A customer needs 12 TB for a backup server on a tight budget. What matters most?", "Capacity and cost per gigabyte", ["Portability", "Screen resolution", "Weight"],
                   "They aren't carrying it, so bulk and price win.")]),
   dict(name="Distributing a film", bullets=["Millions of copies, posted or sold in shops.", "Each copy must be cheap, light and hold a couple of hours of high-definition video.",
        "Read-only is fine: buyers don't need to write to it."], challenge="Which device, and why?", ill=("icons", [("disk", "Blu-ray disc")]), fact="For distributing a film...",
        tasks=[mcq("Which storage is most suitable for selling a film in shops?", "Optical disc, such as Blu-ray: cheap to mass produce and easy to post", ["Solid state drives, one per customer", "Magnetic tape for every buyer", "A hard disk per customer"],
                   "Cost per copy is what matters here."),
               mcq("Why is read-only acceptable for this?", "Customers only need to watch the film, not write to the disc", ["Because writing is illegal", "Because discs can't store video", "Because it makes the film shorter"],
                   "No write capability keeps the cost down.")]),
   dict(name="Carrying work home", bullets=["Small files, carried in a pocket every day.", "Needs to survive knocks and plug into any computer.",
        "Capacity needed is small compared with a server."], challenge="Which device, and why?", ill=("icons", [("disk", "USB stick"), ("laptop", "Any computer")]), fact="For carrying work between home and the office...",
        tasks=[mcq("Which device suits carrying work between home and an office?", "A USB flash drive: small, portable and durable", ["An internal hard disk", "A magnetic tape", "A CD-ROM that can't be written to"],
                   "Solid state, portable and plugs in anywhere."),
               mcq("Which characteristic is least important here?", "Capacity", ["Portability", "Durability", "Compatibility"], "Documents are small; the device just has to survive the journey.")]),
   dict(name="Music, cameras and consoles", bullets=["MP3 player: small, no moving parts, survives movement, so solid state.",
        "Video camera: fast writes and portability, so a solid state memory card.", "Console game: mass-produced, so optical disc, or a download."],
        challenge="Which device for each, and why?", ill=("icons", [("phone", "MP3 player"), ("disk", "SD card"), ("pc", "Console")]), fact="For portable devices...",
        tasks=[match("Match each situation to the most suitable storage.", [["MP3 player", "Solid state: small, light, survives movement"],
                     ["Video camera", "Solid state memory card: fast writes and portable"], ["Console game in a shop", "Optical disc: cheap to mass produce"],
                     ["School network main storage", "Magnetic hard disks: large capacity at low cost"]], "All four appear in your lesson's scenario list.")]),
   dict(name="Servers and operating systems", bullets=["School network storage: many terabytes, always plugged in, so magnetic hard disks.",
        "A computer's operating system: needs to load fast, so solid state.", "Servers often use both: SSD for speed, hard disks for bulk."],
        challenge="Why do servers often use two types of storage together?", ill=("icons", [("server", "File server"), ("ram", "SSD boot drive")]), fact="For servers...",
        tasks=[mcq("Why do schools use magnetic hard disks for bulk network storage?", "They give the most gigabytes for the money and never leave the server room", ["They are the fastest available", "They are the most portable", "They can't fail"],
                   "Capacity and cost outweigh speed here."),
               mcq("Why is an SSD used for a computer's operating system?", "It loads and responds much faster than a hard disk", ["It is cheaper per gigabyte", "It holds more data", "It is easier to post"],
                   "Boot time is where SSDs shine.")]),
   dict(name="Long-term archives", bullets=["Training videos kept for years: huge capacity, rarely accessed, so magnetic tape or archive discs.",
        "Photo backups: a second copy, kept somewhere else, often an external hard disk or the cloud.", "Any backup should be kept away from the original."],
        challenge="Which device for long-term photo backup, and why?", ill=("icons", [("disk", "Tape archive"), ("cloud", "Cloud backup")]), fact="For long-term storage...",
        tasks=[mcq("A company archives 200 TB of training videos it rarely opens. Which is most suitable?", "Magnetic tape: enormous capacity at the lowest cost", ["Optical discs, one per video", "USB sticks in a drawer", "Extra RAM"],
                   "Slow access doesn't matter for an archive."),
               mcq("Why should a photo backup be kept in a different place from the originals?", "A fire, flood or theft could destroy both copies at once", ["Backups work faster when cold", "It saves electricity", "The law says so"],
                   "Off-site is the point of a backup.")]),
  ],
  final=dict(name="Final challenge: nine customers", floor_title="Final challenge: nine customers",
    intro="Nine situations from your lesson. Tap the star and match each one to the most suitable type of storage.",
    ill=("tiles", [("Magnetic", "b"), ("Optical", "p"), ("Solid state", "g")], 3),
    tasks=[sort("Which type of storage is most suitable for each situation?", ["Magnetic", "Optical", "Solid state"], [
      ["Distributing a film to shops", "Optical"], ["Transferring work between home and an office", "Solid state"],
      ["Storing tracks on an MP3 player", "Solid state"], ["Main storage for a school network", "Magnetic"],
      ["Storing video on a video camera", "Solid state"], ["Distributing a video game for a console", "Optical"],
      ["Storing a computer's operating system", "Solid state"], ["Long-term storage of training videos", "Magnetic"],
      ["Long-term backup of photos", "Magnetic"]],
      "In the exam, always name the characteristic that makes it suitable.")]),
  info=[(0, "Downloads changed things", "Games and films increasingly arrive as downloads, so optical drives are vanishing from computers and consoles."),
        (1, "Cloud is still disks", "Cloud storage is someone else's secondary storage: racks of hard disks and SSDs in a data centre."),
        (2, "Cameras and cards", "Professional cameras use fast memory cards because 4K video writes hundreds of megabytes every second."),
        (3, "Write once", "Archives sometimes use write-once media on purpose, so records can't be altered later."),
        (4, "The 3-2-1 rule", "Three copies, on two types of media, with one off-site. It's the standard advice for backups."),
        (5, "Hybrid drives", "Some drives combine a small SSD with a large hard disk, using the fast part for the files you use most.")],
  ws=dict(title="Applications of storage", objectives=["understand the suitability of storage devices for certain applications",
          "understand the advantages and disadvantages of devices based on their characteristics"],
    starter="Pick three devices in the room and say what kind of storage each one uses, and why that suits it.", starter_lines=4,
    keyterms=["Portability", "Suitability"], keyq="What features of secondary storage make devices suitable for different situations?",
    extra=dict(title="Nine situations", instr="Name the device and justify your choice using a characteristic.", head=["Situation", "Device", "Justification"],
               rows=[[s, "", ""] for s in ["Distributing a film", "Work between home and office", "MP3 player", "School network storage", "Video camera",
                                            "Console game", "Operating system", "Training video archive", "Photo backup"]]),
    exam=[("A photographer needs storage for use on location. Recommend a device and justify your choice.", 4, 5),
          ("Explain why a school uses magnetic hard disks rather than SSDs for its main file storage.", 3, 3)],
    confidence=["Choosing a device for a situation", "Justifying with characteristics", "Advantages and disadvantages"]))

L6 = dict(id="ms-l06", topic="1.2", lesson=6, title="Units lab", img="MS_L06_UnitsLab_360",
  description="From a single bit to a petabyte: why computers use binary, and how to convert between the units.",
  kicker=f"{K12}  |  Lesson 6", scene_title="Units lab", subtitle=SUB12,
  intro="Everything a computer stores is measured in bits. Learn the units from bit to petabyte, why data has to be binary in the first place, and practise converting between them.",
  keywords=["Bit", "Nibble", "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte", "Petabyte"],
  stations=[
   dict(name="Why binary?", bullets=["Computers are built from transistors, which are switches: on or off.", "Two states map perfectly onto 1 and 0.",
        "Everything, from numbers to images and sound, is stored as binary."], challenge="Why is data stored in binary?", ill=("tiles", [("On = 1", "g"), ("Off = 0", "n")], 2),
        fact="Data is stored in binary because...",
        tasks=[mcq("Why do computers use binary?", "Their circuits have two states, on and off, which represent 1 and 0", ["Because binary is shorter to write", "Because people find binary easy to read", "Because it uses less electricity than decimal"],
                   "Two reliable states are much easier to build than ten."),
               mcq("Which of these is stored in binary inside a computer?", "All of them: numbers, text, images and sound", ["Only numbers", "Only text", "Only images"],
                   "Everything ends up as 1s and 0s.")]),
   dict(name="Bits, nibbles and bytes", bullets=["A bit is a single 1 or 0.", "A nibble is 4 bits. A byte is 8 bits.",
        "One byte can store one character, or a number from 0 to 255."], challenge="Show how the number 5 is stored in a nibble.",
        ill=("table", ["Unit", "Size"], [["Bit", "1 binary digit"], ["Nibble", "4 bits"], ["Byte", "8 bits"]]), fact="A bit... A nibble... A byte...",
        tasks=[mcq("How many bits are in a byte?", "8", ["2", "4", "16"], "Half a byte, 4 bits, is a nibble."),
               convert("Show the number 5 in binary. Use the last four bits, as a nibble.", "denary", "binary", 5, "5 is 0101 in a nibble, which is 00000101 in a byte.")]),
   dict(name="Kilo, mega, giga", bullets=["1 kilobyte (kB) = 1,000 bytes. 1 megabyte (MB) = 1,000 kB.",
        "1 gigabyte (GB) = 1,000 MB. 1 terabyte (TB) = 1,000 GB. 1 petabyte (PB) = 1,000 TB.", "Each step up multiplies by 1,000."],
        challenge="Write the units in order and show each as a power of ten.", ill=("table", ["Unit", "Bytes"], [["kB", "1,000"], ["MB", "1,000,000"], ["GB", "10⁹"], ["TB", "10¹²"], ["PB", "10¹⁵"]]),
        fact="The units of storage are...",
        tasks=[order("Put these units in order, smallest first.", ["Bit", "Nibble", "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte", "Petabyte"], "Each unit after byte is 1,000 times the one before."),
               mcq("How many megabytes are in a gigabyte?", "1,000", ["8", "100", "1,024,000"], "OCR uses 1,000 for these conversions.")]),
   dict(name="Converting units", bullets=["Going up a unit: divide by 1,000. Going down: multiply by 1,000.", "Bits to bytes: divide by 8. Bytes to bits: multiply by 8.",
        "Watch the capital B: KB is kilobytes, Kb is kilobits."], challenge="Convert 4,500 MB into gigabytes, and 3 GB into megabytes.",
        ill=("flow", ["bit ×8→ byte", "byte ×1000→ kB", "kB ×1000→ MB", "MB ×1000→ GB"]), fact="To convert between units, you...",
        tasks=[mcq("How many bytes are in 2 kB?", "2,000", ["16", "256", "2,048,000"], "1 kB is 1,000 bytes."),
               mcq("A file is 6,000 MB. How big is it in gigabytes?", "6 GB", ["0.6 GB", "60 GB", "600 GB"], "Divide by 1,000 to go up a unit."),
               mcq("What does a lowercase b mean, as in 34 Kb?", "Kilobits, used for data transmission speeds", ["Kilobytes", "Kilobits per byte", "Nothing: it means the same as KB"],
                   "Uppercase B is bytes, for storage; lowercase b is bits, for speeds.")]),
   dict(name="Storing a number", bullets=["1 bit stores a Boolean: true or false, 1 or 0.", "A nibble stores 0 to 15: enough for a single digit on an LCD display.",
        "A byte stores 0 to 255: enough for one character, such as A = 65."], challenge="Show how 65 is stored in 8 bits.",
        ill=("tiles", [("1 bit: 0 or 1", "b"), ("4 bits: 0-15", "p"), ("8 bits: 0-255", "g")], 3), fact="The number of bits decides...",
        tasks=[convert("Show the number 65 in 8-bit binary. This is the code for the letter A.", "denary", "binary", 65, "65 is 01000001, which is the ASCII code for A."),
               mcq("What is the largest number a byte can store?", "255", ["8", "128", "1,000"], "8 bits give 256 different values, from 0 to 255.")]),
   dict(name="How big is a petabyte?", bullets=["1 PB is a million gigabytes.", "It would hold roughly 250,000 films, or 200 million photos.",
        "Data centres now measure their storage in petabytes and exabytes."], challenge="How many 8 GB memory sticks would it take to hold 1 PB?",
        ill=("tiles", [("1 kB: a page", "b"), ("1 MB: a photo", "p"), ("1 GB: a film clip", "o"), ("1 TB: 250 films", "g"), ("1 PB: a library", "y")], 3),
        fact="A petabyte is...",
        tasks=[mcq("How many gigabytes are in a petabyte?", "1,000,000", ["1,000", "8,000", "1,000,000,000"], "GB → TB → PB is two steps of 1,000."),
               mcq("Roughly how many 8 GB memory sticks would hold 1 TB?", "125", ["8", "80", "1,000"], "1,000 ÷ 8 = 125.")]),
  ],
  final=dict(name="Final challenge: unit conversions", floor_title="Final challenge: unit conversions",
    intro="Convert between units and binary. Tap the star to begin.",
    ill=("table", ["From", "To"], [["1,000 bytes", "1 kB"], ["1,000 kB", "1 MB"], ["1,000 GB", "1 TB"]]),
    tasks=[convert("Show the number 200 in 8-bit binary.", "denary", "binary", 200, "200 is 11001000."),
           sort("Sort these into the correct unit.", ["Kilobyte", "Megabyte", "Gigabyte"], [
             ["1,000 bytes", "Kilobyte"], ["1,000,000 bytes", "Megabyte"], ["1,000 kB", "Megabyte"],
             ["1,000 MB", "Gigabyte"], ["10⁹ bytes", "Gigabyte"], ["A typical short photo file", "Megabyte"]],
             "Each step up the units multiplies by 1,000.")]),
  info=[(0, "1,000 or 1,024?", "Strictly, 1,024 bytes is a kibibyte (KiB). OCR uses 1,000 for a kilobyte, so use 1,000 in the exam."),
        (1, "Why 8 bits?", "A byte settled at 8 bits because it holds one character in early character sets, and 8 is a convenient power of two."),
        (2, "Nibble", "A nibble really is the official name for half a byte: computer scientists do occasionally have a sense of humour."),
        (3, "Exabytes", "After petabyte comes exabyte, then zettabyte. The world now creates well over 100 zettabytes of data a year."),
        (4, "Advertised sizes", "A '1 TB' drive shows as about 931 GB in Windows, because Windows divides by 1,024 while the manufacturer used 1,000."),
        (5, "Bits for speed", "Broadband is sold in megabits per second. 80 Mb/s is only 10 MB/s of actual files, because there are 8 bits in a byte.")],
  ws=dict(title="Units of data storage", objectives=["know the units bit, nibble, byte, kilobyte, megabyte, gigabyte, terabyte and petabyte",
          "be able to convert between units", "understand that data must be converted to binary to be processed"],
    starter="A light switch has two positions. Explain how you could send a message to a friend using only that switch.", starter_lines=2, keyterms=["Bit", "Byte"], keyq="Why is data stored in binary?",
    extra=dict(title="Task: unit conversions", instr="Complete the conversions. Use 1,000 for each step.", head=["From", "To", "Answer"],
               rows=[["4 kB", "bytes", ""], ["3,500 MB", "GB", ""], ["2 GB", "MB", ""], ["6,000 bits", "bytes", ""], ["0.5 TB", "GB", ""]]),
    exam=[("State how many bits there are in a byte.", 1, 1), ("Show how the denary number 5 is stored in a nibble.", 1, 1),
          ("A file is 2,500 MB. Convert this to gigabytes.", 1, 1), ("Explain why data must be converted to binary.", 2, 2)],
    confidence=["Why data is binary", "The units from bit to petabyte", "Converting between units"]))
