"""Topic 2.2 Programming fundamentals - seven 360 experiences, one per lesson.

The OCR J277 2.2 content, in the order it is usually taught: the three basic
constructs, then data types and operators, file handling, records and SQL,
arrays and sub-programs, random numbers, and a revision lesson before the
end-of-topic test. Lesson 8 is the test itself, which is done on paper, so it
has a reflection worksheet in the registry rather than a room.

Related but separate: topic PY, the Python course (specspy.py), which teaches
the same techniques as code a pupil writes and runs. This topic is the exam
content; that one is the practice.

Code shown in a station is either Python 3 or the OCR Exam Reference Language,
never both in one block, and the bullets around it say which. The reference
language forms used here follow the insert in OCR's own J277 Paper 2 sample:
name.length, name.substring(x, i), name.upper, ASC() and CHR(), openRead and
openWrite with readLine, writeLine, endOfFile and close, array a[n] and
a[r,c], and random(a, b).
"""
from kit import mcq, multi, sort, match, order

K22 = "2.2 Programming fundamentals"
SUB22 = "OCR J277 Paper 2  |  Computational thinking, algorithms and programming"

L1 = dict(id="pf-l01", topic="2.2", lesson=1, title="Variable store", img="PF_L01_VariableStore_360",
  description="Inside the variable store: how a program holds data, and the three constructs that control everything it does.",
  kicker=f"{K22}  |  Lesson 1", scene_title="Variable store", subtitle=SUB22,
  intro="Every value a program holds is kept somewhere in this store, labelled with a name. Learn how values get in and out, and the three constructs that decide which line of code runs next.",
  keywords=["Variable", "Constant", "Assignment", "Input", "Output", "Sequence", "Selection", "Iteration"],
  stations=[
   dict(name="Variables and assignment", bullets=["A variable is a named location in memory holding a value that can change while the program runs.",
        "Assignment uses a single equals sign: the value on the right is stored in the variable on the left.",
        "In the OCR Exam Reference Language, score = score + 10 reads the old value, adds ten, then stores the result back."],
        challenge="Explain why score = score + 10 is not a contradiction, even though both sides use the same name.",
        ill=("code", ["lives = 3", "score = 0", "score = score + 10", "print(score)"], 26, [2]),
        fact="A variable is...",
        tasks=[mcq("What does a variable store?", "A value that can change while the program is running",
                   ["A value that is fixed and can never change", "The name of the program", "A single line of code"],
                   "The name stays the same, but the value inside it can be replaced."),
               mcq("What does total = total + 5 do?", "Adds 5 to the value already in total, then stores the new value back in total",
                   ["Checks whether total is equal to total plus 5", "Creates a second variable also called total", "Always sets total to 5"],
                   "A single equals sign assigns a value; it never compares.")]),
   dict(name="Constants", bullets=["A constant is a named value that is set when the program is written and cannot change while it runs.",
        "Constants make a program easier to read, and a value used many times can be changed in one place.",
        "A VAT rate or the number of lives a player starts with are good constants."],
        challenge="Name two values in a quiz game that should be constants, and say why each one should not change.",
        ill=("compare", "Constant", ["Set once, in the code", "Cannot change as it runs", "MAX_LIVES = 3"],
             "Variable", ["Set at any time", "Can change as it runs", "lives = 3"], "g", "b"),
        fact="A constant is...",
        tasks=[mcq("What is a constant?", "A named value that is fixed when the program is written and cannot change as it runs",
                   ["A variable with a very short name", "A value stored on the hard disk", "A value that changes every time the program runs"],
                   "Constants are set once; variables can be reassigned."),
               mcq("Which of these is best stored as a constant in a game?", "The number of lives the player starts with",
                   ["The player's current score", "The player's name", "The number of enemies still alive"],
                   "The starting number of lives is decided by the programmer; the other three change as the game is played.")]),
   dict(name="Input and output", bullets=["Input brings data into a program, usually from the keyboard. Output sends data out, usually to the screen.",
        "In the OCR Exam Reference Language input() and print() do this work.",
        "input() always returns a string, so a number must be cast before it is used in arithmetic."],
        challenge="Write three lines that ask a pupil for their name and age, then output a greeting using both.",
        ill=("code", ['name = input("Name: ")', 'age = int(input("Age: "))', 'print("Hi " + name)', "print(age + 1)"], 26, [1]),
        fact="input() always returns...",
        tasks=[mcq("What data type does input() give the program?", "A string",
                   ["An integer", "A Boolean", "A real number"],
                   "Even if the user types 12, it arrives as the characters 1 and 2."),
               mcq("A program must add 1 to a number the user has typed. What has to happen first?", "The input must be cast to an integer",
                   ["The input must be printed", "The input must be stored in a constant", "The input must be placed inside a loop"],
                   "Arithmetic cannot be done on a string, so cast it to a number first.")]),
   dict(name="Sequence", bullets=["Sequence means the statements are carried out one after another, in the order they are written.",
        "Change the order and you usually change the result.",
        "A variable must be given a value before any line that uses it."],
        challenge="Explain why a program must input a price before the line that calculates the total.",
        ill=("flow", ["Input price", "Add delivery", "Output total"]),
        fact="Sequence means...",
        tasks=[mcq("What does sequence mean?", "Statements are carried out one after another in the order they are written",
                   ["Statements are repeated until a condition is met", "A choice is made between two sets of statements", "Statements run in whichever order the computer finds quickest"],
                   "Nothing is skipped and nothing is repeated: each line runs once, in order."),
               mcq("What is wrong with this sequence:  print(total)  then  total = price * 2 ?", "total is output before it has been given a value",
                   ["print cannot be used with a variable", "There are too few lines in the program", "total should have been a constant"],
                   "Swapping the two lines fixes it: assign first, then use.")]),
   dict(name="Selection", bullets=["Selection chooses which statements to run by testing a condition that is either True or False.",
        "if ... then runs a block only when the condition is True; else runs when it is False; elseif tests a further condition.",
        "In the OCR Exam Reference Language the block ends with endif."],
        challenge="Write selection that outputs Pass for a mark of 40 or more, and Fail for anything lower.",
        ill=("code", ["if mark >= 40 then", '  print("Pass")', "else", '  print("Fail")', "endif"], 26, [0]),
        fact="Selection is used when...",
        tasks=[mcq("What does selection let a program do?", "Choose between different sets of statements by testing a condition",
                   ["Repeat a set of statements a fixed number of times", "Store a value in memory under a name", "Run every statement in the order written"],
                   "Selection is a choice at a fork in the road; iteration is a loop."),
               mcq("mark = 40. What does  if mark > 40 then print(\"Pass\") else print(\"Fail\") endif  output?", "Fail",
                   ["Pass", "Nothing at all", "40"],
                   "40 is not greater than 40, so the else branch runs. The test should have been >= 40.")]),
   dict(name="Iteration", bullets=["Iteration repeats a set of statements. A count-controlled loop repeats a known number of times.",
        "A condition-controlled loop repeats while a condition stays True, so the number of repeats is not known in advance.",
        "In the OCR Exam Reference Language a count-controlled loop uses for and next, and a condition-controlled loop uses while and endwhile."],
        challenge="Give one job that suits a count-controlled loop and one that suits a condition-controlled loop, and say why.",
        ill=("compare", "Count-controlled", ["for i = 0 to 9", "Known number of repeats", "Ends with next i"],
             "Condition-controlled", ["while lives > 0", "Repeats while True", "Ends with endwhile"], "g", "b"),
        fact="A count-controlled loop... A condition-controlled loop...",
        tasks=[mcq("How many times does  for i = 0 to 9  repeat its block?", "10",
                   ["9", "11", "It depends on the starting value of i"],
                   "Both 0 and 9 are included, so that is ten repeats."),
               mcq("Which loop keeps asking for a password until the correct one is typed?", "A condition-controlled loop",
                   ["A count-controlled loop", "A sequence", "A constant"],
                   "You cannot know how many attempts the user will need, so a condition must control the loop.")]),
  ],
  final=dict(name="Final challenge: three constructs", floor_title="Final challenge: name that construct",
    intro="Seven lines from the same program, written in the OCR Exam Reference Language. Tap the star and sort each line into the construct it belongs to.",
    ill=("big", "3 CONSTRUCTS", "Sequence, selection and iteration. Every program ever written is built from these three."),
    tasks=[sort("Which construct does each line show?", ["Sequence", "Selection", "Iteration"], [
      ["total = price + postage", "Sequence"], ['print("Welcome")', "Sequence"], ["age = input(\"Age: \")", "Sequence"],
      ["if age >= 18 then", "Selection"], ["elseif mark >= 70 then", "Selection"],
      ["while lives > 0", "Iteration"], ["for i = 1 to 5", "Iteration"], ["next i", "Iteration"]],
      "A line that just gets on with it is sequence; a line that asks a question is selection; a line that goes back is iteration."),
      mcq("Which construct does  while lives > 0  use?", "Condition-controlled iteration",
          ["Count-controlled iteration", "Selection", "Sequence"],
          "The number of repeats depends on a condition, not on a count.")]),
  info=[(0, "Named in memory", "A variable name is really a label for a memory location, and the computer works with the address rather than the name. Meaningful names like totalScore are not for the computer's benefit; they are for the next person to read your code."),
        (1, "Shouting case", "Programmers often write constant names in capitals, such as MAX_LIVES, as a signal that nothing should change them. Python does not enforce this, so the capital letters are a promise between programmers."),
        (2, "Where output goes", "Output does not have to be the screen. A program can output to a file, a printer, a speaker or another program, and the same data can go to several of them at once."),
        (3, "Sequence bugs", "If two lines are swapped, the program usually still runs but gives the wrong answer. That is a logic error, not a syntax error, and no computer can spot it for you."),
        (4, "Nesting", "An if can be placed inside another if, which is called nesting. It lets a program test a second condition only when the first one was True, like asking for a password only after a username matched."),
        (5, "Infinite loops", "If nothing inside a condition-controlled loop ever makes the condition False, the loop never ends. Always change the variable the condition depends on, somewhere inside the loop.")],
  ws=dict(title="Programming fundamentals: variables and constructs",
    objectives=["know what variables and constants are, and how a value is assigned to each",
                "understand how input and output move data in and out of a program",
                "know what sequence, selection and iteration each do to the order a program runs in"],
    starter="A program asks a pupil for their name and three test marks, then outputs their average. Write down every variable the program needs, and one value that would be better as a constant.", starter_lines=3,
    keyterms=["Assignment", "Count-controlled iteration"], keyq="How does a program store data, and how does it decide which line to run next?",
    exam=[("State the difference between a variable and a constant.", 2, 2),
          ("Describe the difference between count-controlled and condition-controlled iteration. Give an example of when each would be used.", 4, 4),
          ("A program asks for a password and keeps asking until the correct one is entered. Write an algorithm to do this, using the OCR Exam Reference Language or a language you know.", 5, 6)],
    confidence=["The difference between a variable and a constant", "How input and output work, and why input must be cast", "Sequence, selection and count- and condition-controlled iteration"]))

L2 = dict(id="pf-l02", topic="2.2", lesson=2, title="Type foundry", img="PF_L02_TypeFoundry_360",
  description="In the type foundry: the five data types, how values are cast between them, and the operators that do the work.",
  kicker=f"{K22}  |  Lesson 2", scene_title="Type foundry", subtitle=SUB22,
  intro="Every value poured out of this foundry has a data type stamped on it, and that stamp decides what the program may do with it. Learn the five types, how to recast one into another, and the operators that combine them.",
  keywords=["Data type", "Integer", "Real", "Boolean", "Casting", "MOD", "DIV", "Concatenation"],
  stations=[
   dict(name="Data types", bullets=["An integer is a whole number, positive or negative, with no decimal part. A real holds a number with a decimal part.",
        "A Boolean holds only True or False.",
        "A character is one single symbol; a string is a sequence of characters, and may be empty."],
        challenge="Choose a data type for a pupil's name, their age, their average mark and whether they are present.",
        ill=("table", ["Data type", "Example"], [["Integer", "14"], ["Real", "9.75"], ["Boolean", "True"], ["Character", "A"], ["String", "Year 10"]]),
        fact="A real number is different from an integer because...",
        tasks=[mcq("Which data type should store the price 4.99?", "Real",
                   ["Integer", "Boolean", "Character"],
                   "A real number can hold a decimal part, and an integer cannot."),
               mcq("Which data type can hold only two possible values?", "Boolean",
                   ["Character", "Integer", "String"],
                   "A Boolean is either True or False, and nothing else.")]),
   dict(name="Casting", bullets=["Casting converts a value from one data type to another.",
        "In the OCR Exam Reference Language int() casts to an integer, float() to a real, str() to a string and bool() to a Boolean.",
        "Casting is needed because input() always returns a string, and strings cannot be used in arithmetic."],
        challenge="Explain why a program that adds up marks must cast each input before it adds it to the total.",
        ill=("code", ['age = input("Age: ")', "age = int(age)", "print(age + 1)"], 26, [1]),
        fact="Casting is...",
        tasks=[mcq("What does casting mean?", "Converting a value from one data type to another",
                   ["Rounding a number to the nearest whole number", "Giving a variable a new name", "Copying a value into a constant"],
                   "The data type changes. Casting is not the same thing as rounding."),
               mcq("What is the value of  int(\"25\") + 5 ?", "30",
                   ["\"255\"", "\"25\" + 5", "An error, because you cannot add to a string"],
                   "int() turns the string \"25\" into the number 25, so ordinary arithmetic then works.")]),
   dict(name="Arithmetic operators", bullets=["The arithmetic operators are + to add, - to subtract, * to multiply and / to divide.",
        "In the OCR Exam Reference Language the exponent operator is ^, so 3 ^ 2 means 3 to the power 2, which is 9.",
        "The usual order of operations applies: brackets, then exponents, then multiply and divide, then add and subtract."],
        challenge="Work out 3 + 4 * 2 and explain the order you used to get your answer.",
        ill=("table", ["Operator", "Meaning", "Example"], [["+", "Add", "7 + 2 = 9"], ["-", "Subtract", "7 - 2 = 5"],
             ["*", "Multiply", "7 * 2 = 14"], ["/", "Divide", "8 / 2 = 4"], ["^", "Exponent", "3 ^ 2 = 9"]]),
        fact="The exponent operator...",
        tasks=[mcq("In the OCR Exam Reference Language, what is the value of  5 ^ 2 ?", "25",
                   ["10", "7", "52"],
                   "The exponent operator raises 5 to the power 2, so the answer is 5 x 5."),
               mcq("What is the value of  2 + 3 * 4 ?", "14",
                   ["20", "24", "9"],
                   "Multiplication happens before addition, so 3 * 4 is worked out first.")]),
   dict(name="MOD and DIV", bullets=["DIV gives the whole number part of a division and throws the remainder away, so 17 DIV 5 is 3.",
        "MOD gives the remainder left after a whole number division, so 17 MOD 5 is 2.",
        "MOD 2 is a quick test for an even number, because an even number always leaves a remainder of 0."],
        challenge="Use MOD and DIV to turn 95 seconds into a number of whole minutes and a number of seconds left over.",
        ill=("table", ["Expression", "Result"], [["17 DIV 5", "3"], ["17 MOD 5", "2"], ["20 DIV 6", "3"], ["20 MOD 6", "2"], ["9 MOD 2", "1"]]),
        fact="MOD gives... DIV gives...",
        tasks=[mcq("What is the value of  23 MOD 4 ?", "3",
                   ["5", "4", "19"],
                   "4 goes into 23 five times with 3 left over, and MOD gives that remainder."),
               mcq("What is the value of  23 DIV 4 ?", "5",
                   ["3", "5.75", "6"],
                   "DIV gives only the whole number of times 4 goes into 23 and ignores the remainder.")]),
   dict(name="Comparison and Boolean operators", bullets=["The comparison operators are ==, !=, <, >, <= and >=, and each one gives True or False.",
        "AND is True only when both conditions are True. OR is True when at least one condition is True.",
        "NOT reverses a condition, so NOT True gives False."],
        challenge="Write a condition that is True only when a mark is between 40 and 69, including both ends.",
        ill=("table", ["A", "B", "A AND B", "A OR B"], [["False", "False", "False", "False"], ["False", "True", "False", "True"],
             ["True", "False", "False", "True"], ["True", "True", "True", "True"]]),
        fact="AND is True only when...",
        tasks=[mcq("age = 15. What is the result of  age >= 13 AND age <= 19 ?", "True",
                   ["False", "15", "An error, because two conditions cannot be tested at once"],
                   "Both conditions are True, and AND needs both sides to be True."),
               mcq("day = \"Sat\". What is the result of  day == \"Sat\" OR day == \"Sun\" ?", "True",
                   ["False", "Sat", "An error, because OR only works with numbers"],
                   "OR needs only one side to be True, and the first comparison is True.")]),
   dict(name="String manipulation", bullets=["The length of a string is the number of characters in it, counting spaces.",
        "A substring is a part of a string, taken from a given position. Concatenation joins strings together using +.",
        "In the OCR Exam Reference Language name.length, name.substring(0, 3), name.upper and name.lower do this work, and ASC() and CHR() convert between a character and its ASCII code."],
        challenge="Describe how you would build a username from the first three letters of a surname and a pupil's year group.",
        ill=("code", ['name = "Hazel"', "print(name.length)", "print(name.substring(0, 3))", "print(name.upper)"], 24),
        fact="Concatenation means...",
        tasks=[mcq("name = \"Hazel\". In the OCR Exam Reference Language, what does  name.substring(0, 3)  give?", "Haz",
                   ["Hazel", "aze", "zel"],
                   "It starts at position 0, the first character, and takes three characters from there."),
               mcq("In the OCR Exam Reference Language, ASC(\"A\") returns 65. What does  CHR(66)  return?", "The character B",
                   ["The character A", "The number 66", "The number 67"],
                   "CHR converts an ASCII code back into a character, and 66 is one more than the code for A.")]),
  ],
  final=dict(name="Final challenge: work it out", floor_title="Final challenge: six expressions",
    intro="Six expressions written in the OCR Exam Reference Language. Tap the star, work each one out on paper, then match it to its value.",
    ill=("big", "19 MOD 5", "The remainder after a whole number division. Five goes into nineteen three times, leaving four."),
    tasks=[match("Match each expression to its value.", [["19 MOD 5", "4"], ["19 DIV 5", "3"], ["4 ^ 2", "16"],
            ["int(\"8\") + 2", "10"], ["\"Py\" + \"thon\"", "Python"], ["\"Hazel\".length", "5"]],
            "MOD and DIV are the two most often muddled: DIV is how many times it goes in, MOD is what is left over."),
      mcq("Which expression gives the remainder when 30 is divided by 7?", "30 MOD 7",
          ["30 DIV 7", "30 / 7", "30 ^ 7"],
          "MOD gives the remainder, which here is 2, because 7 goes into 30 four times with 2 left over.")]),
  info=[(0, "Why types matter", "Choosing the right data type saves memory and prevents errors. A Boolean needs only one bit of information, while storing the same yes or no as a string needs a byte for every character."),
        (1, "Casting can lose data", "Casting a real number to an integer throws the decimal part away rather than rounding it, so 4.9 becomes 4. If you need rounding, use a rounding function instead of a cast."),
        (2, "Integer division", "Dividing with / can give an answer with a decimal part even when both numbers are whole. That is exactly why DIV exists: it keeps the answer a whole number."),
        (3, "MOD in the real world", "MOD is how programs wrap around. hours MOD 24 keeps a clock in range, and index MOD listLength cycles through a list for ever without ever running off the end."),
        (4, "Short circuits", "Many languages stop evaluating an AND as soon as one side is found to be False, because the final answer cannot change. This is called short-circuit evaluation and it saves time."),
        (5, "ASCII", "ASCII gives every character a number: capital A is 65, lower case a is 97 and the digit 0 is 48. Because the codes run in order, the gap between a capital and its lower case letter is always 32.")],
  ws=dict(title="Programming fundamentals: data types and operators",
    objectives=["know the data types integer, real, Boolean, character and string",
                "understand why casting is needed and how a value is cast from one type to another",
                "know how the arithmetic, comparison and Boolean operators are used"],
    starter="A school report stores a pupil's name, their average mark to one decimal place, their form group, and whether they have full attendance. Write down the most suitable data type for each one.", starter_lines=4,
    keyterms=["Casting", "Concatenation"], keyq="Why does a program need to know what type of data it is working with?",
    exam=[("Identify the most suitable data type for each of these values: 17, 3.5, True, \"Year 10\".", 4, 4),
          ("Explain why casting is needed when a program inputs a number and adds it to a running total.", 3, 3),
          ("A program stores a length of time in seconds. Describe how MOD and DIV could be used to output that time in whole minutes and remaining seconds.", 4, 4)],
    confidence=["The five data types and when to use each one", "What casting is and why input() makes it necessary", "MOD, DIV and the Boolean operators AND, OR and NOT"]))

L3 = dict(id="pf-l03", topic="2.2", lesson=3, title="Filing room", img="PF_L03_FilingRoom_360",
  description="In the filing room: why a program needs files at all, and how it opens, reads, writes, appends and closes them.",
  kicker=f"{K22}  |  Lesson 3", scene_title="Filing room", subtitle=SUB22,
  intro="Everything in the variable store vanishes the moment a program stops. This room is where data is kept instead, so it is still there tomorrow. Learn the four operations every program performs on a file.",
  keywords=["File handling", "Persistence", "Open", "Read", "Write", "Append", "Close"],
  stations=[
   dict(name="Why files", bullets=["Data held in variables is lost as soon as the program stops, because variables are held in RAM.",
        "Writing data to a file stores it on secondary storage, so it is still there the next time the program runs.",
        "Files also let the output of one program become the input of another."],
        challenge="Give two things a game should save to a file, and say what would happen if it did not.",
        ill=("compare", "In a variable", ["Held in RAM", "Lost when the program ends", "Very fast to use"],
             "In a file", ["Held on secondary storage", "Still there next time", "Can be shared"], "r", "g"),
        fact="A file is needed because...",
        tasks=[mcq("Why does a program write data to a file?", "So the data is still there after the program has stopped running",
                   ["So the data can be used inside a loop", "So the data takes up less memory", "So the data is automatically encrypted"],
                   "Variables live in RAM and are lost; a file persists on secondary storage."),
               mcq("A quiz program keeps its high scores in variables only. What happens when the program closes?", "The high scores are lost",
                   ["The high scores are moved to the hard disk automatically", "The high scores become constants", "The high scores are output to the screen"],
                   "Nothing in RAM survives the program ending unless it has been saved to a file.")]),
   dict(name="Opening a file", bullets=["A file must be opened before a program can read from it or write to it.",
        "Opening a file gives the program a handle: a name it uses to refer to that file from then on.",
        "In the OCR Exam Reference Language, newFile(\"scores.txt\") creates a new file and openRead(\"scores.txt\") opens one that already exists."],
        challenge="Explain what could go wrong if a program tries to open a file that does not exist.",
        ill=("code", ['newFile("scores.txt")', 'myFile = openRead("scores.txt")', "myFile.close()"], 26, [1]),
        fact="Opening a file means...",
        tasks=[mcq("Why must a file be opened before it is used?", "The program needs a link to the file on secondary storage before it can read or write",
                   ["Files are encrypted until they are opened", "Opening a file empties it ready for new data", "Opening a file casts its contents to a string"],
                   "Open sets up the connection; read and write then use that connection."),
               mcq("In the OCR Exam Reference Language, what does  newFile(\"log.txt\")  do?", "Creates a new file called log.txt",
                   ["Opens log.txt ready for reading", "Deletes log.txt", "Reads the first line of log.txt"],
                   "newFile makes the file; openRead or openWrite is then used to work with it.")]),
   dict(name="Reading a file", bullets=["Reading copies data from the file into the program, usually one line at a time.",
        "A condition-controlled loop reads line by line until the end of the file is reached.",
        "In the OCR Exam Reference Language, readLine() gets the next line and endOfFile() becomes True when there are no lines left."],
        challenge="Explain why a program reads a file one line at a time rather than all at once.",
        ill=("code", ['myFile = openRead("scores.txt")', "while NOT myFile.endOfFile()", "  print(myFile.readLine())", "endwhile", "myFile.close()"], 24, [1]),
        fact="Reading a file line by line means...",
        tasks=[mcq("What does endOfFile() give once every line has been read?", "True",
                   ["False", "The last line of the file", "The number of lines in the file"],
                   "The loop carries on while endOfFile() is False, and stops the moment it becomes True."),
               mcq("What does readLine() do each time it is called?", "Reads the next line of the file",
                   ["Reads the whole file in one go", "Reads the first line again", "Writes a new line to the file"],
                   "Each call moves one line further on, which is why it works inside a loop.")]),
   dict(name="Writing to a file", bullets=["Writing copies data out of the program and into the file, so it is saved on secondary storage.",
        "In Python 3, open(\"scores.txt\", \"w\") opens a file for writing and deletes anything that was already in it.",
        "Data written to a file is not safe until the file has been closed."],
        challenge="A program saves the high score using mode \"w\" every time it runs. Explain the problem this causes.",
        ill=("code", ['f = open("scores.txt", "w")', 'f.write("Hazel,120\\n")', "f.close()"], 26, [0]),
        fact="Writing to a file means...",
        tasks=[mcq("In Python 3, what happens to data already in a file when it is opened with mode \"w\"?", "It is deleted",
                   ["It is kept, and the new data is added at the end", "It is kept, and the new data is added at the start", "It is copied into a backup file first"],
                   "Mode \"w\" starts the file again from empty, so use mode \"a\" when the old data must be kept."),
               mcq("A program uses print() where it should have used write(). What happens to the data?", "It goes to the screen instead of into the file",
                   ["It goes into the file as well as onto the screen", "It is added to the end of the file", "The program stops with a syntax error"],
                   "print() is output to the screen; write() is output to a file.")]),
   dict(name="Appending", bullets=["Appending adds new data to the end of a file and keeps everything that was already there.",
        "In Python 3, open(\"log.txt\", \"a\") opens a file in append mode.",
        "Appending suits a log or a high score table, where the old records must not be lost."],
        challenge="Explain which mode a program should use to add a new score to a file of past scores, and why.",
        ill=("compare", "Write mode \"w\"", ["Starts the file again", "Old data is lost", "Use for a fresh file"],
             "Append mode \"a\"", ["Adds to the end", "Old data is kept", "Use for a log"], "r", "g"),
        fact="Appending is different from writing because...",
        tasks=[mcq("A program must add today's score to a file of past scores. Which Python 3 mode should it use?", "\"a\"",
                   ["\"w\"", "\"r\"", "\"n\""],
                   "Append mode adds to the end, while write mode would wipe every past score."),
               mcq("Where does appended data go in the file?", "At the end, after the data that is already there",
                   ["At the start, before the data that is already there", "In place of the data that is already there", "Into a second, new file"],
                   "That is why a log file read from top to bottom comes out in date order.")]),
   dict(name="Closing the file", bullets=["Closing a file tells the operating system that the program has finished with it.",
        "Data written to a file may still be waiting in a buffer in memory, and closing the file makes sure it reaches the disk.",
        "A file left open can stop other programs using it, and wastes memory."],
        challenge="Describe two problems that could happen if a program never closed the files it opened.",
        ill=("flow", ["Open the file", "Read or write", "Close the file"]),
        fact="Closing a file is important because...",
        tasks=[mcq("What is the main reason a program closes a file after writing to it?", "To make sure everything still in the buffer is written to the file",
                   ["To delete the file from the disk", "To make the file read-only", "To free up space on the hard disk"],
                   "Until the file is closed, the last data written may never have left memory."),
               mcq("Which is the correct order of operations on a file?", "Open, read or write, close",
                   ["Read or write, open, close", "Open, close, read or write", "Close, open, read or write"],
                   "Nothing can be read or written until the file is open, and nothing is safe until it is closed.")]),
  ],
  final=dict(name="Final challenge: read the file", floor_title="Final challenge: build the file reader",
    intro="Five lines of the OCR Exam Reference Language, jumbled. Tap the star and put them into a working program that outputs every line of scores.txt.",
    ill=("flow", ["Open", "Check end of file", "Read a line", "Close"]),
    tasks=[order("Put these lines into a working program that reads and outputs every line of scores.txt.",
            ['myFile = openRead("scores.txt")', "while NOT myFile.endOfFile()", "  print(myFile.readLine())", "endwhile", "myFile.close()"],
            "Open, loop while there is still something to read, then close. Forget the close and the file stays locked."),
      mcq("Why does the loop check endOfFile() before it reads a line?", "Trying to read past the last line would cause an error",
          ["It makes the program run faster", "It closes the file automatically", "It casts each line to an integer"],
          "The check stops the program trying to read a line that is not there.")]),
  info=[(0, "RAM is volatile", "RAM loses everything in it when the power goes, which is why it is called volatile. Secondary storage such as an SSD keeps data without power, and that is where files live."),
        (1, "File paths", "A file name on its own means a file in the same folder as the program. A longer path tells the operating system exactly where to look, which is why a program that works on one computer may not find its file on another."),
        (2, "CSV files", "A comma separated values file puts one record on each line, with commas between the fields. Reading it line by line and splitting each line at the commas is how most simple data files are loaded."),
        (3, "Text or binary", "A text file stores characters you could read in a text editor. A binary file stores the raw bytes of an image or a sound, which look like nonsense if you open them as text."),
        (4, "Logs", "Almost every system you use keeps an append-only log of what happened and when. Because nothing is ever overwritten, the log can be read afterwards to work out what went wrong."),
        (5, "Lost data", "If a program crashes before closing a file, the last data written can vanish because it never left the buffer. That is one reason programs save as they go rather than only at the very end.")],
  ws=dict(title="Programming fundamentals: file handling",
    objectives=["know why a program needs to store data in a file",
                "understand how a file is opened, read from, written to and closed",
                "know the difference between writing to a file and appending to it"],
    starter="A quiz game keeps a table of high scores. Explain what happens to those scores when the player closes the game, if the program stores them in variables only.", starter_lines=3,
    keyterms=["File handling", "Append"], keyq="How does a program keep hold of data after it has stopped running?",
    exam=[("State one reason why a program writes data to a file rather than keeping it in a variable.", 2, 2),
          ("Describe the four operations a program carries out on a file, in the order they happen.", 4, 4),
          ("A program records every login in a file called log.txt. Explain why the file should be opened in append mode rather than write mode.", 3, 3)],
    confidence=["Why a file is needed at all", "How to open, read, write and close a file", "The difference between writing to a file and appending to it"]))

L4 = dict(id="pf-l04", topic="2.2", lesson=4, title="Record vault", img="PF_L04_RecordVault_360",
  description="In the record vault: how a table of records holds related data, and how SQL asks it questions.",
  kicker=f"{K22}  |  Lesson 4", scene_title="Record vault", subtitle=SUB22,
  intro="Every packet in this community seed library has its own row in a table, and that row is called a record. Learn how a record is built from fields, then learn the language that pulls the records you want back out.",
  keywords=["Record", "Field", "Table", "SQL", "SELECT", "FROM", "WHERE", "Wildcard"],
  stations=[
   dict(name="What is a record", bullets=["A record is one row of related data about a single thing, such as one packet of seed in the library.",
        "The separate pieces of data inside a record are called fields, and each field has its own name.",
        "A table is a set of records that all have exactly the same fields."],
        challenge="Describe the record this seed library would store about one packet of radish seed.",
        ill=("table", ["SeedID", "Name", "Family", "PacketsLeft"], [["1", "Sunflower", "Daisy", "12"], ["2", "Runner Bean", "Legume", "3"],
             ["3", "Radish", "Cabbage", "24"], ["4", "Basil", "Mint", "0"], ["5", "Sweet Pea", "Legume", "7"]]),
        fact="A record is...",
        tasks=[mcq("What is a record?", "One row of related data about a single thing",
                   ["A single piece of data, such as a name", "A whole table of data", "The data type given to a field"],
                   "One packet of seed, one record. The pieces inside it are the fields."),
               mcq("The library stores Name, Family and PacketsLeft about each packet. What is Family?", "A field",
                   ["A record", "A table", "A query"],
                   "A field is one named piece of data; the record is the whole row it sits in.")]),
   dict(name="Fields and data types", bullets=["Every field is given a data type, and only data of that type may be stored in it.",
        "SeedID and PacketsLeft hold whole numbers, so they are integers. Name and Family hold characters, so they hold text.",
        "Fields in the same record can be different data types, which is why a record is more useful than an array."],
        challenge="The library wants to record whether each packet is organic. Choose a data type for that field and say why.",
        ill=("table", ["Field", "Data type", "Example"], [["SeedID", "Integer", "3"], ["Name", "Text", "Radish"],
             ["Family", "Text", "Cabbage"], ["PacketsLeft", "Integer", "24"], ["Organic", "Boolean", "False"]]),
        fact="Each field in a record...",
        tasks=[mcq("A field called Organic stores only True or False. What data type is it?", "Boolean",
                   ["Integer", "Text", "Real"],
                   "A Boolean has only two possible values, so it is the smallest and safest choice here."),
               mcq("Why is every field given a data type?", "So only sensible data of the right kind can be stored in it",
                   ["So the records can be put into alphabetical order", "So the table needs fewer fields", "So the table can be printed"],
                   "The data type is a rule: text cannot be typed into an integer field.")]),
   dict(name="SELECT and FROM", bullets=["SQL, the structured query language, is used to search a table of records.",
        "SELECT lists the fields you want back. FROM names the table they are taken from.",
        "SELECT * means every field in the record, and a query with no condition returns every record in the table."],
        challenge="Write an SQL query that returns just the name and family of every seed in the library.",
        ill=("stack", [("SELECT", "which fields to return", "g"), ("FROM", "which table to look in", "b"), ("WHERE", "which records to keep", "y")]),
        fact="SELECT names... FROM names...",
        tasks=[mcq("What does  SELECT * FROM Seeds;  return?", "Every field of every record in the Seeds table",
                   ["Only the first record in the Seeds table", "Only the fields whose names begin with S", "The number of records in the Seeds table"],
                   "The star is a shorthand for all the fields, and with no WHERE nothing is filtered out."),
               mcq("What job does FROM do in a query?", "It names the table the data is taken from",
                   ["It lists the fields to return", "It sets a condition the records must meet", "It puts the results into order"],
                   "SELECT chooses the columns, FROM chooses the table and WHERE chooses the rows.")]),
   dict(name="WHERE", bullets=["WHERE sets a condition, and only records where that condition is True are returned.",
        "Conditions use =, <>, <, >, <= and >=. A piece of text is written inside single quotes.",
        "In this table,  SELECT Name FROM Seeds WHERE Family = 'Legume';  returns Runner Bean and Sweet Pea."],
        challenge="Write an SQL query that returns the name of every seed with fewer than five packets left.",
        ill=("code", ["SELECT Name, PacketsLeft", "FROM Seeds", "WHERE PacketsLeft < 5;"], 26, [2]),
        fact="WHERE is used to...",
        tasks=[mcq("Using the Seeds table, which records does  WHERE PacketsLeft < 5  return?", "Runner Bean and Basil",
                   ["Basil only", "Radish and Sunflower", "Every record in the table"],
                   "Runner Bean has 3 packets and Basil has 0, and both of those are below 5."),
               mcq("How is a piece of text written inside a WHERE condition?", "Inside single quotes, such as 'Legume'",
                   ["Inside round brackets, such as (Legume)", "With no punctuation at all, such as Legume", "Inside a pair of hashes, such as #Legume#"],
                   "The quotes tell the database it is a value to compare, not the name of a field.")]),
   dict(name="Boolean operators", bullets=["AND returns a record only when both of its conditions are True.",
        "OR returns a record when at least one of its conditions is True.",
        "NOT reverses a condition, so  NOT Family = 'Legume'  returns every record that is not a legume."],
        challenge="Write a query that returns every legume with more than five packets left, then say how many records it gives.",
        ill=("code", ["SELECT Name FROM Seeds", "WHERE Family = 'Legume'", "AND PacketsLeft > 5;"], 26, [2]),
        fact="AND returns a record only when...",
        tasks=[mcq("Using the Seeds table, which seeds does  WHERE Family = 'Legume' AND PacketsLeft > 5  return?", "Sweet Pea only",
                   ["Runner Bean only", "Runner Bean and Sweet Pea", "No records at all"],
                   "Both legumes pass the first test, but Runner Bean has only 3 packets, so AND rules it out."),
               mcq("Which operator returns a record when at least one of two conditions is True?", "OR",
                   ["AND", "NOT", "LIKE"],
                   "AND needs both sides to be True; OR needs only one of them.")]),
   dict(name="LIKE and wildcards", bullets=["LIKE searches a text field for a pattern instead of an exact match.",
        "The % wildcard stands for any number of characters, including none. The _ wildcard stands for exactly one character.",
        "So  WHERE Name LIKE 'S%'  means the name must begin with S and may be followed by anything."],
        challenge="Write a query that returns every seed whose name contains the word Pea, wherever it appears in the name.",
        ill=("table", ["Pattern", "Records returned"], [["'S%'", "Sunflower, Sweet Pea"], ["'%Pea%'", "Sweet Pea"],
             ["'R_dish'", "Radish"], ["'%n'", "Runner Bean"]]),
        fact="The % wildcard stands for...",
        tasks=[mcq("What does the % wildcard stand for in a LIKE pattern?", "Any number of characters, including none",
                   ["Exactly one character", "Any digit from 0 to 9", "A single space"],
                   "The underscore is the one that stands for exactly one character."),
               mcq("Using the Seeds table, which names does  WHERE Name LIKE 'S%'  return?", "Sunflower and Sweet Pea",
                   ["Sunflower only", "Radish and Basil", "Every name that contains the letter s"],
                   "The pattern anchors the S to the start, so Radish is not returned even though it contains an s.")]),
  ],
  final=dict(name="Final challenge: run the query", floor_title="Final challenge: six queries, six answers",
    intro="Six queries on the Seeds table, all beginning SELECT Name FROM Seeds. Tap the star, work through the table row by row, then match each WHERE line to the records it returns.",
    ill=("big", "LIKE 'S%'", "A pattern, not an exact match. The per cent sign stands for any number of characters, so this finds every name that begins with S."),
    tasks=[match("Match each WHERE line to the records it returns.", [["WHERE PacketsLeft = 0", "Basil"],
            ["WHERE PacketsLeft > 20", "Radish"], ["WHERE Family = 'Legume'", "Runner Bean, Sweet Pea"],
            ["WHERE NOT Family = 'Legume'", "Sunflower, Radish, Basil"], ["WHERE Name LIKE 'S%'", "Sunflower, Sweet Pea"],
            ["WHERE Name LIKE '%Pea%'", "Sweet Pea"]],
            "Take one record at a time and ask whether the condition is True for it. If it is, the record is returned."),
      mcq("Which query would find every seed whose name ends in the letter n?", "SELECT Name FROM Seeds WHERE Name LIKE '%n';",
          ["SELECT Name FROM Seeds WHERE Name LIKE 'n%';", "SELECT Name FROM Seeds WHERE Name = 'n';", "SELECT Name FROM Seeds WHERE Name LIKE '_n';"],
          "Put the % before the letter and the pattern means anything, then n at the very end.")]),
  info=[(0, "Why not one big list", "A table of records keeps related data together, so one row can be added, changed or deleted without disturbing any other. Storing the same data as separate lists of names and separate lists of numbers makes it far too easy for the lists to drift out of step."),
        (1, "Primary keys", "A field like SeedID that is different for every record is called a primary key. It matters because two packets could easily share a name, but a key is guaranteed to pick out exactly one record."),
        (2, "SQL is everywhere", "The same SELECT, FROM and WHERE are used by almost every database in the world, from a school register to an airline booking system. Learning them once means you can query any of them."),
        (3, "The order the lines go in", "SQL is read by the database in a fixed order: find the table named in FROM, keep only the records that satisfy WHERE, then return the fields listed in SELECT. Knowing that order explains why a query that returns nothing usually has a problem in its WHERE line."),
        (4, "One letter apart", "Swapping AND for OR normally changes how many records come back, and OR almost always returns more. If a query gives too many results, an OR that should have been an AND is the first thing to check."),
        (5, "Searching as you type", "When a website suggests results while you are still typing, it is usually running a LIKE query with a % on the end of whatever you have typed so far.")],
  ws=dict(title="Programming fundamentals: records and SQL",
    objectives=["know what is meant by a record, a field and a table of records",
                "understand how SELECT, FROM and WHERE are used to search for data",
                "know how AND, OR, NOT and LIKE narrow a search down"],
    starter="A community seed library stores the name, the plant family and the number of packets left for each type of seed. Write down the fields one record would need, and the most suitable data type for each field.", starter_lines=4,
    keyterms=["Record", "Wildcard"], keyq="How does a program store a set of related data, and how does it search it?",
    exam=[("State what is meant by a record and what is meant by a field.", 2, 2),
          ("A table called Seeds has the fields SeedID, Name, Family and PacketsLeft. Write an SQL query that returns the name of every seed with fewer than five packets left.", 3, 3),
          ("Explain the difference between using AND and using OR in the WHERE line of a query. Use an example of each in your answer.", 4, 4)],
    confidence=["What a record, a field and a table are", "How SELECT, FROM and WHERE build a query", "How AND, OR, NOT and the wildcards % and _ are used"]))

L5 = dict(id="pf-l05", topic="2.2", lesson=5, title="Array yard", img="PF_L05_ArrayYard_360",
  description="Out in the array yard: numbered crates in rows and bays, and the sub-programs that work on them.",
  kicker=f"{K22}  |  Lesson 5", scene_title="Array yard", subtitle=SUB22,
  intro="Five crates stand in a line here, and every one of them is numbered rather than named. Learn how an array holds many values under one name, then learn to write sub-programs that do the work on them.",
  keywords=["Array", "Element", "Index", "Zero-indexing", "Sub-program", "Procedure", "Function", "Parameter"],
  stations=[
   dict(name="One-dimensional arrays", bullets=["An array stores many values of the same data type under a single name, instead of a separate variable for each one.",
        "In the OCR Exam Reference Language,  array crate[5]  declares an array with five elements.",
        "An array is given its size when it is declared and keeps it; a list in Python can grow and shrink as the program runs."],
        challenge="Explain why one array is better than five separate variables for storing five crate weights.",
        ill=("code", ["array crate[5]", "crate[0] = 14", "crate[1] = 9", "print(crate[0])"], 26, [0]),
        fact="An array is...",
        tasks=[mcq("In the OCR Exam Reference Language, what does  array crate[5]  declare?", "An array with five elements",
                   ["An array with six elements", "A variable holding the number 5", "Five separate arrays"],
                   "The number in the brackets is how many elements there are, and they are numbered 0 to 4."),
               mcq("What is the main advantage of using one array instead of ten separate variables?", "One name and a loop can handle all ten values",
                   ["An array uses no memory at all", "Each value in an array can be given its own name", "An array does not have to be declared first"],
                   "Ten variables need ten lines of code for every job; an array needs one loop.")]),
   dict(name="Index positions", bullets=["Each element has an index, which is its position in the array. OCR arrays begin at index 0, which is called zero-indexing.",
        "So the first element of  array crate[5]  is crate[0] and the last is crate[4]. Asking for crate[5] goes past the end and causes an error.",
        "An element is changed by naming its index:  crate[2] = 7  replaces whatever was already in position 2. A count-controlled loop iterates over the whole array."],
        challenge="An array holds eight marks. Give the index of the first mark and the index of the last.",
        ill=("code", ["array crate[5]", "for i = 0 to 4", "  print(crate[i])", "next i"], 26, [1]),
        fact="Zero-indexing means...",
        tasks=[mcq("Using zero-indexing, what is the index of the last element of  array crate[5] ?", "4",
                   ["5", "1", "0"],
                   "There are five elements and the first is numbered 0, so the last is numbered 4."),
               mcq("crate[2] holds 31. What does  crate[2] = 7  do?", "It replaces the 31 with 7",
                   ["It adds 7 to the end of the array", "It adds 7 to 31, giving 38", "It creates a new array with seven elements"],
                   "A single equals sign assigns, so the old value in that position is overwritten and lost.")]),
   dict(name="Two-dimensional arrays", bullets=["A two-dimensional array is a table of values with rows and columns. In the OCR Exam Reference Language,  array bay[3,4]  declares 3 rows of 4.",
        "An element needs two indices, the row first and then the column, so bay[0,0] is the top left corner.",
        "Two nested loops iterate over it: the outer loop moves down the rows and the inner loop across the columns."],
        challenge="A noughts and crosses board is stored as  array board[3,3].  Give the two indices of the centre square.",
        ill=("table", ["Row", "Column 0", "Column 1"], [["0", "bay[0,0]", "bay[0,1]"], ["1", "bay[1,0]", "bay[1,1]"], ["2", "bay[2,0]", "bay[2,1]"]]),
        fact="A two-dimensional array is...",
        tasks=[mcq("In the OCR Exam Reference Language, what does  array bay[3,4]  declare?", "A two-dimensional array of 3 rows and 4 columns",
                   ["A one-dimensional array of 34 elements", "Two arrays, one with 3 elements and one with 4", "An array of 3 elements that each hold 4 arrays"],
                   "The first number is the number of rows and the second the number of columns, so there are 12 elements in all."),
               mcq("Which element is the centre square of  array board[3,3] ?", "board[1,1]",
                   ["board[2,2]", "board[0,0]", "board[1,2]"],
                   "With zero-indexing the middle row is row 1 and the middle column is column 1.")]),
   dict(name="Procedures and functions", bullets=["A sub-program is a named block of code that the main program can call, as many times as it needs, without the code being written out again.",
        "A procedure carries out a task but returns no value. In the OCR Exam Reference Language it runs from procedure to endprocedure.",
        "A function always returns a value to the line that called it, using return, and runs from function to endfunction."],
        challenge="Decide whether printing a welcome banner and working out an average should each be a procedure or a function, and say why.",
        ill=("compare", "Procedure", ["procedure ... endprocedure", "Carries out a task", "Returns no value", "Called as  greet(\"Hazel\")"],
             "Function", ["function ... endfunction", "Works out a value", "Sends it back with return", "Called as  x = double(5)"], "b", "g"),
        fact="A procedure... A function...",
        tasks=[mcq("What is the difference between a procedure and a function?", "A function returns a value to the code that called it, and a procedure does not",
                   ["A procedure may be called many times, and a function only once", "A function must be written inside a loop, and a procedure must not", "A procedure may be given parameters, and a function may not"],
                   "Both are sub-programs and both can take parameters. The return value is the only difference."),
               mcq("A sub-program works out the area of a rectangle so the answer can be used in a later calculation. Which should it be?", "A function",
                   ["A procedure", "A constant", "A global variable"],
                   "The answer has to come back to the line that called it, and only a function returns a value.")]),
   dict(name="Parameters and returns", bullets=["A parameter is a variable in the sub-program's definition that receives a value when the sub-program is called.",
        "Parameters let the same sub-program work on different data every time, so it does not have to be rewritten.",
        "return sends one value back to the calling line and ends the function straight away."],
        challenge="Write a function in the OCR Exam Reference Language that takes two marks as parameters and returns their average.",
        ill=("code", ["function average(a, b)", "  return (a + b) / 2", "endfunction", "print(average(12, 18))"], 24, [1]),
        fact="A parameter is...",
        tasks=[mcq("In  function average(a, b),  what are a and b?", "Parameters",
                   ["Return values", "Global variables", "Constants"],
                   "They are named in the definition and given their values when the function is called."),
               mcq("A function is defined as  function average(a, b) return (a + b) / 2 endfunction.  What does  print(average(12, 18))  output?", "15",
                   ["30", "21", "12 18"],
                   "12 and 18 are passed in and added to make 30, and the brackets make sure that happens before the divide.")]),
   dict(name="Local and global", bullets=["A local variable is declared inside a sub-program and only exists while that sub-program is running. Nothing outside it can see the variable.",
        "A global variable can be used anywhere in the program. In the OCR Exam Reference Language it is declared with the keyword global.",
        "Local variables are safer, because two sub-programs can use the same name without clashing and the memory is freed when the sub-program ends."],
        challenge="Give one advantage and one disadvantage of making a player's score a global variable.",
        ill=("compare", "Local variable", ["Declared inside a sub-program", "Only exists while it runs", "Cannot clash with other names"],
             "Global variable", ["Declared with the keyword global", "Can be used anywhere in the program", "Easy to change by accident"], "g", "r"),
        fact="A local variable... A global variable...",
        tasks=[mcq("Where can a local variable be used?", "Only inside the sub-program where it was declared",
                   ["Anywhere in the program", "Only inside loops", "Only in the main program, never in a sub-program"],
                   "The variable is created when the sub-program starts and destroyed when it ends."),
               mcq("Why do programmers use local variables wherever they can?", "Another part of the program cannot change them by mistake",
                   ["They can hold more data than a global variable", "Every sub-program can use them without being passed anything", "They do not need to be given a name"],
                   "Keeping a variable local limits the number of places a bug could have come from.")]),
  ],
  final=dict(name="Final challenge: total the crates", floor_title="Final challenge: build the array totaller",
    intro="Six lines of the OCR Exam Reference Language, jumbled. Tap the star and put them into a working program that adds up all five crate weights and outputs the total.",
    ill=("flow", ["Set total to 0", "Loop 0 to 4", "Add the element", "Output the total"]),
    tasks=[order("Put these lines into a working program that outputs the total of all five elements.",
            ["array crate[5]", "total = 0", "for i = 0 to 4", "  total = total + crate[i]", "next i", "print(total)"],
            "Declare the array, set the running total to zero before the loop, add inside the loop, then output after it."),
      mcq("Why does the loop count up to 4 rather than up to 5?", "crate[5] does not exist, because the indices run from 0 to 4",
          ["The array only holds four values", "A loop counter can never reach 5", "Counting to 5 would make the total twice as large"],
          "Five elements numbered from 0 means the last index is 4, so counting to 5 would read past the end of the array.")]),
  info=[(0, "Same type throughout", "An array holds values of one data type, which is how the computer knows exactly how much space each element needs and where each one begins. A record is the opposite: it is built to hold fields of different types."),
        (1, "Why zero", "The index is really how far an element sits from the start of the array, so the very first element is nothing at all from the start, which is zero. Reading one element is then a single calculation rather than a search."),
        (2, "Rows then columns", "Almost every language writes a two-dimensional array as row first and column second. Getting those two the wrong way round in a nested loop is one of the most common bugs in Year 11 coursework."),
        (3, "Why bother", "Sub-programs are how a large program stays understandable. Each one can be written, tested and fixed on its own, and a sub-program written once can be reused in a completely different program."),
        (4, "One way in, one way out", "A well-written function takes everything it needs through its parameters and sends everything back through its return value. That makes it possible to test the function on its own, with no other part of the program running."),
        (5, "Passing instead of sharing", "Rather than make a variable global so a sub-program can reach it, pass it in as a parameter and send the new value back. The sub-program then works anywhere, and nothing outside it can be changed by surprise.")],
  ws=dict(title="Programming fundamentals: arrays and sub-programs",
    objectives=["know how one- and two-dimensional arrays are declared, read and changed",
                "understand why arrays are zero-indexed and how a loop iterates over one",
                "know the difference between a procedure and a function, and between local and global variables"],
    starter="A program records the number of items in each of five crates. Write down why an array is a better choice than five separate variables, and write the line that would declare it.", starter_lines=3,
    keyterms=["Zero-indexing", "Sub-program"], keyq="How does one name hold many values, and how is code broken into reusable pieces?",
    exam=[("An array is declared as  array scores[6].  State the index of the first element and the index of the last element.", 2, 2),
          ("Explain the difference between a procedure and a function.", 3, 3),
          ("A program stores five crate weights in  array crate[5].  Write an algorithm that outputs the total of all five weights, using the OCR Exam Reference Language or a language you know.", 5, 6)],
    confidence=["How a one- and a two-dimensional array are declared and used", "Why arrays start at index 0, and how to loop over one", "Procedures, functions, parameters, return values and local versus global variables"]))

L6 = dict(id="pf-l06", topic="2.2", lesson=6, title="Chance machine", img="PF_L06_ChanceMachine_360",
  description="Inside the chance machine: generating a random number in a range, why the end points matter, and what pseudo-random really means.",
  kicker=f"{K22}  |  Lesson 6", scene_title="Chance machine", subtitle=SUB22,
  intro="Pull the lever on this machine and out comes a number nobody in the room can predict, not even the programmer who built it. Learn how a program generates one inside a range you choose, and why the computer is only pretending to be unpredictable.",
  keywords=["Random number", "Range", "Pseudo-random", "Seed", "Algorithm", "Simulation", "Shuffle", "Sampling"],
  stations=[
   dict(name="Why random numbers", bullets=["A random number lets a program behave differently each time it runs, so the result cannot be predicted.",
        "Games use them for dice rolls, card shuffles and where an enemy appears.",
        "Simulations, random sampling, shuffling a list and generating a password all need them too."],
        challenge="Give two reasons a dice game would be no fun if the program produced the same number every time.",
        ill=("icons", [("laptop", "Game"), ("form", "Sampling"), ("key", "Password")]),
        fact="Random numbers are used when...",
        tasks=[mcq("Why does a game use random numbers?", "So the game does not play out the same way every time",
                   ["So the game runs faster", "So the game uses less memory", "So the player's score is always worked out correctly"],
                   "Unpredictability is the whole point: the same dice roll every time would make the game pointless."),
               mcq("Which of these jobs needs a random number?", "Choosing which of twenty quiz questions is asked first",
                   ["Working out the average of six marks", "Counting how many questions a pupil answered", "Storing a pupil's name in a variable"],
                   "Only the first job needs an unpredictable choice; the other three give the same answer every time for the same data.")]),
   dict(name="Generating a random number", bullets=["In the OCR Exam Reference Language, random(1, 6) returns a random whole number from 1 to 6, and both end points are included.",
        "The value returned is normally stored in a variable, so the program can use that one number more than once.",
        "Calling the function a second time gives a fresh number, which may or may not be the same as the first."],
        challenge="Write two lines in the OCR Exam Reference Language that roll a dice and output the result.",
        ill=("code", ["dice = random(1, 6)", "print(dice)", "again = random(1, 6)", "print(again)"], 26, [0]),
        fact="In the OCR Exam Reference Language, random(1, 6) returns...",
        tasks=[mcq("In the OCR Exam Reference Language, which values can  random(1, 6)  return?", "Any whole number from 1 to 6, including 1 and 6",
                   ["Any whole number from 1 to 5", "Any whole number from 2 to 5", "Any decimal number between 1 and 6"],
                   "Both end points are included, so all six faces of the dice are possible."),
               mcq("Why is the result of  random(1, 6)  usually stored in a variable?", "So that one rolled number can be used again later in the program",
                   ["So that the user cannot change the number", "Because random(1, 6) cannot be written on its own", "Because the number would otherwise be a string"],
                   "Call the function again and you get a different number, so the first one must be kept if the program still needs it.")]),
   dict(name="Choosing the range", bullets=["The two values passed to the function set the lowest and the highest number that can be returned.",
        "In Python 3, random.randint(1, 6) can return 6, but random.randrange(1, 6) stops at 5.",
        "An array of five elements is indexed 0 to 4, so a random index must come from that range and no wider."],
        challenge="An array holds eight prize names. State the range a random index must come from, and say what would happen if the range went up to 8.",
        ill=("table", ["Python 3 call", "Lowest", "Highest"], [["random.randint(1, 6)", "1", "6"], ["random.randrange(1, 6)", "1", "5"],
             ["random.randint(0, 4)", "0", "4"], ["random.randrange(0, 5)", "0", "4"]]),
        fact="The end points of the range matter because...",
        tasks=[mcq("In Python 3, which numbers can  random.randrange(1, 6)  return?", "1, 2, 3, 4 or 5",
                   ["1, 2, 3, 4, 5 or 6", "2, 3, 4, 5 or 6", "Only 1 or 6"],
                   "randrange stops one short of its second number, while randint includes it."),
               mcq("An array of ten prizes is indexed 0 to 9. Which Python 3 call could return any one of the ten indices and never an invalid one?", "random.randint(0, 9)",
                   ["random.randint(1, 10)", "random.randint(0, 10)", "random.randrange(1, 9)"],
                   "randint includes both ends, so 0 to 9 covers all ten indices and never runs past the last element.")]),
   dict(name="Pseudo-random", bullets=["A computer cannot be truly random: it works each number out with an algorithm, so the numbers are called pseudo-random.",
        "The algorithm starts from a value called the seed, and the same seed always produces the same sequence of numbers.",
        "Most languages take the seed from the computer's clock, so the sequence is different each time the program runs."],
        challenge="Explain why a programmer testing a game might choose to set the seed to the same value every time.",
        ill=("flow", ["Seed value", "Algorithm", "Number out", "Seed for the next one"]),
        fact="Pseudo-random means...",
        tasks=[mcq("Why are the numbers a computer produces described as pseudo-random?", "They are worked out by an algorithm, so they are not truly unpredictable",
                   ["They are always the same number", "They can only ever be between 0 and 1", "They are chosen by the user rather than by the program"],
                   "An algorithm follows fixed steps, so it can only imitate randomness, however convincing the imitation looks."),
               mcq("Where does a language usually take its seed from if the programmer does not set one?", "The computer's clock",
                   ["The number of lines in the program", "The name of the file the program is saved in", "The size of the screen"],
                   "The time is different on every run, so each run starts from a different point in the sequence.")]),
   dict(name="Random in a loop", bullets=["A new number is generated every time the function is called, so a loop can produce a whole set of them.",
        "In the OCR Exam Reference Language a count-controlled loop suits a known number of values, such as ten dice rolls.",
        "Each call is independent of the last, so the same value can come up twice in a row."],
        challenge="Describe what a program would need to do to count how many sixes it rolls in one hundred dice rolls.",
        ill=("code", ["for i = 1 to 10", "  roll = random(1, 6)", "  print(roll)", "next i"], 26, [1]),
        fact="Calling a random function inside a loop...",
        tasks=[mcq("A loop calls  random(1, 6)  ten times. How many of the ten numbers could be the same?", "Any number of them, because each call is independent of the others",
                   ["None, because a random number can never repeat", "Exactly two of them", "All ten of them must be different"],
                   "Every call starts again from scratch, so nothing stops a six appearing twice, or even five times."),
               multi("A program rolls a dice ten times and counts the sixes. Which lines belong inside the loop? Select all that apply.",
                     ["Generating the next random number", "Testing whether the number is a 6", "Adding 1 to the count of sixes",
                      "Setting the count of sixes to 0", "Outputting the final count"],
                     ["Generating the next random number", "Testing whether the number is a 6", "Adding 1 to the count of sixes"],
                     "The count is set to zero once before the loop and output once after it; put either one inside and it is reset or printed on every single roll.")]),
   dict(name="Using randomness well", bullets=["A simulation uses random numbers to model something unpredictable, such as traffic or the weather, so it can be run many times.",
        "Random sampling picks members of a group at random, so the sample is fair and not chosen on purpose.",
        "A shuffle puts a list into a random order, and a password generator picks random characters."],
        challenge="Suggest how a program could pick three pupils at random from a class list without picking the same pupil twice.",
        ill=("tiles", [("Dice roll", "g"), ("Card shuffle", "b"), ("Simulation", "p"), ("Random sample", "o"), ("Password", "y"), ("Lane draw", "k")], 3),
        fact="A simulation uses random numbers to...",
        tasks=[mcq("What is a simulation?", "A program that models a real situation, using random numbers for the parts that are unpredictable",
                   ["A program that gives exactly the same result every time it is run", "A program that checks input data is sensible", "A program that stores records in a table"],
                   "Running the model many times with different random values shows the range of results that could really happen."),
               mcq("Why can a shuffle not simply pick a random position for each item on its own?", "The same position could be picked twice, so one item would appear twice and another not at all",
                   ["Random numbers cannot be used with an array", "A shuffle must use a condition-controlled loop", "The items would come out in the order they started in"],
                   "A shuffle has to keep track of the positions it has already used, so that every item appears exactly once.")]),
  ],
  final=dict(name="Final challenge: how many rolls", floor_title="Final challenge: build the dice roller",
    intro="Six lines of the OCR Exam Reference Language, jumbled. Tap the star and put them into a working program that keeps rolling a dice until it rolls a six, then outputs how many rolls that took.",
    ill=("flow", ["Set the count to 0", "Roll the dice", "Add 1 to the count", "Stop on a six"]),
    tasks=[order("Put these lines into a working program that outputs how many rolls it took to get a six.",
            ["rolls = 0", "do", "  roll = random(1, 6)", "  rolls = rolls + 1", "until roll == 6", "print(rolls)"],
            "The count is set up once before the loop, changed on every roll inside it, and output only after the loop has finished."),
      mcq("The finished program is run twice and outputs 4, then 11. Why?", "The generator is seeded differently each run, so it produces a different sequence of numbers",
          ["The program contains a logic error", "random(1, 6) returns a different range each time it is called", "The program counts in a different way the second time"],
          "Two different answers are exactly what should happen: the numbers are meant to be unpredictable from one run to the next.")]),
  info=[(0, "Nothing is truly random", "A dice is not really unpredictable. Thrown exactly the same way through exactly the same air it would land the same, but the detail is far beyond us, so we call it random. A program's random numbers rest on the same idea."),
        (1, "Read the brackets first", "In an exam question the two numbers in the brackets are most of the marks. Before you answer anything else, write down the lowest and the highest value that the call could possibly return."),
        (2, "Off by one", "A range that is one too wide is one of the commonest bugs in programming. A random index that can equal the size of the array will crash the program eventually, but only on some runs, which makes it very hard to track down."),
        (3, "Where the seed comes from", "Most languages take the seed from the system clock, measured in tiny fractions of a second, so two runs almost never start from the same place. Setting the seed yourself gives the same sequence every time, which is exactly what a tester wants."),
        (4, "Streaks are normal", "Ten rolls of a dice will often contain the same number three times in a row. People expect random data to look evenly spread, so genuinely random results are regularly mistaken for a broken program."),
        (5, "Not strong enough for keys", "A generator seeded from the clock is fine for a game but not for real security, because an attacker who knows roughly when the program ran can work out the sequence. Secure systems gather unpredictable data from hardware instead.")],
  ws=dict(title="Programming fundamentals: random number generation",
    objectives=["know what random numbers are used for in a program",
                "understand how a random whole number is generated within a given range",
                "know that a computer produces pseudo-random numbers from an algorithm and a seed"],
    starter="A quiz program picks one of twenty questions to ask first. Write down what the program must do to choose a different question each time it runs, and the lowest and highest number it needs.", starter_lines=3,
    keyterms=["Pseudo-random", "Seed"], keyq="How does a program produce a number that nobody can predict?",
    exam=[("State two different reasons why a program might need a random number.", 2, 2),
          ("An array called prize holds eight prizes. Describe how a random number could be used to choose one of them, and state the range that number must come from.", 3, 4),
          ("Explain why the numbers produced by a computer are described as pseudo-random.", 3, 3)],
    confidence=["What random numbers are used for in a program", "How to generate a random number in a given range, and why the end points matter", "What pseudo-random means, and what a seed does"]))

L7 = dict(id="pf-l07", topic="2.2", lesson=7, title="Revision HQ 2.2", img="PF_L07_RevisionHQ_360",
  description="Recap every lesson of Programming fundamentals and find out exactly what to revise before your end-of-topic test.",
  kicker=f"{K22}  |  Lesson 7", scene_title="Revision HQ 2.2", subtitle=SUB22,
  intro="Each station takes one lesson from this topic and goes straight for the part that most often goes wrong, so this is a check rather than a re-teach. Work through all six, then take on a lane draw that needs almost everything you have learned.",
  keywords=["Constructs", "Casting", "File handling", "SQL", "Array", "Sub-program", "Pseudo-random"], revision=True,
  stations=[
   dict(name="Constructs recap", bullets=["A single equals sign assigns a value to a variable; a double equals sign compares two values and gives True or False.",
        "Selection makes a choice once. Iteration goes back and repeats.",
        "A condition-controlled loop must change the variable in its condition somewhere inside the loop, or it never ends."],
        challenge="Write down the difference between = and == and give an example of each.",
        ill=("compare", "= assigns", ["lives = 3", "Stores 3 in lives", "Nothing is tested"],
             "== compares", ["lives == 3", "Gives True or False", "Used in a condition"], "b", "g"),
        fact="A single equals sign... A double equals sign...",
        tasks=[mcq("Which of these lines compares two values rather than storing one?", "if total == 20 then",
                   ["total = 20", "total = total + 20", "print(total)"],
                   "A double equals sign asks a question; a single one hands an answer to a variable."),
               mcq("A loop is written as  while lives > 0  but nothing inside it ever changes lives. What happens?", "The loop never ends",
                   ["The loop runs exactly once", "The loop is skipped altogether", "The program stops with a syntax error"],
                   "The condition stays True for ever, so the program carries on until something forces it to stop.")]),
   dict(name="Types and operators recap", bullets=["In the OCR Exam Reference Language, + joins two strings but adds two numbers, so \"7\" + \"2\" gives the string 72 while 7 + 2 gives 9.",
        "input() always returns a string, so a number must be cast before any arithmetic is done with it.",
        "DIV gives how many whole times one number goes into another, and MOD gives the remainder left over."],
        challenge="Explain what int(7.9) gives, and why that is not the same as rounding.",
        ill=("table", ["Expression (OCR ERL)", "Value"], [["\"7\" + \"2\"", "72"], ["int(\"7\") + 2", "9"], ["7 DIV 2", "3"], ["7 MOD 2", "1"]]),
        fact="Casting is needed because...",
        tasks=[mcq("In the OCR Exam Reference Language, what is the value of  \"7\" + \"2\" ?", "The string 72",
                   ["The integer 9", "The real number 7.2", "An error, because two strings cannot be joined"],
                   "Both values are strings, so + joins them end to end instead of adding them together."),
               mcq("What does  int(7.9)  give?", "7",
                   ["8", "7.9", "0.9"],
                   "Casting to an integer throws the decimal part away completely, so it never rounds up.")]),
   dict(name="File handling recap", bullets=["In Python 3, mode \"w\" wipes whatever was in the file, and mode \"a\" adds to the end and keeps what was already there.",
        "In the OCR Exam Reference Language a read loop calls readLine() inside the loop and stops when endOfFile() becomes True.",
        "A file must be closed, or the last data written may never leave the buffer in memory."],
        challenge="A program saves a new high score each week, but the file only ever holds one score. Explain what is wrong and how to fix it.",
        ill=("table", ["Python 3 mode", "What it does", "Old data"], [["\"r\"", "Read from the file", "Kept"], ["\"w\"", "Write to the file", "Deleted"], ["\"a\"", "Append to the file", "Kept"]]),
        fact="The mode a file is opened in decides...",
        tasks=[mcq("A program outputs the first line of a file over and over instead of working through it. Which mistake would cause this?", "The call to readLine() is outside the loop, so no new line is ever read",
                   ["The file was opened in append mode", "The file was never closed", "endOfFile() was tested before the file was opened"],
                   "Each readLine() call moves one line further on, so it has to sit inside the loop for the loop to make progress."),
               mcq("A program appends a line to a file, but the line is missing when the file is opened again. What is the most likely reason?", "The file was never closed, so the last data stayed in the buffer",
                   ["The line was written to the wrong position in the file", "The line was cast to an integer first", "Append mode always deletes the newest line"],
                   "Closing the file pushes everything still waiting in memory out to secondary storage.")]),
   dict(name="Records and SQL recap", bullets=["SELECT chooses the fields, FROM chooses the table and WHERE chooses the records.",
        "Text in a WHERE condition goes inside single quotes, and a pattern with a wildcard needs LIKE rather than =.",
        "AND needs both of its conditions to be True, so it returns the same number of records as OR or fewer."],
        challenge="Write down the three parts of an SQL query and say what each one decides.",
        ill=("compare", "AND", ["Both conditions True", "Narrows the search", "Fewer records come back"],
             "OR", ["At least one condition True", "Widens the search", "More records come back"], "b", "g"),
        fact="The part of a query that decides which records come back is...",
        tasks=[mcq("A table called Pupils has the fields Name, Year and Choir. Which query returns the names of pupils who are in Year 10 and in the choir?", "SELECT Name FROM Pupils WHERE Year = 10 AND Choir = True;",
                   ["SELECT Name FROM Pupils WHERE Year = 10 OR Choir = True;", "SELECT Year, Choir FROM Pupils WHERE Name = 'Year 10';", "SELECT Name FROM Pupils LIKE Year = 10 AND Choir = True;"],
                   "Both conditions must be True at the same time, and AND is the operator that demands that."),
               mcq("A query that should find every surname beginning with M returns no records at all. Which line is the problem?", "WHERE Surname = 'M%'",
                   ["WHERE Surname LIKE 'M%'", "SELECT Surname", "FROM Pupils"],
                   "A pattern containing a wildcard needs LIKE; with = the database hunts for a surname that is literally the two characters M and %.")]),
   dict(name="Arrays and sub-programs recap", bullets=["An array of n elements is indexed 0 to n - 1, so the last index is always one less than the size.",
        "A function returns a value to the line that called it, and a procedure does not.",
        "A local variable only exists inside its own sub-program, so no other part of the program can read it."],
        challenge="An array holds twelve lane numbers. Give the index of the first and of the last, and write the loop that would visit them all.",
        ill=("table", ["Declaration (OCR ERL)", "First index", "Last index"], [["array lane[8]", "0", "7"], ["array scores[10]", "0", "9"], ["array board[3,3]", "0,0", "2,2"]]),
        fact="An index goes out of range when...",
        tasks=[mcq("In the OCR Exam Reference Language, which line reads past the end of  array lane[8] ?", "print(lane[8])",
                   ["print(lane[0])", "print(lane[7])", "print(lane[1])"],
                   "Eight elements are numbered 0 to 7, so index 8 is one place past the last one."),
               mcq("A sub-program works out a total correctly, but the main program cannot use the answer. What is missing?", "A return statement to send the total back",
                   ["A parameter in the sub-program's definition", "A global constant", "An extra loop inside the sub-program"],
                   "With no return it is a procedure, so the value it worked out is thrown away the moment the sub-program ends.")]),
   dict(name="Randomness recap", bullets=["In the OCR Exam Reference Language, random(1, 6) includes both 1 and 6.",
        "A computer produces pseudo-random numbers with an algorithm and a seed, so the same seed gives the same sequence.",
        "A random index must stay inside the array, so an array of six elements needs a number from 0 to 5."],
        challenge="Explain why random(0, 6) is the wrong call for choosing one of six prizes from an array.",
        ill=("big", "random(0, 5)", "Six prizes, indexed 0 to 5. In the OCR Exam Reference Language both end points are included, so this call can pick any one of them and nothing beyond."),
        fact="Pseudo-random numbers come from...",
        tasks=[mcq("In the OCR Exam Reference Language, how many different values can  random(0, 7)  return?", "8",
                   ["7", "6", "9"],
                   "Both ends are included, so 0, 1, 2, 3, 4, 5, 6 and 7 are all possible: exactly one for each element of an array of eight."),
               mcq("A program sets the seed to the same value every time it starts. What effect does that have?", "It produces exactly the same sequence of numbers on every run",
                   ["It produces numbers that are truly random", "It stops the generator ever repeating a number", "It limits every number to the size of the seed"],
                   "A fixed seed makes a run repeatable, which is useful when testing and useless in a game.")]),
  ],
  final=dict(name="Final challenge: the lane draw", floor_title="Final challenge: sports day lane draw",
    intro="Sports day needs a fair draw. Eight runners' names are stored in a file, and the program must give each of them a different lane from 1 to 8, chosen at random, then save the finished list. Tap the star and build it.",
    ill=("flow", ["Read the eight names", "Draw a lane at random", "Check that lane is free", "Write the finished list"]),
    tasks=[order("Put the steps of the lane draw into the order the program must carry them out.",
            ["Read the eight runners' names from the file", "Declare an array of eight lanes, all empty",
             "Pick a random lane number from 0 to 7", "If that lane is already taken, pick another number",
             "Store the runner's name in the empty lane", "Write the finished lane list to a new file"],
            "Set the array up before any drawing happens, and never store a name until you have checked that the lane is free."),
      multi("Which techniques does the lane draw program need? Select all that apply.",
            ["Reading the names in from a file", "An array to hold the eight lanes", "A loop that repeats until a free lane is found",
             "A random number from 0 to 7", "An SQL SELECT statement", "A range check on the runners' names"],
            ["Reading the names in from a file", "An array to hold the eight lanes", "A loop that repeats until a free lane is found", "A random number from 0 to 7"],
            "The names come from a file rather than a database table, and a name has no numerical range to check."),
      mcq("Why must the program check whether a lane is already taken before it stores a name?", "Each call is independent, so the same lane number could easily come up twice",
          ["The array would otherwise run out of memory", "random() stops working after eight calls", "The file could not be written to afterwards"],
          "Two runners in lane 3 and an empty lane 7 is the classic bug in any draw or shuffle.")]),
  info=[(0, "Revision that works", "Cover the bullets at a station, say them out loud from memory, then uncover them and check. Reading them again is much easier, and much less useful, than trying to recall them."),
        (1, "Two marks, two things", "A two-mark question that says state the difference wants both sides written down. Saying what casting does without saying why it is needed throws away half the marks."),
        (2, "Say which language", "Answering a code question in Python instead of the OCR Exam Reference Language is fine, but stick to one of them for the whole answer. Mixing print() with endif loses marks because neither language is being followed."),
        (3, "Three lines, three jobs", "Nearly every SQL mark comes from the same three lines: SELECT for the fields, FROM for the table and WHERE for the records. Write them on separate lines and check each one in turn."),
        (4, "Trace it on paper", "For any program with a loop, draw a column for each variable and add a new row every time round the loop. Most tracing marks in Paper 2 are won or lost on whether you bothered to do this."),
        (5, "The top number", "In a question about choosing an element at random, the marks are in the range. An array of eight elements needs a number from 0 to 7, and an 8 anywhere in that answer will cost you.")],
  ws=dict(title="Revision HQ 2.2: programming fundamentals",
    objectives=["know the whole of topic 2.2 well enough to answer without notes",
                "understand the mistakes that most often lose marks in programming questions",
                "know which lessons are secure and which still need revision before the test"],
    starter="Without looking back at your notes, write down the three programming constructs, the five data types, and the four operations a program carries out on a file.", starter_lines=4,
    keyterms=["Iteration", "Pseudo-random"], keyq="Which parts of 2.2 am I secure on, and which do I need to revise before the test?",
    exam=[("State the difference between a count-controlled loop and a condition-controlled loop.", 2, 2),
          ("A club stores its members in a table called Members, with the fields MemberID, Name, Year and Paid. Write an SQL query that returns the name of every member in Year 10 who has not paid.", 3, 3),
          ("Eight runners' names are stored in a file. Write an algorithm that gives each runner a different lane from 1 to 8, chosen at random, and outputs the finished draw. Use the OCR Exam Reference Language or a language you know.", 6, 8)],
    confidence=["Variables, constants and the three constructs", "Data types, casting, operators and string handling", "Files, records and SQL, arrays, sub-programs and random numbers"]))

# ---------------------------------------------------------------- diagrams
# A diagram button sits at the top left of its station panel. These are placed
# here rather than in newdiagrams.py so that rebuilding a scene keeps them.
for _L, _d in (
  (L1, [(3, "constructs", "Sequence, selection and iteration",
         "The order the lines run in is not the order they are written in. Watch the program counter drop straight through, jump over a block, and jump back.")]),
  (L2, [(5, "strslice", "Inside a string",
         "Every character has a position, counted from 0. See length, a substring taken from a position, upper and lower case, and two strings joined.")]),
  (L3, [(2, "filelines", "Reading a file line by line",
         "The read pointer moves down the file as you read, and what you write is not in the file until it is closed.")]),
  (L4, [(3, "sqlwhere", "How a query runs",
         "WHERE throws away the rows that fail the condition, and only then does SELECT pick the columns. Rows first, columns second.")]),
  (L5, [(1, "arrayindex", "Index positions",
         "The index is a position, not a value, and the last index is one less than the length. Watch an element read, an element changed, and a loop walk the lot."),
        (2, "array2d", "Rows then columns",
         "The first number picks the row and the second picks the column. Swapping them lands you somewhere else entirely."),
        (4, "callreturn", "Calling a sub-program",
         "An argument travels in to the parameter, the sub-program runs, and return carries one value back. The local variables vanish when it finishes.")]),
  (L6, [(3, "randomdist", "Pseudo-random numbers",
         "A seed goes into an algorithm, which makes a number and the next seed. Draw enough of them and every value in the range comes up equally often.")]),
  (L7, [(0, "constructs", "Sequence, selection and iteration", "The three constructs again: straight through, jump over, jump back."),
        (3, "sqlwhere", "How a query runs", "Rows are filtered by WHERE first, then SELECT picks the columns."),
        (4, "arrayindex", "Index positions", "The index is a position, and the last one is one less than the length.")]),
):
    _L["diagrams"] = _d
