from kit import mcq, multi, sort, match, order

K14 = "1.4 Network security"
SUB14 = "OCR J277 Paper 1  |  Computer systems"

L1 = dict(id="ns-l01", topic="1.4", lesson=1, title="Threat map", img="NS_L01_ThreatMap_360",
  description="Meet the six forms of attack on the OCR specification, find out why attackers do it, and follow the CryptoLocker story.",
  kicker=f"{K14}  |  Lesson 1", scene_title="Threat map", subtitle=SUB14,
  intro="Every network is under attack, all the time. In the threat map room you'll meet the six forms of attack you need to know, find out what attackers want, and follow the CryptoLocker story from your starter.",
  keywords=["Malware", "Phishing", "Brute force", "Denial of service", "Data interception", "SQL injection"],
  stations=[
   dict(name="What is a cyberattack?", bullets=["An attempt to damage or disrupt a system, or to gain unauthorised access to it or its data.",
        "Attacks can come from outside the network or from inside it.", "The people who carry them out are often called hackers or attackers."],
        challenge="Write your own definition of a cyberattack.", ill=("icons", [("robot", "Attacker"), ("router", "Network"), ("server", "Your data")]),
        fact="A cyberattack is...",
        tasks=[mcq("What is a cyberattack?", "An attempt to damage, disrupt or gain unauthorised access to a system or its data", ["A software update that goes wrong", "A power cut in a server room", "A network running slowly at busy times"],
                   "Damage, disruption and unauthorised access are the three things attackers are after."),
               mcq("Where can attacks come from?", "Both outside the network and inside it", ["Only from outside the organisation", "Only from other countries", "Only from viruses"],
                   "Insiders, including careless staff, cause a large share of security incidents.")]),
   dict(name="The six forms of attack", bullets=["Malware, social engineering (including phishing), brute-force attacks, denial of service, data interception and theft, and SQL injection.",
        "Some attack the technology; others attack the people using it."], challenge="Which of the six forms of attack targets people rather than computers?",
        ill=("tiles", [("Malware", "r"), ("Phishing", "o"), ("Brute force", "y"), ("Denial of service", "p"), ("Data interception", "b"), ("SQL injection", "g")], 3),
        fact="The six forms of attack are...",
        tasks=[match("Match each form of attack to what it does.", [["Malware", "Malicious software that damages or takes control of a system"],
                     ["Phishing", "Fake messages that trick people into giving away information"], ["Brute-force attack", "Trying huge numbers of passwords until one works"],
                     ["Denial of service", "Flooding a server with requests so it can't respond"], ["Data interception", "Capturing data as it travels across a network"],
                     ["SQL injection", "Entering code into a text box to attack a database"]], "These six are the forms of attack named in the specification.")]),
   dict(name="What do attackers want?", bullets=["Money: ransoms, fraud and selling stolen data.", "Data: personal details, passwords, company secrets.",
        "Disruption: damaging a rival, making a political point, or simply showing off."], challenge="Suggest two reasons someone might attack a school's network.",
        ill=("tiles", [("Money", "y"), ("Data", "b"), ("Disruption", "r"), ("Showing off", "p")], 2), fact="Attackers are usually after...",
        tasks=[mcq("Why do most criminal cyberattacks happen?", "To make money", ["To improve software", "To test networks legally", "To help companies"],
                   "Ransom payments, fraud and selling stolen data all make money for attackers."),
               mcq("A pen tester is paid by a company to attack its systems. Is this a crime?", "No, because the company has given permission", ["Yes, all attacks are crimes", "Yes, unless it fails", "No, because no data is stored"],
                   "Permission is what separates penetration testing from criminal hacking.")]),
   dict(name="CryptoLocker", bullets=["CryptoLocker was ransomware that appeared in 2013 and encrypted victims' files.",
        "Victims were told to pay a ransom in Bitcoin to get their files back.", "It spread through infected email attachments and a botnet."],
        challenge="Answer the starter questions about CryptoLocker.", ill=("icons", [("lock", "Files encrypted"), ("disk", "Ransom demand")]), fact="CryptoLocker was...",
        tasks=[mcq("What type of malware was CryptoLocker?", "Ransomware", ["A worm with no payload", "Spyware", "A firewall"], "It encrypted files and demanded payment for the key."),
               mcq("How did most victims get infected?", "By opening an infected email attachment", ["By visiting a library", "By using a firewall", "By updating their operating system"],
                   "Email attachments are still one of the most common ways malware spreads.")]),
   dict(name="Operation Tovar", bullets=["In 2014, police forces and security companies from several countries worked together to take down the botnet behind CryptoLocker.",
        "The operation was called Operation Tovar.", "The FBI offered a reward of up to $3 million for information leading to the arrest of Evgeniy Bogachev, who has never been caught."],
        challenge="Why do cybercrime investigations need international cooperation?", ill=("icons", [("server", "Botnet"), ("user", "Police"), ("lock", "Shut down")]),
        fact="Operation Tovar was...",
        tasks=[mcq("What was Operation Tovar?", "An international operation that took down the botnet behind CryptoLocker", ["A new type of ransomware", "A firewall product", "A password cracking tool"],
                   "It involved police forces, universities and security companies in several countries."),
               mcq("Why is catching cybercriminals difficult?", "Attackers can operate from another country, hiding their identity and location", ["Attacks leave no trace at all", "Police aren't allowed to investigate computers", "The internet has no addresses"],
                   "That's why investigations are international and take years.")]),
   dict(name="How much damage?", bullets=["CryptoLocker is estimated to have extorted around $3 million from victims before it was shut down.",
        "The cost of an attack isn't only the ransom: there's downtime, lost data, recovery and damage to reputation.", "Organisations can also be fined if they fail to protect personal data."],
        challenge="List four costs to a school if its network were attacked.", ill=("tiles", [("Ransom", "r"), ("Downtime", "o"), ("Lost data", "y"), ("Reputation", "p"), ("Recovery", "b"), ("Fines", "g")], 3),
        fact="The costs of an attack include...",
        tasks=[multi("Which of these are costs of a successful attack on a business? Select all that apply.", ["Downtime while systems are offline", "Money spent recovering data",
                     "Damage to the company's reputation", "Possible fines for failing to protect personal data", "The price of new office furniture", "Staff holidays"],
                     ["Downtime while systems are offline", "Money spent recovering data", "Damage to the company's reputation", "Possible fines for failing to protect personal data"],
                     "The ransom is often the smallest part of the total cost.")]),
  ],
  final=dict(name="Final challenge: name that attack", floor_title="Final challenge: name that attack",
    intro="Eight incidents have been reported to the security team. Tap the star and sort each one into the form of attack it describes.",
    ill=("tiles", [("Malware", "r"), ("Phishing", "o"), ("Brute force", "y"), ("Denial of service", "p"), ("Data interception", "b"), ("SQL injection", "g")], 3),
    tasks=[sort("Which form of attack does each incident describe?", ["Malware", "Phishing", "Brute force", "Denial of service"], [
      ["An email pretending to be from the bank asks for a password", "Phishing"], ["Software downloaded with a game secretly deletes files", "Malware"],
      ["A program tries a million passwords on one account", "Brute force"], ["A website is flooded with fake requests until it goes offline", "Denial of service"],
      ["A text message claims a parcel is waiting and links to a fake login page", "Phishing"], ["A program encrypts files and demands a payment", "Malware"],
      ["Thousands of infected computers send traffic to one server at once", "Denial of service"], ["A dictionary of common passwords is tried against a login page", "Brute force"]],
      "Data interception and SQL injection come up in lessons 3 and 8.")]),
  info=[(0, "White hats and black hats", "Attackers who break in illegally are called black hats. White hats do the same thing with permission, to help organisations find weaknesses before criminals do."),
        (1, "Attacks per day", "Large organisations see thousands of attempted attacks every day. Most are automated programs scanning for weaknesses, not people."),
        (2, "Hacktivism", "Some attacks are political: groups attack organisations they disagree with to make a point. This is called hacktivism."),
        (3, "Paying doesn't help", "Police advise against paying ransoms: it funds more crime and the files often stay locked. Good backups are a far better defence."),
        (4, "Still wanted", "Evgeniy Bogachev is still on the FBI's most wanted cyber list, with a reward of up to $3 million."),
        (5, "The law", "In the UK, the Computer Misuse Act 1990 makes unauthorised access to a computer system a crime, even if nothing is damaged.")],
  ws=dict(title="Forms of attack", objectives=["understand the different forms of attack against computer systems"],
    starter="Choose a cyberattack that has been in the news. Write down who was attacked, what the attackers wanted, and what it cost the organisation.", starter_lines=4,
    keyterms=["Malware", "Social engineering"], keyq="What forms of attack threaten a network, and what do attackers want?",
    exam=[("Name two forms of attack that target people rather than software.", 2, 2), ("Explain why most criminal cyberattacks happen.", 2, 2),
          ("A small business is hit by ransomware. Describe three costs it will face beyond the ransom itself.", 6, 6)],
    confidence=["The six forms of attack", "Why attackers attack", "The costs of a successful attack"]))

L2 = dict(id="ns-l02", topic="1.4", lesson=2, title="Malware lab", img="NS_L02_MalwareLab_360",
  description="Study viruses, worms, trojans, ransomware and spyware under the microscope, and learn how to stop them.",
  kicker=f"{K14}  |  Lesson 2", scene_title="Malware lab", subtitle=SUB14,
  intro="Malware is any software written to do harm. In the lab you'll meet each type, see how it spreads and what it does, and learn the defences that stop it.",
  keywords=["Malware", "Virus", "Worm", "Trojan", "Ransomware", "Spyware", "Anti-malware"],
  stations=[
   dict(name="What is malware?", bullets=["Malware is short for malicious software: any program written to damage or gain access to a system.",
        "It can delete or change files, steal data, spy on users or take control of a computer.", "It spreads through downloads, attachments, websites and USB sticks."],
        challenge="Write a definition of malware in your own words.", ill=("icons", [("bug", "Malware"), ("pc", "Victim"), ("robot", "Attacker")]), fact="Malware is...",
        tasks=[mcq("What does malware mean?", "Malicious software: programs written to cause harm or gain access", ["Hardware that has broken", "Software that is out of date", "A type of firewall"],
                   "Malware is a broad term covering viruses, worms, trojans, ransomware and spyware."),
               mcq("Which is the most common way malware reaches a computer?", "A user opens an infected email attachment or download", ["Through the power supply", "By the computer being too old", "Through the monitor cable"],
                   "Most malware still needs a person to open something.")]),
   dict(name="Viruses", bullets=["A virus attaches itself to a file or program.", "It needs the user to run that file before it can do anything.",
        "Once running, it copies itself into other files and spreads when those files are shared."], challenge="Why does a virus need a user to do something?",
        ill=("flow", ["Infected file", "User opens it", "Copies itself", "Spreads with files"]), fact="A virus...",
        tasks=[mcq("How does a virus spread?", "It attaches to files, and spreads when those files are opened and shared", ["It travels through the network on its own", "It disguises itself as useful software", "It encrypts files and demands payment"],
                   "Needing a user to run it is what separates a virus from a worm."),
               mcq("Which of these could carry a virus?", "A program file attached to an email", ["A blank USB stick that has been formatted", "A printed document", "A monitor"],
                   "Any file that can be run, or that contains macros, can carry a virus.")]),
   dict(name="Worms", bullets=["A worm is self-replicating: it copies itself without any user action.", "It spreads across networks by finding weaknesses in software.",
        "Worms can spread extremely fast and use up bandwidth and processing time."], challenge="Why can a worm spread faster than a virus?",
        ill=("flow", ["One infected PC", "Scans network", "Copies itself", "Whole network"]), fact="A worm...",
        tasks=[mcq("What makes a worm different from a virus?", "A worm copies itself across a network without any user action", ["A worm needs a user to open a file", "A worm only affects printers", "A worm is not malware"],
                   "That's why worms can spread through a whole network in minutes."),
               mcq("Which defence helps most against worms?", "Keeping software and operating systems patched and up to date", ["Turning the monitor off", "Using a bigger hard drive", "Deleting old emails"],
                   "Worms exploit known weaknesses, which patches fix.")]),
   dict(name="Trojans", bullets=["A trojan is disguised as legitimate software, such as a free game or a useful tool.", "The user installs it themselves, and it then does something harmful.",
        "Trojans don't replicate, but they often open a backdoor for the attacker."], challenge="Why is the trojan named after the wooden horse?",
        ill=("icons", [("form", "Looks useful"), ("bug", "Hidden payload"), ("robot", "Backdoor")]), fact="A trojan...",
        tasks=[mcq("What is a trojan?", "Malware disguised as legitimate software that the user installs themselves", ["Malware that copies itself across networks", "Software that encrypts a hard drive by accident", "A type of firewall"],
                   "The disguise is the whole point: the user lets it in."),
               mcq("What does a backdoor let an attacker do?", "Access the computer again later, without the normal login", ["Print documents faster", "Improve the Wi-Fi signal", "Delete the trojan"],
                   "Backdoors let attackers return whenever they like.")]),
   dict(name="Ransomware and spyware", bullets=["Ransomware encrypts the user's files and demands a payment for the key.", "Spyware secretly records what the user does, including keystrokes, and sends it to the attacker.",
        "A keylogger is a common form of spyware used to capture passwords."], challenge="Why are good backups the best defence against ransomware?",
        ill=("compare", "Ransomware", ["Encrypts your files", "Demands payment"], "Spyware", ["Records what you do", "Steals passwords"], "r", "p"), fact="Ransomware... Spyware...",
        tasks=[mcq("What does ransomware do?", "Encrypts files and demands payment for the key to unlock them", ["Records every key you press", "Copies itself across a network", "Blocks a website with traffic"],
                   "CryptoLocker, from lesson 1, is an example."),
               mcq("What is a keylogger?", "Spyware that records every key pressed, including passwords", ["A device that unlocks doors", "Software that speeds up typing", "A firewall rule"],
                   "Keyloggers can be software or a small device plugged in behind the keyboard.")]),
   dict(name="Stopping malware", bullets=["Anti-malware software scans files and checks them against known threats.", "Keep operating systems and applications patched and up to date.",
        "Don't open unexpected attachments, and back up important files regularly.", "Firewalls and user access levels limit what malware can reach."],
        challenge="Suggest four things a school could do to reduce malware infections.", ill=("tiles", [("Anti-malware", "g"), ("Updates", "g"), ("Backups", "g"), ("Care with email", "g"), ("Firewall", "g"), ("Access levels", "g")], 3),
        fact="To protect against malware, you should...",
        tasks=[multi("Which of these help protect against malware? Select all that apply.", ["Anti-malware software kept up to date", "Installing operating system updates",
                     "Regular backups", "Not opening unexpected attachments", "Using the same password everywhere", "Turning off the firewall"],
                     ["Anti-malware software kept up to date", "Installing operating system updates", "Regular backups", "Not opening unexpected attachments"],
                     "Backups don't stop an infection, but they mean you don't have to pay a ransom.")]),
  ],
  final=dict(name="Final challenge: identify the malware", floor_title="Final challenge: identify the malware",
    intro="Eight infections have arrived in the lab. Tap the star and sort each description into the type of malware it describes.",
    ill=("tiles", [("Virus", "r"), ("Worm", "o"), ("Trojan", "p"), ("Ransomware", "y")], 4),
    tasks=[sort("Which type of malware does each description match?", ["Virus", "Worm", "Trojan", "Ransomware"], [
      ["Attaches to a file and spreads when that file is shared", "Virus"], ["Copies itself across a network with no user action", "Worm"],
      ["Pretends to be a free game, then opens a backdoor", "Trojan"], ["Encrypts every document and demands Bitcoin", "Ransomware"],
      ["Needs the user to run an infected program", "Virus"], ["Exploits a weakness in unpatched software to spread by itself", "Worm"],
      ["Downloaded as a 'video player update' that steals passwords", "Trojan"], ["Displays a countdown and a payment demand", "Ransomware"]],
      "The key differences: viruses need a user, worms don't, trojans disguise themselves, and ransomware wants money.")]),
  info=[(0, "The first worm", "The Morris worm of 1988 was one of the first. It was meant as an experiment, but it slowed thousands of computers and led to the first conviction under a US computer crime law."),
        (1, "WannaCry", "In 2017, the WannaCry ransomware worm spread worldwide in hours and hit NHS hospitals, cancelling thousands of appointments. A patch already existed, but many systems hadn't installed it."),
        (2, "Signatures and behaviour", "Anti-malware spots known malware by its 'signature', and unknown malware by watching for suspicious behaviour, such as a program encrypting lots of files."),
        (3, "Sandbox", "Security researchers run suspected malware inside a sandbox: an isolated virtual machine where it can do no harm."),
        (4, "Not just PCs", "Phones, smart TVs and even fridges can be infected. Any device that runs software can run malicious software."),
        (5, "3-2-1 backups", "A common rule is 3 copies of your data, on 2 types of storage, with 1 kept off-site. Ransomware can't encrypt a backup that isn't connected.")],
  ws=dict(title="Malware", objectives=["understand the threats of various forms of malware", "understand how to identify and protect against malware"],
    starter="A school laptop suddenly runs slowly, shows pop-ups and its files have odd names. Suggest three things that might have happened to it.", starter_lines=3,
    keyterms=["Virus", "Ransomware"], keyq="How do the different types of malware spread, and what damage do they do?",
    exam=[("Name two types of malware and state what each one does.", 4, 4), ("Explain why a worm can spread through a network faster than a virus.", 3, 3),
          ("Describe three measures a school could take to reduce malware infections.", 6, 6)],
    confidence=["What malware is", "Viruses, worms, trojans, ransomware and spyware", "Protecting against malware"]))

L3 = dict(id="ns-l03", topic="1.4", lesson=3, title="Database break-in", img="NS_L03_DatabaseBreakIn_360",
  description="See how a single quotation mark in a login box can hand over a database, and learn how programmers stop it.",
  kicker=f"{K14}  |  Lesson 3", scene_title="Database break-in", subtitle=SUB14,
  intro="A login box is just a text box, and a text box can accept anything, including code. Find out how SQL injection works, what it lets attackers do, and how to shut it down.",
  keywords=["SQL", "Database", "Injection", "Concatenation", "Validation", "Sanitisation"],
  stations=[
   dict(name="Databases and SQL", bullets=["Websites store usernames, passwords and records in a database.", "SQL (Structured Query Language) is used to ask the database for records, and to add, change or delete them.",
        "SELECT * FROM users WHERE name = 'Sam' asks for Sam's record."], challenge="Write in your own words what SQL is used for.",
        ill=("code", ["SELECT * FROM table_users", "WHERE uname = 'Sam';"], 30), fact="SQL is used to...",
        tasks=[mcq("What is SQL used for?", "Asking a database for records, and adding, changing or deleting them", ["Designing web page layouts", "Encrypting Wi-Fi traffic", "Sending emails"],
                   "SQL is the language databases understand."),
               mcq("Which part of a website would use SQL?", "The login page checking a username and password", ["The colour scheme", "The font size", "The company logo"],
                   "Any page that looks up stored data uses queries like this.")]),
   dict(name="The dangerous line", bullets=["The code in your starter joins the user's input onto the query as text.", "Joining a string to a variable like this is called concatenation.",
        "Whatever the user types becomes part of the SQL command."], challenge="Which line of the starter code is the dangerous one, and why?",
        ill=("code", ['SQL = "SELECT * FROM table_users', '       WHERE uname = \'" + username + "\'; "', "db.Open SQL", "db.MoveFirst", 'return(db("password"))'], 24, [1]),
        fact="The problem with the code is...",
        tasks=[mcq("Joining a string to a variable, as in 'uname = ' + username, is known as what?", "Concatenation", ["Compilation", "Compression", "Encryption"],
                   "This is the answer to your starter question."),
               mcq("Why is building a query this way dangerous?", "Anything the user types becomes part of the SQL command", ["It makes the website load slowly", "It uses too much memory", "It stops the database saving"],
                   "The database can't tell the difference between the programmer's code and the user's input.")]),
   dict(name="The attack", bullets=["An attacker types SQL into the text box instead of a username.", "Entering ' OR 1=1 -- makes the condition always true and comments out the rest.",
        "The database returns every record, and the attacker is logged in."], challenge="Explain how typing ' OR 1=1 -- into a login box can work.",
        ill=("code", ["Username:  ' OR 1=1 --", "", "SELECT * FROM table_users", "WHERE uname = '' OR 1=1 --';"], 26, [0]), fact="An SQL injection attack works by...",
        tasks=[mcq("What does ' OR 1=1 do inside a query?", "It makes the condition always true, so every record matches", ["It deletes the database", "It encrypts the password", "It logs the attacker out"],
                   "1=1 is always true, so the WHERE clause stops filtering anything."),
               mcq("What is the -- for?", "It turns the rest of the line into a comment, so it is ignored", ["It adds two records", "It subtracts a value", "It joins two tables"],
                   "Commenting out the rest removes anything that would break the attacker's query.")]),
   dict(name="What attackers gain", bullets=["Log in as another user, including an administrator.", "Read every record: names, emails, passwords and card details.",
        "Change or delete records, or even destroy whole tables."], challenge="What could an attacker do with a school's student database?",
        ill=("tiles", [("Log in as admin", "r"), ("Read all records", "o"), ("Change data", "y"), ("Delete tables", "p")], 2), fact="A successful SQL injection lets an attacker...",
        tasks=[multi("What can a successful SQL injection attack achieve? Select all that apply.", ["Bypass a login and enter as another user", "Read personal data from the database",
                     "Change or delete records", "Make the website's colours brighter", "Speed up the server"],
                     ["Bypass a login and enter as another user", "Read personal data from the database", "Change or delete records"],
                     "The attacker gets whatever access the website's database account has.")]),
   dict(name="Stopping injection", bullets=["Validate input: check it matches what's expected, such as letters and numbers only.", "Sanitise input: remove or escape dangerous characters like quotation marks.",
        "Use parameterised queries, which keep the user's input separate from the SQL command.", "Give the website's database account only the permissions it needs."],
        challenge="Which defence is the strongest, and why?", ill=("tiles", [("Validation", "g"), ("Sanitisation", "g"), ("Parameterised queries", "g"), ("Least privilege", "g")], 2),
        fact="SQL injection can be prevented by...",
        tasks=[mcq("Which is the strongest defence against SQL injection?", "Using parameterised queries, so input is never treated as code", ["Hiding the login page", "Using a longer password", "Turning off the firewall"],
                   "Validation and sanitisation help, but parameterised queries remove the problem."),
               mcq("What does sanitising input mean?", "Removing or escaping characters that could change the meaning of the query", ["Deleting the user's account", "Encrypting the whole database", "Blocking the user's IP address"],
                   "For example, escaping a single quotation mark so it is treated as text.")]),
   dict(name="Testing for holes", bullets=["Penetration testers deliberately try injection attacks to find weaknesses.", "Detailed error messages help attackers, so live sites should hide them.",
        "Old, unpatched website software is a common way in."], challenge="Why should a live website never show detailed database errors?",
        ill=("icons", [("user", "Pen tester"), ("form", "Login page"), ("server", "Database")]), fact="To find weaknesses, organisations...",
        tasks=[mcq("Why do companies pay penetration testers?", "To find weaknesses like SQL injection before criminals do", ["To design the website's logo", "To sell customer data", "To install new monitors"],
                   "It's legal because the company gives permission."),
               mcq("Why hide detailed error messages on a live site?", "They can tell an attacker how the database is built", ["They slow the website down", "They use up storage", "They upset the web designer"],
                   "Error messages are useful to developers, and just as useful to attackers.")]),
  ],
  final=dict(name="Final challenge: secure the login", floor_title="Final challenge: secure the login",
    intro="The security team is reviewing a login page. Tap the star and sort each practice into safe or risky.",
    ill=("code", ['SELECT * FROM users WHERE uname = ?', 'cmd.Parameters.Add(username)'], 30),
    tasks=[sort("Is each practice safe or risky when writing a login page?", ["Safe", "Risky"], [
      ["Building the query by joining text to the user's input", "Risky"], ["Using parameterised queries", "Safe"],
      ["Checking input contains only letters and numbers", "Safe"], ["Showing the full database error on the page", "Risky"],
      ["Giving the website's database account full admin rights", "Risky"], ["Removing or escaping quotation marks in input", "Safe"],
      ["Having the site penetration tested", "Safe"], ["Trusting that users will only type a username", "Risky"]],
      "Never trust input from a user: that's the lesson behind every one of these.")]),
  info=[(0, "Little Bobby Tables", "A famous web comic shows a pupil named 'Robert'); DROP TABLE Students;--' whose name deletes a school's database. It's a joke, but the attack is real."),
        (1, "Still in the top ten", "Injection attacks have been in the OWASP list of the ten most serious web security risks for over 20 years."),
        (2, "TalkTalk", "In 2015, a UK telecoms company was fined £400,000 after an SQL injection attack exposed the details of around 157,000 customers."),
        (3, "It's not just logins", "Search boxes, contact forms and even web addresses can all be injection points if the input isn't handled safely."),
        (4, "Hashing passwords", "Even if attackers steal a database, properly hashed passwords are extremely hard to reverse. Storing plain-text passwords is a serious mistake."),
        (5, "Automated scanners", "Attackers use automated tools that test thousands of sites for injection flaws, so even small websites are targets.")],
  ws=dict(title="SQL injection", objectives=["understand the concept of SQL injection", "understand how to protect against SQL injection"],
    starter="A website login box passes whatever you type straight into a database query. Suggest what could go wrong, and who might take advantage of it.", starter_lines=3,
    keyterms=["SQL injection", "Input validation"], keyq="How does an SQL injection attack work, and how can it be prevented?",
    exam=[("Describe what happens during an SQL injection attack.", 3, 3), ("Explain two techniques a programmer can use to prevent SQL injection.", 4, 4)],
    confidence=["What SQL injection is", "How the attack works", "How to protect against it"]))

L4 = dict(id="ns-l04", topic="1.4", lesson=4, title="Phishing inbox", img="NS_L04_PhishingInbox_360",
  description="Work through a suspicious inbox: learn what phishing is, what attackers gain, and how to spot the signs.",
  kicker=f"{K14}  |  Lesson 4", scene_title="Phishing inbox", subtitle=SUB14,
  intro="Phishing doesn't attack the computer: it attacks you. Work through an inbox of suspicious messages and learn the signs that give a phishing attempt away.",
  keywords=["Phishing", "Social engineering", "Spoofing", "Link", "Attachment", "Urgency"],
  stations=[
   dict(name="What is phishing?", bullets=["An online fraud technique: fake messages designed to trick people into giving away personal information.",
        "The message pretends to come from a trustworthy organisation, such as a bank or a school.", "It's a form of social engineering: it targets people, not software."],
        challenge="Write the exam definition of phishing in your own words.", ill=("icons", [("robot", "Attacker"), ("form", "Fake email"), ("user", "Victim")]), fact="Phishing is...",
        tasks=[mcq("What is phishing?", "Fraudulent messages that trick people into disclosing personal information by pretending to be trustworthy", ["Software that encrypts your files", "Flooding a server with traffic", "Entering code into a text box"],
                   "This is the exam definition: an online fraud technique that disguises itself as a trustworthy institution."),
               mcq("Why is phishing called social engineering?", "It manipulates people rather than attacking the technology", ["It only works on social media", "It engineers new software", "It needs a social club"],
                   "Social engineering exploits trust, fear and habit.")]),
   dict(name="What attackers gain", bullets=["Usernames and passwords, which open email, banking and school accounts.", "Bank and card details, used for fraud or sold on.",
        "A way into an organisation's network, by stealing a staff login."], challenge="What could an attacker do with a teacher's school password?",
        ill=("tiles", [("Passwords", "r"), ("Bank details", "o"), ("Identity", "y"), ("Network access", "p")], 2), fact="A successful phish gives the attacker...",
        tasks=[mcq("What is the main aim of a phishing attack?", "To get the victim to hand over information such as passwords or bank details", ["To slow down the victim's computer", "To test the victim's antivirus", "To improve the victim's spam filter"],
                   "It's fraud: the victim gives the information away."),
               mcq("Why do attackers target staff logins at a company?", "One stolen login can give access to the whole network", ["Staff computers are faster", "Staff emails are more fun to read", "It makes the attacker an employee"],
                   "Many big breaches start with one phished password.")]),
   dict(name="Spot the signs", bullets=["Check the sender's address, not just the display name.", "Look for urgency or threats: 'act now or your account will be closed'.",
        "Generic greetings, spelling mistakes and odd formatting are clues.", "Unexpected attachments or links asking you to log in."],
        challenge="List four signs that an email might be phishing.", ill=("tiles", [("Odd sender", "r"), ("Urgent threat", "r"), ("'Dear customer'", "o"), ("Spelling errors", "o"), ("Strange link", "r"), ("Unexpected file", "r")], 3),
        fact="Signs of a phishing message include...",
        tasks=[multi("Which of these are warning signs of phishing? Select all that apply.", ["The sender's address doesn't match the organisation", "The message threatens that your account will close today",
                     "A generic greeting such as 'Dear customer'", "A link that goes to an unfamiliar web address", "The email is from someone in your contacts you emailed yesterday", "The company's real logo is used"],
                     ["The sender's address doesn't match the organisation", "The message threatens that your account will close today", "A generic greeting such as 'Dear customer'", "A link that goes to an unfamiliar web address"],
                     "Attackers copy real logos easily, so a good-looking logo proves nothing.")]),
   dict(name="Check the link", bullets=["Hover over a link to see where it really goes.", "Attackers use lookalike addresses, such as barclays-secure-login.com.",
        "A padlock only means the connection is encrypted; it doesn't mean the site is honest."], challenge="Which of the addresses on the wall is genuine, and how can you tell?",
        ill=("tiles", [("bank.co.uk", "g"), ("bank-secure.co.uk", "r"), ("bank.co.uk.login.ru", "r")], 1), fact="To check a link, you should...",
        tasks=[mcq("Which address is most likely to be genuine for a bank called Bank?", "www.bank.co.uk", ["www.bank.co.uk.login.ru", "www.bank-secure-login.com", "www.bank.verify-account.net"],
                   "Read the address from the right: the part just before the first single slash is the real domain."),
               mcq("Does a padlock in the address bar mean a site is safe?", "No: it only means the connection is encrypted", ["Yes, always", "Yes, if the site has a logo", "Only on phones"],
                   "Criminals can get certificates for their fake sites too.")]),
   dict(name="Targeted phishing", bullets=["Spear phishing targets one person, using details about them to look convincing.", "Whaling targets senior staff, such as a head teacher or finance director.",
        "Smishing uses text messages and vishing uses phone calls."], challenge="Why is spear phishing more likely to succeed than a mass email?",
        ill=("icons", [("phone", "Smishing"), ("headphones", "Vishing"), ("user", "Spear phishing")]), fact="Targeted phishing includes...",
        tasks=[mcq("What is spear phishing?", "A phishing message aimed at one person, using personal details to look convincing", ["Phishing sent to millions of people", "Phishing by post", "Phishing that uses malware only"],
                   "Attackers gather details from social media to make it believable."),
               mcq("A text message says a parcel is held and asks you to pay a fee. What is this?", "Smishing", ["Whaling", "A worm", "A denial-of-service attack"], "Smishing is phishing by SMS.")]),
   dict(name="What to do", bullets=["Don't click links or open attachments in suspicious messages.", "Check with the organisation using a number or address you already know.",
        "Report it: to the teacher, the IT team, or a national reporting service.", "If you did click, change your password straight away and tell someone."],
        challenge="Write the three steps you would take if you thought you had been phished.", ill=("flow", ["Don't click", "Check separately", "Report it", "Change password"]), fact="If a message looks like phishing, you should...",
        tasks=[mcq("You get an email asking you to confirm your password. What should you do?", "Don't click. Check with the organisation using contact details you already trust", ["Reply with the password to check if it's real", "Forward it to your friends", "Click the link but type carefully"],
                   "No genuine organisation asks for your password by email."),
               mcq("You clicked a phishing link and typed your password. What's the first thing to do?", "Change that password immediately, and any account that shares it", ["Wait and see if anything happens", "Turn the computer off for a week", "Delete the email and say nothing"],
                   "Speed limits the damage, and telling the IT team helps protect everyone else.")]),
  ],
  final=dict(name="Final challenge: phish or safe?", floor_title="Final challenge: phish or safe?",
    intro="Eight messages are waiting in the inbox. Tap the star and sort each one: is it a phishing sign, or normal?",
    ill=("icons", [("form", "Inbox"), ("robot", "Attacker"), ("lock", "Your details")]),
    tasks=[sort("Is each feature a phishing warning sign, or normal for a genuine message?", ["Phishing sign", "Normal"], [
      ["'Dear customer, your account will be closed in 24 hours'", "Phishing sign"], ["An email address like support@bank-verify.co", "Phishing sign"],
      ["A link that goes to bank.co.uk.secure-login.ru", "Phishing sign"], ["A receipt from a shop you used yesterday, with your name on it", "Normal"],
      ["An unexpected attachment called invoice.exe", "Phishing sign"], ["A newsletter you signed up for, with an unsubscribe link", "Normal"],
      ["A message asking you to reply with your password", "Phishing sign"], ["A school email from a teacher's usual address about homework", "Normal"]],
      "Remember: urgency, odd addresses and requests for details are the big three.")]),
  info=[(0, "Where the name comes from", "'Phishing' is a play on 'fishing': attackers cast out bait and wait to see who bites. The 'ph' comes from 'phreaking', an old form of phone hacking."),
        (1, "Millions a day", "Billions of phishing emails are sent every day. Even a success rate far below 1% makes it worth the attackers' time."),
        (2, "Report it", "In the UK, suspicious emails can be forwarded to report@phishing.gov.uk, and suspicious texts to 7726."),
        (3, "Clever fakes", "Attackers register domains that look almost identical to real ones, sometimes using letters from other alphabets that look the same."),
        (4, "Two-factor helps", "Even if a password is phished, a second factor, such as a code on your phone, usually stops the attacker getting in."),
        (5, "Simulated phishing", "Many organisations send their own fake phishing emails to staff as training, then offer extra help to anyone who clicks.")],
  ws=dict(title="Phishing (part 1)", objectives=["understand what phishing is", "understand how to identify and protect against phishing"],
    starter="Think of a message you have received that looked suspicious. What made you doubt it? If you have never had one, describe what you would look for.", starter_lines=3,
    keyterms=["Phishing", "Social engineering"], keyq="How can you recognise a phishing message, and what should you do about it?",
    exam=[("Describe what phishing is and what the attacker is trying to obtain.", 3, 3), ("Give two features of a message that suggest it is phishing.", 2, 2),
          ("Explain two measures an organisation can take to reduce the risk of staff being phished.", 4, 4)],
    confidence=["What phishing is", "What attackers gain", "Spotting and reporting phishing"]))

L5 = dict(id="ns-l05", topic="1.4", lesson=5, title="Social engineering HQ", img="NS_L05_SocialEngineeringHQ_360",
  description="People are the weakest link: blagging, shouldering, baiting and the everyday habits that let attackers in.",
  kicker=f"{K14}  |  Lesson 5", scene_title="Social engineering HQ", subtitle=SUB14,
  intro="Why break the security when you can just ask someone to open the door? This is social engineering: the techniques attackers use on people, and the habits that make it easy for them.",
  keywords=["Social engineering", "Blagging", "Shouldering", "Baiting", "Weak point", "Policy"],
  stations=[
   dict(name="People as a weak point", bullets=["Human actions cause many security problems: not installing updates, not locking doors, not logging off.",
        "Passwords written on sticky notes, or shared with a friend.", "Printouts with personal data left lying around, and attachments opened without thinking."],
        challenge="List five ways people at your school could accidentally weaken security.", ill=("tiles", [("Sticky note password", "r"), ("Not logging off", "r"), ("Door left open", "r"), ("No updates", "r"), ("Printouts left out", "r"), ("Sharing logins", "r")], 3),
        fact="People are a weak point because...",
        tasks=[multi("Which of these are examples of people being a weak point? Select all that apply.", ["Writing a password on a sticky note", "Not logging off a shared computer",
                     "Leaving the server room door unlocked", "Ignoring operating system updates", "Using a password manager", "Locking the screen when leaving a desk"],
                     ["Writing a password on a sticky note", "Not logging off a shared computer", "Leaving the server room door unlocked", "Ignoring operating system updates"],
                     "The last two are good practice: they make people a strength instead."),
               mcq("Why do attackers target people rather than software?", "People can be tricked, and it's often easier than defeating the technology", ["People are always offline", "Software has no weaknesses", "People own the servers"],
                   "Firewalls can't stop someone from holding a door open.")]),
   dict(name="Blagging", bullets=["Blagging, also called pretexting, means inventing a story to get information.", "For example, phoning the IT desk pretending to be a head teacher locked out of an account.",
        "Attackers research their target first so the story sounds real."], challenge="Write a blagging script an attacker might use on a school receptionist. How should staff respond?",
        ill=("icons", [("headphones", "Fake phone call"), ("user", "Helpful staff"), ("key", "Access given")]), fact="Blagging is...",
        tasks=[mcq("What is blagging?", "Inventing a convincing story to persuade someone to give information or access", ["Sending a fake email to thousands of people", "Watching someone type a password", "Leaving an infected USB stick in a car park"],
                   "Blagging is done person to person, often by phone."),
               mcq("Someone phones claiming to be from IT and asks for your password to 'fix an error'. What should you do?", "Refuse, and check with the IT team using a number you know", ["Give it, because IT staff can be trusted", "Give a slightly changed version", "Email it instead of saying it"],
                   "Genuine IT staff never need your password.")]),
   dict(name="Shouldering and tailgating", bullets=["Shouldering, or shoulder surfing, means watching someone enter a password or PIN.",
        "Tailgating means following an authorised person through a secure door.", "Both rely on people being polite or not paying attention."],
        challenge="How could a school reduce shouldering at its computers?", ill=("icons", [("user", "Attacker"), ("pc", "Your screen"), ("lock", "Your PIN")]), fact="Shouldering is... Tailgating is...",
        tasks=[mcq("What is shouldering?", "Watching someone enter their password or PIN to steal it", ["Carrying a server out of a building", "Sending a fake text message", "Guessing a password with software"],
                   "Cash machines and school logins are common targets."),
               mcq("How does tailgating get someone into a secure building?", "They follow an authorised person through the door before it closes", ["They climb through a window", "They email the receptionist", "They guess the door code with software"],
                   "Staff should politely challenge anyone without a pass.")]),
   dict(name="Baiting", bullets=["Baiting leaves something tempting for the victim to pick up, such as a USB stick labelled 'Payroll'.",
        "When it's plugged in, malware installs itself.", "Online baiting offers free downloads, prizes or games."],
        challenge="Why should you never plug in a USB stick you found?", ill=("icons", [("disk", "Found USB"), ("bug", "Hidden malware"), ("pc", "Your computer")]), fact="Baiting is...",
        tasks=[mcq("What is baiting?", "Leaving something tempting, such as an infected USB stick, for a victim to use", ["Flooding a website with requests", "Watching someone type a PIN", "Encrypting files for a ransom"],
                   "Curiosity is the weakness being exploited."),
               mcq("You find a USB stick in the car park labelled 'Staff salaries'. What should you do?", "Hand it to the IT team without plugging it in", ["Plug it into a school computer to find the owner", "Take it home and check it there", "Throw it in the bin"],
                   "Plugging it in is exactly what the attacker hopes for.")]),
   dict(name="Phishing, vishing and smishing", bullets=["Phishing by email, vishing by phone call, smishing by text message.", "All three use the same trick: pretend to be trusted, then create urgency.",
        "Recorded messages and spoofed caller IDs make vishing convincing."], challenge="How is vishing different from blagging?",
        ill=("tiles", [("Phishing: email", "o"), ("Vishing: call", "p"), ("Smishing: text", "b")], 3), fact="Phishing, vishing and smishing are...",
        tasks=[match("Match each technique to how it reaches the victim.", [["Phishing", "Email"], ["Vishing", "Phone call"], ["Smishing", "Text message"], ["Baiting", "An infected USB stick or download"]],
                     "They differ in the channel, but all are social engineering.")]),
   dict(name="Turning people into a strength", bullets=["Training staff and students to recognise attacks.", "Clear policies: never share passwords, always lock screens, challenge strangers.",
        "Two-factor authentication, so a stolen password isn't enough.", "An acceptable use policy that everyone agrees to."],
        challenge="Write three rules you'd put in a school's acceptable use policy.", ill=("tiles", [("Training", "g"), ("Policies", "g"), ("Two-factor", "g"), ("Lock screens", "g")], 2),
        fact="To stop social engineering, organisations...",
        tasks=[mcq("What is an acceptable use policy?", "The rules a user signs up to before they are allowed on the organisation's network", ["Software that blocks viruses", "A password cracking program", "A type of firewall"],
                   "It sets out what users may and may not do."),
               mcq("Which is the best defence against social engineering?", "Training people to recognise the techniques, backed by clear policies", ["A faster internet connection", "More powerful servers", "Longer URLs"],
                   "Technology alone can't stop someone being persuaded.")]),
  ],
  final=dict(name="Final challenge: name the technique", floor_title="Final challenge: name the technique",
    intro="Eight incidents from around the school. Tap the star and sort each one into the social engineering technique it describes.",
    ill=("tiles", [("Blagging", "p"), ("Shouldering", "b"), ("Baiting", "o"), ("Phishing", "r")], 4),
    tasks=[sort("Which technique does each incident describe?", ["Blagging", "Shouldering", "Baiting", "Phishing"], [
      ["A caller pretends to be the head teacher and asks for a password reset", "Blagging"], ["Someone stands behind you while you type your PIN", "Shouldering"],
      ["A USB stick labelled 'Exam papers' is left in the corridor", "Baiting"], ["An email claims your account will close unless you log in now", "Phishing"],
      ["A stranger in a high-vis jacket says they're here to fix the servers", "Blagging"], ["A free game download secretly installs malware", "Baiting"],
      ["A camera is angled at the keypad by the office door", "Shouldering"], ["A text message asks you to confirm your bank details", "Phishing"]],
      "All four are social engineering: they target people, not technology.")]),
  info=[(0, "The famous social engineer", "Kevin Mitnick, once the FBI's most wanted hacker, said he got most of his access by simply asking people, rather than by breaking software."),
        (1, "USB drops work", "In one study, researchers dropped USB sticks around a university car park. Around half were picked up and plugged into a computer."),
        (2, "Politeness is a weakness", "Holding a door open is polite, but it also defeats an expensive door lock. Good security training tells staff it's fine to ask for a pass."),
        (3, "Caller ID lies", "Phone numbers can be spoofed, so a call that appears to come from your bank may not. Hang up and call back on a number you know."),
        (4, "Screen privacy", "Privacy filters make a screen look black from the side, which makes shouldering much harder in public places."),
        (5, "Clean desk", "Many organisations have a clean-desk policy: no printouts or notes left out when you leave, so nothing sensitive is on show.")],
  ws=dict(title="Phishing part 2: social engineering", objectives=["understand what phishing is", "understand how to identify and protect against phishing", "understand the ways people are a weak point"],
    starter="What do we mean by people as a weak point in a secure system?", starter_lines=3,
    keyterms=["Blagging", "Shouldering"], keyq="What does a phishing attack set out to achieve?",
    exam=[("Explain, with examples, why people are often the easiest way into a secure system.", 8, 9), ("Describe two measures that reduce the risk of social engineering.", 4, 4)],
    confidence=["Ways people are a weak point", "Blagging, shouldering and baiting", "Protecting against social engineering"]))
