"""The Python course - thirteen 360 experiences, one per lesson.

This is not a specification topic. It sits beyond OCR J277 as topic "PY", so a
teacher can teach programming and track progress through it without it being
mistaken for 2.2 Programming techniques, which it is closely related to but not
a substitute for.

The practice tasks on every station are the verified code questions from
tools/codebank/pr-lNN.json. They are read at import time and turned into task
dicts here, so the bank stays the single source of truth: nothing about a
question - its wording, its brief, its tests or its marks - is retyped in this
file. The six station names also come from the bank, in the bank's order, so a
station can never drift away from the questions sitting on it.
"""
import os, json
from kit import mcq, multi, sort, match, order

KPY = "Python programming"
SUBPY = "Revise 360 Python course  |  Beyond the OCR J277 specification"

BANK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "codebank")
_LOADED = {}


def _bank(lesson):
    if lesson not in _LOADED:
        with open(os.path.join(BANK, lesson + ".json"), encoding="utf-8") as fh:
            _LOADED[lesson] = json.load(fh)
    return _LOADED[lesson]


def code_tasks(lesson, station):
    """The bank's questions for one station, as player tasks.

    `id` and `station` are bank bookkeeping and are left behind. Model
    solutions are not in the bank at all - they live in answers/, which git
    ignores - so none can reach a file the browser downloads.
    """
    out = []
    for q in _bank(lesson)["questions"]:
        if q["station"] != station:
            continue
        t = dict(t="code", marks=q["marks"], q=q["q"], brief=q["brief"],
                 starter=q["starter"], tests=q["tests"], fb=q["fb"])
        # The diagram the Hint button opens: the technique this question needs
        if q.get("hint"):
            t["hint"] = q["hint"]
        if q.get("forbid"):
            t["forbid"] = q["forbid"]
        out.append(t)
    if not out:
        raise ValueError(f"{lesson} station {station} has no questions in the bank")
    return out


def stn(lesson, i, bullets, challenge, ill, fact):
    """One station: its name and its tasks come from the bank, the rest is teaching."""
    return dict(name=_bank(lesson)["stations"][i], bullets=bullets,
                challenge=challenge, ill=ill, fact=fact, tasks=code_tasks(lesson, i))


# ---------------------------------------------------------------- Lesson 1
L1 = dict(id="pr-l01", topic="PY", lesson=1, title="Tuck shop till", img="PR_L01_TuckShopTill_360",
  description="Write your first working programs: print to the screen, store values in variables, read what the user types and cast between data types.",
  kicker=f"{KPY}  |  Lesson 1", scene_title="Tuck shop till", subtitle=SUBPY,
  intro="Every program you will ever write starts here: showing something on the screen, storing a value and asking the user for one. Work the tuck shop till and you will have written your first real programs.",
  keywords=["print", "Variable", "input", "String", "Integer", "Casting", "Concatenation"],
  stations=[
   stn("pr-l01", 0, ["print() shows a value on the screen and then moves down to the next line.",
        "Text to be printed exactly goes inside quotes, and one print() gives one line of output.",
        "Mistake: leaving the quotes off, so Python hunts for a variable with that name instead."],
       "Why does Python treat Juice and \"Juice\" as two completely different things?",
       ("code", ['print("Tuck shop")', 'print("Juice 60p")', 'print("Thank you")'], 28),
       "Printing one line of text is still the first program most programmers ever write."),
   stn("pr-l01", 1, ["A variable is a named box in memory holding one value you can use again later.",
        "name = value stores it, and the name always goes on the left of the equals sign.",
        "Mistake: a second assignment replaces the value, it does not add to it."],
       "Name two values the till has to remember while it is running.",
       ("code", ['price = 60', 'item = "Juice"', 'print(item)', 'print(price)'], 28, [0, 1]),
       "In programming = means 'put this in here', not 'is the same as'."),
   stn("pr-l01", 2, ["input() stops the program, waits for a line to be typed and hands that line back.",
        "Store what comes back in a variable, or the value the user typed is thrown away.",
        "Mistake: forgetting that input() always gives text, even when digits were typed."],
       "What is the difference between printing a prompt and reading the reply?",
       ("code", ['name = input("Name: ")', 'print("Hello " + name)'], 28, [0]),
       "input() is patient: a program will sit on that line for as long as it takes."),
   stn("pr-l01", 3, ["Integers count whole things, floats hold decimals, strings hold text and booleans hold True or False.",
        "+ adds two numbers but joins two strings, so the data type decides what happens.",
        "Mistake: joining a number to a string with +, which Python refuses to do."],
       "Which data type would you choose for a library fine of 1.50, and why?",
       ("table", ["Value", "Data type"], [["12", "Integer"], ["1.5", "Float"], ["Ada", "String"], ["True", "Boolean"]]),
       "Joining strings end to end has its own name: concatenation."),
   stn("pr-l01", 4, ["Casting changes a value from one data type into another.",
        "int() and float() turn text into a number, and str() turns a number into text.",
        "Mistake: casting with int() before checking the text really is a whole number."],
       "Why does int(input()) appear in so many programs?",
       ("code", ['cartons = int(input())', 'total = cartons * 2', 'print("Total " + str(total))'], 26, [0, 2]),
       "Cast is borrowed from metalwork: the value is poured into a new shape."),
   stn("pr-l01", 5, ["Real programs read several values, work something out and print a tidy report.",
        "Decide the data type each value needs before you write a single line.",
        "Mistake: printing the lines in a different order from the one the task asked for."],
       "Plan the inputs, the variables and the output lines of a competitor card.",
       ("flow", ["Read input", "Store it", "Work it out", "Print it"]),
       "Input, process, output is such a common pattern that it has its own initials: IPO."),
  ],
  final=dict(name="Final challenge: name the data type", floor_title="Final challenge: name the data type",
    intro="Eight values have come through the till. Tap the star and sort each one into the data type Python would store it as.",
    ill=("tiles", [("Integer", "b"), ("Float", "g"), ("String", "p"), ("Boolean", "o")], 4),
    tasks=[sort("Which data type would Python use for each value?", ["Integer", "Float", "String", "Boolean"], [
      ["7", "Integer"], ["0", "Integer"], ["2.5", "Float"], ["0.75", "Float"],
      ["Juice", "String"], ["60p", "String"], ["True", "Boolean"], ["False", "Boolean"]],
      "Choosing the right type first saves a casting bug later on.")]),
  info=[(0, "The first line", "Printing a greeting has been the traditional first program in a new language since the 1970s."),
        (1, "Naming rules", "A Python variable name can hold letters, digits and underscores, but it cannot start with a digit or contain a space."),
        (2, "Why it waits", "input() reads one whole line, so the program only carries on once the Enter key has been pressed."),
        (3, "One bit each", "A boolean has only two possible values, so it needs just one bit of storage - the smallest piece of data there is."),
        (4, "Silent rounding", "int() on a float throws the decimal part away instead of rounding, so int(3.9) is 3."),
        (5, "Reading an error", "A traceback names the line that failed. Read its last line first: that says what Python could not do.")],
  ws=dict(title="Output, variables and input", objectives=["know how to print a line of output and store a value in a variable",
      "know how to read a value with input() and choose the data type it needs",
      "understand why a value that has been typed in must be cast before it can be calculated with"],
    starter="Three lines run in this order: price = 40, then price = 65, then print(price). Write down exactly what is printed, and explain in one sentence what became of the first value.", starter_lines=3,
    keyterms=["Variable", "Casting", "Concatenation", "Data type"],
    keyq="Why must a program decide the data type of a value before it can do anything useful with it?",
    exam=[("A pupil writes two lines to add a 50p bag charge to a price that has been typed in: price = input('Price: ') and then print(price + 50). State what Python does when this runs, and rewrite the two lines so they work.", 3, 5),
          ("Write a program that reads a pupil's name and the number of library books they are holding, then prints one line giving the name and how many of their 6 allowed books are still free.", 4, 10),
          ("Write a program that reads the price of one pencil in pence and how many pencils are bought, then prints the total cost in pence.", 3, 8)],
    confidence=["Printing output and storing a value in a variable", "Reading input and choosing its data type", "Casting between text and numbers"]))

# ---------------------------------------------------------------- Lesson 2
L2 = dict(id="pr-l02", topic="PY", lesson=2, title="Number workshop", img="PR_L02_NumberWorkshop_360",
  description="Every arithmetic operator you need: add, subtract, multiply, divide, integer division, modulus, powers, rounding and random numbers.",
  kicker=f"{KPY}  |  Lesson 2", scene_title="Number workshop", subtitle=SUBPY,
  intro="Computers were built to calculate, and Python has an operator for every kind of sum in the specification. Work through the number workshop and learn which one to reach for.",
  keywords=["Arithmetic", "Integer division", "Modulus", "Exponent", "round()", "abs()", "random"],
  stations=[
   stn("pr-l02", 0, ["+ adds, - subtracts, * multiplies and / divides.",
        "/ always gives a float, so 10 / 2 prints 5.0 rather than 5.",
        "Mistake: writing 2n for two lots of n, when Python needs 2 * n."],
       "Which operator would you use to halve the price of a pencil?",
       ("table", ["Operator", "Does", "Example"], [["+", "Add", "3 + 4 = 7"], ["-", "Subtract", "9 - 4 = 5"],
        ["*", "Multiply", "3 * 4 = 12"], ["/", "Divide", "9 / 2 = 4.5"]]),
       "The * was chosen for multiply because early keyboards had no times sign on them."),
   stn("pr-l02", 1, ["// divides and throws the remainder away, giving a whole number.",
        "% gives only the remainder, and is called the modulus.",
        "Mistake: using / when the answer must be whole, which leaves a .0 on the end."],
       "How many full crates of 12 do 50 returned books fill, and how many are left over?",
       ("big", "50 // 12 = 4", "50 % 12 = 2, the books left on the trolley"),
       "% is the quickest test for an even number: n % 2 is 0 whenever n is even."),
   stn("pr-l02", 2, ["** raises a number to a power, so 5 ** 2 is 25 and 5 ** 3 is 125.",
        "A square root is the power of 0.5, or math.sqrt() once math has been imported.",
        "Mistake: writing 5 ^ 2, which does something else entirely in Python."],
       "Give two different ways of working out the square root of 49.",
       ("code", ['side = 5', 'print(side ** 2)', 'print(side ** 3)', 'print(49 ** 0.5)'], 26, [3]),
       "** is the exponent operator, and exponent is simply another word for power."),
   stn("pr-l02", 3, ["round(x) gives the nearest whole number, and round(x, 2) keeps two decimal places.",
        "abs() removes the sign, so a difference can be reported without saying which way.",
        "Mistake: rounding early, then carrying the rounded value into the next calculation."],
       "Why does a till round to 2 decimal places rather than to a whole number?",
       ("code", ['amount = 7.456', 'print(round(amount))', 'print(round(amount, 2))', 'print(abs(-3.2))'], 26, [2, 3]),
       "Python rounds a value ending in exactly .5 towards the even number, so round(2.5) is 2."),
   stn("pr-l02", 4, ["import random first, then random.randint(a, b) gives a whole number from a to b, both included.",
        "random.seed(n) makes the same sequence come out every time, so an answer can be marked.",
        "Mistake: calling randint again instead of storing the number you have already drawn."],
       "Why would a program ever want its random numbers to be predictable?",
       ("code", ['import random', 'random.seed(4)', 'roll = random.randint(1, 6)', 'print(roll)'], 26, [2]),
       "A computer works its random numbers out with a formula, so they are really pseudo-random."),
   stn("pr-l02", 5, ["Work out the order of a calculation before you type it: brackets, powers, then * / // %, then + -.",
        "Store a part-finished answer in a named variable to keep a long calculation readable.",
        "Mistake: rounding part way through, which makes every figure after it slightly wrong."],
       "In what order does Python work through 2 + 3 * 4 ** 2?",
       ("flow", ["Brackets", "Powers", "Times, divide", "Add, subtract"]),
       "BIDMAS is the same rule in a maths lesson as it is in a Python program."),
  ],
  final=dict(name="Final challenge: pick the operator", floor_title="Final challenge: pick the operator",
    intro="Eight jobs have come into the workshop. Tap the star and choose the operator or function each one needs.",
    ill=("tiles", [("//", "b"), ("%", "g"), ("**", "p"), ("round()", "o")], 4),
    tasks=[sort("Which operator or function does each job need?", ["//", "%", "**", "round()"], [
      ["How many full boxes of 10", "//"], ["How many are left over", "%"], ["The volume of a cube", "**"],
      ["Money to the nearest penny", "round()"], ["Whole minutes in 200 seconds", "//"],
      ["The seconds left after those minutes", "%"], ["The area of a square", "**"], ["A time to 1 decimal place", "round()"]],
      "// and % are a pair: one gives the whole part, the other the leftovers.")]),
  info=[(0, "Dividing by zero", "Any program that divides by a number the user typed should check it is not zero first, or Python stops with an error."),
        (1, "Clock arithmetic", "% is how a program wraps round: hour 25 on a 24-hour clock is 25 % 24, which is 1."),
        (2, "Any root at all", "Every root can be written as a power, so a cube root is the power of one third and 27 ** (1/3) is 3."),
        (3, "Floats are close, not exact", "0.1 + 0.2 does not give exactly 0.3, because a float is stored in binary and some decimals will not fit."),
        (4, "Shuffling", "random.shuffle() mixes a list up, which is how a program deals out a hand of cards."),
        (5, "Why order matters", "Without an agreed order, 2 + 3 * 4 could mean 20 instead of 14, so every language fixes one.")],
  ws=dict(title="Arithmetic in Python", objectives=["know which arithmetic operator to use for each kind of calculation",
      "understand the difference between /, // and % and what each one hands back",
      "know how to round a result and how to draw a random number"],
    starter="Work these out by hand, with no computer: 17 / 5, 17 // 5, 17 % 5 and 2 ** 5. Beside each answer write whether Python gives a whole number or a decimal.", starter_lines=4,
    keyterms=["Integer division", "Modulus", "Exponent", "Pseudo-random"],
    keyq="How do you choose between /, // and % when the answer to a calculation has to come out as a whole number?",
    exam=[("A program works out how many full boxes of 6 eggs a crate will fill, and the line reads boxes = eggs / 6. State what is wrong with the result this gives, and write the line corrected.", 2, 4),
          ("Write a program that reads a number of minutes and prints it as a number of whole hours and the minutes left over.", 4, 9),
          ("Write a program that reads two amounts of money in pounds and prints their mean, rounded to two decimal places.", 4, 9)],
    confidence=["Choosing the right arithmetic operator", "Using // and % for whole-number answers", "Rounding a result and drawing a random number"]))

# ---------------------------------------------------------------- Lesson 3
L3 = dict(id="pr-l03", topic="PY", lesson=3, title="Decision gate", img="PR_L03_DecisionGate_360",
  description="Selection from the ground up: comparisons, if, else, elif, the logical operators and decisions nested inside other decisions.",
  kicker=f"{KPY}  |  Lesson 3", scene_title="Decision gate", subtitle=SUBPY,
  intro="A program that always does the same thing is not much use. At the decision gate you will write the conditions that let a program choose, from a single comparison to a whole nest of them.",
  keywords=["Selection", "Condition", "Boolean", "if", "else", "elif", "and", "or", "not"],
  stations=[
   stn("pr-l03", 0, ["A comparison gives a boolean back: either True or False.",
        "The comparison operators are ==, !=, >, <, >= and <=.",
        "Mistake: comparing with one =, when one = stores a value and two compare them."],
       "What does a > b print when a is 5 and b is 5?",
       ("code", ['a = 12', 'b = 9', 'print(a > b)', 'print(a == b)'], 26, [2, 3]),
       "A value that can only be True or False is named after George Boole, who returns in topic 2.4."),
   stn("pr-l03", 1, ["if runs the indented block below it only when its condition is True.",
        "else catches every other case, and needs no condition of its own.",
        "Mistake: missing the colon, or not indenting the block underneath it."],
       "Why does a lift loaded to exactly its 450 kg limit need careful wording?",
       ("code", ['if load <= 450:', '    print("go")', 'else:', '    print("too heavy")'], 26, [0, 2]),
       "Python uses indentation where most languages use brackets, so layout is part of the code."),
   stn("pr-l03", 2, ["elif adds another condition, which is only tested if the ones above it were False.",
        "Python stops at the first branch that is True and skips everything below.",
        "Mistake: putting a wide band first, so it catches everything and the later branches never run."],
       "Why must the weight bands of a courier's price list be tested in order?",
       ("code", ['if level > last:', '    print("rising")', 'elif level < last:', '    print("falling")', 'else:', '    print("steady")'], 24, [2]),
       "elif is short for 'else if', and some languages make you write both words out."),
   stn("pr-l03", 3, ["and is True only when both sides are, and or is True when at least one side is.",
        "not flips a condition over, so not raining is True whenever raining is False.",
        "Mistake: writing wind < 20 or 30, which Python reads as something quite different."],
       "Write the condition for a drone allowed up in light wind and good visibility.",
       ("code", ['if wind < 20 and vis > 5:', '    print("fly")', 'if alarm and not staff:', '    print("locked")'], 24, [0, 2]),
       "Python stops reading an and as soon as one side is False, which is called short-circuiting."),
   stn("pr-l03", 4, ["A decision can sit inside another, and the inner one is only reached if the outer was True.",
        "Each level of nesting is indented one more step in than the one above.",
        "Mistake: nesting where a single and would have said the same thing far more clearly."],
       "Rewrite a nested if as one condition joined with and.",
       ("code", ['if dry:', '    if players >= 11:', '        print("play")', '    else:', '        print("call off")'], 24, [1]),
       "Deeply nested ifs are so hard to follow that programmers call the shape the arrow of doom."),
   stn("pr-l03", 5, ["Work the boundaries out first, then write the bands in the order the rules apply.",
        "Test on the edge of every band, because that is exactly where conditions go wrong.",
        "Mistake: using > where the rule says 'or more', which loses the boundary value."],
       "Which three totals would you test on a medal program with cut-offs at 27 and 24?",
       ("table", ["Total", "Medal"], [["27 or more", "Gold"], ["24 to 26", "Silver"], ["21 to 23", "Bronze"], ["Under 21", "None"]]),
       "An off-by-one error at a boundary is one of the most common bugs there is."),
  ],
  final=dict(name="Final challenge: true or false", floor_title="Final challenge: true or false",
    intro="The wind is 15, the visibility is 8 and the alarm is off. Tap the star and decide whether each condition is True or False.",
    ill=("tiles", [("wind = 15", "b"), ("vis = 8", "g"), ("alarm = False", "o")], 3),
    tasks=[sort("With wind 15, visibility 8 and the alarm off, is each condition True or False?", ["True", "False"], [
      ["wind < 20", "True"], ["wind > 20", "False"], ["vis >= 8", "True"], ["vis > 8", "False"],
      ["wind < 20 and vis > 5", "True"], ["wind > 20 or vis > 5", "True"], ["not alarm", "True"],
      ["alarm and vis > 5", "False"]],
      "Work each side out on its own first, then join them with and, or or not.")]),
  info=[(0, "One = or two", "A single = stores a value and == compares two. Mixing them up is one of the first bugs every programmer meets."),
        (1, "No switch here", "Some languages have a switch statement for choosing between many options. Python does the same job with elif."),
        (2, "Unreachable code", "If a band that catches everything is tested first, no branch below it can ever run - those lines are unreachable."),
        (3, "Same as the gates", "and, or and not behave exactly like the AND, OR and NOT gates you draw truth tables for in topic 2.4."),
        (4, "Flatten it", "A nested if can often be replaced by one condition joined with and, which is easier to read and easier to test."),
        (5, "Read the wording", "'At least', 'no more than' and 'over' all mean different things. Write the boundary value down before you code it.")],
  ws=dict(title="Selection: if, elif and else", objectives=["know how to write a condition using the comparison operators",
      "understand how if, elif and else choose between several outcomes",
      "know how to join two conditions together with and, or and not"],
    starter="A program holds three branches: if score > 20 prints Gold, elif score > 10 prints Silver, and else prints Bronze. Write down what is printed when score is 30, when it is 11, and when it is 10.", starter_lines=3,
    keyterms=["Selection", "Condition", "elif", "Nested selection"],
    keyq="Why does the order the branches are written in change what an if ... elif ... else actually does?",
    exam=[("A car park charges 2 pounds for up to 2 hours and 5 pounds for longer. A pupil writes if hours > 2 then prints 2, and else prints 5. Identify the logic error and write the two lines corrected.", 3, 5),
          ("Write a program that reads a wind speed in mph and prints Calm below 8, Breezy from 8 up to but not including 25, and Gale at 25 or more.", 4, 10),
          ("Write a program that reads a greenhouse temperature and whether the roof vent is open, and prints Open the vent only when the temperature is above 28 degrees and the vent is shut.", 4, 10)],
    confidence=["Writing a condition with a comparison operator", "Choosing between if, elif and else", "Joining conditions with and, or and not"]))

# ---------------------------------------------------------------- Lesson 4
L4 = dict(id="pr-l04", topic="PY", lesson=4, title="Lap counter", img="PR_L04_LapCounter_360",
  description="Count-controlled iteration: the for loop, the range it counts through, running totals and loops nested inside other loops.",
  kicker=f"{KPY}  |  Lesson 4", scene_title="Lap counter", subtitle=SUBPY,
  intro="When you know how many times something has to happen, a counting loop does it for you. At the lap counter you will learn to control a for loop and to use the number it counts with.",
  keywords=["Iteration", "Count-controlled", "for", "range", "Counter", "Running total", "Nested loop"],
  stations=[
   stn("pr-l04", 0, ["for i in range(4): runs the indented block below it four times.",
        "Count-controlled iteration is used when the number of repeats is known in advance.",
        "Mistake: leaving the line to repeat outside the loop, so it only runs once."],
       "How would you repeat an announcement as many times as the user asks for?",
       ("code", ['for i in range(4):', '    print("Bus is late")'], 28, [0]),
       "Iteration is the proper name for repetition, and it is one of the three basic program structures."),
   stn("pr-l04", 1, ["The loop variable holds the count on each pass, so you can print it or calculate with it.",
        "range(n) counts from 0, so the values are 0 up to n - 1.",
        "Mistake: expecting range(5) to include 5, or to start at 1."],
       "What numbers does range(5) actually count through?",
       ("code", ['for lane in range(1, 7):', '    print("Lane", lane)'], 28, [0]),
       "Counting from 0 is normal in programming, and it is why the first item of a list is item 0."),
   stn("pr-l04", 2, ["range(start, stop) counts from start up to but not including stop.",
        "A third value is the step, so range(10, 0, -2) counts back down in twos.",
        "Mistake: forgetting stop is never reached, which quietly loses the last value."],
       "Which range lists the hall rows from 4 to 9 inclusive?",
       ("table", ["Written", "Counts through"], [["range(3)", "0 1 2"], ["range(1, 4)", "1 2 3"],
        ["range(2, 9, 3)", "2 5 8"], ["range(3, 0, -1)", "3 2 1"]]),
       "A range does not build a list of its numbers: it works each one out as the loop asks for it."),
   stn("pr-l04", 3, ["A running total is set to 0 before the loop and grows inside it.",
        "total = total + value adds this pass's value to whatever is already there.",
        "Mistake: setting the total back to 0 inside the loop, which loses everything counted so far."],
       "Where must a running total be set to zero, and why there?",
       ("code", ['total = 0', 'for i in range(7):', '    total = total + int(input())', 'print(total)'], 26, [0, 2]),
       "A counter and a running total work the same way: one adds 1, the other adds a value."),
   stn("pr-l04", 4, ["A nested loop runs the whole inner loop on every single pass of the outer one.",
        "Rows and columns are the usual job: the outer loop picks the row, the inner one the column.",
        "Mistake: indenting the inner loop's body wrongly, so all the rows run together."],
       "How many lines does a loop of 4 columns inside a loop of 3 rows print?",
       ("code", ['for row in range(3):', '    for col in range(4):', '        print("*", end="")', '    print()'], 24, [1]),
       "Two nested loops of 10 run 100 times, so nesting multiplies the work rather than adding to it."),
   stn("pr-l04", 5, ["Decide what each loop counts before you write it, and name the variable after that.",
        "Build the total, the count and the best value in the same single pass through the data.",
        "Mistake: printing inside the loop when the task asks for one line at the end."],
       "Plan the loop, the counter and the total for a report on a set of words.",
       ("flow", ["Totals to 0", "Loop the items", "Update totals", "Print report"]),
       "One pass that gathers several answers at once beats looping over the same data again and again."),
  ],
  final=dict(name="Final challenge: how many times?", floor_title="Final challenge: how many times?",
    intro="Eight loops are running on the lap counter. Tap the star and sort each one by how many times its block runs.",
    ill=("code", ['for i in range(0, 12, 2):', '    print(i)', '', 'for i in range(3, 0, -1):', '    print(i)'], 36),
    tasks=[sort("How many times does each loop run its block?", ["0", "3", "5", "6"], [
      ["range(3)", "3"], ["range(1, 4)", "3"], ["range(5)", "5"], ["range(2, 7)", "5"],
      ["range(0, 12, 2)", "6"], ["range(6, 0, -1)", "6"], ["range(0)", "0"], ["range(4, 4)", "0"]],
      "Count the values the range actually produces: stop is never one of them.")]),
  info=[(0, "Three structures", "Sequence, selection and iteration are the three building blocks of every program ever written."),
        (1, "Why i", "The loop variable is traditionally i, for index, with j and k for nested loops - but a name that says what it counts is clearer."),
        (2, "Counting down", "A negative step counts backwards, which is how a program works through a list from the end to the start."),
        (3, "One pass, many answers", "A single loop can build a total, a count and a highest value all at once, which saves going through the data twice."),
        (4, "Multiplying work", "Nesting multiplies: three loops of 1000 inside each other would run a thousand million times."),
        (5, "Which loop", "If you know the number of repeats, use for. If it depends on what happens, use while - which is the next lesson.")],
  ws=dict(title="Count-controlled iteration: the for loop", objectives=["know how to write a for loop that repeats a block a set number of times",
      "understand how range() decides which values the loop counter takes",
      "know how to build a running total inside a loop, and how to put one loop inside another"],
    starter="Write down every number printed by for i in range(2, 9, 3), then say how many lines of output there are altogether.", starter_lines=3,
    keyterms=["Count-controlled iteration", "range()", "Running total", "Nested loop"],
    keyq="How do you decide what to put inside range() so that a loop counts exactly the values you want?",
    exam=[("A program should print the numbers 1 to 10 but prints 0 to 9 instead. Its loop begins for i in range(10). State which values the original range() counted through, and rewrite the line so the loop prints 1 to 10.", 2, 4),
          ("Write a program that reads 7 daily rainfall figures in millimetres and prints their total and their mean.", 5, 11),
          ("Write a program that reads a size from the user and prints a solid square of hash characters of that size.", 4, 10)],
    confidence=["Writing a for loop with the right range", "Keeping a running total inside a loop", "Using one loop inside another"]))

# ---------------------------------------------------------------- Lesson 5
L5 = dict(id="pr-l05", topic="PY", lesson=5, title="Waiting room", img="PR_L05_WaitingRoom_360",
  description="Condition-controlled iteration: while loops, validation loops that ask again, sentinel values and choosing between for and while.",
  kicker=f"{KPY}  |  Lesson 5", scene_title="Waiting room", subtitle=SUBPY,
  intro="Sometimes a program cannot know how many repeats it needs until it is already running. In the waiting room you will write condition-controlled loops that keep going until something changes.",
  keywords=["Condition-controlled", "while", "Validation loop", "Sentinel", "Infinite loop", "Counter"],
  stations=[
   stn("pr-l05", 0, ["while repeats its block for as long as its condition stays True.",
        "The condition is tested before every pass, so a while loop can run no times at all.",
        "Mistake: never changing the condition inside the loop, which leaves it running forever."],
       "What has to change inside a while loop for it ever to stop?",
       ("code", ['count = 5', 'while count > 0:', '    print(count)', '    count = count - 1'], 26, [1, 3]),
       "A loop whose condition never becomes False is an infinite loop, and it will freeze the program."),
   stn("pr-l05", 1, ["A validation loop reads a value, then asks again for as long as it breaks the rules.",
        "Read once above the loop, then read again at the bottom of it.",
        "Mistake: leaving the second read out, so the same bad value is tested forever."],
       "Why does a validation loop need an input() in two different places?",
       ("code", ['n = int(input())', 'while n < 1 or n > 20:', '    print("try again")', '    n = int(input())'], 24, [1, 3]),
       "This shape has a name of its own: input validation, which is the heart of topic 2.3."),
   stn("pr-l05", 2, ["A sentinel is an agreed value meaning 'no more data', such as -1 or the word end.",
        "The loop keeps going until the sentinel arrives, however many items came before it.",
        "Mistake: counting the sentinel itself as one of the real values."],
       "Why must a sentinel be a value the real data can never take?",
       ("code", ['total = 0', 'price = int(input())', 'while price != -1:', '    total = total + price', '    price = int(input())'], 24, [2]),
       "Sentinel means guard: the value stands at the end of the data keeping watch."),
   stn("pr-l05", 3, ["A counter and a running total are set up before the loop and updated inside it.",
        "The same pass can count the items and test each one against a rule.",
        "Mistake: updating the counter after the loop has already finished."],
       "How would you count how many of the scores read reached 40?",
       ("code", ['count = 0', 'while n != -1:', '    count = count + 1', '    n = int(input())'], 26, [2]),
       "A while loop with a counter can do anything a for loop can, but a for loop says it more clearly."),
   stn("pr-l05", 4, ["Use for when the number of repeats is known before the loop starts.",
        "Use while when it depends on the data, or on what the user chooses to type.",
        "Mistake: a while loop with its own counter where a for loop would be shorter and safer."],
       "Which loop would you use to read a known number of parcel weights?",
       ("compare", "for", ["Count is known", "Reads 5 weights"], "while", ["Count is not known", "Asks until valid"], "b", "o"),
       "Both kinds are called iteration, and the exam expects you to name which one you have used."),
   stn("pr-l05", 5, ["Set every total and counter up before the loop, and report them after it.",
        "One while loop can both validate what comes in and gather the figures you need.",
        "Mistake: reporting inside the loop, which prints a line for every item read."],
       "Plan the variables a swimming session report needs before its loop starts.",
       ("flow", ["Set up totals", "Read a value", "Not the sentinel?", "Report"]),
       "A loop that reads until a sentinel copes with no data at all, as long as the totals start at zero."),
  ],
  final=dict(name="Final challenge: for or while?", floor_title="Final challenge: for or while?",
    intro="Eight jobs are waiting. Tap the star and decide whether each one needs a count-controlled for loop or a condition-controlled while loop.",
    ill=("compare", "for", ["The count is known", "Count-controlled"], "while", ["The count is not known", "Condition-controlled"], "b", "o"),
    tasks=[sort("Which kind of loop does each job need?", ["for", "while"], [
      ["Print a message four times", "for"], ["Read exactly seven temperatures", "for"],
      ["Ask until a valid locker number is typed", "while"], ["Read prices until -1 is typed", "while"],
      ["List the lanes from 1 to 6", "for"], ["Keep guessing until the number is right", "while"],
      ["Add up a known number of marks", "for"], ["Double the weed until it covers the pond", "while"]],
      "If you can say the number of repeats before the loop starts, use for.")]),
  info=[(0, "Stuck forever", "If a program stops responding, an infinite loop is often why: the condition it waits for can never become False."),
        (1, "Ask again politely", "A good validation loop says what was wrong with the last answer, not just 'try again'."),
        (2, "Choosing a sentinel", "-1 works for a price, because a price can never be negative. For a temperature it would be a terrible choice."),
        (3, "Count or total", "A counter always adds 1. A running total adds whatever came in. Plenty of programs need both at once."),
        (4, "Testing at the bottom", "Some languages have a loop that tests its condition at the end, so it always runs once. Python does not, so the first read goes above the loop."),
        (5, "No data at all", "A program given no data should still print something sensible. Start every total at zero and it will.")],
  ws=dict(title="Condition-controlled iteration: the while loop", objectives=["know how to write a while loop and what makes it stop repeating",
      "understand how a validation loop keeps asking until the value typed in is acceptable",
      "know how a sentinel value ends a loop when the amount of data is not known in advance"],
    starter="A program sets count = 5, then a while loop runs for as long as count > 0, and the only line inside the loop prints count. Describe what happens when this program runs, and write down the one line that is missing.", starter_lines=3,
    keyterms=["Condition-controlled iteration", "Validation loop", "Sentinel value", "Infinite loop"],
    keyq="How do you decide between a for loop and a while loop before you write a single line of code?",
    exam=[("A validation loop reads a number, then repeats for as long as it is outside 1 to 50. When 99 is typed the program reports the same wrong number over and over. State what has been left out of the loop, and where in the loop it belongs.", 2, 4),
          ("Write a program that reads lengths of rope in centimetres until 0 is typed, then prints how many lengths were read and their total length.", 5, 11),
          ("Write a program that keeps asking for a password until one of at least 8 characters is typed, and then prints Accepted.", 4, 10)],
    confidence=["Writing a while loop that stops", "Writing a validation loop that asks again", "Using a sentinel value to end a loop"]))

# ---------------------------------------------------------------- Lesson 6
L6 = dict(id="pr-l06", topic="PY", lesson=6, title="Letter press", img="PR_L06_LetterPress_360",
  description="String handling: length and position, slicing, upper and lower case, searching inside text and the character codes behind every letter.",
  kicker=f"{KPY}  |  Lesson 6", scene_title="Letter press", subtitle=SUBPY,
  intro="Text is the data programs handle most, and Python has a tool for every part of it. At the letter press you will measure, cut, compare and search strings.",
  keywords=["String", "len()", "Index", "Slice", "upper()", "lower()", "ord()", "chr()"],
  stations=[
   stn("pr-l06", 0, ["len() gives the number of characters in a string, spaces included.",
        "Characters are numbered from 0, so the last one sits at len() - 1.",
        "Mistake: asking for position len(), which is one past the end and stops the program."],
       "Which position holds the last character of a six-letter word?",
       ("code", ['word = input()', 'print(len(word))', 'print(word[0])', 'print(word[len(word) - 1])'], 24, [3]),
       "A negative index counts from the end, so word[-1] is always the last character."),
   stn("pr-l06", 1, ["A slice takes a run of characters, so word[0:3] gives the first three.",
        "The first number is included and the second is not, exactly like range().",
        "Mistake: expecting word[0:3] to give four characters rather than three."],
       "Which slice gives everything except the first and last characters?",
       ("code", ['word = "LANTERN"', 'print(word[0:3])', 'print(word[1:-1])'], 26, [1, 2]),
       "Python's way of slicing is so useful that several other languages have copied it."),
   stn("pr-l06", 2, ["upper() and lower() hand back a new string and leave the original untouched.",
        "Comparing two strings in the same case ignores how they happened to be typed.",
        "Mistake: calling lower() but never storing or using what it gives back."],
       "Why does a program compare two names in lower case before deciding they match?",
       ("code", ['a = input().lower()', 'b = input().lower()', 'if a == b:', '    print("same")'], 26, [0, 1]),
       "Strings are compared by character code, so in Python every capital sorts before every small letter."),
   stn("pr-l06", 3, ["in tests whether one string appears anywhere inside another.",
        "find() gives the position it starts at, or -1 when it is not there at all.",
        "Mistake: treating find()'s 0 as 'not found', when 0 means the very start."],
       "How can a program tell 'not found' apart from 'found at the start'?",
       ("code", ['line = input()', 'if "bus" in line:', '    print(line.find("bus"))', 'else:', '    print("no")'], 24, [1, 2]),
       "startswith() and endswith() answer the two most common search questions on their own."),
   stn("pr-l06", 4, ["Every character is stored as a number, and ord() gives that number.",
        "chr() goes the other way, turning a code back into its character.",
        "Mistake: forgetting to wrap round after z, which gives a punctuation mark instead."],
       "How would you work out the letter that comes after y?",
       ("code", ['print(ord("A"))', 'print(ord("a"))', 'print(chr(66))'], 28, [0, 1]),
       "A is 65 and a is 97, so the gap between a capital and its small letter is always 32."),
   stn("pr-l06", 5, ["Build a new string one character at a time inside a loop.",
        "isalpha() and isdigit() sort the letters from the digits as you go.",
        "Mistake: trying to change one character in place, when a string cannot be edited."],
       "Plan how you would build a reversed copy of a word.",
       ("code", ['out = ""', 'for ch in word:', '    out = ch + out', 'print(out)'], 26, [2]),
       "A word that reads the same backwards is a palindrome, and reversing a string is how you test for one."),
  ],
  final=dict(name="Final challenge: what does it give?", floor_title="Final challenge: what does it give?",
    intro="The word on the press is LANTERN, stored in a variable called word. Tap the star and match each piece of Python to what it gives back.",
    ill=("table", ["Position", "0", "1", "2", "3", "4", "5", "6"], [["Character", "L", "A", "N", "T", "E", "R", "N"]]),
    tasks=[match("The word is LANTERN. What does each piece of Python give back?", [
      ["len(word)", "7"], ["word[0]", "L"], ["word[-1]", "N"], ["word[0:3]", "LAN"],
      ["word.lower()", "lantern"], ["word.find(\"T\")", "3"], ["\"AN\" in word", "True"], ["ord(\"A\")", "65"]],
      "Counting from 0, and a slice that stops before its second number, explain most of these.")]),
  info=[(0, "Spaces count", "len() counts every character, so a space, a comma and a full stop each add one to the length."),
        (1, "Open ends", "A slice can leave a number out: word[:3] starts at the beginning and word[3:] runs to the end."),
        (2, "Nothing is changed", "upper() does not change the original - it hands back a new string. Strings in Python cannot be edited in place."),
        (3, "Searching fairly", "To search without caring about capitals, lower() both the text and the thing you are looking for before you search."),
        (4, "Beyond A to Z", "ord() gives a Unicode code point, so it works for letters from any alphabet, not only A to Z."),
        (5, "Building strings", "Adding to a string makes a brand new one each time. For a long job, collecting the pieces in a list and joining them once is quicker.")],
  ws=dict(title="String handling", objectives=["know how to find the length of a string and the character at a given position",
      "understand how a slice takes part of a string, and why its end position is left out",
      "know how to change case, search inside text, and move between a character and its code"],
    starter="The variable word holds Cavendish. Write down what each of these gives: len(word), word[0], word[0:4], word[-1] and word.upper().", starter_lines=4,
    keyterms=["Index", "Slice", "Character set", "ord() and chr()"],
    keyq="Why are the characters of a string numbered from 0 rather than from 1?",
    exam=[("A program tries to print the last character of a word with print(word[len(word)]) and stops with an error. Explain why it fails, and write the line corrected.", 3, 5),
          ("Write a program that reads a surname and prints a username made from its first three letters in lower case followed by the number of letters in the surname.", 4, 10),
          ("Write a program that reads a line of text and a single letter, and prints how many times that letter appears in the text, counting capitals and small letters as the same.", 5, 11)],
    confidence=["Using len() and an index on a string", "Taking a slice out of a string", "Searching text and using ord() and chr()"]))

# ---------------------------------------------------------------- Lesson 7
L7 = dict(id="pr-l07", topic="PY", lesson=7, title="Stock shelves", img="PR_L07_StockShelves_360",
  description="One-dimensional arrays: making a list, reading an item by its index, traversing it, adding and removing items, and totals and averages.",
  kicker=f"{KPY}  |  Lesson 7", scene_title="Stock shelves", subtitle=SUBPY,
  intro="One variable holds one value, which is no use at all for a whole class of marks. A list holds many values under one name, and the stock shelves are where you learn to use one.",
  keywords=["Array", "List", "Index", "append()", "remove()", "pop()", "Traverse"],
  stations=[
   stn("pr-l07", 0, ["Square brackets make a list, with the items separated by commas.",
        "A list can start out empty and be filled by a loop as the data arrives.",
        "Mistake: creating the empty list inside the loop, which throws each item away again."],
       "Which line must go above the loop that fills a list, and why?",
       ("code", ['nums = []', 'for i in range(5):', '    nums.append(int(input()))', 'print(nums)'], 26, [0, 2]),
       "The exam calls these arrays. Python calls them lists, and unlike an array they can grow and shrink."),
   stn("pr-l07", 1, ["A list is indexed from 0, so the third item sits at position 2.",
        "len() gives how many items there are, which makes the last index len() - 1.",
        "Mistake: an index past the end, which stops the program with an error."],
       "Which index holds the last of seven scores?",
       ("code", ['lunch = ["pasta", "curry", "pie"]', 'print(lunch[0])', 'print(lunch[2])'], 24, [1, 2]),
       "Counting from 0 means an index is the number of items you step over to reach it."),
   stn("pr-l07", 2, ["for item in list: hands you each value in turn.",
        "for i in range(len(list)): gives the positions instead, for when you need the index too.",
        "Mistake: printing the index when the task asked for the value, or the other way round."],
       "When do you need the position rather than the value itself?",
       ("code", ['for name in plants:', '    print(name, len(name))', 'for i in range(len(nums)):', '    print(i, nums[i])'], 22, [0, 2]),
       "Going through every item of a list in turn is called traversing it."),
   stn("pr-l07", 3, ["append() adds one item onto the end of the list.",
        "remove() takes out the first item with that value, and pop(i) takes out the one at position i.",
        "Mistake: removing items while looping over the same list, which makes the loop skip some."],
       "What is the difference between remove(\"Ada\") and pop(0)?",
       ("code", ['queue.append("Ada")', 'queue.remove("Ben")', 'queue.pop(0)', 'print(queue)'], 26, [1, 2]),
       "pop() hands the removed item back, so it can be used as well as deleted."),
   stn("pr-l07", 4, ["Total the list in a loop, then divide by len() to get the mean.",
        "Track the highest and lowest by comparing each item against the best found so far.",
        "Mistake: starting the highest at 0, which fails on a list of negative numbers."],
       "What should the highest-so-far start as, if the data could be negative?",
       ("code", ['total = 0', 'for n in nums:', '    total = total + n', 'print(total / len(nums))'], 26, [3]),
       "Dividing by len() on an empty list crashes, so check the list is not empty first."),
   stn("pr-l07", 5, ["One pass can build the total, count the items and remember where the best mark was.",
        "Report the figures after the loop has finished, not while it is still running.",
        "Mistake: finding the best value but forgetting to record the position it was found at."],
       "Plan the variables needed to report on eight marks in a single pass.",
       ("flow", ["Fill the list", "Loop it once", "Update figures", "Report"]),
       "Keeping the position of the best value as well as the value answers 'which one' as well as 'how much'."),
  ],
  final=dict(name="Final challenge: what does it do?", floor_title="Final challenge: what does it do?",
    intro="The basket holds [\"tea\", \"jam\", \"rice\"]. Tap the star and match each list operation to what it does.",
    ill=("stack", [("basket[0]", "tea", "b"), ("basket[1]", "jam", "g"), ("basket[2]", "rice", "p")]),
    tasks=[match("Match each list operation to what it does.", [
      ["basket.append(\"oats\")", "Adds oats onto the end"], ["basket.remove(\"jam\")", "Takes out the first jam"],
      ["basket.pop(0)", "Takes out the first item"], ["len(basket)", "How many items there are"],
      ["basket[2]", "The third item"], ["basket[-1]", "The last item"]],
      "An index reads an item, while append, remove and pop change what is in the list.")]),
  info=[(0, "One name, many values", "Without lists, a program for 30 marks would need 30 variables - and 30 lines to total them."),
        (1, "Out of range", "An index error is nearly always an off-by-one: the last index of a list of 7 is 6, not 7."),
        (2, "Which loop", "for item in list is tidier when you only need the values. Use range(len(list)) when you need the position too."),
        (3, "Removing safely", "Deleting from a list while looping over it makes the loop skip items. Build a new list instead."),
        (4, "The average of nothing", "An empty list has no average at all, so a robust program checks the length before it divides."),
        (5, "Lists inside lists", "A list can hold other lists, which is how a program stores a grid - and that is the next lesson.")],
  ws=dict(title="One-dimensional arrays", objectives=["know how to create a list and read one item out of it by its index",
      "understand how to traverse a list in order to total, count or compare its items",
      "know how to add an item onto a list and how to take one out again"],
    starter="The list shelf holds Nails, Screws, Bolts and Nuts, in that order. Write down what shelf[0], shelf[3] and len(shelf) each give, and the index of the last item.", starter_lines=4,
    keyterms=["Array", "Index", "Traverse", "append() and pop()"],
    keyq="Why is the last item of a list always at index len(list) - 1?",
    exam=[("A loop over a list of six prices begins for i in range(1, 6). State which price is never looked at, and rewrite the line so that every price is included.", 2, 4),
          ("Write a program that reads 6 javelin throws in metres into a list, then prints the longest throw and the position it is stored at.", 5, 11),
          ("Write a program that holds a list of five club members, removes a name the user types in, then prints the list and how many members are left.", 4, 10)],
    confidence=["Creating a list and reading an item by its index", "Traversing a list to total or compare its items", "Adding items to a list and removing them"]))

# ---------------------------------------------------------------- Lesson 8
L8 = dict(id="pr-l08", topic="PY", lesson=8, title="Seating plan hall", img="PR_L08_SeatingPlanHall_360",
  description="Two-dimensional arrays: a list of lists, reading a cell by row and column, nested loops over a grid, and totalling rows and columns.",
  kicker=f"{KPY}  |  Lesson 8", scene_title="Seating plan hall", subtitle=SUBPY,
  intro="A register, a seating plan and a scoreboard are all grids. A two-dimensional array stores one by putting a list inside a list, and the hall is where you learn to read and total it.",
  keywords=["Two-dimensional", "Array", "Row", "Column", "Nested loop", "Index"],
  stations=[
   stn("pr-l08", 0, ["A two-dimensional array is a list whose items are themselves lists.",
        "Each inner list is one row, and the rows normally all hold the same number of items.",
        "Mistake: expecting len() on a grid to count the cells, when it counts the rows."],
       "How many rows and how many columns does [[1, 2, 3], [4, 5, 6]] have?",
       ("code", ['grid = [[1, 2, 3],', '        [4, 5, 6]]', 'print(len(grid))', 'print(len(grid[0]))'], 26, [2, 3]),
       "A table in a database and a grid in a program are stored much the same way: rows made of fields."),
   stn("pr-l08", 1, ["grid[row][col] reads one cell, with the row first and the column second.",
        "grid[row] on its own gives back that whole row as a list.",
        "Mistake: swapping the two indexes over, which reads a completely different cell."],
       "Which index comes first when you read a cell, the row or the column?",
       ("table", ["", "col 0", "col 1", "col 2"], [["row 0", "4", "7", "2"], ["row 1", "5", "1", "9"]]),
       "The exam writes this cell as array[1,2]; Python writes exactly the same cell as grid[1][2]."),
   stn("pr-l08", 2, ["Two nested loops visit every cell: the outer picks the row, the inner the column.",
        "Print a new line after the inner loop ends, to start the next row.",
        "Mistake: putting that new line inside the inner loop, which prints one value per line."],
       "Which loop should be the outer one if you want to print row by row?",
       ("code", ['for r in range(2):', '    for c in range(3):', '        print(grid[r][c], end=" ")', '    print()'], 24, [0, 1]),
       "A grid of 10 rows by 10 columns holds 100 cells, so a nested loop over it runs 100 times."),
   stn("pr-l08", 3, ["To total one row, loop across the columns with the row index held still.",
        "sum(grid[r]) does the same job in one step, once you know which row you want.",
        "Mistake: letting the row index change inside the loop, which totals the wrong cells."],
       "Which index stays the same all the way through a row total?",
       ("code", ['total = 0', 'for c in range(4):', '    total = total + grid[1][c]', 'print(total)'], 26, [2]),
       "Totalling every row and then totalling those totals gives the grand total of the whole grid."),
   stn("pr-l08", 4, ["To total one column, loop down the rows with the column index held still.",
        "The loop runs once for every row, so its range is len(grid).",
        "Mistake: using the number of columns as the range when travelling down a column."],
       "Why does a column total loop over the rows rather than the columns?",
       ("code", ['total = 0', 'for r in range(3):', '    total = total + grid[r][2]', 'print(total)'], 26, [2]),
       "Swapping the two loops over turns a row total into a column total, and nothing else changes."),
   stn("pr-l08", 5, ["To search a grid, loop every cell and record the row and column where you found it.",
        "A found flag, set before the loops start, says whether anything matched at all.",
        "Mistake: reporting only the row when the task asks where in the row it was too."],
       "Plan how you would find a name in a seating plan and report its row.",
       ("flow", ["Loop the rows", "Loop the columns", "Record r and c", "Report"]),
       "Searching every cell of a grid in turn is a linear search, just in two dimensions."),
  ],
  final=dict(name="Final challenge: read the grid", floor_title="Final challenge: read the grid",
    intro="The scoreboard holds [[4, 7, 2], [5, 1, 9]] in a variable called grid. Tap the star and match each piece of Python to what it gives back.",
    ill=("table", ["", "col 0", "col 1", "col 2"], [["row 0", "4", "7", "2"], ["row 1", "5", "1", "9"]]),
    tasks=[match("The grid is [[4, 7, 2], [5, 1, 9]]. What does each piece of Python give back?", [
      ["len(grid)", "2 rows"], ["len(grid[0])", "3 columns"], ["grid[0][0]", "4"],
      ["grid[1][2]", "9"], ["grid[1]", "[5, 1, 9]"], ["sum(grid[0])", "13"]],
      "The row index always comes first, and both indexes count from 0.")]),
  info=[(0, "Rows first", "A grid is described as rows by columns, so a 3 by 4 grid has 3 rows of 4 items each."),
        (1, "Two notations", "Pseudocode in the exam writes a cell as array[1,2]. Python writes the same cell as grid[1][2]."),
        (2, "One long line", "Memory is one long line of addresses, so a grid is stored row after row. Reading along a row is the natural direction."),
        (3, "sum() a row", "sum() totals a list, so sum(grid[0]) totals a whole row in one step - but a column still needs a loop."),
        (4, "Ragged grids", "Nothing stops the rows being different lengths, though most tasks assume they match. Use len(grid[r]) if they might not."),
        (5, "Three dimensions", "A list of grids is a three-dimensional array, which is how a program might hold a seating plan for every week of term.")],
  ws=dict(title="Two-dimensional arrays", objectives=["know how to create a two-dimensional array as a list of lists",
      "understand how a row index and a column index together pick out one cell",
      "know how to use two nested loops to total a row, a column or a whole grid"],
    starter="The grid g holds two rows: 4, 9, 2 in the first and 7, 1, 6 in the second. Write down what g[0][2], g[1][0] and len(g) each give, and which row and column hold the 6.", starter_lines=4,
    keyterms=["Two-dimensional array", "Row and column", "Cell", "Nested loop"],
    keyq="Which index comes first when a program reads a cell, and why does swapping the two over give a different answer?",
    exam=[("A program that should total column 2 of a grid of 4 rows by 3 columns begins its loop with for r in range(len(grid[0])). Explain why this looks at the wrong number of cells, and write the line corrected.", 3, 5),
          ("Write a program that reads a grid of 3 rows by 4 columns of merit points and prints the total for each row.", 5, 11),
          ("Write a program that prints a grid of 2 rows by 3 columns of prices that is already stored in the program, one row to a line.", 4, 10)],
    confidence=["Creating a list of lists", "Reading a cell with a row index and a column index", "Totalling rows and columns with nested loops"]))

# ---------------------------------------------------------------- Lesson 9
L9 = dict(id="pr-l09", topic="PY", lesson=9, title="Assembly line", img="PR_L09_AssemblyLine_360",
  description="Subprograms: writing a procedure, passing values in through parameters, returning a value, and the difference between local and global variables.",
  kicker=f"{KPY}  |  Lesson 9", scene_title="Assembly line", subtitle=SUBPY,
  intro="Long programs are built out of small named parts. On the assembly line you will write procedures and functions, pass values into them and get answers back out.",
  keywords=["Subprogram", "Procedure", "Function", "Parameter", "Argument", "return", "Local", "Global"],
  stations=[
   stn("pr-l09", 0, ["def names a subprogram, and the indented block below it is what that subprogram does.",
        "Nothing happens until the name is called, with brackets after it.",
        "Mistake: defining a procedure and never calling it, so none of it ever runs."],
       "What is the difference between defining a procedure and calling it?",
       ("code", ['def signoff():', '    print("End of report")', '', 'signoff()'], 26, [0, 3]),
       "Writing a job once and calling it many times has a name of its own: code reuse."),
   stn("pr-l09", 1, ["A parameter in the brackets lets whoever calls the subprogram pass a value in.",
        "The value handed over is the argument, and inside it is used like any other variable.",
        "Mistake: giving the arguments in a different order from the parameters."],
       "Why is a procedure with a parameter more useful than one without?",
       ("code", ['def label(item, price):', '    print(item, price)', '', 'label("Juice", 60)'], 26, [0, 3]),
       "The names in the definition are the parameters; the values handed over when it is called are the arguments."),
   stn("pr-l09", 2, ["return hands a value back to whatever called the subprogram.",
        "The call can then be stored in a variable, printed, or used inside a bigger sum.",
        "Mistake: printing inside when the task says return, so nothing is handed back."],
       "Why would a task insist a subprogram returns a value rather than prints it?",
       ("code", ['def area(w, h):', '    return w * h', '', 'print(area(3, 4))'], 26, [1, 3]),
       "return ends the subprogram there and then, so any line written after it never runs."),
   stn("pr-l09", 3, ["A function returns a value; a procedure just does a job and returns nothing.",
        "Both are subprograms, and in Python both are written with def.",
        "Mistake: calling something a function when all it does is print."],
       "Decide whether each subprogram in your program is a function or a procedure.",
       ("compare", "Function", ["Returns a value", "return w * h"], "Procedure", ["Returns nothing", "print(w * h)"], "g", "b"),
       "The exam marks this difference, so say 'function' only when a value actually comes back."),
   stn("pr-l09", 4, ["A variable made inside a subprogram is local: it exists only while that subprogram runs.",
        "A global variable belongs to the main program, and global lets a subprogram change it.",
        "Mistake: expecting a local variable's value to survive after the subprogram ends."],
       "Why can two subprograms both use a variable called total without clashing?",
       ("code", ['score = 0', '', 'def win():', '    global score', '    score = score + 3'], 26, [3]),
       "Keeping variables local is good practice: it stops one part of a program quietly breaking another."),
   stn("pr-l09", 5, ["A subprogram may call another one, so a big job splits into small named steps.",
        "Calling a function inside a loop lets one piece of code answer the same question many times.",
        "Mistake: repeating the same lines instead of writing one subprogram and calling it."],
       "Plan which parts of a booking receipt program should become subprograms.",
       ("flow", ["main", "receipt()", "line_total()", "Return a value"]),
       "Breaking a problem into named parts is decomposition, which you met in topic 2.1."),
  ],
  final=dict(name="Final challenge: function or procedure?", floor_title="Final challenge: function or procedure?",
    intro="Eight subprograms have come off the line. Tap the star and decide whether each one is a function or a procedure.",
    ill=("flow", ["Call it", "Do the job", "Return a value?", "Back to main"]),
    tasks=[sort("Is each subprogram a function or a procedure?", ["Function", "Procedure"], [
      ["Works out an area and returns it", "Function"], ["Prints a horizontal rule", "Procedure"],
      ["Returns pass or fail for a mark", "Function"], ["Prints a stock label", "Procedure"],
      ["Gives back double a number", "Function"], ["Adds 3 to a global score", "Procedure"],
      ["Returns the total of a list", "Function"], ["Prints a sign-off line", "Procedure"]],
      "If a value comes back it is a function. If it only does a job, it is a procedure.")]),
  info=[(0, "Why bother", "A job written once and called from four places is tested once and fixed once. The same lines copied four times are four bugs waiting to happen."),
        (1, "Default values", "A parameter can be given a default, so label(\"Juice\") still works when the price is usually the same."),
        (2, "Returning more", "return can hand back several values at once, separated by commas, and the caller unpacks them."),
        (3, "Already written", "len(), int() and round() are functions somebody else wrote: you call them exactly the way you call your own."),
        (4, "Globals are risky", "Any subprogram can change a global, so one bug can break all of them. Parameters and return values are safer."),
        (5, "Calling itself", "A subprogram is even allowed to call itself. That is called recursion, and it is how a merge sort splits a list.")],
  ws=dict(title="Subprograms: procedures and functions", objectives=["know how to define a subprogram with def and how to call it",
      "understand how a parameter passes a value into a subprogram and how return passes one back out",
      "know the difference between a local variable and a global one"],
    starter="A program defines a subprogram called banner with one print line inside it, and then stops. Nothing is printed when it runs. Explain why, and write down the line that has been left out.", starter_lines=3,
    keyterms=["Subprogram", "Parameter and argument", "return", "Local and global variable"],
    keyq="When should a subprogram return a value rather than print one?",
    exam=[("A subprogram called vat takes an amount and its last line is print(amount * 0.2). The main program writes tax = vat(50) and then prints tax, which shows None. Explain why, and write the change needed inside the subprogram.", 3, 5),
          ("Write a function that takes a length and a width in metres and returns the area, and a main program that uses it to print the area of two different rooms.", 5, 11),
          ("Write a procedure that takes a pupil's name and a score and prints one tidy line of a results table, then call it for three different pupils.", 4, 10)],
    confidence=["Defining a subprogram and calling it", "Passing values in with parameters and back with return", "Telling a local variable from a global one"]))

# ---------------------------------------------------------------- Lesson 10
L10 = dict(id="pr-l10", topic="PY", lesson=10, title="Records office", img="PR_L10_RecordsOffice_360",
  description="File handling: opening a file, reading it whole or line by line, the write and append modes, and splitting a line of records into its fields.",
  kicker=f"{KPY}  |  Lesson 10", scene_title="Records office", subtitle=SUBPY,
  intro="Data in variables disappears the moment a program ends. A file keeps it, and the records office is where you learn to open one, read it, write it and search it.",
  keywords=["File handling", "open()", "read()", "readlines()", "Write mode", "Append mode", "Record", "Field"],
  stations=[
   stn("pr-l10", 0, ["open(name, \"r\") opens a file for reading and hands back a file object.",
        ".read() gives the whole file as one string, and .close() lets go of it when you are done.",
        "Mistake: opening a file that is not there, which stops the program with an error."],
       "Why should a program close a file as soon as it has finished with it?",
       ("icons", [("disk", "File"), ("form", "Records"), ("pc", "Program")]),
       "A file left open can keep other programs out, and may lose data that was not written yet."),
   stn("pr-l10", 1, [".readline() reads one line, while .readlines() gives a list of every line.",
        "Each line still carries its newline, so .strip() tidies that off before you use it.",
        "Mistake: measuring a line before stripping it, which counts the newline as a character."],
       "Why is a stripped line one character shorter than the line that was read?",
       ("code", ['f = open("log.txt", "r")', 'lines = f.readlines()', 'f.close()', 'print(len(lines))'], 24, [1]),
       "A newline is one single invisible character, which is why a stripped line comes out shorter."),
   stn("pr-l10", 2, ["open(name, \"w\") opens a file for writing and empties whatever was in it.",
        ".write() adds no newline of its own, so put a newline on the end of each line yourself.",
        "Mistake: using write mode on a file you meant to add to, which wipes it completely."],
       "What happens to the contents of a file the moment it is opened in w mode?",
       ("code", ['f = open("report.txt", "w")', 'f.write("Line one")', 'f.write("Line two")', 'f.close()'], 24, [0]),
       "Write mode creates the file if it is not there, which is handy and dangerous in equal measure."),
   stn("pr-l10", 3, ["open(name, \"a\") is append mode: new text goes on the end and nothing is lost.",
        "Logs are always appended, so yesterday's entries are still there tomorrow.",
        "Mistake: leaving the newline out, so the new entry runs straight into the last one."],
       "Which mode would a visitor log use, and why that one?",
       ("compare", "Mode w", ["Empties the file", "Starts again"], "Mode a", ["Keeps the file", "Adds to the end"], "r", "g"),
       "Three modes cover everything you need: r to read, w to write from scratch and a to add on the end."),
   stn("pr-l10", 4, ["A record is one line of the file, and its fields are the parts separated by a comma.",
        ".split(\",\") breaks a line into a list of its fields.",
        "Mistake: splitting before stripping, which leaves a newline stuck on the last field."],
       "How does a program find the record for one particular name?",
       ("code", ['line = line.strip()', 'fields = line.split(",")', 'if fields[0] == wanted:', '    print(fields[1])'], 24, [1]),
       "A file of comma-separated records is a CSV file, and a spreadsheet will open one straight away."),
   stn("pr-l10", 5, ["Read the whole file first, close it, then work on the lines you are holding.",
        "A program can read one file and write a second one in the same run.",
        "Mistake: looping over a file you have already closed, or reading and writing one file at once."],
       "Plan the two files a sales report program would need.",
       ("flow", ["Read the file", "Work each record", "Write a report", "Read it back"]),
       "Skipping blank lines is worth doing every time: a stray newline at the end of a file is very common."),
  ],
  final=dict(name="Final challenge: which mode?", floor_title="Final challenge: which mode?",
    intro="Eight jobs have reached the records office. Tap the star and choose the file mode each one needs.",
    ill=("flow", ["open()", "read or write", "close()"]),
    tasks=[sort("Which file mode does each job need?", ["r", "w", "a"], [
      ["Print a notice that is already saved", "r"], ["Count the lines of a log", "r"],
      ["Create a fresh report, replacing the old one", "w"], ["Save a list of totals from scratch", "w"],
      ["Add today's visitor to the end of the log", "a"], ["Record one more reading without losing the others", "a"],
      ["Search the records for a name", "r"], ["Start a new alerts file", "w"]],
      "r reads, w starts again from empty, and a adds on the end.")]),
  info=[(0, "Where it looks", "A program looks for a file in the folder it is running in, unless you give it a fuller path."),
        (1, "One line at a time", "Looping straight over the file object reads it a line at a time, which matters when a file is too big to fit in memory."),
        (2, "No undo", "Write mode empties the file the instant it opens, before you have written anything at all."),
        (3, "Why logs append", "A log is evidence of what happened. Appending adds an entry without touching anything already written."),
        (4, "A table in disguise", "A file of records is a table: each line is a row and each field is a column."),
        (5, "Closing safely", "Python's with open(...) as f: closes the file for you, even if the program hits an error part way through.")],
  ws=dict(title="File handling", objectives=["know how to open a text file, read what is in it and close it again",
      "understand the difference between write mode and append mode",
      "know how to split one line of a file into its separate fields"],
    starter="A program opens scores.txt in write mode, and the file already holds 40 lines of results. Write down what the file holds the moment that line has run, and which mode should have been used to add to it instead.", starter_lines=3,
    keyterms=["Append mode", "Record", "Field", "split()"],
    keyq="Why does the mode a file is opened in matter more than anything else on that line?",
    exam=[("Every line read from a file is measured with len(), and each answer comes out one character bigger than expected. Name the character being counted, and write the line that removes it.", 2, 4),
          ("Write a program that adds a new visitor's name onto the end of log.txt without losing the names already in it, and then prints the whole file.", 4, 10),
          ("Each line of members.txt holds a name and an age, separated by a comma. Write a program that prints the name of every member aged 16 or over.", 5, 11)],
    confidence=["Opening, reading and closing a file", "Choosing between write mode and append mode", "Splitting a record into its fields"]))

# ---------------------------------------------------------------- Lesson 11
L11 = dict(id="pr-l11", topic="PY", lesson=11, title="Sorting depot", img="PR_L11_SortingDepot_360",
  description="Code the standard algorithms yourself: linear and binary search, then bubble, insertion and merge sort, and count the comparisons each one needs.",
  kicker=f"{KPY}  |  Lesson 11", scene_title="Sorting depot", subtitle=SUBPY,
  intro="You met these algorithms in topic 2.1 and traced them on paper. Now you will write them. At the sorting depot every search and every sort is yours to code, not just to describe.",
  keywords=["Linear search", "Binary search", "Bubble sort", "Insertion sort", "Merge sort", "Pass", "Comparison"],
  stations=[
   stn("pr-l11", 0, ["A linear search checks each item in turn until it finds the one it wants.",
        "It works on any list, in order or not, and reports the position or that nothing matched.",
        "Mistake: printing 'not found' inside the loop, once for every item that did not match."],
       "Why must 'not found' be decided after the loop has finished?",
       ("code", ['for i in range(len(nums)):', '    if nums[i] == wanted:', '        print(i)', '        found = True'], 24, [1]),
       "A linear search over a million items may need a million comparisons, which is why sorted data is worth having."),
   stn("pr-l11", 1, ["A binary search looks at the middle item, then throws away the half that cannot hold the answer.",
        "It only works on a list that is already in order.",
        "Mistake: not moving low or high, which leaves the loop checking the same middle forever."],
       "How much of the list can a binary search rule out with its first comparison?",
       ("code", ['while low <= high:', '    mid = (low + high) // 2', '    if nums[mid] < wanted:', '        low = mid + 1'], 24, [1]),
       "Doubling the list adds only one more comparison, so a million items need about twenty."),
   stn("pr-l11", 2, ["A bubble sort compares each neighbouring pair and swaps them if they are the wrong way round.",
        "Every pass pushes the largest remaining value to the end, so n items need up to n - 1 passes.",
        "Mistake: a swap that loses a value, because one side was overwritten before it was copied."],
       "How does a bubble sort know that it can stop early?",
       ("code", ['for i in range(len(n) - 1):', '    if n[i] > n[i + 1]:', '        n[i], n[i + 1] = n[i + 1], n[i]'], 24, [2]),
       "A whole pass with no swaps at all means the list is already in order, so the sort can stop there."),
   stn("pr-l11", 3, ["An insertion sort takes the next item and slides it back into place among the sorted ones.",
        "The front of the list is always in order, and it grows by one item each time round.",
        "Mistake: overwriting an item instead of shifting it along to make room."],
       "Which part of the list is already sorted part way through an insertion sort?",
       ("code", ['for i in range(1, len(n)):', '    v = n[i]', '    j = i - 1', '    while j >= 0 and n[j] > v:'], 24, [1]),
       "An insertion sort is how most people sort a hand of cards without ever being taught to."),
   stn("pr-l11", 4, ["A merge sort splits the list in half over and over, then merges the pieces back in order.",
        "Merging compares the front of each sorted list and takes the smaller one each time.",
        "Mistake: stopping when one list runs out, instead of copying the rest of the other."],
       "Why is merging two sorted lists easier than sorting one unsorted one?",
       ("code", ['while i < len(a) and j < len(b):', '    if a[i] <= b[j]:', '        out.append(a[i])', '        i = i + 1'], 22, [1]),
       "A merge sort usually beats a bubble sort, but it needs extra memory to hold the pieces."),
   stn("pr-l11", 5, ["Count the comparisons to compare two algorithms fairly on exactly the same data.",
        "A binary search needs sorted data, so sort the list first and search it afterwards.",
        "Mistake: binary searching an unsorted list, which quietly gives the wrong answer."],
       "Plan an experiment that shows a binary search beating a linear one.",
       ("compare", "Linear search", ["Any list at all", "Up to n checks"], "Binary search", ["Sorted list only", "About 20 per million"], "o", "g"),
       "Sorting costs time too, so for one single search a linear search of unsorted data can still win."),
  ],
  final=dict(name="Final challenge: which algorithm?", floor_title="Final challenge: which algorithm?",
    intro="Eight descriptions have arrived at the depot. Tap the star and sort each one into the algorithm it describes.",
    ill=("tiles", [("Linear", "b"), ("Binary", "g"), ("Bubble", "p"), ("Merge", "o")], 4),
    tasks=[sort("Which algorithm does each description belong to?", ["Linear", "Binary", "Bubble", "Merge"], [
      ["Checks every item in turn", "Linear"], ["Works on an unsorted list", "Linear"],
      ["Halves the list at every step", "Binary"], ["Needs the data in order first", "Binary"],
      ["Swaps neighbouring pairs", "Bubble"], ["Counts passes until none swap", "Bubble"],
      ["Splits the list right down, then joins it back", "Merge"], ["Joins two sorted lists into one", "Merge"]],
      "Two of these search and two of these sort, and only one of the searches needs sorted data.")]),
  info=[(0, "The found flag", "A flag set to False before the loop is the tidiest way to report 'not found' exactly once."),
        (1, "Whole middles only", "mid = (low + high) // 2 uses // so the middle is a whole number: a list index can never be 3.5."),
        (2, "Swapping in one line", "Python can swap two values in one line with a, b = b, a. Most languages need a third variable to hold one of them."),
        (3, "Nearly sorted", "On a list that is almost in order an insertion sort is very quick, because hardly anything has to move."),
        (4, "Divide and conquer", "Splitting a problem into smaller copies of itself is called divide and conquer, and merge sort is the classic example."),
        (5, "When it matters", "On a short list any sort is fast enough. The difference only shows up on large data - which is where the exam questions live.")],
  ws=dict(title="Coding the search and sort algorithms", objectives=["know how to code a linear search and a binary search",
      "understand how a bubble sort, an insertion sort and a merge sort each put a list in order",
      "know why a binary search needs its list to be in order before it starts"],
    starter="The sorted list holds 3, 8, 12, 19, 24, 31, 40. Write down the item a binary search looks at first, second and third while hunting for 31, and how many comparisons that took.", starter_lines=4,
    keyterms=["Linear search", "Binary search", "Pass", "Comparison"],
    keyq="Why is a binary search so much faster than a linear search on a long list, and what does using one cost you?",
    exam=[("A linear search prints Not found from inside its loop, so searching one list prints that message several times. State where the message should go instead, and explain why putting it there fixes the problem.", 3, 5),
          ("Write a program that reads 8 whole numbers into a list, puts them in order using a bubble sort, and prints the sorted list.", 6, 13),
          ("Write a program that uses a binary search to look for a membership number the user types in, within a list of 10 numbers already in order, and prints its position or Not found.", 6, 13)],
    confidence=["Coding a linear search and a binary search", "Coding a bubble, insertion or merge sort", "Explaining why a binary search needs sorted data"]))

# ---------------------------------------------------------------- Lesson 12
L12 = dict(id="pr-l12", topic="PY", lesson=12, title="Gatehouse", img="PR_L12_Gatehouse_360",
  description="Write the validation a robust program needs: presence, type, range, length and format checks, loops that keep asking, and authentication.",
  kicker=f"{KPY}  |  Lesson 12", scene_title="Gatehouse", subtitle=SUBPY,
  intro="Users mistype, and some of them try it on. At the gatehouse you will write the checks that keep bad data out and the loops that keep asking until the data is right.",
  keywords=["Validation", "Presence check", "Type check", "Range check", "Length check", "Format check", "Authentication"],
  stations=[
   stn("pr-l12", 0, ["A presence check refuses input that is empty once any stray spaces are stripped off.",
        "A type check uses isdigit(), so text typed where a number was wanted cannot crash the program.",
        "Mistake: casting with int() before checking, which stops the program instead of rejecting the value."],
       "Why must a type check happen before the value is cast?",
       ("code", ['name = input().strip()', 'if name == "":', '    print("nothing entered")'], 26, [1]),
       "Validation checks data is sensible, not that it is true: a wrong but sensible date passes every check."),
   stn("pr-l12", 1, ["A range check refuses anything that falls outside the allowed limits.",
        "Inclusive limits need >= and <=, so the boundary values themselves are accepted.",
        "Mistake: using > where the rule says 'or more', which rejects a perfectly valid boundary."],
       "Which two values would you test on a score that must be 1 to 10?",
       ("code", ['if score < 1 or score > 10:', '    print("out of range")', 'else:', '    print("ok")'], 26, [0]),
       "Negative values are fine for a temperature but never for an age, so a range check must suit its data."),
   stn("pr-l12", 2, ["A length check counts the characters with len(), against a minimum and a maximum.",
        "A format check tests the pattern: which positions must be letters and which must be digits.",
        "Mistake: checking the pattern before the length, which can read past the end of the string."],
       "Describe the checks a reference of two letters then four digits needs.",
       ("code", ['ref = input()', 'if len(ref) != 6:', '    print("wrong length")', 'elif not ref[0:2].isalpha():', '    print("wrong format")'], 22, [1, 3]),
       "isalpha(), isdigit() and isnumeric() each answer one format question about a whole string at once."),
   stn("pr-l12", 3, ["A validation loop reads once, then repeats for as long as the value breaks a rule.",
        "Saying which rule was broken makes the program far easier to use.",
        "Mistake: leaving the second input() out, so the loop tests the same bad value forever."],
       "Why should a program say what was wrong rather than just 'invalid'?",
       ("code", ['n = input()', 'while not n.isdigit():', '    print("digits only")', '    n = input()'], 26, [1, 3]),
       "A loop that keeps asking until the data is right is the simplest defensive design there is."),
   stn("pr-l12", 4, ["Authentication checks who the user is, usually with a username and a password.",
        "An attempt counter lets a program lock the account after a set number of tries.",
        "Mistake: counting the attempts but never stopping, so guessing can carry on forever."],
       "What is the difference between validation and authentication?",
       ("pair", "user", "lock", "User", "Account", "Password tried", "Access granted"),
       "Validation checks data and authentication checks people, and the exam asks for that difference often."),
   stn("pr-l12", 5, ["Validate each value in its own loop before the program moves on to the next one.",
        "A program that keeps going when one line of data is wrong is more useful than one that stops.",
        "Mistake: validating at the end, when the first bad value has already been used."],
       "Plan the checks a club sign-up needs for a username and an age.",
       ("flow", ["Read a value", "Check the rules", "Ask again?", "Use it"]),
       "Skipping a bad line and counting it is often better than stopping: the report still comes out."),
  ],
  final=dict(name="Final challenge: which check?", floor_title="Final challenge: which check?",
    intro="Eight rules are pinned up in the gatehouse. Tap the star and sort each one into the kind of check it is.",
    ill=("tiles", [("Presence", "b"), ("Type", "g"), ("Range", "p"), ("Length", "o"), ("Format", "k")], 3),
    tasks=[sort("Which kind of check is each rule?", ["Presence", "Type", "Range", "Length", "Format"], [
      ["The field has not been left empty", "Presence"], ["Something was typed before Enter", "Presence"],
      ["The value is a whole number", "Type"], ["The reading is a number, not a word", "Type"],
      ["The score is from 1 to 10", "Range"], ["The password is 8 to 16 characters", "Length"],
      ["The reference is two letters then four digits", "Format"], ["The date is written as DD/MM/YYYY", "Format"]],
      "A length check counts characters; a format check tests the pattern they make.")]),
  info=[(0, "Strip it first", "A stray space is still a character, so a presence check should strip the input before testing it for empty."),
        (1, "Inclusive means both", "'From 1 to 10 inclusive' means 1 and 10 both pass. Test them: that is exactly what boundary data is for."),
        (2, "Length, then format", "Checking the length first means a format check can safely look at a particular position in the string."),
        (3, "Three tries", "Locking an account after three wrong passwords stops a program being guessed at one attempt at a time."),
        (4, "Never stored plainly", "Real systems never keep a password as it was typed. They store a hash of it, which cannot be read back."),
        (5, "Keep going", "A program that skips a bad line and says how many it skipped is more useful than one that stops at the first problem.")],
  ws=dict(title="Writing validation and authentication", objectives=["know how to code a presence, type, range, length and format check",
      "understand how a validation loop keeps asking until the value typed in passes every check",
      "know how to code an authentication check that allows only a set number of attempts"],
    starter="A program reads an age with age = int(input()) and the user types the word twelve. Write down what happens to the program, and the check that should have come before the cast.", starter_lines=3,
    keyterms=["Validation", "Format check", "Validation loop", "Authentication"],
    keyq="Why is refusing bad data better than letting a program stop with an error?",
    exam=[("A range check for a satisfaction score that must be from 1 to 10 inclusive is written if score > 1 and score < 10. State the two scores this wrongly refuses, and write the condition corrected.", 3, 5),
          ("Write a program that keeps asking for a tutor group code of exactly one letter followed by two digits until a valid one is typed.", 6, 13),
          ("Write a program that allows three attempts at the four-digit passcode 2471, and prints Locked if all three attempts are wrong.", 5, 11)],
    confidence=["Coding a presence, type and range check", "Coding a length check and a format check", "Writing a validation loop and an authentication check"]))

# ---------------------------------------------------------------- Lesson 13
L13 = dict(id="pr-l13", topic="PY", lesson=13, title="Query desk", img="PR_L13_QueryDesk_360",
  description="Ask a database a question with SQL: SELECT and FROM, filtering with WHERE, comparing values, joining conditions with AND and OR, and sorting with ORDER BY.",
  kicker=f"{KPY}  |  Lesson 13", scene_title="Query desk", subtitle=SUBPY,
  intro="A database holds far more than a program could ever keep in memory, and SQL is how you ask it a question. At the query desk you will write queries against a table of games.",
  keywords=["SQL", "Database", "Table", "Field", "Record", "SELECT", "FROM", "WHERE", "ORDER BY"],
  stations=[
   stn("pr-l13", 0, ["SELECT names the fields you want, and FROM names the table they live in.",
        "SELECT * means every field, and with no WHERE every record comes back.",
        "Mistake: listing the fields in the wrong order, since results come out in the order you asked for."],
       "Which part of a query decides how many records come back?",
       ("code", ['SELECT title', 'FROM games', '', 'SELECT title, players', 'FROM games'], 26, [0, 3]),
       "SQL stands for Structured Query Language, and it is a language for asking rather than for programming."),
   stn("pr-l13", 1, ["WHERE filters the records, keeping only the ones whose condition is true.",
        "Text to match goes inside quotes, and numbers do not.",
        "Mistake: leaving the quotes off text, so SQL looks for a field with that name instead."],
       "Which records come back from a query that has no WHERE at all?",
       ("code", ['SELECT title', 'FROM games', "WHERE kind = 'card'"], 28, [2]),
       "WHERE looks at each record on its own and decides whether to keep it or drop it."),
   stn("pr-l13", 2, ["The comparisons are =, <>, >, <, >= and <=, and they work on numbers and on text.",
        "'Longer than 45' is > 45, but '45 or longer' is >= 45.",
        "Mistake: using > where the question says 'or more', which loses the boundary record."],
       "Write the WHERE clause for games lasting 45 minutes or longer.",
       ("table", ["Wording", "SQL"], [["longer than 45", "> 45"], ["45 or longer", ">= 45"],
        ["under 20", "< 20"], ["not a card game", "<> 'card'"]]),
       "SQL writes 'not equal to' as <>, where Python writes it as !=."),
   stn("pr-l13", 3, ["AND keeps a record only when both conditions hold; OR keeps it when either one does.",
        "Brackets make the meaning clear when AND and OR appear in the same WHERE.",
        "Mistake: using AND where the question means OR, which often gives no records at all."],
       "Why would AND give nothing for 'under 20 minutes or over 60'?",
       ("code", ['SELECT title', 'FROM games', "WHERE kind = 'card'", 'AND players >= 3'], 26, [2, 3]),
       "AND narrows the results down and OR widens them out, which is worth saying out loud as you write."),
   stn("pr-l13", 4, ["ORDER BY sorts the results by a field, smallest or earliest first.",
        "DESC reverses that, so the largest or latest comes first instead.",
        "Mistake: putting ORDER BY before WHERE, when it always comes last."],
       "Which clause lists the longest games first?",
       ("code", ['SELECT title, minutes', 'FROM games', 'ORDER BY minutes', '', 'ORDER BY minutes DESC'], 24, [2, 4]),
       "Ascending is the default order, which SQL calls ASC, so it is almost never typed out."),
   stn("pr-l13", 5, ["The clauses always come in the order SELECT, FROM, WHERE, ORDER BY.",
        "Build a query one clause at a time and check what comes back at every step.",
        "Mistake: mixing up the quotes, so a word is read as a field name and the query finds nothing."],
       "Write a query for games that are not card games and last an hour or less, longest first.",
       ("flow", ["SELECT", "FROM", "WHERE", "ORDER BY"]),
       "One line of SQL can do the work of a loop, an if statement and a sort put together."),
  ],
  final=dict(name="Final challenge: build the query", floor_title="Final challenge: build the query",
    intro="The table games has the fields title, kind, players and minutes. Tap the star and put the clauses of one query into the order SQL needs them.",
    ill=("table", ["title", "kind", "players", "minutes"], [["Hedge Maze", "strategy", "4", "75"],
         ["Tide Pools", "card", "2", "20"], ["Night Market", "party", "8", "45"]]),
    tasks=[order("Put these clauses into the order SQL needs them.",
      ["SELECT title, minutes", "FROM games", "WHERE kind <> 'card'", "AND minutes <= 60", "ORDER BY minutes DESC"],
      "SELECT, FROM, WHERE and then ORDER BY - always in that order.")]),
  info=[(0, "Asking, not telling", "SQL says what you want, not how to get it. The database works the steps out for itself."),
        (1, "Quotes matter", "WHERE kind = card looks for a field called card and fails. WHERE kind = 'card' looks for the word."),
        (2, "Boundaries again", "'Over 60' and '60 or more' are different queries. The off-by-one that bites in Python bites here too."),
        (3, "Use brackets", "WHERE a AND b OR c can mean two different things, and brackets say which one you meant."),
        (4, "Sorting text", "ORDER BY on a text field sorts alphabetically, which is how a list of names is put into order."),
        (5, "Why a database", "A database holds far more than a program's memory, and many people can query the same table at the same time.")],
  ws=dict(title="Querying a database with SQL", objectives=["know how SELECT and FROM choose the fields and the table a query reads",
      "understand how WHERE decides which records a query hands back",
      "know how to join conditions with AND and OR, and how to sort results with ORDER BY"],
    starter="A table called Tree holds the fields Name, Height and Native, and 30 records. Write down how many fields and how many records come back from SELECT Name, Height FROM Tree, and which clause you would add to cut the records down.", starter_lines=3,
    keyterms=["SQL", "Record and field", "WHERE", "ORDER BY"],
    keyq="Which clause of a query decides which fields come back, and which clause decides which records?",
    exam=[("A query is written SELECT Title FROM Game ORDER BY Length WHERE Players = 2. State the error in it, and write the query out corrected.", 2, 4),
          ("A table called Track holds the fields Title, Artist, Seconds and Genre. Write a query that lists the title and artist of every track longer than 240 seconds, longest first.", 4, 6),
          ("Using the same Track table, write a query that lists the title of every track that is Jazz or Blues and lasts under 180 seconds.", 4, 6)],
    confidence=["Writing a SELECT ... FROM query", "Filtering records with WHERE", "Using AND, OR and ORDER BY"]))
