from kit import mcq, multi, sort, match, order

K12 = "1.2 Memory and storage"
SUB12 = "OCR J277 Paper 1  |  Computer systems"
def convert(q, frm, to, value, fb=""): return dict(t="convert", q=q, **{"from": frm}, to=to, value=value, fb=fb)
def pixels(q, target, fb="", depth=1, title=None):
    h = len(target); w = len(target[0])
    return dict(t="pixels", q=q, w=w, h=h, depth=depth, target=target, fb=fb, title=title or "Colour the grid")
def sound(q, samples=8, depth=3, fb="", title=None, waveSrc=None):
    d = dict(t="sound", q=q, samples=samples, depth=depth, fb=fb, title=title or "Sample the sound wave")
    if waveSrc: d["waveSrc"] = waveSrc
    return d

SMILE = [[0,0,1,1,1,1,0,0],[0,1,0,0,0,0,1,0],[1,0,1,0,0,1,0,1],[1,0,0,0,0,0,0,1],[1,0,1,0,0,1,0,1],[1,0,0,1,1,0,0,1],[0,1,0,0,0,0,1,0],[0,0,1,1,1,1,0,0]]
ARROW = [[0,0,0,1,1,0,0,0],[0,0,1,1,1,1,0,0],[0,1,1,1,1,1,1,0],[1,1,0,1,1,0,1,1],[0,0,0,1,1,0,0,0],[0,0,0,1,1,0,0,0],[0,0,0,1,1,0,0,0],[0,0,0,1,1,0,0,0]]
FLAG4 = [[3,3,3,3,3,3,0,0],[3,1,1,1,1,3,0,0],[3,1,2,2,1,3,0,0],[3,1,2,2,1,3,0,0],[3,1,1,1,1,3,0,0],[3,3,3,3,3,3,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]]
STRIPES = [[1,1,1,1,1,1,1,1],[0,0,0,0,1,1,1,1],[1,1,0,0,0,0,1,1],[0,0,0,0,0,0,0,0],[1,1,1,1,0,0,0,0],[0,0,1,1,1,1,0,0],[1,1,1,1,1,1,1,1],[0,0,0,0,0,0,0,0]]

L13 = dict(id="ms-lesson13", topic="1.2", lesson=13, title="Pixel studio", img="MS_L13_PixelStudio",
  description="Colour pixels and watch the bits add up: resolution, colour depth, metadata and image file size.",
  kicker=f"{K12}  |  Lesson 13", scene_title="Pixel studio", subtitle=SUB12,
  intro="Zoom in far enough and every image is a grid of coloured squares, each stored as a binary number. Colour your own, and see exactly how the file size is built.",
  keywords=["Pixel", "Bitmap", "Resolution", "Colour depth", "Metadata", "File size"],
  stations=[
   dict(name="Pixels and bitmaps", bullets=["A bitmap image is a grid of pixels.", "Each pixel's colour is stored as a binary number.",
        "The computer rebuilds the image by colouring each pixel in turn."], challenge="Colour the grid to match the image on the wall.",
        ill=("tiles", [("1 = white", "n"), ("0 = black", "b")], 2), fact="A bitmap image is...",
        tasks=[pixels("Colour the grid to match the image. Each pixel is 1 bit: black is 0 and white is 1.", SMILE, "This image is 8 × 8 × 1 = 64 bits, which is 8 bytes."),
               mcq("What is a pixel?", "A single point of colour in an image", ["A type of file", "A unit of storage", "A colour palette"], "Picture element: the smallest part of a bitmap.")]),
   dict(name="Colour depth", bullets=["Colour depth is the number of bits used for each pixel.", "1 bit gives 2 colours; 2 bits give 4; 8 bits give 256; 24 bits give over 16 million.",
        "The number of colours is 2 to the power of the colour depth."], challenge="How many colours can be stored with a colour depth of 4 bits?",
        ill=("table", ["Colour depth", "Colours"], [["1 bit", "2"], ["2 bits", "4"], ["8 bits", "256"], ["24 bits", "16,777,216"]]), fact="Colour depth is...",
        tasks=[pixels("This image uses a colour depth of 2 bits, so four colours. Copy it.", FLAG4, "Four colours need 2 bits per pixel: 00, 01, 10 and 11.", depth=2),
               mcq("How many colours can a colour depth of 8 bits represent?", "256", ["8", "64", "1,024"], "2 to the power 8.")]),
   dict(name="Resolution", bullets=["Resolution is the number of pixels in the image, usually written width × height.",
        "More pixels means more detail, and a bigger file.", "Doubling the width and height makes the file four times bigger."],
        challenge="A 400 × 300 image is doubled in both directions. How many times bigger is the file?", ill=("compare", "Low resolution", ["Fewer pixels", "Blocky", "Small file"], "High resolution", ["More pixels", "Detailed", "Big file"], "o", "g"),
        fact="Resolution is...",
        tasks=[mcq("What does resolution mean?", "The number of pixels in the image, width × height", ["The number of colours available", "The size of the screen", "How fast the image loads"],
                   "Don't confuse it with colour depth."),
               mcq("An image is doubled in width and in height. What happens to the file size?", "It becomes four times larger", ["It doubles", "It stays the same", "It halves"],
                   "Twice the width and twice the height gives four times as many pixels.")]),
   dict(name="Metadata", bullets=["Metadata is data about the data: information stored with the image.",
        "Examples: width, height, colour depth, file type, date created, camera settings and sometimes GPS location.", "Without it, the computer wouldn't know how to display the pixels."],
        challenge="State four items of metadata for a photo.", ill=("table", ["Metadata", "Example"], [["Width", "1920"], ["Height", "1080"], ["Colour depth", "24 bits"], ["Date", "12/05/2026"]]),
        fact="Metadata is...",
        tasks=[multi("Which of these are examples of image metadata? Select all that apply.", ["The image's width and height", "The colour depth", "The date the photo was taken",
                     "The camera settings used", "The colour of each pixel", "The monitor's brightness"],
                     ["The image's width and height", "The colour depth", "The date the photo was taken", "The camera settings used"],
                     "The pixel colours are the data itself, not metadata."),
               mcq("Why does an image file need metadata?", "So the computer knows the dimensions and colour depth needed to rebuild the image", ["To make the file bigger", "To store the pixels twice", "To stop the image being copied"],
                   "Without the width, the computer wouldn't know where each row ends.")]),
   dict(name="Calculating file size", bullets=["File size in bits = width × height × colour depth.", "Divide by 8 for bytes, then by 1,000 for kilobytes.",
        "Real files are a little larger because of metadata."], challenge="Calculate the raw size of the image you coloured in, in bits and bytes.",
        ill=("code", ["size = width × height × colour depth", "8 × 8 × 1 = 64 bits", "64 ÷ 8 = 8 bytes"], 28), fact="Image file size is calculated by...",
        tasks=[mcq("A 200 × 100 image has a colour depth of 4 bits. What is its size in bits?", "80,000", ["20,000", "800", "160,000"], "200 × 100 × 4."),
               mcq("That image is how many bytes?", "10,000", ["80,000", "1,250", "20,000"], "80,000 ÷ 8 = 10,000 bytes.")]),
   dict(name="Quality against size", bullets=["Increasing resolution or colour depth improves quality but increases file size.",
        "Choose the lowest that still looks good enough for the job.", "A website icon needs far less than a poster."],
        challenge="Why might a website use a lower resolution image than a printed poster?", ill=("flow", ["More pixels", "More colours", "Better quality", "Bigger file"]),
        fact="Quality and file size are linked because...",
        tasks=[pixels("Copy this arrow icon. It's 1-bit, so just black and white.", ARROW, "Simple icons don't need many colours: 64 bits is plenty."),
               mcq("Which change would make an image file smaller?", "Reducing the colour depth from 24 bits to 8 bits", ["Increasing the resolution", "Adding more metadata", "Saving it twice"],
                   "Fewer bits per pixel means a smaller file.")]),
  ],
  final=dict(name="Final challenge: build an image", floor_title="Final challenge: build an image",
    intro="Copy the image, then answer the file size questions. Tap the star to begin.",
    ill=("tiles", [("width × height × depth", "y")], 1),
    tasks=[pixels("Copy this 2-bit image. Watch the file size readout as you work.", FLAG4, "8 × 8 × 2 = 128 bits, or 16 bytes.", depth=2),
           mcq("An image is 1,000 × 500 pixels with a colour depth of 8 bits. What is the file size in kilobytes?", "500", ["4,000", "62.5", "5,000"],
               "1,000 × 500 × 8 = 4,000,000 bits, ÷ 8 = 500,000 bytes, ÷ 1,000 = 500 kB."),
           mcq("Which pair of items would both be stored as metadata?", "The image's dimensions and the date it was created", ["The pixel colours and the file size", "The screen brightness and the printer type", "The user's password and the file name"],
               "Metadata describes the image, not the device showing it.")]),
  info=[(0, "Picture element", "The word pixel is short for 'picture element'. Your phone's camera captures tens of millions of them at once."),
        (1, "True colour", "24-bit colour uses 8 bits each for red, green and blue, giving 16.7 million shades: more than the human eye can distinguish."),
        (2, "Why images look blocky", "Enlarging a bitmap doesn't add detail, so pixels become visible. Vector images, drawn from shapes, don't have that problem."),
        (3, "Hidden GPS", "Photos taken on a phone often store the exact location in their metadata, which is worth knowing before sharing them online."),
        (4, "Bitmap sizes", "An uncompressed 12-megapixel photo at 24-bit colour would be about 36 MB. Compression is what makes it around 3 MB."),
        (5, "Screens do the same", "Your screen is a grid of pixels too, each made of red, green and blue subpixels, blended by your eye.")],
  ws=dict(title="Bitmaps", objectives=["understand how an image is a series of pixels represented in binary", "know what is meant by metadata",
          "understand the effect of colour depth and resolution on file size"],
    starter="Zoom right into a photo on your phone until it goes blocky. What are you actually looking at, and what is stored for each square?", starter_lines=3,
    keyterms=["Pixel", "Metadata"], keyq="How does a computer store graphics?",
    extra=dict(title="Task: file size", instr="Calculate the raw file size for each image. Show your working.", head=["Image", "Working", "Size"],
               rows=[["8 × 8, 1-bit", "", ""], ["8 × 8, 2-bit", "", ""], ["640 × 480, 8-bit", "", ""], ["1920 × 1080, 24-bit", "", ""]]),
    exam=[("Describe what metadata is, and give two examples stored with a photo.", 3, 3),
          ("An image is 320 × 240 pixels with a colour depth of 4 bits. Calculate the file size in kilobytes, showing your working.", 4, 5),
          ("Explain what happens to the quality and the file size when colour depth is increased.", 3, 3)],
    confidence=["Pixels and bitmaps", "Colour depth and resolution", "Metadata and file size"]))

L14 = dict(id="ms-lesson14", topic="1.2", lesson=14, title="Sound studio", img="MS_L14_SoundStudio",
  description="Turn a sound wave into binary: sampling, sample rate, bit depth, and the effect on quality and file size.",
  kicker=f"{K12}  |  Lesson 14", scene_title="Sound studio", subtitle=SUB12,
  intro="Sound is a wave, and computers only store numbers. Find out how sampling turns one into the other, and what sample rate and bit depth do to quality and file size.",
  keywords=["Analogue", "Sampling", "Sample rate", "Bit depth", "Duration", "File size"],
  stations=[
   dict(name="Analogue to digital", bullets=["Sound is an analogue wave: it changes smoothly and continuously.", "Computers store discrete numbers, so the wave must be measured at intervals.",
        "Each measurement is called a sample, and is stored in binary."], challenge="Why can't a computer store a sound wave exactly?",
        ill=("flow", ["Sound wave", "Measure at intervals", "Store as binary"]), fact="Sampling means...",
        tasks=[mcq("What is sampling?", "Measuring the amplitude of a sound wave at regular intervals and storing each measurement in binary", ["Playing a sound back at a lower speed", "Copying part of one song into another", "Removing the quiet parts of a recording"],
                   "Each measurement becomes a binary number."),
               sound("Place a sample in each column, at the level nearest the wave.", 8, 3, "Each sample is stored as a 3-bit binary number.")]),
   dict(name="Sample rate", bullets=["Sample rate is the number of samples taken per second, measured in hertz.",
        "A higher rate follows the wave more closely, so the recording is more accurate.", "CD quality is 44,100 Hz."],
        challenge="What happens to the recording if the sample rate is too low?", ill=("compare", "Low sample rate", ["Fewer samples", "Rougher shape", "Smaller file"], "High sample rate", ["More samples", "Closer to the wave", "Bigger file"], "o", "g"),
        fact="Sample rate is...",
        tasks=[mcq("What does sample rate measure?", "How many samples are taken each second", ["How many bits are used for each sample", "How long the recording lasts", "How loud the sound is"],
                   "It's measured in hertz."),
               mcq("What is the effect of doubling the sample rate?", "Better quality, and twice the file size", ["Better quality with no change in size", "Worse quality and a smaller file", "No change at all"],
                   "Twice as many samples to store.")]),
   dict(name="Bit depth", bullets=["Bit depth is the number of bits used to store each sample.", "More bits means more possible levels, so the amplitude is recorded more precisely.",
        "3 bits give 8 levels; 16 bits give 65,536."], challenge="How many levels does a bit depth of 4 give?",
        ill=("table", ["Bit depth", "Levels"], [["3 bits", "8"], ["8 bits", "256"], ["16 bits", "65,536"]]), fact="Bit depth is...",
        tasks=[sound("This time the bit depth is 4, giving 16 levels. Place each sample at the nearest level.", 8, 4, "More levels means each sample is closer to the true height of the wave."),
               mcq("What is the effect of increasing the bit depth?", "Each sample is recorded more precisely, and the file gets bigger", ["More samples are taken each second", "The recording lasts longer", "The sound plays faster"],
                   "Bit depth is about precision, not how often you sample.")]),
   dict(name="Sound file size", bullets=["File size (bits) = sample rate × bit depth × duration in seconds.", "Double any one of them and the file size doubles.",
        "Stereo doubles it again, because each channel is stored separately."], challenge="Calculate the size of 10 seconds at 8,000 Hz with 8-bit samples.",
        ill=("code", ["size = sample rate × bit depth × seconds", "8000 × 8 × 10 = 640,000 bits", "÷ 8 = 80,000 bytes = 80 kB"], 26), fact="Sound file size is calculated by...",
        tasks=[mcq("A 30-second clip is sampled at 44,100 Hz with a bit depth of 16. What is its size in bits?", "21,168,000", ["1,323,000", "705,600", "2,646,000"],
                   "44,100 × 16 × 30."),
               mcq("Which change would halve a sound file's size?", "Halving the sample rate", ["Doubling the bit depth", "Recording in stereo", "Adding metadata"],
                   "Half as many samples, half the size, and some loss of quality.")]),
   dict(name="Quality against size", bullets=["Higher sample rate and bit depth mean better quality and bigger files.",
        "Speech needs far less than music, so phone calls use low rates.", "Choose what's good enough for the purpose."],
        challenge="Why is a phone call sampled at a much lower rate than a music track?", ill=("table", ["Use", "Typical rate"], [["Phone call", "8,000 Hz"], ["Music CD", "44,100 Hz"], ["Studio", "96,000 Hz"]]),
        fact="Quality and file size are linked because...",
        tasks=[mcq("Why do phone calls use a low sample rate?", "Speech is still clear, and the smaller files are quicker to transmit", ["Phones can't store binary", "It makes voices sound better", "It uses less battery to speak"],
                   "Quality only has to be good enough for the job."),
               mcq("Which combination gives the highest quality recording?", "A high sample rate and a high bit depth", ["A low sample rate and a high bit depth", "A high sample rate and a low bit depth", "A low sample rate and a low bit depth"],
                   "Both together decide how closely the digital copy follows the wave.")]),
   dict(name="In the studio", bullets=["Practise reading a wave and choosing the nearest level at each sample.", "Then calculate the file size from your choices.",
        "This is exactly what an exam question on sound representation looks like."], challenge="Complete both sampling tasks on your worksheet.",
        ill=("flow", ["Sample", "Round to nearest level", "Store in binary"]), fact="To sample a wave, I should...",
        tasks=[sound("Sample this wave. It rises and falls twice, so look carefully.", 8, 3, "Each column stores one 3-bit sample.", waveSrc="0.5 + 0.45 * Math.sin(t * Math.PI * 4)"),
               mcq("A sample is stored with 3 bits. What is the highest level it can record?", "111, which is level 7", ["3", "8", "1,000"], "3 bits give 8 levels, numbered 0 to 7.")]),
  ],
  final=dict(name="Final challenge: sample and calculate", floor_title="Final challenge: sample and calculate",
    intro="Sample the wave, then work out the file sizes. Tap the star to begin.",
    ill=("code", ["size = rate × depth × duration"], 30),
    tasks=[sound("Place each sample at the level nearest the wave.", 8, 3, "8 samples × 3 bits = 24 bits for this short sound."),
           mcq("A 60-second recording is sampled at 20,000 Hz with a bit depth of 8. What is the file size in bytes?", "1,200,000", ["9,600,000", "150,000", "120,000"],
               "20,000 × 8 × 60 = 9,600,000 bits, ÷ 8 = 1,200,000 bytes."),
           mcq("The same recording is made in stereo. What happens to the file size?", "It doubles, because each channel is stored separately", ["It stays the same", "It halves", "It becomes four times bigger"],
               "Two channels means twice the samples.")]),
  info=[(0, "Nyquist", "To record a sound accurately you must sample at least twice its highest frequency. Human hearing reaches about 20 kHz, hence 44.1 kHz on CDs."),
        (1, "Bit depth and noise", "Low bit depth adds a hiss called quantisation noise, because each sample is rounded to the nearest level."),
        (2, "MP3", "MP3 files are much smaller than CD audio because they throw away sounds most people can't hear: that's lossy compression, in lesson 15."),
        (3, "Studio quality", "Music studios record at 96 kHz or higher with 24-bit depth, giving huge files that are mixed down later."),
        (4, "Telephone bandwidth", "Phone systems keep only 300 Hz to 3,400 Hz, which is why voices sound thinner on a call than in person."),
        (5, "Vinyl is analogue", "A record groove is a physical copy of the wave, with no sampling at all: that's what people mean by analogue sound.")],
  ws=dict(title="Sound", objectives=["understand how sound is sampled and stored in digital form",
          "understand how sample rate, duration and bit depth affect file size and quality"],
    starter="Sound is a smooth wave, but computers store numbers. Suggest how a recording could be turned into numbers, and what is lost.", starter_lines=3,
    keyterms=["Sampling", "Sample rate"], keyq="How do computers store sound, and what are the implications for sample rate, duration and bit depth?",
    extra=dict(title="Task: sound file sizes", instr="Calculate each file size. Show your working.", head=["Recording", "Working", "Size"],
               rows=[["10 s, 8,000 Hz, 8-bit", "", ""], ["3 min, 44,100 Hz, 16-bit", "", ""], ["30 s, 22,050 Hz, 16-bit, stereo", "", ""]]),
    exam=[("Describe what happens when a sound wave is sampled.", 2, 2), ("Explain the effect on quality and file size of doubling the bit depth.", 3, 3),
          ("A recording lasts 45 seconds at 12,000 Hz with a bit depth of 16. Calculate the file size in kilobytes, showing your working.", 4, 5)],
    confidence=["How sampling works", "Sample rate and bit depth", "Calculating sound file size"]))

L15 = dict(id="ms-lesson15", topic="1.2", lesson=15, title="Compression works", img="MS_L15_CompressionWorks",
  description="Why files are compressed, the difference between lossy and lossless, and run-length encoding in action.",
  kicker=f"{K12}  |  Lesson 15", scene_title="Compression works", subtitle=SUB12,
  intro="Raw files are enormous. Compression shrinks them, but there's a choice to make: throw data away for a smaller file, or keep every bit and shrink it more carefully.",
  keywords=["Compression", "Lossy", "Lossless", "Run-length encoding", "Bandwidth", "Quality"],
  stations=[
   dict(name="Why compress?", bullets=["Smaller files use less storage space.", "They transfer faster and use less bandwidth, so streaming and downloads work better.",
        "More files fit on a device, and web pages load quicker."], challenge="Give three reasons a website compresses its images.",
        ill=("tiles", [("Less storage", "g"), ("Faster transfer", "g"), ("Less bandwidth", "g"), ("Quicker streaming", "g")], 2), fact="Files are compressed because...",
        tasks=[multi("Why is data compressed? Select all that apply.", ["To use less storage space", "To transfer files more quickly", "To use less bandwidth",
                     "To make the data impossible to read", "To add more colours to an image"], ["To use less storage space", "To transfer files more quickly", "To use less bandwidth"],
                     "Making data unreadable is encryption, which is a different thing."),
               mcq("Which is a benefit of compression for a video streaming service?", "Video can be sent over slower connections without buffering", ["Videos gain extra detail", "It stops piracy", "It removes the need for servers"],
                   "Less data per second means fewer interruptions.")]),
   dict(name="Lossy compression", bullets=["Some data is permanently removed to make the file much smaller.",
        "The removed detail is chosen to be hard for people to notice, such as sounds outside normal hearing.", "The original file can never be recovered."],
        challenge="Name two file types that use lossy compression.", ill=("compare", "Before", ["Full detail", "Large file"], "After lossy", ["Detail removed", "Much smaller"], "b", "o"),
        fact="Lossy compression...",
        tasks=[mcq("What happens to the data in lossy compression?", "Some is permanently removed, so the original can't be restored", ["It is rearranged but all kept", "It is encrypted", "It is copied twice"],
                   "That's why it's called lossy: data is lost."),
               mcq("Which file types typically use lossy compression?", "JPEG images and MP3 audio", ["Word documents and spreadsheets", "Program files", "ZIP archives"],
                   "Photos and music can lose detail without most people noticing.")]),
   dict(name="Lossless compression", bullets=["No data is lost: the file is rewritten more efficiently, and can be restored exactly.",
        "Patterns and repeats are recorded once instead of many times.", "The saving is smaller than with lossy compression."],
        challenge="Why must a program file be compressed losslessly?", ill=("compare", "Lossy", ["Smaller", "Data lost"], "Lossless", ["Exact copy restored", "Less saving"], "o", "g"),
        fact="Lossless compression...",
        tasks=[mcq("What is the key feature of lossless compression?", "The original file can be restored exactly", ["It always gives the smallest file", "It removes unimportant detail", "It only works on images"],
                   "Nothing is thrown away."),
               mcq("Why must text and program files use lossless compression?", "Losing even one character or instruction would corrupt the file", ["They are too small to compress", "They contain no patterns", "Lossy compression is illegal for text"],
                   "A program with missing bits simply won't run.")]),
   dict(name="Which one, when?", bullets=["Photos, music and video: lossy is fine, and the saving is big.",
        "Text, spreadsheets, program files and archives: lossless only.", "Sometimes both: a video may use lossy video with lossless subtitles."],
        challenge="Choose lossy or lossless for five file types, and justify each.", ill=("tiles", [("Photo: lossy", "o"), ("Music: lossy", "o"), ("Text: lossless", "g"), ("Program: lossless", "g")], 2),
        fact="Lossy is used for... Lossless is used for...",
        tasks=[sort("Which type of compression should be used for each file?", ["Lossy", "Lossless"], [
                    ["A photo on a web page", "Lossy"], ["A music streaming track", "Lossy"], ["A word-processed essay", "Lossless"],
                    ["A program's installer", "Lossless"], ["A spreadsheet of results", "Lossless"], ["A video on a streaming service", "Lossy"]],
                    "If losing detail would break the file, it has to be lossless.")]),
   dict(name="Run-length encoding", bullets=["A lossless method: instead of storing every pixel, store the colour and how many times it repeats.",
        "001 1011 means eleven pixels of colour 001.", "It works brilliantly on images with large blocks of one colour, and badly on noisy photos."],
        challenge="Encode the first two lines of the image using run-length encoding.", ill=("code", ["Raw:  0 0 0 0 1 1 1 1", "RLE:  0×4, 1×4", "Stored as: 0 100 1 100"], 26),
        fact="Run-length encoding works by...",
        tasks=[pixels("Copy this image, then look at each row: how many runs does it have?", STRIPES, "Rows of repeated pixels compress well with run-length encoding."),
               mcq("A row of 8 pixels is 00001111. How would run-length encoding store it?", "Colour 0 four times, then colour 1 four times", ["Eight separate pixel values", "The average colour of the row", "Only the first pixel"],
                   "Two runs instead of eight values.")]),
   dict(name="Does it always help?", bullets=["RLE shrinks images with long runs of the same colour.",
        "On a detailed photo, where colours change every pixel, it can make the file bigger.", "Compare the raw size with the compressed size to decide."],
        challenge="Compare the raw data size and the compressed size for your image.", ill=("compare", "Simple image", ["Long runs", "RLE works well"], "Photo", ["Colour changes constantly", "RLE can make it bigger"], "g", "r"),
        fact="Run-length encoding works best when...",
        tasks=[mcq("When does run-length encoding work best?", "When the image has large areas of the same colour", ["When every pixel is a different colour", "When the image is a photograph", "When the image is in colour"],
                   "Runs are what it compresses."),
               mcq("What happens if RLE is used on an image where every pixel differs from the next?", "The compressed file can be larger than the original", ["It halves the file size", "It deletes the image", "Nothing changes"],
                   "Each run of one still needs a count stored.")]),
  ],
  final=dict(name="Final challenge: compress it", floor_title="Final challenge: compress it",
    intro="Sort the file types, then answer the run-length encoding questions. Tap the star to begin.",
    ill=("code", ["001 1011 = eleven pixels of colour 001"], 28),
    tasks=[sort("Is each statement about lossy or lossless compression?", ["Lossy", "Lossless"], [
             ["Data is permanently removed", "Lossy"], ["The original file can be restored exactly", "Lossless"],
             ["Used for MP3 and JPEG files", "Lossy"], ["Used for text and program files", "Lossless"],
             ["Usually gives the smallest file", "Lossy"], ["Run-length encoding is an example", "Lossless"]],
             "Lossy trades quality for size; lossless keeps everything."),
           mcq("A 1-bit image row is 11111000. How many runs does run-length encoding need?", "2", ["8", "3", "5"], "Five 1s then three 0s: two runs."),
           mcq("Why is compression especially important for streaming video?", "It reduces the bandwidth needed, so video plays without buffering", ["It improves the picture quality", "It stops adverts", "It makes screens brighter"],
               "Less data per second is the whole point.")]),
  info=[(0, "ZIP", "ZIP files use lossless compression, which is why a zipped document opens exactly as it was, character for character."),
        (1, "JPEG artefacts", "Save a JPEG repeatedly and it slowly degrades: each save throws a little more detail away."),
        (2, "Fax machines", "Run-length encoding is old technology: fax machines used it to send pages of mostly white paper quickly."),
        (3, "Streaming", "Video services compress the same film at several quality levels and switch between them as your connection changes."),
        (4, "Lossless audio", "Formats like FLAC compress music losslessly, giving files around half the size of raw audio with no quality loss."),
        (5, "Already compressed", "Zipping a JPEG saves almost nothing: the file has already had its patterns squeezed out.")],
  ws=dict(title="Compression", objectives=["know why data is compressed", "understand the difference between lossy and lossless compression",
          "know why some data can only be compressed losslessly"],
    starter="A three-minute song is about 30 MB uncompressed, but under 3 MB as an MP3. Suggest what could have been removed, and what could not.", starter_lines=3, keyterms=["Lossy compression", "Lossless compression"],
    keyq="What are the effects on a file for each type of compression?",
    extra=dict(title="Run-length encoding", instr="Write the RLE for the first two rows of your image, then compare the sizes.",
               head=["Row", "Raw pixels", "Run-length encoding"], rows=[["1", "", ""], ["2", "", ""], ["Size comparison", "", ""]]),
    exam=[("Give two reasons why files are compressed before being sent over a network.", 2, 2), ("Compare lossy and lossless compression, using an example of a file that suits each.", 6, 6),
          ("Explain why run-length encoding shrinks a cartoon image more than a photograph.", 3, 3)],
    confidence=["Why data is compressed", "Lossy and lossless", "Run-length encoding"]))

L16 = dict(id="ms-lesson16", topic="1.2", lesson=16, title="Revision HQ 1.2 part 2", img="MS_L16_RevisionHQ12Part2",
  description="Recap lessons 12 to 15: character sets, images, sound and compression, ready for the second test.",
  kicker=f"{K12}  |  Lesson 16", scene_title="Revision HQ 1.2 part 2", subtitle="Catch up and revise lessons 12 to 15",
  intro="Each station sums up one part of data representation. Answer its quiz, and your results will show what to revise before the test. Then finish any outstanding tasks.",
  keywords=["Character set", "ASCII", "Unicode", "Pixels", "Sampling", "Compression"], revision=True,
  stations=[
   dict(name="Character sets", bullets=["A character set links characters to binary codes.", "ASCII: 7 bits, 128 characters. Unicode: 16+ bits, every writing system.",
        "n bits give 2ⁿ characters."], challenge="Explain why Unicode files are larger than ASCII files.", ill=("table", ["Set", "Bits", "Characters"], [["ASCII", "7", "128"], ["Extended", "8", "256"], ["Unicode", "16+", "65,536+"]]),
        tasks=[mcq("How many characters can 8 bits represent?", "256", ["8", "128", "512"], "2 to the power 8."),
               mcq("What is the advantage of Unicode?", "It can represent characters from every writing system", ["It uses fewer bits", "It makes files smaller", "It is faster to type"], "Coverage, at the cost of size."),
               mcq("A text file has 100 characters in 8-bit ASCII. How big is it?", "100 bytes", ["800 bytes", "12.5 bytes", "1,000 bits"], "100 × 8 = 800 bits = 100 bytes.")]),
   dict(name="Images", bullets=["File size = width × height × colour depth.", "Colour depth is bits per pixel; n bits give 2ⁿ colours.",
        "Metadata stores dimensions, colour depth, date and more."], challenge="Calculate the size of a 500 × 500 image at 8-bit colour depth.",
        ill=("code", ["500 × 500 × 8 = 2,000,000 bits", "= 250,000 bytes = 250 kB"], 26),
        tasks=[mcq("What is the formula for an image's file size?", "Width × height × colour depth", ["Width + height + colour depth", "Resolution ÷ colour depth", "Sample rate × duration"], "In pixels and bits."),
               mcq("A colour depth of 4 bits gives how many colours?", "16", ["4", "8", "256"], "2 to the power 4."),
               mcq("Which is an example of metadata?", "The date the image was taken", ["The colour of pixel 1", "The screen size", "The printer model"], "Metadata describes the file.")]),
   dict(name="Sound", bullets=["File size = sample rate × bit depth × duration.", "Sample rate is samples per second; bit depth is bits per sample.",
        "Higher values mean better quality and bigger files."], challenge="Calculate the size of 20 seconds at 16,000 Hz and 8-bit depth.",
        ill=("code", ["16,000 × 8 × 20 = 2,560,000 bits", "= 320,000 bytes = 320 kB"], 26),
        tasks=[mcq("What does bit depth mean for sound?", "The number of bits used to store each sample", ["The number of samples per second", "How long the recording is", "How loud it is"], "More bits means more levels."),
               mcq("Doubling the sample rate does what to the file?", "Doubles its size and improves quality", ["Halves its size", "No change", "Removes the metadata"], "Twice as many samples."),
               mcq("What is sampling?", "Measuring the wave's amplitude at regular intervals", ["Playing the sound back slowly", "Removing quiet parts", "Compressing the file"], "Each measurement is stored in binary.")]),
   dict(name="Compression", bullets=["Lossy: data removed permanently, much smaller files, used for photos, music and video.",
        "Lossless: nothing lost, the original can be restored, used for text and programs.", "Run-length encoding is a lossless method."],
        challenge="State two reasons why data is compressed.", ill=("compare", "Lossy", ["Data removed", "Smallest files"], "Lossless", ["Exact restore", "Less saving"], "o", "g"),
        tasks=[mcq("Which type of compression is used for MP3 files?", "Lossy", ["Lossless", "Neither", "Both at once"], "Sounds most people can't hear are removed."),
               mcq("Why can't a program file use lossy compression?", "Missing data would stop the program working", ["Programs are too small", "It would take too long", "Programs have no patterns"], "Every byte matters."),
               mcq("How does run-length encoding save space?", "It stores a colour once with the number of times it repeats", ["It deletes every second pixel", "It reduces the colour depth", "It crops the image"], "Great for big blocks of one colour.")]),
   dict(name="Calculations practice", bullets=["Write the formula, substitute the numbers, then convert the units.", "Divide bits by 8 for bytes, then by 1,000 for kB and again for MB.",
        "Check the answer is sensible."], challenge="Complete the three calculations on your worksheet.", ill=("flow", ["Formula", "Substitute", "Convert", "Check"]),
        tasks=[mcq("A 400 × 300 image has 8-bit colour. What is the size in kB?", "120", ["960", "12", "1,200"], "400 × 300 × 8 = 960,000 bits, ÷ 8 = 120,000 bytes = 120 kB."),
               mcq("A 60-second sound is 22,050 Hz at 16 bits. Roughly how large is it?", "About 2.6 MB", ["About 26 MB", "About 260 kB", "About 21 MB"], "22,050 × 16 × 60 ÷ 8 = 2,646,000 bytes."),
               mcq("A 2,000-character file uses 16-bit Unicode. How big is it in bytes?", "4,000", ["2,000", "32,000", "250"], "2,000 × 16 = 32,000 bits = 4,000 bytes.")]),
   dict(name="Exam technique", bullets=["Show your working: method marks are available even if the final number is wrong.",
        "Watch the units the question asks for.", "Learn the definitions: sampling, metadata, character set, lossy, lossless."],
        challenge="Which command words appear most in this topic?", ill=("tiles", [("State", "b"), ("Describe", "g"), ("Explain", "o"), ("Calculate", "p")], 2),
        tasks=[mcq("A question says 'calculate' and is worth 3 marks. What should you include?", "The formula, the substituted numbers and the final answer with units", ["Just the answer", "A diagram", "A definition of the formula"], "Method marks are free marks."),
               mcq("A question asks for the answer in kilobytes but you have bits. What do you do?", "Divide by 8, then by 1,000", ["Divide by 1,000 only", "Multiply by 8", "Leave it in bits"], "Bits to bytes to kilobytes."),
               mcq("Which definition is correct?", "Metadata is data about the data, such as an image's dimensions", ["Metadata is the colour of each pixel", "Metadata is a type of compression", "Metadata is the file's name only"], "Learn this one word for word.")]),
  ],
  final=dict(name="Final challenge: data representation", floor_title="Final challenge: data representation",
    intro="A mixed set from the second half of the topic. Tap the star to begin.",
    ill=("tiles", [("Text", "b"), ("Images", "p"), ("Sound", "o"), ("Compression", "g")], 4),
    tasks=[convert("Convert the character code 90 (the letter Z) into 8-bit binary.", "denary", "binary", 90, "90 is 01011010."),
           sort("Which part of the topic does each fact belong to?", ["Text", "Images", "Sound", "Compression"], [
             ["ASCII uses 7 bits per character", "Text"], ["Colour depth is bits per pixel", "Images"],
             ["Sample rate is measured in hertz", "Sound"], ["Lossy removes data permanently", "Compression"],
             ["Metadata stores the dimensions", "Images"], ["Unicode covers every writing system", "Text"],
             ["Bit depth sets the number of levels", "Sound"], ["Run-length encoding is lossless", "Compression"]],
             "Check your results table to see what to revise.")]),
  info=[(0, "Revision tip", "Write the three file size formulas on a card and test yourself until you can write them from memory."),
        (1, "Common slip", "Forgetting to divide by 8 turns bits into bytes wrongly, and costs a mark in nearly every series."),
        (2, "Definitions win marks", "Sampling, metadata, character set, lossy and lossless are all 1 or 2-mark definition questions."),
        (3, "Compression choice", "If the question involves text, a program or a spreadsheet, the answer is always lossless."),
        (4, "Quality and size", "Almost every question here can be answered with: more bits means better quality and a bigger file."),
        (5, "Binary blitz", "Use the Binary blitz challenge to get fast at conversions: they appear in nearly every paper.")],
  ws=dict(title="Catch-up and revision: lessons 12 to 16", objectives=["know which parts of data representation I am secure on", "finish outstanding tasks from lessons 12 to 15"],
    starter="Without notes, write the three file size formulas: images, sound and text.", starter_lines=3, keyterms=[], keyq=None,
    checklist=["Character foundry worksheet (L12): your name in binary", "Pixel studio worksheet (L13): the bitmap and file size calculations",
               "Sound studio worksheet (L14): the sampling tasks", "Compression works worksheet (L15): lossy and lossless, and run-length encoding"],
    exam=[("Describe the difference between lossy and lossless compression.", 4, 4), ("An image is 640 × 480 with 8-bit colour depth. Calculate its size in kilobytes.", 3, 4)],
    rag=["Character sets: ASCII and Unicode", "Images: pixels, colour depth, resolution, metadata", "Image file size calculations",
         "Sound: sampling, sample rate, bit depth", "Sound file size calculations", "Compression: lossy and lossless", "Run-length encoding"],
    confidence=["Character sets", "Images and sound", "Compression"]))
