from kit import mcq, multi, sort, match, order, calc

K12 = "1.2 Memory and storage"
SUB12 = "OCR J277 Paper 1  |  Computer systems"
def convert(q, frm, to, value, fb=""): return dict(t="convert", q=q, **{"from": frm}, to=to, value=value, fb=fb)
def addshift(q, fb="", **kw): return dict(t="addshift", q=q, fb=fb, **kw)

L7 = dict(id="ms-l07", topic="1.2", lesson=7, title="Capacity calculator", img="MS_L07_CapacityCalculator_360",
  description="Work out how much storage images, sound and text really need, and how many files will fit.",
  kicker=f"{K12}  |  Lesson 7", scene_title="Capacity calculator", subtitle=SUB12,
  intro="How many photos fit on a 64 GB card? How big is a three-minute song? Learn the three file size formulas and use them on real scenarios.",
  keywords=["File size", "Resolution", "Colour depth", "Sample rate", "Bit depth", "Capacity"],
  stations=[
   dict(name="What is data capacity?", bullets=["Capacity is how much data a device can hold, measured in bytes and their multiples.",
        "To work out what you need, calculate one file's size, then multiply by how many files.", "Always check whether the answer is wanted in bits, bytes, MB or GB."],
        challenge="How would you work out how many photos fit on a memory card?", ill=("flow", ["Size of one file", "× number of files", "Convert units"]),
        fact="Data capacity means...",
        tasks=[mcq("What is the first step in a capacity calculation?", "Work out the size of one file", ["Divide the card size by 8", "Convert everything to bits", "Count the pixels on the screen"],
                   "Then multiply by the number of files and convert units."),
               mcq("A card holds 64 GB and each photo is 4 MB. Roughly how many photos fit?", "16,000", ["160", "1,600", "160,000"], "64,000 MB ÷ 4 MB = 16,000.")]),
   dict(name="Image file size", bullets=["File size (bits) = width × height × colour depth.", "Width and height are in pixels; colour depth is bits per pixel.",
        "Divide by 8 for bytes, then by 1,000 for kB and again for MB.", "Real files also include metadata."],
        challenge="Calculate the size of a 1,000 × 800 image with a colour depth of 8 bits.", ill=("code", ["size = width × height × colour depth", "1000 × 800 × 8 = 6,400,000 bits", "÷ 8 = 800,000 bytes = 800 kB"], 26),
        fact="Image file size is calculated by...",
        tasks=[mcq("What is the formula for the size of a bitmap image?", "Width × height × colour depth", ["Width + height + colour depth", "Width × height ÷ colour depth", "Resolution × sample rate"],
                   "All in pixels and bits per pixel."),
               mcq("A 500 × 400 image has a colour depth of 4 bits. What is its size in bits?", "800,000", ["200,000", "1,600,000", "8,000"], "500 × 400 × 4 = 800,000 bits."),
               # Choosing between four answers and working one out are not the
               # same skill, and this lesson is about the second. Different
               # numbers from the wall, the worked example, the worksheet and
               # the exam practice, so none of them gives this away.
               calc("Now work one out yourself, one step at a time.",
                    ["bits", "bytes", "kB"], [["", "", ""]], [["2400000", "300000", "300"]],
                    given=["width = 500", "height = 300", "colour depth = 16 bits"],
                    title="A 500 × 300 image at 16 bits",
                    fb="500 × 300 × 16 = 2,400,000 bits. ÷ 8 = 300,000 bytes. ÷ 1,000 = 300 kB.")]),
   dict(name="Sound file size", bullets=["File size (bits) = sample rate × bit depth × duration in seconds.", "Sample rate is measured in hertz: samples per second.",
        "Stereo doubles it, because there are two channels."], challenge="Calculate the size of 30 seconds recorded at 44,100 Hz with a bit depth of 16.",
        ill=("code", ["size = sample rate × bit depth × seconds", "44100 × 16 × 30 = 21,168,000 bits", "÷ 8 = 2,646,000 bytes ≈ 2.6 MB"], 26),
        fact="Sound file size is calculated by...",
        tasks=[mcq("What is the formula for the size of a sound file?", "Sample rate × bit depth × duration", ["Width × height × colour depth", "Sample rate + bit depth + duration", "Bit depth ÷ duration"],
                   "Multiply by the number of channels for stereo."),
               mcq("A 10-second clip is recorded at 8,000 Hz with a bit depth of 8. What is its size in bits?", "640,000", ["80,000", "64,000", "6,400,000"], "8,000 × 8 × 10 = 640,000 bits."),
               calc("Now work one out yourself, one step at a time.",
                    ["bits", "bytes", "kB"], [["", "", ""]], [["7056000", "882000", "882"]],
                    given=["sample rate = 22,050 Hz", "bit depth = 8", "duration = 40 seconds"],
                    title="40 seconds at 22,050 Hz, 8-bit",
                    fb="22,050 × 8 × 40 = 7,056,000 bits. ÷ 8 = 882,000 bytes. ÷ 1,000 = 882 kB.")]),
   dict(name="Text file size", bullets=["File size (bits) = number of characters × bits per character.", "ASCII uses 7 or 8 bits per character; Unicode often uses 16.",
        "Spaces and punctuation are characters too."], challenge="Calculate the size of a 2,000-character message in 8-bit ASCII.",
        ill=("code", ["size = characters × bits per character", "2000 × 8 = 16,000 bits", "÷ 8 = 2,000 bytes = 2 kB"], 26), fact="Text file size is calculated by...",
        tasks=[mcq("A 500-character text file uses 8 bits per character. How large is it?", "500 bytes", ["500 bits", "4,000 bytes", "64 bytes"], "500 × 8 = 4,000 bits, which is 500 bytes."),
               mcq("Why is the same text larger in Unicode than in ASCII?", "Unicode uses more bits per character", ["Unicode adds pictures", "Unicode repeats each character", "It isn't: they're the same"],
                   "More bits per character means a bigger file."),
               calc("Now work one out yourself, one step at a time.",
                    ["bits", "bytes", "kB"], [["", "", ""]], [["24000", "3000", "3"]],
                    given=["characters = 1,500", "bits per character = 16"],
                    title="1,500 characters in 16-bit Unicode",
                    fb="1,500 × 16 = 24,000 bits. ÷ 8 = 3,000 bytes. ÷ 1,000 = 3 kB.")]),
   dict(name="Scenario practice", bullets=["Read carefully: what's the file size, and how many files?", "Convert at the end, not halfway through.",
        "Show your working: marks are given for the method as well as the answer."], challenge="Complete the three scenarios on your worksheet.",
        ill=("table", ["Scenario", "Working"], [["200 photos, 2 MB each", "200 × 2 = 400 MB"], ["1 hour of audio at 1 MB/min", "60 MB"], ["Fits on 1 GB?", "460 MB: yes"]]),
        fact="When answering capacity questions, I should...",
        tasks=[mcq("300 photos are 3 MB each. Will they fit on a 1 GB memory stick?", "No: they need 900 MB, which fits, but only just", ["No: they need 9 GB", "Yes: they need 90 MB", "Yes: they need 30 MB"],
                   "300 × 3 MB = 900 MB, which is under 1,000 MB."),
               mcq("Why should you show your working?", "Marks are given for the method, even if the final number is wrong", ["It makes the answer longer", "It is required by law", "It doesn't matter"],
                   "Write the formula, substitute the numbers, then convert.")]),
   dict(name="Estimating", bullets=["Rounding helps: treat 1,024 as 1,000 and 44,100 Hz as 44 kHz.", "Check the answer is sensible: a photo shouldn't come out as 3 GB.",
        "Compression makes real files smaller than the calculated raw size."], challenge="Why is a real JPEG smaller than the calculated file size?",
        ill=("compare", "Raw size", ["Calculated", "Every pixel stored"], "Real file", ["Compressed", "Much smaller"], "b", "g"), fact="Calculated sizes are usually...",
        tasks=[mcq("Why is a real photo file usually smaller than the calculated raw size?", "It has been compressed", ["The camera rounds down", "Metadata is removed", "Pixels are deleted at random"],
                   "Compression is covered in lessons 15 and 16."),
               mcq("Which would double a bitmap image's file size?", "Doubling the colour depth", ["Halving the resolution", "Renaming the file", "Saving it twice"],
                   "Doubling either the number of pixels or the bits per pixel doubles the size.")]),
  ],
  final=dict(name="Final challenge: work it out", floor_title="Final challenge: work it out",
    intro="Three calculations, one of each type. Tap the star and choose the right answer for each.",
    ill=("code", ["image = w × h × depth", "sound = rate × depth × seconds", "text = characters × bits"], 30),
    tasks=[mcq("An image is 800 × 600 with a colour depth of 8 bits. What is the file size in bytes?", "480,000", ["3,840,000", "60,000", "4,800"],
               "800 × 600 × 8 = 3,840,000 bits, and ÷ 8 = 480,000 bytes."),
           mcq("A 60-second clip is sampled at 20,000 Hz with a bit depth of 16. What is the file size in bits?", "19,200,000", ["1,200,000", "320,000", "2,400,000"],
               "20,000 × 16 × 60 = 19,200,000 bits."),
           mcq("A text file has 4,000 characters stored in 16-bit Unicode. How big is it in bytes?", "8,000", ["4,000", "64,000", "500"], "4,000 × 16 = 64,000 bits, and ÷ 8 = 8,000 bytes."),
           # The lesson's key question - "how many fit?" - answered rather than
           # recognised. Three steps, one mark each, so the method is what is
           # marked, which is what the worksheet and the exam also reward.
           calc("How many of these photos fit on the card? Work through it one step at a time.",
                ["one photo (bits)", "one photo (kB)", "photos that fit"],
                [["", "", ""]], [["14400000", "1800", "200"]],
                given=["photo = 1,000 × 600 at 24 bits", "card = 360,000 kB free"],
                title="Final challenge: will they fit?",
                fb="1,000 × 600 × 24 = 14,400,000 bits. ÷ 8 = 1,800,000 bytes = 1,800 kB. "
                   "360,000 ÷ 1,800 = 200 photos.")]),
  info=[(0, "CD quality", "A music CD samples at 44,100 Hz with 16-bit depth in stereo, which is about 10 MB per minute of audio."),
        (1, "Why 44,100?", "Sampling must be at least twice the highest frequency you want to record. Human hearing stops around 20 kHz, so 44.1 kHz covers it."),
        (2, "Raw photos", "Professional cameras can save 'raw' files with 14 bits per colour channel, which is why they're often 30 MB or more each."),
        (3, "Metadata adds up", "A photo's metadata includes the date, camera settings and often GPS coordinates, which is worth remembering in exam answers."),
        (4, "Streaming", "An hour of standard-definition streaming uses roughly 1 GB; 4K uses about 7 GB, which is why data limits matter."),
        (5, "Show your working", "Examiners award method marks. Even if you slip up dividing by 8, the formula and substitution can still earn marks.")],
  ws=dict(title="Data capacity and calculations", objectives=["know what data capacity means", "understand how to calculate data capacity requirements"],
    starter="A phone advert says 128 GB of storage. Work out roughly how many 4 MB photos that is, and check with a partner.", starter_lines=2,
    keyterms=["Data capacity", "File size"], keyq="How do you calculate data capacity?",
    extra=dict(title="Three capacity scenarios", instr="Show your working for each, and give the answer in a sensible unit.", head=["Scenario", "Working", "Answer"],
               rows=[["Image: 1,200 × 900, 24-bit colour", "", ""], ["Sound: 3 minutes, 44,100 Hz, 16 bits", "", ""], ["Text: 5,000 characters, 8-bit ASCII", "", ""]]),
    exam=[("State the formula for calculating the file size of a bitmap image.", 1, 1),
          ("An image is 600 × 400 pixels with a colour depth of 8 bits. Calculate the file size in kilobytes. Show your working.", 3, 4),
          ("A sound is sampled at 16,000 Hz with a bit depth of 8 for 20 seconds. Calculate the file size in kilobytes.", 3, 4)],
    confidence=["Image file size calculations", "Sound file size calculations", "Converting to sensible units"]))

L8 = dict(id="ms-l08", topic="1.2", lesson=8, title="Binary workshop", img="MS_L08_BinaryWorkshop_360",
  description="Convert between denary and 8-bit binary, add binary numbers, and see what happens when they overflow.",
  kicker=f"{K12}  |  Lesson 8", scene_title="Binary workshop", subtitle=SUB12,
  intro="Time to work in binary. Convert both ways, learn which bit is most significant, add two 8-bit numbers, and find out what an overflow error is.",
  keywords=["Binary", "Denary", "Place value", "MSB", "LSB", "Carry", "Overflow"],
  stations=[
   dict(name="Place values", bullets=["Each bit in an 8-bit number has a place value: 128, 64, 32, 16, 8, 4, 2, 1.", "Add the place values above every 1 to get the denary number.",
        "The largest 8-bit number is 255, when every bit is 1."], challenge="What is 11111111 in denary, and why?",
        ill=("table", ["128", "64", "32", "16", "8", "4", "2", "1"], [["1", "0", "0", "1", "1", "1", "0", "0"]]), fact="The place values of an 8-bit number are...",
        tasks=[convert("Convert 10011100 into denary.", "binary", "denary", 156, "128 + 16 + 8 + 4 = 156."),
               mcq("What is the largest number that 8 bits can store?", "255", ["128", "256", "1,000"], "All eight place values added together: 128 + 64 + 32 + 16 + 8 + 4 + 2 + 1 = 255.")]),
   dict(name="Denary to binary", bullets=["Work from the left: does 128 fit? If yes, write 1 and subtract it.", "Carry on down through 64, 32, 16, 8, 4, 2 and 1.",
        "Check by adding your place values back up."], challenge="Convert 173 into 8-bit binary and show your working.",
        ill=("flow", ["Does 128 fit?", "Subtract and move on", "Repeat to 1", "Check the total"]), fact="To convert denary to binary, you...",
        tasks=[convert("Convert 173 into 8-bit binary.", "denary", "binary", 173, "128 + 32 + 8 + 4 + 1 = 173, so 10101101."),
               convert("Convert 96 into 8-bit binary.", "denary", "binary", 96, "64 + 32 = 96, so 01100000.")]),
   dict(name="MSB and LSB", bullets=["The most significant bit (MSB) is the leftmost bit: it has the largest place value.",
        "The least significant bit (LSB) is the rightmost: place value 1.", "Changing the MSB changes the number by 128; changing the LSB changes it by 1."],
        challenge="Explain the terms most significant bit and least significant bit.", ill=("tiles", [("MSB = 128", "r"), ("LSB = 1", "b")], 2), fact="The MSB is... The LSB is...",
        tasks=[mcq("Which bit is the most significant bit?", "The leftmost bit, with the place value 128", ["The rightmost bit, with place value 1", "The middle bit", "Whichever bit is a 1"],
                   "Most significant means it makes the biggest difference to the value."),
               mcq("Changing the least significant bit from 0 to 1 changes the number by how much?", "1", ["128", "8", "255"], "The LSB is the ones column.")]),
   dict(name="Binary addition", bullets=["Add column by column from the right, just like denary.", "0+0 = 0; 0+1 = 1; 1+1 = 10, so write 0 and carry 1.",
        "1+1+1 = 11, so write 1 and carry 1."], challenge="Add 00101101 and 00011011, showing your carries.",
        ill=("code", ["  0 0 1 0 1 1 0 1", "+ 0 0 0 1 1 0 1 1", "= 0 1 0 0 1 0 0 0"], 28), fact="To add binary numbers, you...",
        tasks=[addshift("Add these two binary numbers. Tick the overflow box only if the answer needs a 9th bit.", mode="add", a=45, b=27, fb="45 + 27 = 72, which fits in 8 bits."),
               mcq("In binary, what is 1 + 1?", "0, carry 1", ["2", "1", "11 with no carry"], "Binary has no digit 2, so it carries into the next column.")]),
   dict(name="Overflow", bullets=["8 bits can only hold 0 to 255.", "If the answer needs a 9th bit, it can't be stored: this is an overflow error.",
        "The stored answer is wrong, which can crash a program or corrupt data."], challenge="What can happen to the most significant bit when you add two binary numbers?",
        ill=("code", ["  1 1 1 1 0 0 0 0   (240)", "+ 0 0 0 1 0 1 0 0   (20)", "= 1 0 0 0 0 0 1 0 0   (260!)"], 26), fact="An overflow error happens when...",
        tasks=[addshift("Add these two binary numbers, and tick the overflow box if the answer needs a 9th bit.", mode="add", a=240, b=20, fb="240 + 20 = 260, which is more than 255, so there is an overflow."),
               mcq("What is an overflow error?", "The result of a calculation is too large for the number of bits available", ["A number that is too small to store", "A file that is too big for the disk", "A program that runs too long"],
                   "With 8 bits, anything over 255 overflows.")]),
   dict(name="Why it matters", bullets=["More bits means bigger numbers: 16 bits reach 65,535.", "Programs must choose a data type big enough for the values they'll hold.",
        "Famous failures, including a rocket, have been caused by overflow."], challenge="Suggest a situation where an overflow error could be dangerous.",
        ill=("table", ["Bits", "Largest value"], [["8", "255"], ["16", "65,535"], ["32", "4,294,967,295"]]), fact="Overflow matters because...",
        tasks=[mcq("How can a programmer avoid overflow errors?", "Use a data type with enough bits for the largest possible value", ["Use smaller numbers only", "Turn off error checking", "Use denary instead of binary"],
                   "16 or 32 bits gives much more headroom."),
               mcq("How many values can 16 bits represent?", "65,536", ["256", "1,024", "16"], "2 to the power 16.")]),
  ],
  final=dict(name="Final challenge: convert and add", floor_title="Final challenge: convert and add",
    intro="Three tasks: convert both ways, then add with an overflow check. Tap the star to start.",
    ill=("table", ["128", "64", "32", "16", "8", "4", "2", "1"], [["?", "?", "?", "?", "?", "?", "?", "?"]]),
    tasks=[convert("Convert 214 into 8-bit binary.", "denary", "binary", 214, "128 + 64 + 16 + 4 + 2 = 214, so 11010110."),
           convert("Convert 01101110 into denary.", "binary", "denary", 110, "64 + 32 + 8 + 4 + 2 = 110."),
           addshift("Add these two binary numbers, and tick the overflow box if needed.", mode="add", a=198, b=87, fb="198 + 87 = 285, which needs a 9th bit, so there is an overflow error.")]),
  info=[(0, "Counting on fingers", "In binary you can count to 31 on one hand: each finger is a place value, 1, 2, 4, 8 and 16."),
        (1, "Ariane 5", "In 1996 a rocket was destroyed 40 seconds after launch because a number too large was squeezed into too few bits."),
        (2, "Gandhi's nukes", "A famous game bug turned a peaceful leader aggressive when a value dropped below zero and wrapped around, though the story is partly myth."),
        (3, "Two's complement", "Negative numbers are stored using two's complement, where the MSB signals the sign. That's A level, but it starts here."),
        (4, "Why 255 appears everywhere", "Colour values often run 0 to 255 because each colour channel is stored in one byte."),
        (5, "Odd or even", "The least significant bit tells you instantly whether a binary number is odd (1) or even (0).")],
  ws=dict(title="Binary conversion and addition", objectives=["convert positive denary whole numbers (0-255) to 8-bit binary and back",
          "add two 8-bit binary integers", "understand the terms most and least significant bit", "understand how overflow errors occur"],
    starter="An 8-bit counter reads 11111111. What do you think happens when it counts one more?", starter_lines=2,
    keyterms=["Binary", "Overflow error"], keyq="What can happen when you add two binary numbers together?",
    extra=dict(title="Task: conversions", instr="Convert each number, showing the place values you used.", head=["Denary", "8-bit binary"],
               rows=[["37", ""], ["", "11001010"], ["190", ""], ["", "00110110"], ["255", ""]]),
    exam=[("Convert the denary number 173 into 8-bit binary.", 1, 1), ("Convert the binary number 01101110 into denary.", 1, 1),
          ("Add the binary numbers 11000110 and 01010111. State whether an overflow error occurs.", 3, 3), ("Explain what is meant by an overflow error.", 2, 2)],
    confidence=["Denary to binary", "Binary to denary", "Binary addition and overflow"]))

L10 = dict(id="ms-l10", topic="1.2", lesson=10, title="Shift and hex lab", img="MS_L10_ShiftAndHexLab_360",
  description="Multiply and divide with binary shifts, and learn why programmers write binary in hexadecimal.",
  kicker=f"{K12}  |  Lesson 10", scene_title="Shift and hex lab", subtitle=SUB12,
  intro="Two tools of the trade: binary shifts, which multiply and divide in one move, and hexadecimal, which makes long binary numbers readable.",
  keywords=["Binary shift", "Left shift", "Right shift", "Hexadecimal", "Nibble", "Overflow"],
  stations=[
   dict(name="Left shift", bullets=["Every bit moves left, and a 0 comes in at the right.", "A shift of one place multiplies the number by 2; two places multiplies by 4.",
        "Any bit pushed off the left end is lost: that's an overflow."], challenge="Illustrate a left shift of 1 on an 8-bit number without an overflow.",
        ill=("flow", ["00011010 (26)", "shift left 1", "00110100 (52)"]), fact="A left shift...",
        tasks=[addshift("Shift this number one place to the left.", mode="shift", value=26, dir="left", places=1, fb="26 × 2 = 52."),
               mcq("What does a left shift of 2 places do to a number?", "Multiplies it by 4", ["Multiplies it by 2", "Divides it by 4", "Adds 2 to it"], "Each place doubles the value, so two places is × 4.")]),
   dict(name="Right shift", bullets=["Every bit moves right, and a 0 comes in at the left.", "A shift of one place divides the number by 2.",
        "Bits pushed off the right end are lost, so the answer is rounded down."], challenge="Illustrate a right shift of 1 on an 8-bit number without an underflow.",
        ill=("flow", ["01001100 (76)", "shift right 1", "00100110 (38)"]), fact="A right shift...",
        tasks=[addshift("Shift this number one place to the right.", mode="shift", value=76, dir="right", places=1, fb="76 ÷ 2 = 38."),
               mcq("What happens when a 1 is pushed off the right-hand end during a right shift?", "It is lost, so the answer is rounded down", ["It wraps around to the left", "It causes an overflow error", "The shift is cancelled"],
                   "That's why 7 right-shifted once gives 3, not 3.5.")]),
   dict(name="Shifts and precision", bullets=["Shifting is very fast, so processors use it instead of multiplying and dividing where they can.",
        "Left shifts can overflow if a 1 is pushed off the left end.", "Right shifts lose the remainder."],
        challenge="Why might a programmer use a shift instead of multiplying by 2?", ill=("compare", "Left shift", ["× 2 each place", "Can overflow"], "Right shift", ["÷ 2 each place", "Loses remainders"], "b", "p"),
        fact="Shifts are used because...",
        tasks=[addshift("Shift this number two places to the left.", mode="shift", value=50, dir="left", places=2, fb="50 × 4 = 200, which still fits in 8 bits."),
               mcq("Why do processors use shifts rather than multiplication where possible?", "A shift is a much faster operation", ["Shifts are more accurate", "Multiplication isn't possible in binary", "Shifts use less storage"],
                   "It's one of the ALU's simplest operations.")]),
   dict(name="Why hexadecimal?", bullets=["Hexadecimal is base 16, using 0-9 then A-F.", "One hex digit represents exactly 4 bits, so a byte is two hex digits.",
        "It's much shorter and easier for people to read and copy than long binary."], challenge="Write out the hex digits and their denary values.",
        ill=("table", ["Hex", "Denary", "Binary"], [["9", "9", "1001"], ["A", "10", "1010"], ["F", "15", "1111"]]), fact="Hexadecimal is used because...",
        tasks=[mcq("Why do programmers use hexadecimal?", "It is shorter than binary and easier to read, and each digit is exactly 4 bits", ["Computers store data in hexadecimal", "It uses less memory", "It is the only base with letters"],
                   "Computers still work in binary; hex is for humans."),
               mcq("What is the denary value of the hex digit C?", "12", ["10", "11", "13"], "A = 10, B = 11, C = 12, D = 13, E = 14, F = 15.")]),
   dict(name="Denary and hex", bullets=["Denary to hex: divide by 16; the whole number is the first digit, the remainder the second.",
        "Or convert to binary first, then split into two nibbles.", "Hex to denary: first digit × 16, plus the second digit."],
        challenge="Convert 207 into hexadecimal, showing your method.", ill=("code", ["207 ÷ 16 = 12 remainder 15", "12 = C, 15 = F", "207 = CF"], 28), fact="To convert between denary and hex...",
        tasks=[convert("Convert 207 into 2-digit hexadecimal.", "denary", "hex", 207, "207 ÷ 16 = 12 remainder 15, so CF."),
               convert("Convert 2D into denary.", "hex", "denary", 45, "2 × 16 = 32, plus D (13) = 45.")]),
   dict(name="Binary and hex", bullets=["Split the byte into two nibbles of 4 bits.", "Convert each nibble separately into one hex digit.",
        "1101 0110 becomes D6."], challenge="Convert 10111010 into hexadecimal.", ill=("code", ["1101 0110", "1101 = 13 = D", "0110 = 6", "= D6"], 28), fact="To convert binary to hex, you...",
        tasks=[convert("Convert 10111010 into hexadecimal.", "binary", "hex", 186, "1011 = B and 1010 = A, so BA."),
               convert("Convert E4 into 8-bit binary.", "hex", "binary", 228, "E = 1110 and 4 = 0100, so 11100100.")]),
  ],
  final=dict(name="Final challenge: shift and convert", floor_title="Final challenge: shift and convert",
    intro="Three tasks mixing shifts and hexadecimal. Tap the star to start.",
    ill=("table", ["Binary", "Hex", "Denary"], [["1111", "F", "15"], ["1010", "A", "10"], ["0110", "6", "6"]]),
    tasks=[addshift("Shift this number one place left. Watch for an overflow.", mode="shift", value=100, dir="left", places=1, fb="100 × 2 = 200, which still fits."),
           convert("Convert 11010110 into hexadecimal.", "binary", "hex", 214, "1101 = D and 0110 = 6, so D6."),
           convert("Convert 9F into denary.", "hex", "denary", 159, "9 × 16 = 144, plus F (15) = 159.")]),
  info=[(0, "Colour codes", "Web colours are written in hex: #FF0000 is red, because the red channel is 255 and the others are 0."),
        (1, "MAC addresses", "The MAC addresses from topic 1.3 are written in hex pairs for exactly this reason: each pair is one byte."),
        (2, "Shifting in code", "In many languages, x << 1 means shift left, and programmers use it as a fast way to double a number."),
        (3, "Underflow", "Shifting right too far loses everything, leaving zero. That's sometimes called an underflow."),
        (4, "Base 16 by hand", "Counting in hex: 8, 9, A, B, C, D, E, F, 10. That '10' means sixteen, not ten."),
        (5, "Memory dumps", "When engineers inspect memory, it's displayed in hex, because a screen of pure binary would be unreadable.")],
  ws=dict(title="Binary shift and hexadecimal", objectives=["know how to perform left and right binary shifts", "understand what a binary shift achieves",
          "convert denary to 2-digit hexadecimal and back", "convert between binary and hexadecimal"],
    starter="Why might a programmer prefer to write FF rather than 11111111? Suggest two reasons.", starter_lines=3,
    keyterms=["Binary shift", "Hexadecimal"], keyq="What is the relationship between denary, binary and hexadecimal?",
    extra=dict(title="Task: conversions", instr="Complete the table.", head=["Denary", "8-bit binary", "Hex"],
               rows=[["45", "", ""], ["", "11100100", ""], ["", "", "B7"], ["208", "", ""]]),
    exam=[("Explain what a left shift of one place achieves.", 2, 2), ("Perform a right shift of two places on 10110000 and state the denary result.", 2, 2),
          ("Convert the denary number 207 into hexadecimal.", 1, 1), ("Convert the binary number 10111010 into hexadecimal.", 1, 1)],
    confidence=["Left and right shifts", "Denary and hexadecimal", "Binary and hexadecimal"]))

L11 = dict(id="ms-l11", topic="1.2", lesson=11, title="Revision HQ 1.2 part 1", img="MS_L11_RevisionHQ12Part1_360",
  description="Recap lessons 1 to 10: memory, storage, units, capacity, binary, shifts and hexadecimal.",
  kicker=f"{K12}  |  Lesson 11", scene_title="Revision HQ 1.2 part 1", subtitle="Catch up and revise lessons 1 to 10",
  intro="Each station sums up one part of the first half of the topic. Answer its quiz, and your score screen will show what to revise. Finish any outstanding tasks too.",
  keywords=["RAM", "ROM", "Virtual memory", "Storage", "Units", "Binary", "Hex"], revision=True,
  stations=[
   dict(name="Primary storage", bullets=["RAM: volatile, read/write, holds what's in use.", "ROM: non-volatile, read-only, holds the boot program.",
        "Primary storage is directly accessible by the CPU."], challenge="State two differences between RAM and ROM.", ill=("icons", [("ram", "RAM"), ("cpu", "ROM")]),
        tasks=[mcq("Which is volatile?", "RAM", ["ROM", "A hard disk", "An SSD"], "Volatile means the contents are lost without power."),
               mcq("What does ROM hold?", "The boot program or BIOS", ["Your documents", "Open applications", "Virtual memory"], "It starts the computer up."),
               mcq("What does primary storage mean?", "Memory the CPU can access directly", ["Storage kept off-site", "The largest drive in the computer", "Cloud storage"], "RAM, ROM, cache and registers.")]),
   dict(name="Virtual memory", bullets=["Secondary storage used as extra RAM when RAM is full.", "Data is swapped in and out as the CPU needs it.",
        "Much slower than RAM, so more RAM is the real fix."], challenge="Explain why virtual memory slows a computer down.", ill=("flow", ["RAM full", "Swap out", "Swap in"]),
        tasks=[mcq("When is virtual memory used?", "When RAM is full", ["When the computer is switched off", "When ROM is full", "Only on servers"], "It borrows space from secondary storage."),
               mcq("Why is virtual memory slow?", "Secondary storage is much slower than RAM", ["It is stored online", "It uses the ROM", "It only works at night"], "Every swap means slow disk access."),
               mcq("What is the best way to reduce the use of virtual memory?", "Install more RAM", ["Buy a bigger monitor", "Delete the BIOS", "Use a slower CPU"], "More RAM means less swapping.")]),
   dict(name="Secondary storage", bullets=["Magnetic: platters and a read/write head; cheap and huge.", "Optical: a laser reading pits and lands; cheap and portable.",
        "Solid state: flash memory; fast and durable but dearer."], challenge="Name a suitable device for a laptop and justify it.", ill=("icons", [("disk", "Magnetic"), ("disk", "Optical"), ("ram", "Solid state")]),
        tasks=[mcq("Which type has no moving parts?", "Solid state", ["Magnetic", "Optical", "Tape"], "That's why it survives being carried around."),
               mcq("Which is cheapest per gigabyte for very large amounts of data?", "Magnetic", ["Solid state", "Optical", "RAM"], "Hard disks and tape store bulk data cheaply."),
               mcq("Which would you choose for a video camera's storage?", "A solid state memory card", ["An internal hard disk", "A Blu-ray disc", "Magnetic tape"], "Portable, durable and fast to write.")]),
   dict(name="Units and capacity", bullets=["Bit, nibble (4), byte (8), then kB, MB, GB, TB, PB, each ×1,000.",
        "Image size = width × height × colour depth.", "Sound size = sample rate × bit depth × duration."], challenge="Calculate the size of a 400 × 300 image at 8 bits per pixel.",
        ill=("table", ["Unit", "Size"], [["Byte", "8 bits"], ["kB", "1,000 bytes"], ["MB", "1,000 kB"]]),
        tasks=[mcq("How many bytes are in 3 kB?", "3,000", ["24", "384", "3,072,000"], "Use 1,000 per step in the exam."),
               mcq("What is the formula for image file size?", "Width × height × colour depth", ["Width + height + depth", "Sample rate × duration", "Characters × bits"], "All in pixels and bits."),
               mcq("A sound is 8,000 Hz, 8-bit, 10 seconds. What is its size in bits?", "640,000", ["80,000", "6,400", "64,000"], "8,000 × 8 × 10.")]),
   dict(name="Binary and addition", bullets=["Place values: 128, 64, 32, 16, 8, 4, 2, 1.", "MSB is leftmost, LSB is rightmost.",
        "8 bits hold 0 to 255; anything larger overflows."], challenge="Convert 173 to binary and add 00001111 to it.", ill=("table", ["128", "64", "32", "16", "8", "4", "2", "1"], [["1", "0", "1", "0", "1", "1", "0", "1"]]),
        tasks=[mcq("What is 10011100 in denary?", "156", ["142", "158", "172"], "128 + 16 + 8 + 4."),
               mcq("What is the largest number 8 bits can hold?", "255", ["128", "256", "512"], "All bits set to 1."),
               mcq("When does an overflow error occur?", "When the result needs more bits than are available", ["When a number is negative", "When two numbers are equal", "When the disk is full"], "Over 255 in 8 bits.")]),
   dict(name="Shifts and hex", bullets=["Left shift ×2 per place; right shift ÷2 per place.", "One hex digit is exactly 4 bits.",
        "A = 10 up to F = 15."], challenge="Convert 11010110 into hexadecimal.", ill=("table", ["Binary", "Hex"], [["1101", "D"], ["0110", "6"]]),
        tasks=[mcq("A left shift of 1 place does what?", "Multiplies by 2", ["Divides by 2", "Adds 1", "Reverses the bits"], "Each place is worth double."),
               mcq("What is 1111 in hexadecimal?", "F", ["E", "15", "10"], "F is 15 in denary."),
               mcq("How many bits does one hex digit represent?", "4", ["1", "8", "16"], "That's why a byte is two hex digits.")]),
  ],
  final=dict(name="Final challenge: mixed practice", floor_title="Final challenge: mixed practice",
    intro="Three practical tasks from across the first half of the topic. Tap the star to begin.",
    ill=("table", ["128", "64", "32", "16", "8", "4", "2", "1"], [["?", "?", "?", "?", "?", "?", "?", "?"]]),
    tasks=[convert("Convert 149 into 8-bit binary.", "denary", "binary", 149, "128 + 16 + 4 + 1 = 149."),
           addshift("Add these two binary numbers, ticking overflow if needed.", mode="add", a=180, b=95, fb="180 + 95 = 275, so there is an overflow."),
           convert("Convert 10110010 into hexadecimal.", "binary", "hex", 178, "1011 = B and 0010 = 2, so B2.")]),
  info=[(0, "Revision tip", "Practise conversions little and often. Five minutes a day beats an hour the night before."),
        (1, "Check by adding", "After converting denary to binary, always add the place values back up to check you get the original number."),
        (2, "Units in the exam", "Read carefully whether the answer is wanted in bits, bytes, kB or MB: it's the most common place to drop a mark."),
        (3, "Storage answers", "Name the device, name the characteristic, then link it to the scenario. All three parts earn marks."),
        (4, "Say it simply", "Volatile means 'loses its contents when the power is off'. Learn that phrase word for word."),
        (5, "Try Binary blitz", "The bonus Binary blitz challenge is the fastest way to get quick at conversions before the test.")],
  ws=dict(title="Catch-up and revision: lessons 1 to 10", objectives=["know which parts of the topic I am secure on", "finish any outstanding tasks from lessons 1 to 10"],
    starter="Without notes, write down the eight units of storage in order, and the eight place values of an 8-bit number.", starter_lines=3,
    keyterms=[], keyq=None,
    checklist=["Memory bay worksheet (L1): the RAM and ROM comparison table", "Swap space worksheet (L2): the virtual memory scenario",
               "Storage warehouse and Top Trumps worksheets (L3 and L4): the device cards", "Pick the storage worksheet (L5): the nine situations",
               "Units lab worksheet (L6): the unit conversions", "Capacity calculator worksheet (L7): the three calculations",
               "Binary workshop worksheet (L8): conversions and addition", "Shift and hex lab worksheet (L10): shifts and hexadecimal"],
    exam=[("Convert 149 into 8-bit binary.", 1, 1), ("Explain why a computer uses virtual memory.", 3, 3)],
    rag=["RAM and ROM", "Virtual memory", "Types of secondary storage", "Characteristics and suitability", "Units of storage", "Capacity calculations", "Binary conversion and addition", "Shifts and hexadecimal"],
    confidence=["Memory and storage", "Units and capacity", "Binary, shifts and hex"]))

L12 = dict(id="ms-l12", topic="1.2", lesson=12, title="Character foundry", img="MS_L12_CharacterFoundry_360",
  description="How text becomes binary: character sets, ASCII and Unicode, and why more bits means more characters.",
  kicker=f"{K12}  |  Lesson 12", scene_title="Character foundry", subtitle=SUB12,
  intro="Computers store text as numbers. Find out what a character set is, why ASCII ran out of room, and how Unicode fits every writing system in the world.",
  keywords=["Character set", "ASCII", "Unicode", "Character code", "Bits", "File size"],
  stations=[
   dict(name="Text as numbers", bullets=["Every character has a number, called its character code.", "The code is stored in binary, like any other number.",
        "The computer uses a character set to know which code means which character."], challenge="Convert the first letter of your name into binary.",
        ill=("table", ["Character", "Denary", "Binary"], [["A", "65", "01000001"], ["B", "66", "01000010"], ["a", "97", "01100001"]]), fact="Text is stored as...",
        tasks=[convert("The letter A has the character code 65. Show 65 in 8-bit binary.", "denary", "binary", 65, "65 is 01000001."),
               mcq("What is a character set?", "A collection of characters and the binary codes used to represent them", ["A set of fonts", "A group of keyboards", "The characters on one page"],
                   "Both computers must use the same set to agree on the meaning.")]),
   dict(name="ASCII", bullets=["ASCII uses 7 bits, giving 128 different characters.", "It covers English letters, digits, punctuation and control codes.",
        "Extended ASCII uses 8 bits for 256 characters."], challenge="How many characters can 7 bits represent, and why?", ill=("table", ["Bits", "Characters"], [["7", "128"], ["8", "256"]]),
        fact="ASCII is...",
        tasks=[mcq("How many characters can 7-bit ASCII represent?", "128", ["7", "256", "1,024"], "2 to the power 7."),
               mcq("Why was ASCII not enough for the whole world?", "It has no room for other alphabets, such as Arabic, Chinese or Greek", ["It was too slow", "It used too much storage", "It could not store digits"],
                   "128 codes barely cover English.")]),
   dict(name="The ASCII pattern", bullets=["Codes are in order: A is 65, B is 66, and so on.", "Lower case starts 32 later: a is 97.",
        "The digits 0 to 9 are codes 48 to 57."], challenge="If A is 65, what is E? And what is e?", ill=("code", ["A = 65   Z = 90", "a = 97   z = 122", "0 = 48   9 = 57"], 30),
        fact="In ASCII, the codes are ordered so that...",
        tasks=[mcq("If A is 65, what is D?", "68", ["66", "67", "69"], "The codes run in alphabetical order."),
               mcq("Why is the gap between A and a exactly 32?", "It makes converting between upper and lower case easy: just add or subtract 32", ["It is a coincidence", "There are 32 letters", "32 is the size of a byte"],
                   "It's a neat trick built into the character set.")]),
   dict(name="Unicode", bullets=["Unicode was designed to represent every writing system in the world.", "It uses 16 bits or more, giving tens of thousands of characters.",
        "It includes emoji, and the first 128 codes match ASCII."], challenge="Give two advantages and one disadvantage of Unicode compared with ASCII.",
        ill=("compare", "ASCII", ["7 or 8 bits", "128 or 256 characters"], "Unicode", ["16+ bits", "Every language, plus emoji"], "b", "g"), fact="Unicode is...",
        tasks=[mcq("What is the main advantage of Unicode over ASCII?", "It can represent characters from every writing system, not just English", ["It uses fewer bits per character", "It makes files smaller", "It is faster to type"],
                   "Coverage is the point of Unicode."),
               mcq("What is the main disadvantage of Unicode?", "It uses more bits per character, so files are larger", ["It can't store English", "It has no emoji", "It only works online"],
                   "More bits per character means bigger text files.")]),
   dict(name="Bits and characters", bullets=["The number of bits decides how many characters can be represented: 2 to the power n.",
        "2 bits give 4; 4 bits give 16; 8 bits give 256.", "Add one bit and you double the number of characters."],
        challenge="How many binary combinations are there with 2, 4 and 8 bits?", ill=("table", ["Bits", "Combinations"], [["2", "4"], ["4", "16"], ["8", "256"], ["16", "65,536"]]),
        fact="The relationship between bits and characters is...",
        tasks=[mcq("How many different characters can 4 bits represent?", "16", ["4", "8", "32"], "2 to the power 4."),
               mcq("A character set has 1,000 characters. How many bits are needed per character?", "10", ["8", "9", "16"], "2 to the power 9 is 512, which isn't enough, but 2 to the power 10 is 1,024.")]),
   dict(name="Text file size", bullets=["File size = number of characters × bits per character.", "The same message in Unicode is roughly twice the size of 8-bit ASCII.",
        "Spaces and punctuation count as characters."], challenge="Calculate the size of a 1,000-character message in ASCII and in 16-bit Unicode.",
        ill=("code", ["1000 characters × 8 bits = 8,000 bits", "1000 characters × 16 bits = 16,000 bits"], 28), fact="Text file size is calculated by...",
        tasks=[mcq("A message has 250 characters stored in 8-bit ASCII. How big is it in bytes?", "250", ["2,000", "31", "8"], "250 × 8 = 2,000 bits, which is 250 bytes."),
               mcq("The same message is stored in 16-bit Unicode. How big is it now?", "500 bytes", ["250 bytes", "1,000 bytes", "125 bytes"], "Twice the bits per character means twice the size.")]),
  ],
  final=dict(name="Final challenge: spell it in binary", floor_title="Final challenge: spell it in binary",
    intro="Convert character codes and answer the character set questions. Tap the star to begin.",
    ill=("code", ["A = 65 = 01000001", "B = 66 = 01000010", "C = 67 = 01000011"], 30),
    tasks=[convert("The letter H has the character code 72. Show 72 in 8-bit binary.", "denary", "binary", 72, "72 is 01001000."),
           convert("This binary is a character code: what is it in denary? (It is the letter i.)", "binary", "denary", 105, "01101001 is 105, the code for lower-case i."),
           sort("Does each statement describe ASCII or Unicode?", ["ASCII", "Unicode"], [
             ["Uses 7 bits for 128 characters", "ASCII"], ["Represents every writing system in the world", "Unicode"],
             ["Uses 16 bits or more per character", "Unicode"], ["Enough for English letters, digits and punctuation", "ASCII"],
             ["Includes emoji", "Unicode"], ["Produces smaller text files", "ASCII"]], "The first 128 Unicode codes are the same as ASCII, for compatibility.")]),
  info=[(0, "Morse code first", "Character codes are older than computers: Morse code assigned patterns of dots and dashes to letters in the 1830s."),
        (1, "Control codes", "The first 32 ASCII codes aren't printable: they're instructions such as carriage return, line feed and tab."),
        (2, "Emoji are characters", "Every emoji has a Unicode code point, which is why they can be typed, searched and sorted like letters."),
        (3, "UTF-8", "The most common way to store Unicode, UTF-8, uses one byte for ASCII characters and more for others, keeping English text small."),
        (4, "Mojibake", "When text turns into strange symbols, it's usually because it was saved in one character set and read in another."),
        (5, "Sorting", "Because A is 65 and a is 97, a simple sort puts all the capitals before the lower-case letters.")],
  ws=dict(title="Character sets", objectives=["understand that all data, including text, is represented in binary", "know what is meant by a character set",
          "understand the relationship between the number of bits and the number of characters", "know about ASCII and Unicode"],
    starter="A vending machine has 4 buttons. How many different combinations of two presses are there? What about 8 buttons?", starter_lines=2,
    keyterms=["Character set", "Unicode"], keyq="How does a computer store characters, and what are the implications for the number of bits used?",
    extra=dict(title="Task: your name in binary", instr="Use the ASCII codes (A = 65, a = 97) to write the first five letters of your name.",
               head=["Letter", "ASCII code", "8-bit binary"], rows=[["", "", ""], ["", "", ""], ["", "", ""], ["", "", ""], ["", "", ""]]),
    exam=[("State what is meant by a character set.", 1, 1), ("Explain why Unicode uses more storage than ASCII.", 2, 2),
          ("A character set uses 8 bits per character. State how many characters it can represent.", 1, 1)],
    confidence=["What a character set is", "ASCII and Unicode", "Bits, characters and file size"]))
