from kit import mcq, multi, sort, match, order

K24 = "2.4 Boolean logic"
SUB24 = "OCR J277 Paper 2  |  Computational thinking, algorithms and programming"
def circuit(q, expr, fb=""): return dict(t="circuit", q=q, expr=expr, fb=fb)
def expr_(q, expr, fb="", out=None): d = dict(t="expr", q=q, expr=expr, fb=fb); d.update(out=out) if out else None; return d
def table(q, expr, fb="", cols=None, out=None, inputs=None, diagram=True):
    d = dict(t="table", q=q, expr=expr, fb=fb, diagram=diagram)
    if cols: d["cols"] = cols
    if out: d["out"] = out
    if inputs: d["inputs"] = inputs
    return d

L1 = dict(id="bl-lesson1", topic="2.4", lesson=1, title="Logic gate lab", img="BL_L01_LogicGateLab",
  description="Meet AND, OR and NOT, fill in their truth tables, then build your own logic circuits by dragging gates and wires.",
  kicker=f"{K24}  |  Lesson 1", scene_title="Logic gate lab", subtitle=SUB24,
  intro="Every decision a computer makes comes down to three logic gates: AND, OR and NOT. Learn how each one works, then build real logic circuits by dragging gates onto a board and wiring them up.",
  keywords=["AND", "OR", "NOT", "Truth table", "Logic diagram", "Input", "Output"],
  stations=[
   dict(name="The AND gate", bullets=["The output is 1 (true) only if both inputs are 1.", "In a Boolean expression: A AND B, or A ∧ B.", "Think: 'A and B must both be true'."],
        challenge="Give an everyday example of an AND decision.", ill=("gate", "AND", "∧"), fact="An AND gate outputs 1 when...",
        tasks=[mcq("When is the output of an AND gate 1?", "Only when both inputs are 1", ["When either input is 1", "When both inputs are 0", "When the inputs are different"], "Both inputs have to be true."),
               table("Complete the truth table for A AND B. Click each ? to change it to 0 or 1.", "A AND B", "Only the last row, where both inputs are 1, outputs 1.")]),
   dict(name="The OR gate", bullets=["The output is 1 if either input is 1, or both are.", "In a Boolean expression: A OR B, or A ∨ B.", "Think: 'at least one of them is true'."],
        challenge="Give an everyday example of an OR decision.", ill=("gate", "OR", "∨"), fact="An OR gate outputs 1 when...",
        tasks=[mcq("When is the output of an OR gate 0?", "Only when both inputs are 0", ["When either input is 0", "When both inputs are 1", "Never"], "One true input is enough to make OR output 1."),
               table("Complete the truth table for A OR B.", "A OR B", "Only the first row, where both inputs are 0, outputs 0.")]),
   dict(name="The NOT gate", bullets=["NOT has one input, and it reverses it: 1 becomes 0 and 0 becomes 1.", "In a Boolean expression: NOT A, or ¬A.", "The small circle on the symbol means 'invert'."],
        challenge="Why does the NOT gate only have one input?", ill=("gate", "NOT", "¬"), fact="A NOT gate...",
        tasks=[mcq("What does a NOT gate do?", "Reverses its input: 1 becomes 0, and 0 becomes 1", ["Outputs 1 when both inputs are 1", "Outputs 1 when either input is 1", "Always outputs 0"], "NOT is also called an inverter."),
               table("Complete the truth table for NOT A.", "NOT A", "NOT flips each input.")]),
   dict(name="Symbols and pseudocode", bullets=["AND can be written ∧, OR can be written ∨, and NOT can be written ¬.", "Programs use the same logic in if statements.",
        "In the cash machine program, the card is present and the PIN matches, so the AND is true."], challenge="What does the cash machine program output, and why?",
        ill=("code", ["pin = 1234", "card = True", "if card and pin == 1234:", '    print("Welcome")', "else:", '    print("Card declined")'], 26),
        fact="The symbols for AND, OR and NOT are...",
        tasks=[match("Match each symbol to its operator.", [["∧", "AND"], ["∨", "OR"], ["¬", "NOT"]], "You'll see these symbols in exam questions."),
               mcq("What does the cash machine program output?", "Welcome", ["Card declined", "1234", "Nothing"], "Both conditions are true, so the AND is true.")]),
   dict(name="Two-level circuits", bullets=["Gates can feed into other gates.", "In (A OR B) AND C, the brackets are worked out first: the OR gate feeds the AND gate.",
        "Work from the inputs on the left to the output on the right."], challenge="Build the circuits on the board: drag gates from the top and wire outputs to inputs.",
        ill=("diagram", "(A OR B) AND C"), fact="In a two-level circuit...",
        tasks=[circuit("Build the circuit for Q = A AND C.", "A AND C", "One AND gate, with inputs A and C."),
               circuit("Build the circuit for Q = (A OR B) AND C.", "(A OR B) AND C", "The OR gate's output feeds one input of the AND gate.")]),
   dict(name="NOT and brackets", bullets=["NOT is worked out before AND and OR, unless there are brackets.", "NOT A OR B means (NOT A) OR B.",
        "NOT (A AND B) means work out A AND B first, then reverse it."], challenge="What's the difference between NOT A AND B and NOT (A AND B)?", ill=("diagram", "NOT (A AND B)"), fact="NOT is worked out...",
        tasks=[mcq("In NOT A OR B, which part is worked out first?", "NOT A", ["A OR B", "B", "They're all worked out at once"], "NOT applies only to the thing right after it, unless there are brackets."),
               circuit("Build the circuit for Q = NOT A OR B.", "NOT A OR B", "NOT A feeds one input of the OR gate."),
               circuit("Build the circuit for Q = NOT (A AND B).", "NOT (A AND B)", "The AND gate's output goes into the NOT gate.")]),
  ],
  final=dict(name="Final challenge: build and read", floor_title="Final challenge: build and read",
    intro="Build a four-input circuit, then write the expression for a diagram. Drag the tiles into the answer row to write an expression.",
    ill=("tiles", [("AND ∧", "b"), ("OR ∨", "p"), ("NOT ¬", "o")], 3),
    tasks=[circuit("Build the circuit for Q = (A AND B) OR (C AND D).", "(A AND B) OR (C AND D)", "Two AND gates feed one OR gate."),
           expr_("Write the Boolean expression for this logic diagram.", "NOT (A OR B)", "The OR gate comes first, then its output is reversed.")]),
  info=[(0, "George Boole", "Boolean logic is named after George Boole, an English mathematician who described this kind of algebra in 1854, long before computers existed."),
        (1, "Made of transistors", "Inside a CPU, logic gates are built from transistors, tiny electronic switches. A modern CPU contains billions of them."),
        (2, "Claude Shannon", "In 1937, a student called Claude Shannon showed that Boole's logic could be built with electrical switches. That idea is the basis of every digital computer."),
        (3, "Search engines", "Many search engines and library catalogues let you use AND, OR and NOT to narrow down your search results."),
        (4, "One gate to rule them all", "A NAND gate (NOT AND) is 'universal': any other gate, and so any computer, can be built using only NAND gates."),
        (5, "1 and 0", "True and false, on and off, 1 and 0: they all mean the same thing in logic. Computers use the voltage in a wire to represent them.")],
  ws=dict(title="Simple logic diagrams", objectives=["know the symbols for the logic gates AND, OR and NOT", "understand the truth tables for AND, OR and NOT", "combine Boolean operators using AND, OR and NOT"],
    starter="A cash machine checks that a card is present AND the PIN is correct before it pays out. Write down two more everyday decisions that need both conditions to be true.", starter_lines=2,
    keyterms=["AND gate", "Logic gate"], keyq="How do you draw a logic diagram?",
    exam=[("Draw the logic diagram for Q = NOT (P AND R).", 2, 0), ("Give the output of an OR gate when its inputs are 0 and 1.", 1, 1), ("Complete a truth table for NOT S.", 2, 0)],
    draw_exam=True,
    confidence=["The symbols for AND, OR and NOT", "The truth tables for AND, OR and NOT", "Combining operators in logic diagrams"]))

L2 = dict(id="bl-lesson2", topic="2.4", lesson=2, title="Truth table detectives", img="BL_L02_TruthTableDetectives",
  description="Crack two- and three-input truth tables, including intermediate columns, and work out logic from electric circuits.",
  kicker=f"{K24}  |  Lesson 2", scene_title="Truth table detectives", subtitle=SUB24,
  intro="A truth table shows the output of a circuit for every possible combination of inputs. Learn how to set one out, then solve one- and two-level circuits using intermediate columns.",
  keywords=["Truth table", "Input", "Output", "Intermediate", "Combination", "2ⁿ rows"],
  stations=[
   dict(name="Setting out a truth table", bullets=["List every combination of inputs. Each input doubles the rows: 2 inputs give 4 rows, 3 give 8, 4 give 16.", "Count up in binary: 00, 01, 10, 11.",
        "Then work out the output for each row."], challenge="How many rows would a truth table with 5 inputs need?",
        ill=("table", ["A", "B", "C"], [["0", "0", "0"], ["0", "0", "1"], ["0", "1", "0"], ["...", "...", "..."], ["1", "1", "1"]]), fact="To complete a truth table, you...",
        tasks=[mcq("How many rows does a truth table with 3 inputs need?", "8", ["3", "6", "9"], "Each input doubles the number of rows: 2 × 2 × 2 = 8."),
               mcq("How many rows does a truth table with 4 inputs need?", "16", ["4", "8", "12"], "2⁴ = 16.")]),
   dict(name="Electric circuits", bullets=["Two switches in a row (series): the bulb lights only if both are on. That's AND.", "Two switches side by side (parallel): the bulb lights if either is on. That's OR."],
        challenge="Design a circuit with switches that behaves like an OR gate.", ill=("compare", "Series", ["Both switches on", "= AND"], "Parallel", ["Either switch on", "= OR"], "b", "p"), fact="Switches in series... Switches in parallel...",
        tasks=[mcq("Two switches in series control a bulb. Which gate does this represent?", "AND", ["OR", "NOT", "None"], "Current can only flow if both switches are closed."),
               mcq("Two switches in parallel control a bulb. Which gate does this represent?", "OR", ["AND", "NOT", "None"], "Current can flow through either switch.")]),
   dict(name="NOT AND, NOT OR", bullets=["NOT (A AND B): work out A AND B, then reverse every result.", "NOT (A OR B): work out A OR B, then reverse every result.",
        "An intermediate column for the bracket makes this easier."], challenge="Complete both truth tables at this station.", ill=("diagram", "NOT (A AND B)"), fact="To find NOT (A AND B)...",
        tasks=[table("Complete the truth table for Q = NOT (A AND B).", "NOT (A AND B)", "It's the AND table, reversed.", cols=[["X", "A AND B"]]),
               table("Complete the truth table for Q = NOT (A OR B).", "NOT (A OR B)", "It's the OR table, reversed.", cols=[["X", "A OR B"]])]),
   dict(name="Three inputs", bullets=["With three inputs there are 8 rows.", "Use intermediate columns for each gate.", "(A AND B) AND NOT C: work out A AND B, then NOT C, then AND them together."],
        challenge="Which rows of (A AND B) AND NOT C output 1?", ill=("diagram", "(A AND B) AND NOT C"), fact="With three inputs...",
        tasks=[table("Complete the truth table for Q = (A AND B) AND NOT C.", "(A AND B) AND NOT C", "Only A = 1, B = 1, C = 0 outputs 1.", cols=[["X", "A AND B"], ["Y", "NOT C"]])]),
   dict(name="NOT A AND (B OR C)", bullets=["Work out NOT A in one column and B OR C in another.", "Then AND those two columns together.", "The output is 1 only when A is 0 and at least one of B and C is 1."],
        challenge="Explain why every row where A = 1 gives an output of 0.", ill=("diagram", "NOT A AND (B OR C)"), fact="For NOT A AND (B OR C)...",
        tasks=[table("Complete the truth table for Q = NOT A AND (B OR C).", "NOT A AND (B OR C)", "Rows where A = 1 always give 0, because NOT A is 0.", cols=[["X", "NOT A"], ["Y", "B OR C"]])]),
   dict(name="Four inputs", bullets=["Four inputs need 16 rows.", "Group the inputs: (A OR B) and (C AND D) can be worked out separately.", "Then combine the two intermediate columns."],
        challenge="Write the expression for the diagram in the experience.", ill=("diagram", "(A OR B) AND (C AND D)"), fact="With four inputs...",
        tasks=[mcq("For Q = (A OR B) AND (C AND D), which must be true for Q to be 1?", "C and D must both be 1, and at least one of A and B must be 1", ["All four inputs must be 1", "Any one input must be 1", "A and B must both be 0"], "Both halves must be true."),
               expr_("Write the Boolean expression for this logic diagram.", "(A AND B) OR (C AND D)", "Two AND gates feed an OR gate.")]),
  ],
  final=dict(name="Final challenge: detective's table", floor_title="Final challenge: the detective's table",
    intro="Complete the full truth table, using the intermediate columns to help you.",
    ill=("diagram", "(A OR B) OR NOT C"),
    tasks=[table("Complete the truth table for Q = (A OR B) OR NOT C.", "(A OR B) OR NOT C", "Only A = 0, B = 0, C = 1 outputs 0.", cols=[["X", "A OR B"], ["Y", "NOT C"]])]),
  info=[(0, "Binary counting", "The input columns of a truth table are just binary numbers counting up: 000, 001, 010 and so on. That's why there are 2ⁿ rows."),
        (1, "De Morgan's law", "NOT (A AND B) always gives the same result as NOT A OR NOT B. This rule, called De Morgan's law, lets engineers simplify circuits."),
        (2, "Light switches", "The two-way light switches at the top and bottom of many staircases work like an XOR gate: flipping either switch changes the light."),
        (3, "Truth tables everywhere", "Engineers use truth tables to test that circuits do exactly what they should, before building them."),
        (4, "Short circuits", "In real circuits, each extra gate adds a tiny delay. Designers try to use as few gates as possible."),
        (5, "Big tables", "A circuit with 10 inputs would need a truth table with 1,024 rows, so computers check large circuits automatically.")],
  ws=dict(title="Applying logic operators and truth tables", objectives=["understand how to complete truth tables from one- and two-level logic diagrams"],
    starter="A microwave only runs when the door is shut and the start button is pressed. A car beeps if either front door is open. Which logic gate does each one behave like?", starter_lines=3,
    keyterms=["Truth table", "Boolean operator"], keyq="How do you complete a truth table?",
    exam=[("State how many rows a truth table needs for four inputs.", 1, 1), ("Complete a truth table for Q = NOT P OR (Q AND R) on the back of this sheet.", 8, 0)],
    confidence=["Setting out a truth table", "One-level truth tables", "Two-level truth tables with intermediate columns"]))

L3 = dict(id="bl-lesson3", topic="2.4", lesson=3, title="Circuit workshop", img="BL_L03_CircuitWorkshop",
  description="Turn real scenarios into logic circuits and truth tables: a shop alarm, a hospital lift and a greenhouse heater.",
  kicker=f"{K24}  |  Lesson 3", scene_title="Circuit workshop", subtitle=SUB24,
  intro="Engineers turn real problems into logic. In the workshop you'll read three scenarios, build the circuit for each one, and complete its truth table.",
  keywords=["Scenario", "Logic diagram", "Truth table", "Intermediate output", "AND", "OR", "NOT"],
  stations=[
   dict(name="From words to logic", bullets=["Find the inputs and the output in the scenario.", "Look for the words 'and', 'or', 'not', 'either' and 'regardless'.",
        "Decide which parts go in brackets, then build from the inputs to the output."], challenge="How do you create a logic diagram from a scenario?",
        ill=("flow", ["Find inputs", "Find the logic words", "Add brackets", "Draw gates"]), fact="To turn a scenario into logic...",
        tasks=[mcq("'The alarm sounds if the door is open AND it is night.' Which gate is needed?", "AND", ["OR", "NOT", "No gate"], "Both conditions must be true."),
               mcq("'Regardless of the sensors, the alarm always sounds if the manual button is pressed.' How is the button joined to the rest?", "With an OR gate", ["With an AND gate", "With a NOT gate", "It isn't connected"], "'Regardless' means the button alone is enough, so it's OR.")]),
   dict(name="Scenario 1: the shop alarm", bullets=["A shop alarm sounds (X) if the door sensor is triggered (A) AND the shop is closed (B).", "Whatever the sensors say, it always sounds if the panic button is pressed (C)."],
        challenge="Build the shop alarm circuit, then complete its truth table.", ill=("icons", [("user", "Movement (A)"), ("lock", "Night (B)"), ("bug", "Manual (C)")]), fact="The shop alarm expression is...",
        tasks=[circuit("Build the shop alarm circuit: X = (A AND B) OR C.", "(A AND B) OR C", "A and B go into an AND gate, whose output goes into an OR gate with C."),
               table("Complete the truth table for the shop alarm.", "(A AND B) OR C", "The alarm is off only when C is 0 and A AND B is 0.", cols=[["W", "A AND B"]], out="X")]),
   dict(name="Scenario 2: the hospital lift", bullets=["A hospital lift has two doors (A and B). An alarm sounds (X)...", "if either door is still open,",
        "AND either the lift is moving (C) OR it is overloaded (D)."], challenge="Why do both halves of this circuit use OR gates?", ill=("diagram", "(A OR B) AND (C OR D)", "X"), fact="The hospital lift expression is...",
        tasks=[circuit("Build the hospital lift circuit: X = (A OR B) AND (C OR D).", "(A OR B) AND (C OR D)", "Two OR gates feed an AND gate."),
               mcq("In the hospital lift, when does the alarm sound?", "When at least one door is open, and the lift is either moving or overloaded", ["Only when both doors are open", "Whenever the lift moves", "Never"], "Both OR gates must output 1.")]),
   dict(name="Scenario 3: the greenhouse", bullets=["A greenhouse heater runs (X) if the gardener switches it on (A) OR the timer starts it (B).", "A window sensor (C) normally sends 0.",
        "When a window is opened it sends 1, and the heater must switch off."], challenge="Why does the window sensor need a NOT gate?", ill=("icons", [("user", "Operator (A)"), ("pc", "Schedule (B)"), ("lock", "Override (C)")]), fact="The greenhouse expression is...",
        tasks=[circuit("Build the greenhouse circuit: X = (A OR B) AND NOT C.", "(A OR B) AND NOT C", "NOT C means an open window stops the heater."),
               table("Complete the truth table for the greenhouse.", "(A OR B) AND NOT C", "Whenever C = 1, the heater is off.", cols=[["V", "A OR B"], ["W", "NOT C"]], out="X")]),
   dict(name="Editing a diagram", bullets=["Sometimes a diagram needs changing to match a new rule.", "Check each gate against the scenario, one at a time.",
        "Test your change with a truth table."], challenge="The shop alarm should now need the panic button AND the shop to be closed. How would the circuit change?", ill=("diagram", "(A AND B) OR C", "X"), fact="To edit a logic diagram...",
        tasks=[mcq("A circuit should output 1 only when both sensors are on, but it uses an OR gate. How do you fix it?", "Replace the OR gate with an AND gate", ["Add a NOT gate", "Remove one sensor", "Add another OR gate"], "AND needs both inputs to be 1."),
               mcq("The greenhouse window sensor is wired straight into the AND gate, without a NOT gate. What goes wrong?", "The heater runs only when a window is open", ["Nothing changes", "The heater never switches on", "The alarm sounds"],
                   "Without NOT, an open window would let the heater run.")]),
   dict(name="Reading diagrams", bullets=["To write an expression from a diagram, start at the output and work backwards.", "Each gate becomes an operator, and each gate feeding another becomes brackets."],
        challenge="Write the expression for the diagram in the experience.", ill=("diagram", "NOT A AND (B OR C)"), fact="To write an expression from a diagram...",
        tasks=[expr_("Write the Boolean expression for this logic diagram.", "NOT A AND (B OR C)", "NOT A and (B OR C) both feed the AND gate."),
               expr_("Write the Boolean expression for this logic diagram.", "(A OR B) AND NOT C", "This is the greenhouse circuit.", out="X")]),
  ],
  final=dict(name="Final challenge: design and test", floor_title="Final challenge: design and test",
    intro="A security light turns on (Q) if it's dark (A) AND movement is detected (B), unless the test switch (C) is on. Build it, then complete its truth table.",
    ill=("icons", [("lock", "Dark (A)"), ("user", "Movement (B)"), ("pc", "Test switch (C)")]),
    tasks=[circuit("Build the security light: Q = (A AND B) AND NOT C.", "(A AND B) AND NOT C", "'Unless' becomes AND NOT."),
           table("Complete the truth table for NOT (A AND B) OR C.", "NOT (A AND B) OR C", "Work out A AND B, reverse it, then OR it with C.", cols=[["X", "A AND B"], ["Y", "NOT (A AND B)"]])]),
  info=[(0, "Logic in everyday rules", "Nearly every automatic device hides a logic expression: a boiler, a lift, a car alarm. Reading the rule and underlining the words and, or and not is most of the work."),
        (1, "Real alarms", "Burglar alarms really are built from logic like this, often with extra inputs for doors, windows and a timer."),
        (2, "Fail-safe design", "Emergency stops are usually wired so that a broken wire also stops the machine. Safety engineers call this fail-safe design."),
        (3, "Programmable logic", "Factories use programmable logic controllers (PLCs), which are programmed with logic diagrams very like the ones you're drawing."),
        (4, "Test everything", "A truth table tests every possible combination, so engineers can prove a safety circuit will always behave correctly."),
        (5, "Simplify it", "Different circuits can give identical truth tables. Engineers choose the one with the fewest gates, because it's cheaper and faster.")],
  ws=dict(title="Create, complete or edit logic diagrams and truth tables", objectives=["understand how to create, complete or edit logic diagrams and truth tables for given scenarios"],
    starter="A security light should come on when it is dark AND movement is detected, unless the test switch is on. Write that rule in your own words, then underline the logic words.", starter_lines=3,
    keyterms=["Logic diagram", "Intermediate output"], keyq="How do you create logic diagrams from truth tables?",
    exam=[("A fire door alarm sounds (Q) when the door is open (D) AND the building is locked (L), or when the test button (T) is pressed. Write the Boolean expression.", 2, 2), ("Draw the logic diagram for your expression.", 3, 0)],
    rag=["The AND, OR and NOT gates and their symbols", "Truth tables for one-level diagrams", "Truth tables for two-level diagrams", "Logic diagrams from expressions", "Expressions and diagrams from scenarios"],
    confidence=["Creating diagrams for scenarios", "Completing truth tables with intermediate outputs", "Editing and reading logic diagrams"]))
