"""Original Topic 2.5 authoring data for Revise360. No third-party lesson assets."""
def mc(q,right,*wrong,fb): return dict(t='mcq',q=q,a=[right,*wrong],fb=fb)
def match(q,pairs,fb):return dict(t='match',q=q,pairs=pairs,fb=fb)
def sort(q,cats,items,fb):return dict(t='sort',q=q,cats=cats,items=items,fb=fb)
def order(q,steps,fb):return dict(t='order',q=q,steps=steps,fb=fb)
def multi(q,opts,correct,fb):return dict(t='multi',q=q,opts=opts,correct=correct,fb=fb)
def board(t,q,**kw):return dict(t=t,q=q,**kw)
def station(name,facts,challenge,answer,tasks):return dict(name=name,facts=facts,challenge=challenge,answer=answer,tasks=tasks)
LESSONS=[
 dict(id='pl-l01',lesson=1,title='Language design studio',slug='LanguageDesignStudio', subtitle='Choose the right level of language',
 description='Compare human-readable source code with machine instructions, then choose a language for a real development brief in the language design studio.',
 objectives=['Compare high-level and low-level languages.','Explain source code, machine code and portability.','Justify a language choice using the needs of a project.'],
 starter='A school changes its computers. What might make an existing program difficult to move to the new machines?',
 starterAnswer='The program might depend on a particular processor, operating system or library. It may need a compatible translator or changes to its source code.',
 terms=[('Source code','Program instructions written by a programmer in a programming language.'),('Portability','How readily a program can be used on a different computer system.')],
 stations=[
 station('Instructions for people and processors',['Source code is the version a programmer writes and edits.','A processor executes instructions in its own machine code.','High-level source must be processed by a suitable translator before the processor can perform its instructions.'], 'Why can a processor not directly execute a Python assignment as written?', 'Its instruction set uses machine-code operations; a translator must process the high-level source.',[
 mc('A developer edits total = price * quantity. What are they editing?','Source code','A processor circuit','The finished machine-code executable','A RAM address',fb='The expression is human-readable source code. It describes a calculation without listing individual processor operations.'),
 mc('What can a processor execute directly?','Machine-code instructions for its instruction set','Any English instruction','Python source without any translator','Comments in a source file',fb='The processor recognises its machine-code instruction set. It does not directly understand high-level source.')]),
 station('High-level languages',['High-level languages hide many hardware details.','Meaningful names and familiar expressions help people write, read and maintain code.','One high-level statement can require several machine instructions.'], 'Why could a high-level language reduce the time spent maintaining a school booking system?', 'Clear expressions and meaningful names help developers understand and change the program; fewer hardware details need to be managed.',[
 multi('Which TWO features support maintainability?',['Meaningful variable names','Expressions that hide hardware detail','Instructions written only as binary','A requirement to manage every register'],['Meaningful variable names','Expressions that hide hardware detail'],'Clear source makes the intention easier to follow. Binary and register management add detail for the programmer.'),
 mc('A statement calculates the average of three readings. How many machine instructions must it become?','The number depends on the language implementation and target processor','Exactly one in every case','Always exactly three','None, because high-level code bypasses the CPU',fb='A high-level operation can become several low-level instructions; the mapping is not a fixed universal ratio.')]),
 station('Low-level languages',['Machine code and assembly language are low-level forms.','Assembly uses mnemonic instruction names rather than long strings of binary.','Low-level code is closely tied to a processor instruction set and exposes hardware details.'], 'Why might low-level code be useful in a small part of a device controller?', 'It can give a programmer precise control over processor operations or hardware resources, at the cost of more difficult development.',[
 sort('Classify the descriptions.',['High-level','Low-level'],[['An expression hides register handling','High-level'],['Instructions are closely tied to one processor family','Low-level'],['Mnemonic operations name hardware instructions','Low-level'],['Code focuses on the problem rather than each CPU step','High-level']],'Both levels are useful. Choose according to the problem and the control needed.'),
 mc('Which is a realistic drawback of low-level programming?','It takes specialist knowledge and is harder to move between processor families','It can never access hardware','It is automatically free of bugs','It cannot contain instructions',fb='Detailed control brings more work for the programmer and stronger dependence on the target architecture.')]),
 station('Portability is conditional',['High-level source is usually easier to move between platforms.','The destination still needs a compatible implementation and required libraries.','A compiled executable normally targets a particular platform; portable source does not make every executable universal.'], 'A source file runs on two systems after installing compatible tools. Does this prove one compiled executable will run everywhere?', 'No. Source portability and binary compatibility are different; the executable may target one processor or operating system.',[
 mc('A program must run on several types of computer. Which choice usually helps?','High-level source with compatible tools for each target','Machine code for just one CPU used unchanged everywhere','Removing every translator','Using memory addresses as all variable names',fb='High-level source generally travels more easily, but platform-specific libraries or features can still require changes.'),
 mc('Why might an executable made for one processor fail on another?','The target processor may use a different instruction set','The source uses too many comments','All executables require the original editor','Executables contain no instructions',fb='Compiled code must match the required target platform.')]),
 station('Choose for the brief',['There is no best language level for every project.','Compare development time, maintenance, portability and hardware control.','Support a recommendation with the needs stated in the brief.'], 'Recommend a level for a museum booking tool used on several systems. Link your choice to two needs.', 'High-level: clearer code supports updates and compatible implementations can support different systems. Check any platform-dependent libraries.',[
 board('language','Choose a language level and the reason that best meets the museum brief.',brief='museum'),
 mc('Which explanation is strongest?','High-level source makes regular feature changes easier for a team to maintain','High-level is always faster because it is newer','Assembly is best because it is harder to read','Machine code works unchanged on all processors',fb='A justified choice connects a characteristic to the particular project, rather than making an absolute claim.')]),
 station('Challenge the shortcuts',['Readable code can still contain errors.','Low-level code is not automatically faster than every compiled high-level program.','Testing checks behaviour; choosing a language does not prove correctness.'], 'Explain why “low-level always means faster” is too strong.', 'Performance depends on the implementation, algorithm, compiler and hardware. Low-level control can help, but does not guarantee a faster program.',[
 board('language','Now choose for a carefully specified hardware-control routine.',brief='device'),
 mc('A program is readable and compiles successfully. What must the developer still do?','Test that the outputs meet the requirements','Assume every result is correct','Delete the test data','Convert the source to a picture',fb='Translation can succeed even when a program implements the wrong calculation.')])],
 plenary=[mc('A team must maintain a timetable app across different systems. Which recommendation is best justified?','High-level source for maintainability and portability, with compatible tools on each system','Machine code because one binary fits every CPU','Assembly because no specialist knowledge is needed','No programming language is needed',fb='Link the choice to the team and target platforms. Portability still has conditions.'),
 match('Match each term to its meaning.',[['Source code','Instructions written by a programmer'],['Machine code','Instructions executed directly by the target CPU'],['Portability','Ease of moving a program between systems']],'Source code is translated or processed for execution; machine code is specific to the target instruction set.')],
 exam=[('Explain two reasons to choose a high-level language for a booking system maintained by several programmers.',4,'Meaningful/readable source (1) helps the team understand and modify it (1). Greater source portability (1) supports different systems when compatible implementations exist (1). Accept another explained relevant reason.'),('Explain why a machine-code program for one CPU may not run on a different CPU.',2,'Machine code uses a particular instruction set (1); a different CPU may not recognise those instructions (1).')]),
 dict(id='pl-l02',lesson=2,title='Instruction workshop',slug='InstructionWorkshop',subtitle='Follow code down to the processor',
 description='Step through an original miniature processor, watch its accumulator and output, and connect readable instructions to binary machine code. Includes clearly labelled low-level enrichment.',
 objectives=['Distinguish source, assembly-style instructions and machine code.','Explain why machine instructions depend on the target CPU.','Trace a small instruction sequence as optional enrichment.'],
 starter='A program should add 6 and 2, then display 8. What information would help you check each step?',starterAnswer='The instructions, their order, the current values, the next instruction and the output help you trace the calculation.',
 terms=[('Machine code','Binary-encoded instructions that a particular processor can execute directly.'),('Mnemonic','A short, memorable name used to represent an operation.')],
 stations=[
 station('Three views of one job',['A high-level statement describes the intended calculation.','Assembly-style mnemonics expose small processor operations.','Machine code encodes operations and their data in binary.'], 'Why can a short high-level calculation require several CPU instructions?', 'The CPU may need separate operations to load values, calculate and output or store the result.',[
 match('Match each description to a level.',[['total = first + second','High-level source'],['ADD followed by an operand','Assembly-style instruction'],['A binary instruction word executed by a CPU','Machine code']],'Mnemonic instructions are readable labels for low-level operations. The examples are not a real processor specification.'),
 mc('Which statement about assembly-style instructions is correct?','Mnemonic names represent low-level operations','The CPU directly reads every mnemonic as English','The same assembly instruction set exists on all CPUs','They remove the need to understand instruction order',fb='Mnemonic source is more readable than binary, but still closely reflects a processor design.')]),
 station('Meet the teaching processor',['This original model has one accumulator, which holds the working value.','The instruction pointer identifies the next instruction.','SET replaces the working value; ADD changes it; EMIT displays it; HALT stops execution.'], 'In the workshop, how is the accumulator different from the output?', 'The accumulator is the current working value; the output is a value sent for display. Changing the accumulator does not automatically display it.',[
 mc('The accumulator is 3. ADD 4 is executed. What is its new value?','7','4','3','34',fb='In this model ADD combines its operand with the value already in the accumulator.'),
 mc('After SET 5, then SET 2, what is in the accumulator?','2','7','5','52',fb='SET replaces the previous value. It does not add to it.')]),
 station('Build and trace',['Select the operation in each slot before stepping through the program.','Track the accumulator and next instruction after each step.','The model is enrichment: OCR J277 does not require this instruction set or assembler knowledge.'], 'Build a program that adds 3 and 4 and displays 7. Record the accumulator after each step.', 'SET 3 gives 3; ADD 4 gives 7; EMIT displays 7 without changing it; HALT stops. This is one correct sequence.',[
 board('machine','Build a program that displays 7 by adding 3 and 4, then step until it halts.',mode='sum'),
 mc('Which step sends the working value to the output?','EMIT','SET','ADD','HALT',fb='The teaching processor only displays a value when EMIT executes.')]),
 station('Encode an instruction',['Our invented instruction word contains four operation bits and four operand bits.','SET uses operation bits 0001; ADD uses 0010.','This encoding belongs only to the teaching model; real CPUs use their own formats.'], 'Using the displayed encoding, explain the two parts of 0010 0100.', '0010 selects ADD; 0100 represents the operand 4. The instruction adds 4 to the accumulator.',[
 mc('In this model, ADD 4 has operation bits 0010 and operand bits 0100. Which word encodes it?','0010 0100','0100 0010','0001 0100','0010 0001',fb='Place the operation field first, then the four-bit operand. This is not a real CPU encoding.'),
 mc('Why should you not send this invented encoding to an arbitrary real CPU?','Its instruction format and operation codes may be different','Real CPUs never use binary','Four bits always mean a letter','A mnemonic is identical to an electrical signal',fb='An instruction only has meaning within the instruction set and encoding designed for its processor.')]),
 station('Diagnose the sequence',['Correct operations in the wrong order can give the wrong output.','A trace helps locate the first difference between expected and actual behaviour.','Changing the instructions means the previous trace is no longer evidence for the new program.'], 'A program emits 3 before adding 4. Why is its displayed result not 7?', 'The output was produced before the addition. Move EMIT after ADD, then rerun the corrected program.',[
 board('machine','Repair the out-of-order program so it displays 7, then step through the corrected version.',mode='repair'),
 mc('A trace reaches the wrong result without any invalid instruction. What kind of problem is likely?','A logic error in the sequence','Proof that the CPU cannot add','A spelling error must exist','A broken screen must be the cause',fb='A valid sequence can still implement the wrong algorithm.')]),
 station('Control has a cost',['Working close to the processor exposes small operations explicitly.','That control can be useful, but there is more detail to manage.','For J277, focus on language characteristics and translation; the simulator makes those ideas visible.'], 'Why is this four-step example not evidence that all high-level code is inefficient?', 'It illustrates abstraction, not a performance benchmark. Efficient machine instructions can also be produced from high-level code.',[
 mc('What does the workshop mainly demonstrate?','High-level tasks can be represented as smaller processor operations','All real processors have exactly four instructions','Every high-level statement is one byte','Assembly programming is compulsory for J277',fb='The model is deliberately small and original. Its instruction set is enrichment, not required recall.'),
 mc('Which job most clearly benefits from precise low-level control?','A carefully optimised routine that must manipulate particular hardware resources','A project whose only requirement is easy editing by beginners','A document with no executable instructions','A page of revision notes',fb='Specific hardware requirements can justify extra implementation detail.')])],
 plenary=[mc('Why is machine code described as processor-dependent?','Its binary instruction patterns belong to a particular instruction set','All CPUs understand identical operations','It is always written in Python','It contains no operands',fb='Different architectures can assign different meanings to the same binary pattern.'),
 mc('What is the best comparison?','Assembly-style mnemonics are more readable than binary but remain close to hardware','Assembly source is executed as English','Machine code is independent of hardware','A high-level language cannot calculate',fb='Both machine code and assembly are low-level; mnemonics help humans read the operations.')],
 exam=[('Give one difference between high-level source and machine code, and explain why translation is needed.',3,'High-level source uses abstractions/readable expressions whereas machine code is binary CPU instructions (1). A CPU executes its own instruction set (1), so high-level source must be processed into executable operations (1).'),('A hardware team chooses low-level code. Explain one benefit and one drawback.',4,'Precise control over hardware/resources (1) suits a specific device requirement (1). More complex or processor-specific code (1) makes development, maintenance or porting harder (1).')]),
 dict(id='pl-l03',lesson=3,title='Translation exchange',slug='TranslationExchange',subtitle='Compare compiling and interpreting',
 description='Send an original program through a compiler or interpreter model. Investigate where an error stops progress, fix it, then choose a translation approach for development and release.',
 objectives=['Explain why translation is needed.','Compare the behaviour of compilers and interpreters.','Justify a translation approach for development and distribution.'],
 starter='A program contains a mistake in its third instruction. What might happen to the first two instructions when you try to run it?',starterAnswer='It depends on the translation approach and error. In the simplified interpretation model, earlier valid statements may execute before the error is reached. A compilation failure can prevent a new runnable build.',
 terms=[('Compiler','Software that translates a source program into target code before that compiled result is executed.'),('Interpreter','Software that processes and carries out source instructions during execution.')],
 stations=[
 station('Why translate',['The processor executes machine instructions, not the high-level source as written.','A translator connects source instructions to operations the computer can carry out.','Translation does not prove that the program meets its requirements.'], 'Why is translating a program different from testing it?', 'Translation prepares executable operations; testing compares actual behaviour with expected results and can reveal logic errors.',[
 mc('What is the purpose of a language translator?','Process source code into a form or operations that can be executed','Guarantee that every algorithm is correct','Draw the user interface automatically','Replace the processor',fb='A translator enables execution. Correct outputs still need to be tested.'),
 mc('A program translates but calculates the wrong discount. What is still needed?','Testing and correction of its logic','A claim that translation guarantees correctness','Deletion of the requirements','A faster monitor',fb='A valid expression can perform the wrong calculation.')]),
 station('Compile before running',['In the GCSE model, a compiler translates the whole source program before execution.','A successful build produces target code that can be saved and run again.','Changes to the source require a new build to update that compiled version.'], 'Why can a user run a compiled release without the original compiler?', 'Translation has already produced the target program. It must still be compatible with the target platform and have any required runtime components.',[
 order('Put a successful compiled workflow in order.',['Write or edit source code','Compile the source for a target platform','Obtain a successful build','Run the compiled result'],'If a build fails, correct the reported problem and compile again before running the updated result.'),
 mc('A developer changes a calculation in the source. What updates the compiled release?','Recompile and distribute the new build','Run the old executable and expect its instructions to change','Rename the source file only','Remove the editor',fb='The existing compiled file does not update itself when its source changes.')]),
 station('Interpret during execution',['In the simplified GCSE model, an interpreter processes and executes source statement by statement.','If an error is reached, execution stops there and reports the problem.','The interpreting software is used again when the source is run again.'], 'Why can an interpreter be useful while a programmer is making frequent changes?', 'The programmer can run and test changes without a separate whole-program build step, and inspect where execution encounters a problem.',[
 mc('In this model, what happens when interpretation reaches an invalid instruction?','It reports the error and stops at that point','It silently fixes the instruction','It proves earlier output was correct','It always generates a distributable executable',fb='Earlier valid instructions may already have run. Real implementations can also perform checks before execution.'),
 mc('Why can repeated interpretation have an execution cost?','Source processing happens during each run','The screen must redraw the entire source','Interpreters cannot use memory','All source is converted to an image',fb='Compiled code can avoid repeating the same translation work at runtime. Actual performance depends on the implementation.')]),
 station('Observe the error',['Use the same small program in both modes.','The simulator deliberately models whole-program compilation and statement-at-a-time interpretation.','Some real systems combine techniques; this is a conceptual comparison, not a timing benchmark.'], 'Record what each mode outputs before the deliberately invalid instruction is fixed.', 'The failed compile produces no new runnable build or output. The interpretation model displays 6 before stopping on its third line.',[
 board('translator','Investigate both modes with the error, repair it, then successfully run both modes.'),
 mc('The interpreter displayed 6 before stopping. What can you conclude?','At least one earlier output instruction executed','The entire program completed successfully','The compiler must also have displayed 6','There are no logic errors',fb='Partial output is evidence of earlier execution, not evidence that the entire program works.')]),
 station('Development and distribution',['Interpretation can support a quick edit-run-debug cycle.','A compiled release can be distributed without giving users the high-level source.','Target compatibility and runtime dependencies still matter for a compiled program.'], 'Give one reason a supplier might compile a stable release for a specified platform.', 'It can distribute the compiled result without requiring the user to translate the source, and avoid repeating that translation each run.',[
 sort('Match each need to the approach it most directly supports.',['Compiler','Interpreter'],[['Create a saved target-code build before users run it','Compiler'],['Process source instructions during each run','Interpreter'],['Distribute the translated program without supplying high-level source','Compiler'],['Use the simplified statement-at-a-time edit-run cycle','Interpreter']],'Both can be used during development; the choice depends on the language tools and project requirements.'),
 mc('Which claim about compiled releases needs correcting?','They work on every processor and operating system without checking','They may need rebuilding after source changes','They can be distributed as target code','They can avoid repeated source translation on each run',fb='Compiled output usually targets a particular platform and may depend on runtime support.')]),
 station('Compare without absolutes',['Both approaches can help identify errors, but neither guarantees correct logic.','A compiler may report several translation errors from a build.','An interpreter can help locate a problem during execution; error behaviour depends on the tool and error type.'], 'Why is “a compiler finds every mistake” an unreliable claim?', 'It can report translation errors but a valid program can still contain logical mistakes or fail with particular data.',[
 multi('Select the TWO defensible statements.',['A compiler can produce a saved target-code build','Successful translation guarantees correct logic','An interpreter processes source during execution','Every interpreted program is slower than every compiled program'],['A compiler can produce a saved target-code build','An interpreter processes source during execution'],'Avoid universal speed claims; use the stated translation models when comparing the approaches.'),
 mc('What should a developer do after fixing an error?','Rerun relevant tests using the corrected program','Assume the change cannot affect anything else','Keep distributing only the failed build','Remove all error messages',fb='Testing the correction checks both the intended fix and other affected behaviour.')])],
 plenary=[mc('A team distributes a stable application to a known platform. Which benefit supports compilation?','Users can run the translated build without compiling its source','It guarantees no logic errors','The source changes automatically update all installed copies','The executable runs on every instruction set',fb='Compilation can support distribution, but does not remove testing or platform requirements.'),
 match('Match each statement to the approach.',[['Translates the source before running its compiled result','Compiler'],['Processes source while carrying out its instructions','Interpreter']],'These are the GCSE comparison models. Some real implementations combine compilation and interpretation.')],
 exam=[('Explain two differences between a compiler and an interpreter in the GCSE model.',4,'Compiler translates the whole program before execution (1), interpreter processes statements during execution (1). Compiled target code can be saved and run again (1), interpreted source is processed again on later runs (1). Accept another valid paired comparison.'),('Explain why a compiled program still needs testing.',2,'Translation can succeed despite a logic error (1), so actual outputs must be compared with expected results (1).')]),
 dict(id='pl-l04',lesson=4,title='Developer control room',slug='DeveloperControlRoom',subtitle='Use IDE tools to find and fix a problem',
 description='Explore an original simulated IDE: edit a faulty calculation, use diagnostics, set a breakpoint, inspect variables and run tests before releasing your program.',
 objectives=['Describe an IDE and its main facilities.','Explain how editing, diagnostics, translation and execution support development.','Use a breakpoint and a variable watch to investigate a logic error.'],
 starter='A program runs without crashing but gives a ticket total that is too small. What would you investigate first?',starterAnswer='Compare the expected and actual total, inspect the values used and check the calculation. A program can run successfully while its logic is wrong.',
 terms=[('IDE','An integrated development environment that brings programming tools together.'),('Error diagnostic','Information that helps a programmer locate or understand a problem.')],
 stations=[
 station('One environment',['An IDE brings tools for writing, translating, running and debugging code into one working environment.','The exact features vary between products and languages.','An IDE helps the programmer work; it does not choose the correct algorithm for them.'], 'How could integration reduce the effort of checking a small change?', 'The programmer can edit, run and inspect the program in one environment instead of switching between separate tools.',[
 mc('What does IDE stand for?','Integrated development environment','Internal data execution','Instruction design engine','Internet debugging extension',fb='An IDE combines programming facilities into one environment.'),
 match('Match the core facility to its role.',[['Editor','Create and change source code'],['Translator','Process source for execution'],['Run-time environment','Provide facilities needed to execute the program'],['Error diagnostics','Help locate or explain problems']],'OCR J277 asks you to know these facilities and how they help program development.')]),
 station('The source editor',['The editor lets you write and change source code.','Syntax highlighting can make keywords, strings and comments easier to distinguish.','Auto-indentation or completion can reduce routine typing, but suggestions still need checking.'], 'Why does syntax highlighting not prove that a calculation is correct?', 'It identifies types of code elements; it does not know whether the calculation matches the requirements.',[
 mc('Which facility lets a developer change price + quantity to price * quantity?','The source editor','The screen brightness control','The output window alone','A backup archive',fb='The editor changes source. The program must be rerun to test the change.'),
 mc('How can automatic indentation help?','It supports a consistent layout and can reduce indentation mistakes','It guarantees the correct algorithm','It replaces the need to run tests','It permanently removes every syntax error',fb='Editor assistance reduces some effort, but the programmer must still check the result.')]),
 station('Read the diagnostic',['A syntax diagnostic can identify a location and describe invalid source.','The reported location may be near the cause rather than the exact fix.','A logic error can produce an incorrect result without a translation diagnostic.'], 'A diagnostic says “unexpected closing bracket”. What should you do next?', 'Inspect that line and nearby bracket pairs, correct the source, and run or build again before testing the result.',[
 mc('Which problem is most likely to produce a syntax diagnostic?','A missing closing bracket in a function call','A valid multiplication when addition was intended','A correct result printed in a small font','A variable with a meaningful name',fb='Syntax diagnostics concern the language rules. Valid syntax can still implement the wrong logic.'),
 mc('No syntax problems are reported, but the total is wrong. What should you inspect?','The calculation and the values it uses','Only the colour theme','Only the file icon','Nothing, because the result must be correct',fb='A logic error often requires tracing and testing rather than a syntax fix.')]),
 station('Run and observe',['The run-time environment supports execution and interaction with input and output.','A translator may be invoked by a build or run command.','Use expected results to decide whether the observed output is correct.'], 'A ticket costs 4 and a customer buys 3. What output should a correct total calculation produce?', '12. A result of 7 suggests the program added price and quantity instead of multiplying.',[
 mc('Which is the best test for a total price calculation?','Known price and quantity with an independently calculated expected total','Any data without an expected output','Changing the font and assuming success','Only opening the source file',fb='A test needs an expected result to compare with the actual output.'),
 mc('Why can a program fail during execution even after translation succeeds?','Some errors depend on the values or situation at runtime','Translation always prevents runtime problems','The editor must be closed first','Machine code never uses data',fb='For example, division by zero can depend on an input value. Successful translation alone is insufficient.')]),
 station('Pause and inspect',['A breakpoint pauses execution at a chosen point.','A variable watch shows values at that pause; stepping advances through instructions.','Use the first unexpected value to narrow down the location of a logic error.'], 'Where would you pause to inspect the inputs to a wrong total calculation?', 'Pause immediately before the calculation; inspect price and quantity, then step and compare total with the expected value.',[
 board('ide','Set the breakpoint, inspect the values, repair the total calculation and pass both tests.'),
 mc('What does a variable watch help a developer do?','Inspect current values while debugging','Guarantee that every variable has the intended value','Turn source code into a photograph','Replace the specification',fb='The watch makes state visible. The programmer still decides whether those values are appropriate.')]),
 station('Test the change',['Fixing one example is not enough evidence for every input.','Rerun relevant tests after changing source.','Record the input, expected output, actual output and whether the test passed.'], 'Why does testing two different orders provide stronger evidence than repeatedly testing the same order?', 'It checks the behaviour with different values and may reveal a solution that only happens to work for the first case.',[
 sort('Choose the facility that directly addresses each need.',['Editor','Diagnostics','Run-time environment','Translator'],[['Change a source expression','Editor'],['Read an explanation of a syntax problem','Diagnostics'],['Execute the program and observe its output','Run-time environment'],['Convert or process the source for execution','Translator']],'Several facilities can work together when you press Run, but their roles are different.'),
 mc('After changing total = price + quantity to multiplication, what is the best next step?','Rerun tests with expected results for different inputs','Stop because any edit must be an improvement','Delete the output evidence','Change the variable names only',fb='Test the corrected source, including relevant cases that could reveal a remaining mistake.')])],
 plenary=[mc('A teacher wants evidence that an IDE helped locate a logic error. Which evidence is strongest?','A breakpoint and variable values showing where the wrong total was calculated','A screenshot of a new colour theme','The fact that no error message appeared','A larger font in the editor',fb='Useful debugging evidence connects a tool to the observed problem.'),
 match('Match the action to the tool.',[['Pause before a calculation','Breakpoint'],['Inspect the value of quantity','Variable watch'],['Advance one instruction','Step control']],'These debugging facilities support investigation. Their names and layouts vary between IDEs.')],
 exam=[('Describe how an editor and an error-diagnostic facility each help a programmer.',4,'Editor creates/changes source (1), allowing correction or development of instructions (1). Diagnostics identify/explain a problem or its location (1), helping the programmer investigate and correct it (1).'),('Explain how a breakpoint and variable watch can help locate an incorrect total.',3,'Pause before/around the calculation (1), inspect relevant current values (1), step and compare the result with the expected value to locate the mistake (1).')])
]
